#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['affine', 'affine.tests']

package_data = \
{'': ['*']}

extras_require = \
{'dev': ['pydocstyle', 'flake8', 'coveralls'],
 'test': ['pytest >=4.6', 'pytest-cov']}

setup(name='affine',
      version='%%PORTVERSION%%',
      description='Matrices describing affine transformation of the plane',
      author=None,
      author_email='Sean Gillies <sean.gillies@gmail.com>',
      url=None,
      packages=packages,
      package_data=package_data,
      extras_require=extras_require,
      python_requires='>=3.7',
     )
