--- pyproject.toml.orig	2026-04-24 16:43:43 UTC
+++ pyproject.toml
@@ -42,7 +42,7 @@ dev = [
 ]
 
 [build-system]
-requires = ["uv_build>=0.9.0,<0.10.0"]
+requires = ["uv_build>=0.9.0"]
 build-backend = "uv_build"
 
 [tool.uv.build-backend]
