# Created by: Kubilay Kocak <koobs@FreeBSD.org>
# $FreeBSD$

PORTNAME=	libfvde
PORTVERSION=	20130305
PORTREVISION=	1
CATEGORIES=	sysutils
MASTER_SITES=	https://googledrive.com/host/0B3fBvzttpiiSLUVJYl9XRWhKSjg/
DISTFILES=	${PORTNAME}-experimental-${PORTVERSION}${EXTRACT_SUFX}

MAINTAINER=	koobs@FreeBSD.org
COMMENT=	Library and tools for reading FileVault (FVDE) encrypted volumes

LICENSE=	LGPL3

USES=		pkgconfig
USE_GNOME=	libxml2 gnomehack
USE_LDCONFIG=	yes
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
