.Dd August 05, 2013
.Dt JITSI 1
.Os
.Sh NAME
.Nm jitsi
.Nd a VoIP, videoconferencing and instant messaging application
.Sh SYNOPSIS
.Nm
.Op Ar options
.Op Ar uri-to-call
.Sh DESCRIPTION
.Nm Jitsi
is a VoIP, videoconferencing and instant messaging application available in a variety of operating systems. It supports several protocols including SIP and SIMPLE, XMPP and Jingle, MSNP, YMSG, and OSCAR. These protocols are used by major communication services/networks (Google Talk, Facebook Chat, MSN, Yahoo! Messenger, AIM, ICQ). Voice and video calls can be done using SIP and XMPP, file transfers with XMPP, MSNP, YMSG, and OSCAR, and instant messaging with SIP (no multi-user chats), XMPP, MSNP, YMSG, and OSCAR.
.Pp
The following options are available:
.Bl -tag -width indent
.It Fl c, -config= Ar DIR
Use the directory
.Ar DIR
for the configuration files. The default directory is
.Pa $HOME/.jitsi
.It Fl d, -debug
Print debugging messages to stdout.
.It Fl h, -help
Print the current version, the list of available options, and exit.
.It Fl m, -multiple
Allow more than one instance launch.
.It Fl 6, -ipv6
Force use of IPv6 addresses where possible.
.It Fl 4, -ipv4
Force use of IPv4 addresses only.
.It Fl v, -version
Print the current version and exit.
.El
.Pp
The optional
.Ar uri-to-call
parameter can be specified to start a call from the command-line. If Jitsi is already running then the call is handled by the running instance, except when it is explicitly told to allow multiple instance launch.
.Sh IMPLEMENTATION NOTES
Jitsi is an open source application mostly written in Java with some parts (such as audio/video capture and rendering) written in native code. Its GUI is based on the widget toolkit Swing. Its architecture is build upon the OSGi framework, using the implementation provided by Apache Felix.
.Pp
A good resource about the internals of Jitsi can be found in the
.Sq Jitsi Chapter
of the
.Sq The Architecture of Open Source Applications
book.
.Ad http://www.aosabook.org/en/jitsi.html
.Sh FILES
.Pa $HOME/.jitsi
The default directory for the configuration files of jitsi
.Sh AUTHORS
.An -nosplit
Jitsi was created by
.An "Emil Ivov" Aq  emcho@jitsi.org
and currently is being developed by the
.An "Jitsi Team and Contributors" Aq https://jitsi.org/Development/TeamAndContributors
.Pp
This manual page was written by
.An "Tzanetos Balitsaris" Aq tzabal@it.teithe.gr
as part of the Jitsi FreeBSD port.
