--- cmake/ssl.cmake.orig	2018-04-29 16:21:47 UTC
+++ cmake/ssl.cmake
@@ -265,10 +265,10 @@ MACRO (MYSQL_CHECK_SSL)
         OPENSSL_MAJOR_VERSION "${OPENSSL_VERSION_NUMBER}"
         )
     ENDIF()
     IF(OPENSSL_INCLUDE_DIR AND
        OPENSSL_LIBRARY   AND
        CRYPTO_LIBRARY      AND
-       OPENSSL_MAJOR_VERSION STREQUAL "1"
+       (OPENSSL_MAJOR_VERSION STREQUAL "1" OR OPENSSL_MAJOR_VERSION STREQUAL "2")
       )
       SET(OPENSSL_FOUND TRUE)
       FIND_PROGRAM(OPENSSL_EXECUTABLE openssl
