--- pyproject.toml.orig	2026-04-02 17:25:33 UTC
+++ pyproject.toml
@@ -1,5 +1,5 @@
 [project]
-name = "Werkzeug"
+name = "werkzeug"
 version = "3.1.8"
 description = "The comprehensive WSGI web application library."
 readme = "README.md"
