# Created by: Peter Schuller <peter.schuller@infidyne.com>
# $FreeBSD$

PORTNAME=	boto
PORTVERSION=	2.16.0
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	rm@FreeBSD.org
COMMENT=	Python interface to Amazon Web Services

LICENSE=	MIT

USE_PYTHON=	2
USE_PYDISTUTILS=easy_install
PYDISTUTILS_AUTOPLIST=yes

CONFLICTS=	p5-Net-Amazon-Route53-[0-9]*

.include <bsd.port.mk>
