--- pyproject.toml.orig	1970-01-01 00:00:00 UTC
+++ pyproject.toml
@@ -23,7 +23,7 @@ dependencies = [
 requires-python = ">=3.11"
 dependencies = [
     "fonttools[ufo] >= 4.63.0",
-    "orjson >= 3.11.9, < 4",
+    "orjson >= 3.11.4, < 4",
     "typing_extensions >= 4.15.0",
     "ufonormalizer >= 0.6.3",
     "ufoLib2[json] >= 0.18.1",
@@ -76,8 +76,8 @@ yuri = "vfbLib.value:yuri"
 yuri = "vfbLib.value:yuri"
 
 [build-system]
-requires = ["uv_build>=0.11.8,<0.12"]
-build-backend = "uv_build"
+requires = ["flit-core >= 3.12"]
+build-backend = "flit_core.buildapi"
 
 
 [tool.coverage.paths]
