--- Canna.conf.orig	2025-08-15 04:38:35 UTC
+++ Canna.conf
@@ -109,7 +109,8 @@
 # define DefErrDir $(cannaPrefix)/log
 # define DefLibCannaDir $(cannaExecPrefix)/lib
 #else 
-# define DefCannaPrefix /usr/local/canna
+PREFIX?= /usr/local
+# define DefCannaPrefix $(PREFIX)
 # ifdef ObsoleteInstallDir
 #  define DefErrDir /usr/spool/canna
 #  define DefLibCannaDir /usr/lib
@@ -182,7 +183,7 @@ cannaOwnerGroup =
 #ifdef InstallAsUser
 cannaOwnerGroup =
 #else
-cannaOwnerGroup = -o $(cannaOwner) -g $(cannaGroup)
+cannaOwnerGroup =
 #endif
 
 cannaShLibMajor = 1
@@ -206,9 +207,9 @@ CHMOD = :
 CHGRP = :
 CHMOD = :
 #else
-CHOWN = chown
-CHGRP = chgrp
-CHMOD = chmod
+CHOWN = :
+CHGRP = :
+CHMOD = :
 #endif
 
 /* 日本語マニュアルを使わないのであればコメントアウト */
