--- pyproject.toml.orig	2026-06-23 07:30:29 UTC
+++ pyproject.toml
@@ -11,7 +11,7 @@ requires-python = ">=3.6"
 ]
 urls = { "Homepage" = "https://github.com/dirkjanm/ldapdomaindump/" }
 requires-python = ">=3.6"
-license = "MIT"
+license = { text = "MIT" }
 dependencies = [
   "dnspython",
   "ldap3>=2.5,!=2.5.2,!=2.5.0,!=2.6"
