--- Cargo.toml.orig	2006-07-24 01:21:28 UTC
+++ Cargo.toml
@@ -27,13 +27,15 @@ default = [
   "lz4",
   "bzip2",
   "brotli",
-  "xz",
+  "xz-shared",
   "zstd",
-  "gzip",
-  "zlib",
-  "deflate",
+  "gzip-shared",
+  "zlib-shared",
+  "deflate-shared",
+  "use-system-blosc2-shared",
+  "use-system-isal-shared",
 ]
-experimental = ["blosc2", "igzip", "ideflate", "izlib"]
+experimental = ["blosc2-shared", "use-system-blosc2-shared", "igzip-shared", "ideflate-shared", "izlib-shared", "use-system-isal-shared"]
 
 extension-module = ["pyo3/extension-module"]
 
