# New ports collection makefile for:	cqcam
# Version required:	0.45a
# Date created:		29 Oct 1997
# Whom:			Kensaku Masuda <greg@greg.rim.or.jp>
#
# $Id: Makefile,v 1.2 1998/02/21 22:37:54 fenner Exp $
#

DISTNAME=	cqcam-0.45a
CATEGORIES=	graphics tk80
MASTER_SITES=	http://www.cs.virginia.edu/~patrick/cqcam/
EXTRACT_SUFX=	.tgz

MAINTAINER=	ports@FreeBSD.ORG

LIB_DEPENDS=	tk80\\.1:${PORTSDIR}/x11/tk80

MAN1=		cqcam.1

.include <bsd.port.mk>
