--- cmake/GammaRayProbeABI.cmake.orig	2021-03-22 12:26:15 UTC
+++ cmake/GammaRayProbeABI.cmake
@@ -110,7 +110,7 @@ else()
       set(GAMMARAY_PROBE_ABI "${GAMMARAY_PROBE_ABI}-arm")
     endif()
   else()
-    if(CMAKE_SYSTEM_PROCESSOR MATCHES "i[3456]86" OR CMAKE_SYSTEM_PROCESSOR MATCHES "x86" OR CMAKE_SYSTEM_PROCESSOR MATCHES "corei")
+    if(CMAKE_SYSTEM_PROCESSOR MATCHES "i[3456]86" OR CMAKE_SYSTEM_PROCESSOR MATCHES "x86" OR CMAKE_SYSTEM_PROCESSOR MATCHES "amd64" OR CMAKE_SYSTEM_PROCESSOR MATCHES "corei")
       if(CMAKE_SIZEOF_VOID_P EQUAL 8)
         set(GAMMARAY_PROBE_ABI "${GAMMARAY_PROBE_ABI}-x86_64")
       else()
