--- cmake/version.cmake.orig	2018-12-07 05:19:36 UTC
+++ cmake/version.cmake
@@ -4,7 +4,7 @@ set(CADABRA_VERSION_PATCH 2)
 set(CADABRA_VERSION_TWEAK 0)
 set(COPYRIGHT_YEARS "2001-2018")
 math(EXPR SYSTEM_BITS "${CMAKE_SIZEOF_VOID_P} * 8")
-find_program(GIT git PATHS ${GIT_DIR})
+#find_program(GIT git PATHS ${GIT_DIR})
 if(GIT)
   message("-- Git found: ${GIT}")
   execute_process(COMMAND git rev-parse --short HEAD OUTPUT_VARIABLE GIT_SHORT_SHA     OUTPUT_STRIP_TRAILING_WHITESPACE)
@@ -16,7 +16,7 @@ endif()
 if(GIT_SHORT_SHA)
   set(CADABRA_VERSION_BUILD "${GIT_COMMIT_SERIAL}.${GIT_SHORT_SHA}")
 else()
-  set(CADABRA_VERSION_BUILD "private")
+  set(CADABRA_VERSION_BUILD "from the FreeBSD port")
 endif()
 if(GIT_COMMIT_DATE)
   set(CADABRA_VERSION_DATE "${GIT_COMMIT_DATE}")
