--- rebar.config.script.orig	2016-07-11 13:29:03 UTC
+++ rebar.config.script
@@ -1,11 +1,6 @@
 IsRebar3 = erlang:function_exported(rebar3, main, 1),
 
 Rebar2Deps = [
-    {jsx, ".*", {git, "https://github.com/talentdeficit/jsx.git",
-                 {tag,"2.8.0"}}},
-
-    {hackney, ".*", {git, "https://github.com/benoitc/hackney.git",
-                     {tag, "1.6.2"}}}
 ],
 
 case IsRebar3 of
