# New ports collection makefile for:	FrontPage Hebrew Web Administration
# Date created:		Sat Oct 25 16:30:00 CDT 2001
# Whom:			hetzels@westbend.net
#
# $FreeBSD$
#

PORTNAME=	frontpage
CATEGORIES=	www hebrew
PKGNAMEPREFIX=	he-

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Microsoft Frontpage Hebrew Web Administration

MD5_FILE=	${.CURDIR}/distinfo

FP_LANG=	hbr
FP_LANGUAGE=	Hebrew
FP_LCID=	1037

MASTERDIR=	${.CURDIR}/../frontpage-ar

.include "${MASTERDIR}/Makefile"
