#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['myst_parser']

package_data = \
{'': ['*']}

install_requires = \
['attrs>=19',
 'docutils>=0.15,<0.18',
 'jinja2',
 'markdown-it-py>=1.0.0,<3.0.0',
 'mdit-py-plugins~=0.3.0',
 'pyyaml',
 'sphinx>=3.1,<5',
 'typing-extensions']

extras_require = \
{'code_style': ['pre-commit~=2.12'],
 'linkify': ['linkify-it-py~=1.0'],
 'rtd': ['ipython',
         'sphinx-book-theme',
         'sphinx-panels',
         'sphinxcontrib-bibtex~=2.4',
         'sphinxext-rediraffe~=0.2.7',
         'sphinxcontrib.mermaid~=0.7.1',
         'sphinxext-opengraph~=0.6.3'],
 'testing': ['beautifulsoup4',
             'coverage',
             'docutils~=0.17.0',
             'pytest>=6,<7',
             'pytest-cov',
             'pytest-regressions',
             'pytest-param-files~=0.3.4']}

entry_points = \
{'console_scripts': ['myst-anchors = myst_parser.cli:print_anchors',
                     'myst-docutils-html = myst_parser.docutils_:cli_html',
                     'myst-docutils-html5 = myst_parser.docutils_:cli_html5',
                     'myst-docutils-latex = myst_parser.docutils_:cli_latex',
                     'myst-docutils-pseudoxml = '
                     'myst_parser.docutils_:cli_pseudoxml',
                     'myst-docutils-xml = myst_parser.docutils_:cli_xml']}

setup(name='myst-parser',
      version='%%PORTVERSION%%',
      description='An extended commonmark compliant parser, with bridges to docutils & sphinx.',
      author=None,
      author_email='Chris Sewell <chrisj_sewell@hotmail.com>',
      url=None,
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      entry_points=entry_points,
      python_requires='>=3.7',
     )
