--- m	Wed May 18 11:55:48 2005
+++ Makefile.PL	Wed May 18 11:56:07 2005
@@ -668,11 +668,11 @@
 	cd "$(MODPERL_SRC)" && $(MAKE)
 
 modperl_lib_install:
-	cd "$(MODPERL_SRC)" && $(MAKE) DESTDIR=$(DESTDIR) install
+#	cd "$(MODPERL_SRC)" && $(MAKE) DESTDIR=$(DESTDIR) install
 
 modperl_xs_h_install:
-	@$(MKPATH) $(DESTDIR)$(MODPERL_AP_INCLUDEDIR)
-	$(CP) $(MODPERL_XS_H_FILES) $(DESTDIR)$(MODPERL_AP_INCLUDEDIR)
+#	@$(MKPATH) $(DESTDIR)$(MODPERL_AP_INCLUDEDIR)
+#	$(CP) $(MODPERL_XS_H_FILES) $(DESTDIR)$(MODPERL_AP_INCLUDEDIR)
 
 modperl_src_clean:
 	cd "$(MODPERL_SRC)" && $(MAKE) clean
