# $FreeBSD$

PORTNAME=	Date_Holidays_Iceland
PORTVERSION=	0.1.2
CATEGORIES=	devel www pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	Driver based class to calculate holidays in Iceland

LICENSE=	PHP301

BUILD_DEPENDS=	${PEARDIR}/Date/Holidays.php:devel/pear-Date_Holidays@${PHP_FLAVOR}
RUN_DEPENDS=	${PEARDIR}/Date/Holidays.php:devel/pear-Date_Holidays@${PHP_FLAVOR}

USES=		pear

.include <bsd.port.mk>
