--- src/appleseed.studio/python/pythoninterpreter.cpp.orig	2019-08-31 15:49:01 UTC
+++ src/appleseed.studio/python/pythoninterpreter.cpp
@@ -62,7 +62,7 @@ BOOST_PYTHON_MODULE(_appleseedpythonbuiltin)
 }
 
 // Generated by BOOST_PYTHON_MODULE() declarations in module.cpp files.
-extern "C" void init_appleseedstudio();
+extern "C" PyObject* PyInit__appleseedstudio();
 
 namespace appleseed {
 namespace studio {
@@ -177,8 +177,8 @@ void PythonInterpreter::initialize(OutputRedirector re
     // from e.g. renderer::Project to appleseedpython.Project.
     //
 
-    PyImport_AppendInittab("_appleseedpythonbuiltin", init_appleseedpythonbuiltin);
-    PyImport_AppendInittab("_appleseedstudio", init_appleseedstudio);
+    PyImport_AppendInittab("_appleseedpythonbuiltin", PyInit__appleseedpythonbuiltin);
+    PyImport_AppendInittab("_appleseedstudio", PyInit__appleseedstudio);
     Py_Initialize();
 
     bpy::object main_module = bpy::import("__main__");
