# $FreeBSD$

PORTNAME=	Module-CPANfile
PORTVERSION=	1.1002
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	lth@FreeBSD.org
COMMENT=	Parse cpanfile

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
