PORTNAME=	Bytes-Random-Secure-Tiny
PORTVERSION=	1.011
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	pi@FreeBSD.org
COMMENT=	Generate cryptographically-secure random bytes
WWW=		https://metacpan.org/release/Bytes-Random-Secure-Tiny

LICENSE=	ART20

USES=		perl5
USE_PERL5=	configure

PLIST_FILES=	${SITE_PERL_REL}/Bytes/Random/Secure/Tiny.pm \
		${SITE_PERL_REL}/Bytes/Random/Secure/Tiny.pod \
		${SITE_MAN3_REL}/Bytes::Random::Secure::Tiny.3.gz

.include <bsd.port.mk>
