# New ports collection makefile for:	p5-CGP-CLI
# Date created:	   01 Jun 2010
# Whom:		   Alexander Kriventsov <avk@vl.ru>
#
# $FreeBSD$
#

PORTNAME=	CGP-CLI
PORTVERSION=	2.7.5
CATEGORIES=	mail perl5
MASTER_SITES=	http://ftp.spbu.ru/CPAN/authors/id/J/JB/JBUHACOFF/
PKGNAMEPREFIX=	p5-

MAINTAINER=	avk@vl.ru
COMMENT=	CommunigatePro Command Line Interface perl module

PERL_CONFIGURE=	yes

MAN3=	CGP::CLI.3

.include <bsd.port.mk>
