# New ports collection makefile for: Mew (for xemacs20)
# Version required:	1.93
# Date created:		17 January 1998
# Whom:			Kiriyama Kazuhiko <kiri@kiri.toba-cmt.ac.jp>
#
# $Id: Makefile,v 1.1.1.1 1998/11/05 22:13:27 kuriyama Exp $
#

PKGNAME=	mew-xemacs20-1.93

EMACS_NAME=	XEmacs-20.4
DIRSECTION=	Local Packages:
DIRENTRY=	"* Mew::		Messaging in the Emacs World."
INFOFILE=	mew.info

MASTERDIR=	${.CURDIR}/../../mail/mew-common
PKGDIR=		${.CURDIR}/pkg

.include	"${MASTERDIR}/Makefile"
