--- pyproject.toml.orig	2026-03-06 17:34:39 UTC
+++ pyproject.toml
@@ -4,8 +4,7 @@ requires-python = ">=3.10"
 description = "xml2rfc generates RFCs and IETF drafts from document source in XML according to the IETF xml2rfc v2 and v3 vocabularies."
 readme = "README.md"
 requires-python = ">=3.10"
-license = "BSD-3-Clause"
-license-files = ["LICENSE"]
+license = {file = "LICENSE"}
 authors = [{name = "IETF Tools", email = "tools-help@ietf.org"}]
 keywords = ["ietf", "rfc", "id", "internet-draft", "xml", "xml2rfc", "xmlrfc"]
 classifiers = [
