# Created by: James FitzGibbon <jfitz@FreeBSD.org>
# $FreeBSD$

PORTNAME=	Data-ShowTable
PORTVERSION=	4.1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl5 module to pretty-print arrays of data

LICENSE=	GPLv2

PERL_CONFIGURE=	yes

MAN1=		showtable.1
MAN3=		Data::ShowTable.3

.include <bsd.port.mk>
