# Created by: Shell Hung <shell@shellhung.org>
# $FreeBSD$

PORTNAME=	Date-Chinese
PORTVERSION=	1.12
PORTREVISION=	1
CATEGORIES=	chinese perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module to calculate dates in the Chinese calendar

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
