# Created by: Wes Peters <wes@FreeBSD.org>
# $FreeBSD$

PORTNAME=	obliterate
PORTVERSION=	0.5
CATEGORIES=	sysutils
MASTER_SITES=	${MASTER_SITE_LOCAL}
MASTER_SITE_SUBDIR=wes

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Securely delete file[s]

PLIST_FILES=	bin/obliterate
MAN8=		obliterate.8

NO_STAGE=	yes
.include <bsd.port.mk>
