--- pyproject.toml.orig	2026-09-22 02:36:50.911002000 -0700
+++ pyproject.toml	2026-09-23 07:22:26.322483000 -0700
@@ -6,7 +6,8 @@
 readme = "README.md"
 # https://peps.python.org/pep-0621/#readme
 requires-python = ">=3.10"
-license = "MIT"
+# FreeBSD's py-setuptools 63.1.0 cannot handle the license expression
+# license = "MIT"
 authors = [{ "name" = "Sorin Sbarnea", "email" = "ssbarnea@redhat.com" }]
 maintainers = [{ "name" = "Sorin Sbarnea", "email" = "ssbarnea@redhat.com" }]
 keywords = ["ansible"]
@@ -76,7 +77,7 @@
 [build-system]
 requires = [
   "setuptools_scm[toml] >= 7.0.5",  # required for "no-local-version" scheme
-  "setuptools >= 83.0.0",  # required by pyproject+setuptools_scm integration and editable installs
+  "setuptools >= 63.1.0",  # required by pyproject+setuptools_scm integration and editable installs
 ]
 build-backend = "setuptools.build_meta"
 
