--- fdb/schema.py.orig	2016-01-07 16:01:02 UTC
+++ fdb/schema.py
@@ -2521,7 +2521,7 @@ class Table(BaseSchemaItem):
                 coldef += '%s' % datatype
             if col.isidentity():
                 coldef += ' GENERATED BY DEFAULT AS IDENTITY'
-                if col.generator.inital_value <> 0:
+                if col.generator.inital_value != 0:
                     coldef += ' (START WITH %d)' % col.generator.inital_value
             else:
                 if col.has_default():
