# Created by: grog
# $FreeBSD$

PORTNAME=	xtset
PORTVERSION=	1.1
CATEGORIES=	x11
MASTER_SITES=	ftp://ftp.lemis.com/pub/

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Utility to set title on an xterm

NO_WRKSUBDIR=	YES

PLIST_FILES=	bin/xtset
MAN1=		xtset.1

NO_STAGE=	yes
.include <bsd.port.mk>
