--- pyproject.toml.orig	2024-06-09 16:20:06 UTC
+++ pyproject.toml
@@ -11,7 +11,7 @@ typing-inspect = ">=0.4.0, <1"
 [tool.poetry.dependencies]
 python = "^3.7"
 typing-inspect = ">=0.4.0, <1"
-marshmallow = ">=3.18.0,<4.0.0"
+marshmallow = ">=3.18.0"
 
 [tool.poetry.group.dev.dependencies]
 pytest = "^7.1"
