#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['sphinx_design', 'sphinx_design.compiled']

package_data = \
{'': ['*']}

install_requires = \
['sphinx>=4,<6']

extras_require = \
{'code_style': ['pre-commit~=2.12'],
 'rtd': ['myst-parser~=0.18.0'],
 'testing': ['myst-parser~=0.18.0',
             'pytest~=7.1',
             'pytest-cov',
             'pytest-regressions'],
 'theme_furo': ['furo>=2022.06.04,<2022.07'],
 'theme_pydata': ['pydata-sphinx-theme~=0.9.0'],
 'theme_rtd': ['sphinx-rtd-theme~=1.0'],
 'theme_sbt': ['sphinx-book-theme~=0.3.0']}

setup(name='sphinx_design',
      version='%%PORTVERSION%%',
      description='A sphinx extension for designing beautiful, view size responsive web components.',
      author=None,
      author_email='Chris Sewell <chrisj_sewell@hotmail.com>',
      url=None,
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      python_requires='>=3.7',
     )
