--- conn.c.orig	2009-02-19 21:50:36.000000000 +0300
+++ conn.c	2009-02-19 21:52:45.000000000 +0300
@@ -497,8 +497,20 @@
 #ifdef LDAP_OPT_X_TLS_KEYFILE
     case LDAP_OPT_X_TLS_KEYFILE:
 #endif
-#ifdef LDAP_OPT_X_TLS_PROTOCOL
-    case LDAP_OPT_X_TLS_PROTOCOL:
+#ifdef LDAP_OPT_X_TLS_PROTOCOL_SSL2
+    case LDAP_OPT_X_TLS_PROTOCOL_SSL2:
+#endif
+#ifdef LDAP_OPT_X_TLS_PROTOCOL_SSL3
+    case LDAP_OPT_X_TLS_PROTOCOL_SSL3:
+#endif
+#ifdef LDAP_OPT_X_TLS_PROTOCOL_SSL3
+    case LDAP_OPT_X_TLS_PROTOCOL_TLS1_0:
+#endif
+#ifdef LDAP_OPT_X_TLS_PROTOCOL_SSL3
+    case LDAP_OPT_X_TLS_PROTOCOL_TLS1_1:
+#endif
+#ifdef LDAP_OPT_X_TLS_PROTOCOL_SSL3
+    case LDAP_OPT_X_TLS_PROTOCOL_TLS1_2:
 #endif
 #ifdef LDAP_OPT_X_TLS_CIPHER_SUITE
     case LDAP_OPT_X_TLS_CIPHER_SUITE:
@@ -627,8 +639,20 @@
 #ifdef LDAP_OPT_X_TLS_KEYFILE
 	case LDAP_OPT_X_TLS_KEYFILE:
 #endif
-#ifdef LDAP_OPT_X_TLS_PROTOCOL
-	case LDAP_OPT_X_TLS_PROTOCOL:
+#ifdef LDAP_OPT_X_TLS_PROTOCOL_SSL2
+	case LDAP_OPT_X_TLS_PROTOCOL_SSL2:
+#endif
+#ifdef LDAP_OPT_X_TLS_PROTOCOL_SSL3
+	case LDAP_OPT_X_TLS_PROTOCOL_SSL3:
+#endif
+#ifdef LDAP_OPT_X_TLS_PROTOCOL_SSL3
+	case LDAP_OPT_X_TLS_PROTOCOL_TLS1_0:
+#endif
+#ifdef LDAP_OPT_X_TLS_PROTOCOL_SSL3
+	case LDAP_OPT_X_TLS_PROTOCOL_TLS1_1:
+#endif
+#ifdef LDAP_OPT_X_TLS_PROTOCOL_SSL3
+	case LDAP_OPT_X_TLS_PROTOCOL_TLS1_2:
 #endif
 #ifdef LDAP_OPT_X_TLS_CIPHER_SUITE
 	case LDAP_OPT_X_TLS_CIPHER_SUITE:
