#!/bin/sh
#
# ex:ts=4:sw=4:noet
#-*- mode: makefile; tab-width: 4; -*-
#
# $FreeBSD$

#if [ "$2" = "DEINSTALL" ]; then
# Disabled until pkg runs DEINSTALL before INSTALL in upgrades
if false; then
	FILE="/etc/services"
	echo "===>   Removing spamd entries from ${FILE}"
	sed -i '' \
		-e "/^spamd-sync.*8025/d" \
		-e "/^spamd-cfg.*8026/d" \
		-e "/^spamd.*8025/d" \
		${FILE}
fi
