--- pyproject.toml.orig	2026-03-12 09:59:39 UTC
+++ pyproject.toml
@@ -5,7 +5,6 @@ requires-python = ">=3.10"
 description = "Neo is a package for representing electrophysiology data in Python, together with support for reading a wide range of neurophysiology file formats"
 readme = "README.rst"
 requires-python = ">=3.10"
-license = "BSD-3-Clause"
 classifiers = [
     "Development Status :: 4 - Beta",
     "Programming Language :: Python :: 3",
@@ -34,7 +33,7 @@ download = "http://pypi.python.org/pypi/neo"
 
 
 [build-system]
-requires = ["setuptools>=78.0.2"]
+requires = ["setuptools"]
 build-backend = "setuptools.build_meta"
 
 [project.optional-dependencies]
