MAN3+=	cdk.3 \
	cdk_alphalist.3 \
	cdk_binding.3 \
	cdk_button.3 \
	cdk_buttonbox.3 \
	cdk_calendar.3 \
	cdk_dialog.3 \
	cdk_display.3 \
	cdk_dscale.3 \
	cdk_entry.3 \
	cdk_fscale.3 \
	cdk_fselect.3 \
	cdk_fslider.3 \
	cdk_graph.3 \
	cdk_histogram.3 \
	cdk_itemlist.3 \
	cdk_label.3 \
	cdk_marquee.3 \
	cdk_menu.3 \
	cdk_matrix.3 \
	cdk_mentry.3 \
	cdk_misc.3 \
	cdk_position.3 \
	cdk_process.3 \
	cdk_radio.3 \
	cdk_scale.3 \
	cdk_screen.3 \
	cdk_scroll.3 \
	cdk_selection.3 \
	cdk_slider.3 \
	cdk_swindow.3 \
	cdk_template.3 \
	cdk_traverse.3 \
	cdk_uscale.3 \
	cdk_uslider.3 \
	cdk_viewer.3
BROKENMLINKS+=cdk_alphalist.3 activateCDKAlphalist.3 \
	cdk_alphalist.3 destroyCDKAlphalist.3 \
	cdk_alphalist.3 drawCDKAlphalist.3 \
	cdk_alphalist.3 eraseCDKAlphalist.3 \
	cdk_dialog.3 getCDKAlphalistBox.3 \
	cdk_alphalist.3 getCDKAlphalistContents.3 \
	cdk_alphalist.3 getCDKAlphalistFillerChar.3 \
	cdk_alphalist.3 getCDKAlphalistHighlight.3 \
	cdk_alphalist.3 injectCDKAlphalist.3 \
	cdk_alphalist.3 moveCDKAlphalist.3 \
	cdk_alphalist.3 newCDKAlphalist.3 \
	cdk_alphalist.3 positionCDKAlphalist.3 \
	cdk_alphalist.3 setCDKAlphalist.3 \
	cdk_alphalist.3 setCDKAlphalistBackgroundAttrib.3 \
	cdk_dialog.3 setCDKAlphalistBox.3 \
	cdk_alphalist.3 setCDKAlphalistBackgroundColor.3 \
	cdk_alphalist.3 setCDKAlphalistBoxAttribute.3 \
	cdk_alphalist.3 setCDKAlphalistContents.3 \
	cdk_alphalist.3 setCDKAlphalistFillerChar.3 \
	cdk_alphalist.3 setCDKAlphalistHighlight.3 \
	cdk_alphalist.3 setCDKAlphalistHorizontalChar.3 \
	cdk_alphalist.3 setCDKAlphalistLLChar.3 \
	cdk_alphalist.3 setCDKAlphalistLRChar.3 \
	cdk_alphalist.3 setCDKAlphalistPostProcess.3 \
	cdk_alphalist.3 setCDKAlphalistPreProcess.3 \
	cdk_alphalist.3 setCDKAlphalistULChar.3 \
	cdk_alphalist.3 setCDKAlphalistURChar.3 \
	cdk_alphalist.3 setCDKAlphalistVerticalChar.3 \
	cdk_binding.3 bindCDKObject.3 \
	cdk_binding.3 checkCDKObjectBind.3 \
	cdk_binding.3 cleanCDKObjectBindings.3 \
	cdk_binding.3 getcCDKObject.3 \
	cdk_binding.3 unbindCDKObject.3 \
	cdk_button.3 activateCDKButton.3 \
	cdk_button.3 destroyCDKButton.3 \
	cdk_button.3 drawCDKButton.3 \
	cdk_button.3 eraseCDKButton.3 \
	cdk_button.3 getCDKButtonBox.3 \
	cdk_button.3 getCDKButtonMessage.3 \
	cdk_button.3 injectCDKButton.3 \
	cdk_button.3 moveCDKButton.3 \
	cdk_button.3 newCDKButton.3 \
	cdk_button.3 positionCDKButton.3 \
	cdk_button.3 setCDKButton.3 \
	cdk_button.3 setCDKButtonBackgroundAttrib.3 \
	cdk_button.3 setCDKButtonBackgroundColor.3 \
	cdk_button.3 setCDKButtonboxBackgroundAttrib.3 \
	cdk_button.3 setCDKButtonBox.3 \
	cdk_button.3 setCDKButtonBoxAttribute.3 \
	cdk_button.3 setCDKButtonHorizontalChar.3 \
	cdk_button.3 setCDKButtonLLChar.3 \
	cdk_button.3 setCDKButtonLRChar.3 \
	cdk_button.3 setCDKButtonMessage.3 \
	cdk_button.3 setCDKButtonULChar.3 \
	cdk_button.3 setCDKButtonURChar.3 \
	cdk_button.3 setCDKButtonVerticalChar.3 \
	cdk_buttonbox.3 activateCDKButtonbox.3 \
	cdk_buttonbox.3 destroyCDKButtonbox.3 \
	cdk_buttonbox.3 drawCDKButtonbox.3 \
	cdk_buttonbox.3 eraseCDKButtonbox.3 \
	cdk_buttonbox.3 getCDKButtonboxBox.3 \
	cdk_buttonbox.3 getCDKButtonboxHighlight.3 \
	cdk_buttonbox.3 moveCDKButtonbox.3 \
	cdk_buttonbox.3 injectCDKButtonbox.3 \
	cdk_buttonbox.3 newCDKButtonbox.3 \
	cdk_buttonbox.3 positionCDKButtonbox.3 \
	cdk_buttonbox.3 setCDKButtonbox.3 \
	cdk_buttonbox.3 setCDKButtonboxBackgroundColor.3 \
	cdk_buttonbox.3 setCDKButtonboxBox.3 \
	cdk_buttonbox.3 setCDKButtonboxBoxAttribute.3 \
	cdk_buttonbox.3 setCDKButtonboxHighlight.3 \
	cdk_buttonbox.3 setCDKButtonboxHorizontalChar.3 \
	cdk_buttonbox.3 setCDKButtonboxLLChar.3 \
	cdk_buttonbox.3 setCDKButtonboxLRChar.3 \
	cdk_buttonbox.3 setCDKButtonboxPostProcess.3 \
	cdk_buttonbox.3 setCDKButtonboxPreProcess.3 \
	cdk_buttonbox.3 setCDKButtonboxULChar.3 \
	cdk_buttonbox.3 setCDKButtonboxURChar.3 \
	cdk_buttonbox.3 setCDKButtonboxVerticalChar.3 \
	cdk_calendar.3 activateCDKCalendar.3 \
	cdk_calendar.3 destroyCDKCalendar.3 \
	cdk_calendar.3 drawCDKCalendar.3 \
	cdk_calendar.3 eraseCDKCalendar.3 \
	cdk_calendar.3 getCDKCalendarBox.3 \
	cdk_calendar.3 getCDKCalendarDate.3 \
	cdk_calendar.3 getCDKCalendarDayAttribute.3 \
	cdk_calendar.3 getCDKCalendarHighlight.3 \
	cdk_calendar.3 getCDKCalendarMarker.3 \
	cdk_calendar.3 getCDKCalendarMonthAttribute.3 \
	cdk_calendar.3 getCDKCalendarYearAttribute.3 \
	cdk_calendar.3 injectCDKCalendar.3 \
	cdk_calendar.3 moveCDKCalendar.3 \
	cdk_calendar.3 newCDKCalendar.3 \
	cdk_calendar.3 positionCDKCalendar.3 \
	cdk_calendar.3 removeCDKCalendarMarker.3 \
	cdk_calendar.3 setCDKCalendar.3 \
	cdk_calendar.3 setCDKCalendarBackgroundAttrib.3 \
	cdk_calendar.3 setCDKCalendarBackgroundColor.3 \
	cdk_calendar.3 setCDKCalendarDaysNames.3 \
	cdk_calendar.3 setCDKCalendarBox.3 \
	cdk_calendar.3 setCDKCalendarDate.3 \
	cdk_calendar.3 setCDKCalendarDayAttribute.3 \
	cdk_calendar.3 setCDKCalendarHighlight.3 \
	cdk_calendar.3 setCDKCalendarMarker.3 \
	cdk_calendar.3 setCDKCalendarMonthAttribute.3 \
	cdk_calendar.3 setCDKCalendarMonthsNames.3 \
	cdk_calendar.3 setCDKCalendarPostProcess.3 \
	cdk_calendar.3 setCDKCalendarPreProcess.3 \
	cdk_calendar.3 setCDKCalendarYearAttribute.3 \
	cdk_dialog.3 activateCDKDialog.3 \
	cdk_dialog.3 destroyCDKDialog.3 \
	cdk_misc.3 Beep.3 \
	cdk_dialog.3 drawCDKDialog.3 \
	cdk_dialog.3 eraseCDKDialog.3 \
	cdk_dialog.3 getCDKDialog.3 \
	cdk_dialog.3 getCDKDialogBox.3 \
	cdk_dialog.3 getCDKDialogHighlight.3 \
	cdk_dialog.3 getCDKDialogSeparator.3 \
	cdk_dialog.3 injectCDKDialog.3 \
	cdk_dialog.3 moveCDKDialog.3 \
	cdk_dialog.3 newCDKDialog.3 \
	cdk_dialog.3 positionCDKDialog.3 \
	cdk_dialog.3 setCDKDialog.3 \
	cdk_dialog.3 setCDKDialogBackgroundAttrib.3 \
	cdk_dialog.3 setCDKDialogBackgroundColor.3 \
	cdk_dialog.3 setCDKDialogBox.3 \
	cdk_dialog.3 setCDKDialogBoxAttribute.3 \
	cdk_dialog.3 setCDKDialogHighlight.3 \
	cdk_dialog.3 setCDKDialogHorizontalChar.3 \
	cdk_dialog.3 setCDKDialogLLChar.3 \
	cdk_dialog.3 setCDKDialogLRChar.3 \
	cdk_dialog.3 setCDKDialogPostProcess.3 \
	cdk_dialog.3 setCDKDialogPreProcess.3 \
	cdk_dialog.3 setCDKDialogSeparator.3 \
	cdk_dialog.3 setCDKDialogULChar.3 \
	cdk_dialog.3 setCDKDialogURChar.3 \
	cdk_dialog.3 setCDKDialogVerticalChar.3 \
	cdk_dscale.3 activateCDKDScale.3 \
	cdk_dscale.3 destroyCDKDScale.3 \
	cdk_dscale.3 drawCDKDScale.3 \
	cdk_dscale.3 eraseCDKDScale.3 \
	cdk_dscale.3 getCDKDScaleBox.3 \
	cdk_dscale.3 getCDKDScaleDigits.3 \
	cdk_dscale.3 getCDKDScaleHighValue.3 \
	cdk_dscale.3 getCDKDScaleLowValue.3 \
	cdk_dscale.3 getCDKDScaleValue.3 \
	cdk_dscale.3 injectCDKDScale.3 \
	cdk_dscale.3 moveCDKDScale.3 \
	cdk_dscale.3 newCDKDScale.3 \
	cdk_dscale.3 positionCDKDScale.3 \
	cdk_dscale.3 setCDKDScale.3 \
	cdk_dscale.3 setCDKDScaleBackgroundAttrib.3 \
	cdk_dscale.3 setCDKDScaleBackgroundColor.3 \
	cdk_dscale.3 setCDKDScaleBox.3 \
	cdk_dscale.3 setCDKDScaleBoxAttribute.3 \
	cdk_dscale.3 setCDKDScaleDigits.3 \
	cdk_dscale.3 setCDKDScaleHorizontalChar.3 \
	cdk_dscale.3 setCDKDScaleLLChar.3 \
	cdk_dscale.3 setCDKDScaleLRChar.3 \
	cdk_dscale.3 setCDKDScaleLowHigh.3 \
	cdk_dscale.3 setCDKDScalePostProcess.3 \
	cdk_dscale.3 setCDKDScalePreProcess.3 \
	cdk_dscale.3 setCDKDScaleULChar.3 \
	cdk_dscale.3 setCDKDScaleURChar.3 \
	cdk_dscale.3 setCDKDScaleValue.3 \
	cdk_dscale.3 setCDKDScaleVerticalChar.3 \
	cdk_entry.3 activateCDKEntry.3 \
	cdk_entry.3 cleanCDKEntry.3 \
	cdk_entry.3 destroyCDKEntry.3 \
	cdk_entry.3 drawCDKEntry.3 \
	cdk_entry.3 eraseCDKEntry.3 \
	cdk_entry.3 getCDKEntryBox.3 \
	cdk_entry.3 getCDKEntryFillerChar.3 \
	cdk_entry.3 getCDKEntryHiddenChar.3 \
	cdk_entry.3 getCDKEntryMax.3 \
	cdk_entry.3 getCDKEntryMin.3 \
	cdk_entry.3 getCDKEntryValue.3 \
	cdk_entry.3 injectCDKEntry.3 \
	cdk_entry.3 moveCDKEntry.3 \
	cdk_entry.3 newCDKEntry.3 \
	cdk_entry.3 positionCDKEntry.3 \
	cdk_entry.3 setCDKEntry.3 \
	cdk_entry.3 setCDKEntryBackgroundAttrib.3 \
	cdk_entry.3 setCDKEntryBackgroundColor.3 \
	cdk_entry.3 setCDKEntryBox.3 \
	cdk_entry.3 setCDKEntryBoxAttribute.3 \
	cdk_entry.3 setCDKEntryCB.3 \
	cdk_entry.3 setCDKEntryFillerChar.3 \
	cdk_entry.3 setCDKEntryHiddenChar.3 \
	cdk_entry.3 setCDKEntryHorizontalChar.3 \
	cdk_entry.3 setCDKEntryLLChar.3 \
	cdk_entry.3 setCDKEntryLRChar.3 \
	cdk_entry.3 setCDKEntryMax.3 \
	cdk_entry.3 setCDKEntryMin.3 \
	cdk_misc.3 chlen.3 \
	cdk_entry.3 setCDKEntryPostProcess.3 \
	cdk_entry.3 setCDKEntryPreProcess.3 \
	cdk_entry.3 setCDKEntryULChar.3 \
	cdk_entry.3 setCDKEntryURChar.3 \
	cdk_entry.3 setCDKEntryValue.3 \
	cdk_entry.3 setCDKEntryVerticalChar.3 \
	cdk_fscale.3 activateCDKFScale.3 \
	cdk_fscale.3 destroyCDKFScale.3 \
	cdk_fscale.3 drawCDKFScale.3 \
	cdk_fscale.3 eraseCDKFScale.3 \
	cdk_fscale.3 getCDKFScaleBox.3 \
	cdk_fscale.3 getCDKFScaleDigits.3 \
	cdk_fscale.3 getCDKFScaleHighValue.3 \
	cdk_fscale.3 getCDKFScaleLowValue.3 \
	cdk_fscale.3 getCDKFScaleValue.3 \
	cdk_fscale.3 injectCDKFScale.3 \
	cdk_fscale.3 moveCDKFScale.3 \
	cdk_fscale.3 newCDKFScale.3 \
	cdk_fscale.3 positionCDKFScale.3 \
	cdk_fscale.3 setCDKFScale.3 \
	cdk_fscale.3 setCDKFScaleBackgroundColor.3 \
	cdk_fscale.3 setCDKFScaleBox.3 \
	cdk_fscale.3 setCDKFScaleBoxAttribute.3 \
	cdk_fscale.3 setCDKFScaleDigits.3 \
	cdk_fscale.3 setCDKFScaleHorizontalChar.3 \
	cdk_fscale.3 setCDKFScaleLLChar.3 \
	cdk_fscale.3 setCDKFScaleLRChar.3 \
	cdk_fscale.3 setCDKFScaleLowHigh.3 \
	cdk_fscale.3 setCDKFScalePostProcess.3 \
	cdk_fscale.3 setCDKFScalePreProcess.3 \
	cdk_fscale.3 setCDKFScaleULChar.3 \
	cdk_fscale.3 setCDKFScaleURChar.3 \
	cdk_fscale.3 setCDKFScaleValue.3 \
	cdk_fscale.3 setCDKFScaleVerticalChar.3 \
	cdk_fselect.3 activateCDKFselect.3 \
	cdk_fselect.3 destroyCDKFselect.3 \
	cdk_fselect.3 drawCDKFselect.3 \
	cdk_fselect.3 eraseCDKFselect.3 \
	cdk_fselect.3 getCDKFselectBox.3 \
	cdk_fselect.3 getCDKFselectDirAttribute.3 \
	cdk_fselect.3 getCDKFselectDirectory.3 \
	cdk_fselect.3 getCDKFselectFileAttribute.3 \
	cdk_fselect.3 getCDKFselectFillerChar.3 \
	cdk_fselect.3 getCDKFselectHighlight.3 \
	cdk_fselect.3 getCDKFselectLinkAttribute.3 \
	cdk_fselect.3 getCDKFselectSocketAttribute.3 \
	cdk_fselect.3 injectCDKFselect.3 \
	cdk_fselect.3 moveCDKFselect.3 \
	cdk_fselect.3 newCDKFselect.3 \
	cdk_fselect.3 positionCDKFselect.3 \
	cdk_fselect.3 setCDKFselect.3 \
	cdk_fselect.3 setCDKFselectBackgroundColor.3 \
	cdk_fselect.3 setCDKFselectBackgroundAttrib.3 \
	cdk_fselect.3 setCDKFselectBox.3 \
	cdk_fselect.3 setCDKFselectBoxAttribute.3 \
	cdk_fselect.3 setCDKFselectDirAttribute.3 \
	cdk_fselect.3 setCDKFselectDirectory.3 \
	cdk_fselect.3 setCDKFselectFileAttribute.3 \
	cdk_fselect.3 setCDKFselectFillerChar.3 \
	cdk_fselect.3 setCDKFselectHighlight.3 \
	cdk_fselect.3 setCDKFselectHorizontalChar.3 \
	cdk_fselect.3 setCDKFselectLLChar.3 \
	cdk_fselect.3 setCDKFselectLRChar.3 \
	cdk_fselect.3 setCDKFselectLinkAttribute.3 \
	cdk_fselect.3 setCDKFselectSocketAttribute.3 \
	cdk_fselect.3 setCDKFselectULChar.3 \
	cdk_fselect.3 setCDKFselectURChar.3 \
	cdk_fselect.3 setCDKFselectVerticalChar.3 \
	cdk_fslider.3 activateCDKFSlider.3 \
	cdk_fslider.3 destroyCDKFSlider.3 \
	cdk_fslider.3 drawCDKFSlider.3 \
	cdk_fslider.3 eraseCDKFSlider.3 \
	cdk_fslider.3 getCDKFSliderBox.3 \
	cdk_fslider.3 getCDKFSliderDigits.3 \
	cdk_fslider.3 getCDKFSliderHighValue.3 \
	cdk_fslider.3 getCDKFSliderLowValue.3 \
	cdk_fslider.3 getCDKFSliderValue.3 \
	cdk_fslider.3 injectCDKFSlider.3 \
	cdk_fslider.3 moveCDKFSlider.3 \
	cdk_fslider.3 newCDKFSlider.3 \
	cdk_fslider.3 positionCDKFSlider.3 \
	cdk_fslider.3 setCDKFSlider.3 \
	cdk_fslider.3 setCDKFSliderBackgroundAttrib.3 \
	cdk_fslider.3 setCDKFSliderBackgroundColor.3 \
	cdk_fslider.3 setCDKFSliderBox.3 \
	cdk_fslider.3 setCDKFSliderBoxAttribute.3 \
	cdk_fslider.3 setCDKFSliderDigits.3 \
	cdk_fslider.3 setCDKFSliderHorizontalChar.3 \
	cdk_fslider.3 setCDKFSliderLLChar.3 \
	cdk_fslider.3 setCDKFSliderLRChar.3 \
	cdk_fslider.3 setCDKFSliderLowHigh.3 \
	cdk_fslider.3 setCDKFSliderPostProcess.3 \
	cdk_fslider.3 setCDKFSliderPreProcess.3 \
	cdk_fslider.3 setCDKFSliderULChar.3 \
	cdk_fslider.3 setCDKFSliderURChar.3 \
	cdk_fslider.3 setCDKFSliderValue.3 \
	cdk_fslider.3 setCDKFSliderVerticalChar.3 \
	cdk_graph.3 destroyCDKGraph.3 \
	cdk_graph.3 drawCDKGraph.3 \
	cdk_graph.3 eraseCDKGraph.3 \
	cdk_graph.3 getCDKGraphBox.3 \
	cdk_graph.3 getCDKGraphCharacter.3 \
	cdk_graph.3 getCDKGraphCharacters.3 \
	cdk_graph.3 getCDKGraphDisplayType.3 \
	cdk_graph.3 getCDKGraphValue.3 \
	cdk_graph.3 getCDKGraphValues.3 \
	cdk_graph.3 moveCDKGraph.3 \
	cdk_graph.3 newCDKGraph.3 \
	cdk_graph.3 positionCDKGraph.3 \
	cdk_graph.3 setCDKGraph.3 \
	cdk_graph.3 setCDKGraphBackgroundAttrib.3 \
	cdk_graph.3 setCDKGraphBackgroundColor.3 \
	cdk_graph.3 setCDKGraphBox.3 \
	cdk_graph.3 setCDKGraphBoxAttribute.3 \
	cdk_graph.3 setCDKGraphCharacter.3 \
	cdk_graph.3 setCDKGraphCharacters.3 \
	cdk_graph.3 setCDKGraphDisplayType.3 \
	cdk_graph.3 setCDKGraphHorizontalChar.3 \
	cdk_graph.3 setCDKGraphLLChar.3 \
	cdk_graph.3 setCDKGraphLRChar.3 \
	cdk_graph.3 setCDKGraphULChar.3 \
	cdk_graph.3 setCDKGraphURChar.3 \
	cdk_graph.3 setCDKGraphValue.3 \
	cdk_graph.3 setCDKGraphValues.3 \
	cdk_graph.3 setCDKGraphVerticalChar.3 \
	cdk_histogram.3 destroyCDKHistogram.3 \
	cdk_histogram.3 drawCDKHistogram.3 \
	cdk_histogram.3 eraseCDKHistogram.3 \
	cdk_histogram.3 getCDKHistogramBox.3 \
	cdk_histogram.3 getCDKHistogramFillerChar.3 \
	cdk_histogram.3 getCDKHistogramHighValue.3 \
	cdk_histogram.3 getCDKHistogramLowValue.3 \
	cdk_histogram.3 getCDKHistogramStatsAttr.3 \
	cdk_histogram.3 getCDKHistogramStatsPos.3 \
	cdk_histogram.3 getCDKHistogramValue.3 \
	cdk_histogram.3 getCDKHistogramViewType.3 \
	cdk_histogram.3 moveCDKHistogram.3 \
	cdk_histogram.3 newCDKHistogram.3 \
	cdk_histogram.3 setCDKHistogram.3 \
	cdk_histogram.3 positionCDKHistogram.3 \
	cdk_histogram.3 setCDKHistogramBackgroundAttrib.3 \
	cdk_histogram.3 setCDKHistogramBackgroundColor.3 \
	cdk_histogram.3 setCDKHistogramBox.3 \
	cdk_histogram.3 setCDKHistogramBoxAttribute.3 \
	cdk_histogram.3 setCDKHistogramFillerChar.3 \
	cdk_histogram.3 setCDKHistogramHorizontalChar.3 \
	cdk_histogram.3 setCDKHistogramLLChar.3 \
	cdk_histogram.3 setCDKHistogramLRChar.3 \
	cdk_histogram.3 setCDKHistogramStatsAttr.3 \
	cdk_histogram.3 setCDKHistogramStatsPos.3 \
	cdk_histogram.3 setCDKHistogramULChar.3 \
	cdk_histogram.3 setCDKHistogramURChar.3 \
	cdk_histogram.3 setCDKHistogramValue.3 \
	cdk_histogram.3 setCDKHistogramVerticalChar.3 \
	cdk_histogram.3 setCDKHistogramViewType.3 \
	cdk_itemlist.3 activateCDKItemlist.3 \
	cdk_itemlist.3 destroyCDKItemlist.3 \
	cdk_itemlist.3 drawCDKItemlist.3 \
	cdk_itemlist.3 eraseCDKItemlist.3 \
	cdk_itemlist.3 getCDKItemlistBox.3 \
	cdk_itemlist.3 getCDKItemlistCurrentItem.3 \
	cdk_itemlist.3 getCDKItemlistDefaultItem.3 \
	cdk_itemlist.3 getCDKItemlistValues.3 \
	cdk_itemlist.3 injectCDKItemlist.3 \
	cdk_itemlist.3 moveCDKItemlist.3 \
	cdk_itemlist.3 newCDKItemlist.3 \
	cdk_itemlist.3 positionCDKItemlist.3 \
	cdk_itemlist.3 setCDKItemlist.3 \
	cdk_itemlist.3 setCDKItemlistBackgroundAttrib.3 \
	cdk_itemlist.3 setCDKItemlistBackgroundColor.3 \
	cdk_itemlist.3 setCDKItemlistBox.3 \
	cdk_itemlist.3 setCDKItemlistBoxAttribute.3 \
	cdk_itemlist.3 setCDKItemlistCurrentItem.3 \
	cdk_itemlist.3 setCDKItemlistDefaultItem.3 \
	cdk_itemlist.3 setCDKItemlistHorizontalChar.3 \
	cdk_itemlist.3 setCDKItemlistLLChar.3 \
	cdk_itemlist.3 setCDKItemlistLRChar.3 \
	cdk_itemlist.3 setCDKItemlistPostProcess.3 \
	cdk_itemlist.3 setCDKItemlistPreProcess.3 \
	cdk_itemlist.3 setCDKItemlistULChar.3 \
	cdk_itemlist.3 setCDKItemlistURChar.3 \
	cdk_itemlist.3 setCDKItemlistValues.3 \
	cdk_itemlist.3 setCDKItemlistVerticalChar.3 \
	cdk_label.3 destroyCDKLabel.3 \
	cdk_label.3 drawCDKLabel.3 \
	cdk_label.3 eraseCDKLabel.3 \
	cdk_label.3 getCDKLabelBox.3 \
	cdk_label.3 getCDKLabelMessage.3 \
	cdk_label.3 moveCDKLabel.3 \
	cdk_label.3 newCDKLabel.3 \
	cdk_label.3 positionCDKLabel.3 \
	cdk_label.3 setCDKLabel.3 \
	cdk_label.3 setCDKLabelBackgroundAttrib.3 \
	cdk_label.3 setCDKLabelBackgroundColor.3 \
	cdk_label.3 setCDKLabelBox.3 \
	cdk_label.3 setCDKLabelBoxAttribute.3 \
	cdk_label.3 setCDKLabelHorizontalChar.3 \
	cdk_label.3 setCDKLabelLLChar.3 \
	cdk_label.3 setCDKLabelLRChar.3 \
	cdk_label.3 setCDKLabelMessage.3 \
	cdk_label.3 setCDKLabelULChar.3 \
	cdk_label.3 setCDKLabelURChar.3 \
	cdk_label.3 setCDKLabelVerticalChar.3 \
	cdk_label.3 waitCDKLabel.3 \
	cdk_marquee.3 activateCDKMarquee.3 \
	cdk_marquee.3 destroyCDKMarquee.3 \
	cdk_marquee.3 drawCDKMarquee.3 \
	cdk_marquee.3 getCDKMarqueeBox.3 \
	cdk_marquee.3 eraseCDKMarquee.3 \
	cdk_marquee.3 moveCDKMarquee.3 \
	cdk_marquee.3 newCDKMarquee.3 \
	cdk_marquee.3 positionCDKMarquee.3 \
	cdk_marquee.3 setCDKMarqueeBackgroundAttrib.3 \
	cdk_marquee.3 setCDKMarqueeBackgroundColor.3 \
	cdk_marquee.3 setCDKMarqueeBox.3 \
	cdk_marquee.3 setCDKMarqueeBoxAttribute.3 \
	cdk_marquee.3 setCDKMarqueeHorizontalChar.3 \
	cdk_marquee.3 setCDKMarqueeLLChar.3 \
	cdk_marquee.3 setCDKMarqueeLRChar.3 \
	cdk_marquee.3 setCDKMarqueeULChar.3 \
	cdk_marquee.3 setCDKMarqueeURChar.3 \
	cdk_marquee.3 setCDKMarqueeVerticalChar.3 \
	cdk_matrix.3 activateCDKMatrix.3 \
	cdk_matrix.3 cleanCDKMatrix.3 \
	cdk_matrix.3 cleanCDKMatrixCell.3 \
	cdk_matrix.3 destroyCDKMatrix.3 \
	cdk_matrix.3 drawCDKMatrix.3 \
	cdk_matrix.3 eraseCDKMatrix.3 \
	cdk_matrix.3 getCDKMatrixBox.3 \
	cdk_matrix.3 getCDKMatrixCell.3 \
	cdk_matrix.3 injectCDKMatrix.3 \
	cdk_matrix.3 jumpToCell.3 \
	cdk_matrix.3 moveToCDKMatrixCell.3 \
	cdk_matrix.3 newCDKMatrix.3 \
	cdk_matrix.3 setCDKMatrix.3 \
	cdk_matrix.3 setCDKMatrixBackgroundAttrib.3 \
	cdk_matrix.3 setCDKMatrixBackgroundColor.3 \
	cdk_matrix.3 setCDKMatrixBox.3 \
	cdk_matrix.3 setCDKMatrixBoxAttribute.3 \
	cdk_matrix.3 setCDKMatrixCB.3 \
	cdk_matrix.3 setCDKMatrixCell.3 \
	cdk_matrix.3 setCDKMatrixCells.3 \
	cdk_matrix.3 setCDKMatrixHorizontalChar.3 \
	cdk_matrix.3 setCDKMatrixLLChar.3 \
	cdk_matrix.3 setCDKMatrixLRChar.3 \
	cdk_matrix.3 setCDKMatrixPostProcess.3 \
	cdk_matrix.3 setCDKMatrixPreProcess.3 \
	cdk_matrix.3 setCDKMatrixULChar.3 \
	cdk_matrix.3 setCDKMatrixURChar.3 \
	cdk_matrix.3 setCDKMatrixVerticalChar.3 \
	cdk_mentry.3 activateCDKMentry.3 \
	cdk_mentry.3 cleanCDKMentry.3 \
	cdk_mentry.3 destroyCDKMentry.3 \
	cdk_mentry.3 drawCDKMentry.3 \
	cdk_mentry.3 eraseCDKMentry.3 \
	cdk_mentry.3 getCDKMentryBox.3 \
	cdk_mentry.3 getCDKMentryFillerChar.3 \
	cdk_mentry.3 getCDKMentryMin.3 \
	cdk_mentry.3 getCDKMentryValue.3 \
	cdk_mentry.3 injectCDKMentry.3 \
	cdk_mentry.3 moveCDKMentry.3 \
	cdk_mentry.3 newCDKMentry.3 \
	cdk_mentry.3 positionCDKMentry.3 \
	cdk_mentry.3 setCDKMentry.3 \
	cdk_mentry.3 setCDKMentryBackgroundAttrib.3 \
	cdk_mentry.3 setCDKMentryBackgroundColor.3 \
	cdk_mentry.3 setCDKMentryBox.3 \
	cdk_mentry.3 setCDKMentryBoxAttribute.3 \
	cdk_mentry.3 setCDKMentryCB.3 \
	cdk_mentry.3 setCDKMentryFillerChar.3 \
	cdk_mentry.3 setCDKMentryHorizontalChar.3 \
	cdk_mentry.3 setCDKMentryLLChar.3 \
	cdk_mentry.3 setCDKMentryLRChar.3 \
	cdk_mentry.3 setCDKMentryMin.3 \
	cdk_mentry.3 setCDKMentryPostProcess.3 \
	cdk_mentry.3 setCDKMentryPreProcess.3 \
	cdk_mentry.3 setCDKMentryULChar.3 \
	cdk_mentry.3 setCDKMentryURChar.3 \
	cdk_mentry.3 setCDKMentryValue.3 \
	cdk_mentry.3 setCDKMentryVerticalChar.3 \
	cdk_menu.3 activateCDKMenu.3 \
	cdk_menu.3 destroyCDKMenu.3 \
	cdk_menu.3 drawCDKMenu.3 \
	cdk_menu.3 eraseCDKMenu.3 \
	cdk_menu.3 getCDKMenuCurrentItem.3 \
	cdk_menu.3 getCDKMenuSubTitleHighlight.3 \
	cdk_menu.3 getCDKMenuTitleHighlight.3 \
	cdk_menu.3 injectCDKMenu.3 \
	cdk_menu.3 newCDKMenu.3 \
	cdk_menu.3 setCDKMenu.3 \
	cdk_menu.3 setCDKMenuBackgroundAttrib.3 \
	cdk_menu.3 setCDKMenuBackgroundColor.3 \
	cdk_menu.3 setCDKMenuCurrentItem.3 \
	cdk_menu.3 setCDKMenuPostProcess.3 \
	cdk_menu.3 setCDKMenuPreProcess.3 \
	cdk_menu.3 setCDKMenuSubTitleHighlight.3 \
	cdk_menu.3 setCDKMenuTitleHighlight.3 \
	cdk_misc.3 CDKcountStrings.3 \
	cdk_misc.3 CDKfreeStrings.3 \
	cdk_misc.3 CDKgetDirectoryContents.3 \
	cdk_misc.3 CDKreadFile.3 \
	cdk_misc.3 CDKsplitString.3 \
	cdk_misc.3 baseName.3 \
	cdk_misc.3 char2Chtype.3 \
	cdk_misc.3 chtype2Char.3 \
	cdk_misc.3 cleanChar.3 \
	cdk_misc.3 cleanChtype.3 \
	cdk_misc.3 copyChar.3 \
	cdk_misc.3 copyChtype.3 \
	cdk_misc.3 freeChar.3 \
	cdk_misc.3 freeChtype.3 \
	cdk_misc.3 getListIndex.3 \
	cdk_misc.3 getString.3 \
	cdk_misc.3 intlen.3 \
	cdk_misc.3 mode2Char.3 \
	cdk_misc.3 popupDialog.3 \
	cdk_misc.3 popupLabel.3 \
	cdk_misc.3 searchList.3 \
	cdk_misc.3 sortList.3 \
	cdk_misc.3 stripWhiteSpace.3 \
	cdk_misc.3 viewFile.3 \
	cdk_radio.3 activateCDKRadio.3 \
	cdk_radio.3 destroyCDKRadio.3 \
	cdk_radio.3 drawCDKRadio.3 \
	cdk_radio.3 eraseCDKRadio.3 \
	cdk_radio.3 getCDKRadioBox.3 \
	cdk_radio.3 getCDKRadioChoiceCharacter.3 \
	cdk_radio.3 getCDKRadioHighlight.3 \
	cdk_radio.3 getCDKRadioLeftBrace.3 \
	cdk_radio.3 injectCDKRadio.3 \
	cdk_radio.3 getCDKRadioRightBrace.3 \
	cdk_radio.3 moveCDKRadio.3 \
	cdk_radio.3 newCDKRadio.3 \
	cdk_radio.3 positionCDKRadio.3 \
	cdk_radio.3 setCDKRadio.3 \
	cdk_radio.3 setCDKRadioBackgroundAttrib.3 \
	cdk_radio.3 setCDKRadioBackgroundColor.3 \
	cdk_radio.3 setCDKRadioBox.3 \
	cdk_radio.3 setCDKRadioBoxAttribute.3 \
	cdk_radio.3 setCDKRadioChoiceCharacter.3 \
	cdk_radio.3 setCDKRadioHighlight.3 \
	cdk_radio.3 setCDKRadioHorizontalChar.3 \
	cdk_radio.3 setCDKRadioLLChar.3 \
	cdk_radio.3 setCDKRadioLRChar.3 \
	cdk_radio.3 setCDKRadioLeftBrace.3 \
	cdk_radio.3 setCDKRadioPostProcess.3 \
	cdk_radio.3 setCDKRadioPreProcess.3 \
	cdk_radio.3 setCDKRadioRightBrace.3 \
	cdk_radio.3 setCDKRadioULChar.3 \
	cdk_radio.3 setCDKRadioURChar.3 \
	cdk_radio.3 setCDKRadioVerticalChar.3 \
	cdk_scale.3 activateCDKScale.3 \
	cdk_scale.3 destroyCDKScale.3 \
	cdk_scale.3 drawCDKScale.3 \
	cdk_scale.3 eraseCDKScale.3 \
	cdk_scale.3 getCDKScaleBox.3 \
	cdk_scale.3 getCDKScaleHighValue.3 \
	cdk_scale.3 getCDKScaleLowValue.3 \
	cdk_scale.3 getCDKScaleValue.3 \
	cdk_scale.3 injectCDKScale.3 \
	cdk_scale.3 moveCDKScale.3 \
	cdk_scale.3 newCDKScale.3 \
	cdk_scale.3 positionCDKScale.3 \
	cdk_scale.3 setCDKScale.3 \
	cdk_scale.3 setCDKScaleBackgroundAttrib.3 \
	cdk_scale.3 setCDKFScaleBackgroundAttrib.3 \
	cdk_scale.3 setCDKScaleBackgroundColor.3 \
	cdk_scale.3 setCDKScaleBox.3 \
	cdk_scale.3 setCDKScaleBoxAttribute.3 \
	cdk_scale.3 setCDKScaleHorizontalChar.3 \
	cdk_scale.3 setCDKScaleLLChar.3 \
	cdk_scale.3 setCDKScaleLRChar.3 \
	cdk_scale.3 setCDKScaleLowHigh.3 \
	cdk_scale.3 setCDKScalePostProcess.3 \
	cdk_scale.3 setCDKScalePreProcess.3 \
	cdk_scale.3 setCDKScaleULChar.3 \
	cdk_scale.3 setCDKScaleURChar.3 \
	cdk_scale.3 setCDKScaleValue.3 \
	cdk_scale.3 setCDKScaleVerticalChar.3 \
	cdk_screen.3 destroyCDKScreen.3 \
	cdk_screen.3 endCDK.3 \
	cdk_screen.3 initCDKColor.3 \
	cdk_screen.3 eraseCDKScreen.3 \
	cdk_screen.3 initCDKScreen.3 \
	cdk_screen.3 lowerCDKObject.3 \
	cdk_screen.3 raiseCDKObject.3 \
	cdk_screen.3 refreshCDKScreen.3 \
	cdk_screen.3 registerCDKObject.3 \
	cdk_screen.3 unregisterCDKObject.3 \
	cdk_scroll.3 activateCDKScroll.3 \
	cdk_scroll.3 addCDKScrollItem.3 \
	cdk_scroll.3 deleteCDKScrollItem.3 \
	cdk_scroll.3 destroyCDKScroll.3 \
	cdk_scroll.3 drawCDKScroll.3 \
	cdk_scroll.3 eraseCDKScroll.3 \
	cdk_scroll.3 getCDKScrollBox.3 \
	cdk_scroll.3 getCDKScrollHighlight.3 \
	cdk_scroll.3 getCDKScrollItems.3 \
	cdk_scroll.3 injectCDKScroll.3 \
	cdk_scroll.3 moveCDKScroll.3 \
	cdk_scroll.3 newCDKScroll.3 \
	cdk_scroll.3 positionCDKScroll.3 \
	cdk_scroll.3 setCDKScroll.3 \
	cdk_scroll.3 setCDKScrollBackgroundAttrib.3 \
	cdk_scroll.3 setCDKScrollBackgroundColor.3 \
	cdk_scroll.3 setCDKScrollBox.3 \
	cdk_scroll.3 setCDKScrollBoxAttribute.3 \
	cdk_scroll.3 setCDKScrollHighlight.3 \
	cdk_scroll.3 setCDKScrollHorizontalChar.3 \
	cdk_scroll.3 setCDKScrollItems.3 \
	cdk_scroll.3 setCDKScrollLLChar.3 \
	cdk_scroll.3 setCDKScrollLRChar.3 \
	cdk_scroll.3 setCDKScrollPostProcess.3 \
	cdk_scroll.3 setCDKScrollPreProcess.3 \
	cdk_scroll.3 setCDKScrollULChar.3 \
	cdk_scroll.3 setCDKScrollURChar.3 \
	cdk_scroll.3 setCDKScrollVerticalChar.3 \
	cdk_selection.3 activateCDKSelection.3 \
	cdk_selection.3 destroyCDKSelection.3 \
	cdk_selection.3 drawCDKSelection.3 \
	cdk_selection.3 eraseCDKSelection.3 \
	cdk_selection.3 getCDKSelectionBox.3 \
	cdk_selection.3 getCDKSelectionChoice.3 \
	cdk_selection.3 getCDKSelectionChoices.3 \
	cdk_selection.3 getCDKSelectionHighlight.3 \
	cdk_selection.3 getCDKSelectionMode.3 \
	cdk_selection.3 getCDKSelectionModes.3 \
	cdk_selection.3 injectCDKSelection.3 \
	cdk_selection.3 moveCDKSelection.3 \
	cdk_selection.3 newCDKSelection.3 \
	cdk_selection.3 positionCDKSelection.3 \
	cdk_selection.3 setCDKSelection.3 \
	cdk_selection.3 setCDKSelectionBackgroundAttrib.3 \
	cdk_selection.3 setCDKSelectionBackgroundColor.3 \
	cdk_selection.3 setCDKSelectionBox.3 \
	cdk_selection.3 setCDKSelectionBoxAttribute.3 \
	cdk_selection.3 setCDKSelectionChoice.3 \
	cdk_selection.3 setCDKSelectionChoices.3 \
	cdk_selection.3 setCDKSelectionHighlight.3 \
	cdk_selection.3 setCDKSelectionHorizontalChar.3 \
	cdk_selection.3 setCDKSelectionLLChar.3 \
	cdk_selection.3 setCDKSelectionLRChar.3 \
	cdk_selection.3 setCDKSelectionMode.3 \
	cdk_selection.3 setCDKSelectionModes.3 \
	cdk_selection.3 setCDKSelectionPostProcess.3 \
	cdk_selection.3 setCDKSelectionPreProcess.3 \
	cdk_selection.3 setCDKSelectionULChar.3 \
	cdk_selection.3 setCDKSelectionURChar.3 \
	cdk_selection.3 setCDKSelectionVerticalChar.3 \
	cdk_slider.3 activateCDKSlider.3 \
	cdk_slider.3 destroyCDKSlider.3 \
	cdk_slider.3 drawCDKSlider.3 \
	cdk_slider.3 eraseCDKSlider.3 \
	cdk_slider.3 getCDKSliderBox.3 \
	cdk_slider.3 getCDKSliderHighValue.3 \
	cdk_slider.3 getCDKSliderLowValue.3 \
	cdk_slider.3 getCDKSliderValue.3 \
	cdk_slider.3 injectCDKSlider.3 \
	cdk_slider.3 moveCDKSlider.3 \
	cdk_slider.3 newCDKSlider.3 \
	cdk_slider.3 positionCDKSlider.3 \
	cdk_slider.3 setCDKSlider.3 \
	cdk_slider.3 setCDKSliderBox.3 \
	cdk_slider.3 setCDKSliderBackgroundAttrib.3 \
	cdk_slider.3 setCDKSliderBackgroundColor.3 \
	cdk_slider.3 setCDKSliderBoxAttribute.3 \
	cdk_slider.3 setCDKSliderHorizontalChar.3 \
	cdk_slider.3 setCDKSliderLLChar.3 \
	cdk_slider.3 setCDKSliderLRChar.3 \
	cdk_slider.3 setCDKSliderLowHigh.3 \
	cdk_slider.3 setCDKSliderPostProcess.3 \
	cdk_slider.3 setCDKSliderPreProcess.3 \
	cdk_slider.3 setCDKSliderULChar.3 \
	cdk_slider.3 setCDKSliderURChar.3 \
	cdk_slider.3 setCDKSliderValue.3 \
	cdk_slider.3 setCDKSliderVerticalChar.3 \
	cdk_swindow.3 activateCDKSwindow.3 \
	cdk_swindow.3 addCDKSwindow.3 \
	cdk_swindow.3 cleanCDKSwindow.3 \
	cdk_swindow.3 destroyCDKSwindow.3 \
	cdk_swindow.3 drawCDKSwindow.3 \
	cdk_swindow.3 dumpCDKSwindow.3 \
	cdk_swindow.3 dumpCDKSwindowInformation.3 \
	cdk_swindow.3 eraseCDKSwindow.3 \
	cdk_swindow.3 execCDKSwindow.3 \
	cdk_swindow.3 getCDKSwindowBox.3 \
	cdk_swindow.3 getCDKSwindowContents.3 \
	cdk_swindow.3 injectCDKSwindow.3 \
	cdk_swindow.3 jumpToLineCDKSwindow.3 \
	cdk_swindow.3 loadCDKSwindowInformation.3 \
	cdk_swindow.3 moveCDKSwindow.3 \
	cdk_swindow.3 newCDKSwindow.3 \
	cdk_swindow.3 positionCDKSwindow.3 \
	cdk_swindow.3 saveCDKSwindowInformation.3 \
	cdk_swindow.3 setCDKSwindow.3 \
	cdk_swindow.3 setCDKSwindowBackgroundAttrib.3 \
	cdk_swindow.3 setCDKSwindowBackgroundColor.3 \
	cdk_swindow.3 setCDKSwindowBox.3 \
	cdk_swindow.3 setCDKSwindowBoxAttribute.3 \
	cdk_swindow.3 setCDKSwindowContents.3 \
	cdk_swindow.3 setCDKSwindowHorizontalChar.3 \
	cdk_swindow.3 setCDKSwindowLLChar.3 \
	cdk_swindow.3 setCDKSwindowLRChar.3 \
	cdk_swindow.3 setCDKSwindowPostProcess.3 \
	cdk_swindow.3 setCDKSwindowPreProcess.3 \
	cdk_swindow.3 setCDKSwindowULChar.3 \
	cdk_swindow.3 setCDKSwindowURChar.3 \
	cdk_swindow.3 setCDKSwindowVerticalChar.3 \
	cdk_swindow.3 trimCDKSwindow.3 \
	cdk_template.3 activateCDKTemplate.3 \
	cdk_template.3 cleanCDKTemplate.3 \
	cdk_template.3 destroyCDKTemplate.3 \
	cdk_template.3 drawCDKTemplate.3 \
	cdk_template.3 eraseCDKTemplate.3 \
	cdk_template.3 getCDKTemplateBox.3 \
	cdk_template.3 getCDKTemplateMin.3 \
	cdk_template.3 getCDKTemplateValue.3 \
	cdk_template.3 injectCDKTemplate.3 \
	cdk_template.3 mixCDKTemplate.3 \
	cdk_template.3 newCDKTemplate.3 \
	cdk_template.3 setCDKTemplate.3 \
	cdk_template.3 setCDKTemplateBackgroundAttrib.3 \
	cdk_template.3 setCDKTemplateBackgroundColor.3 \
	cdk_template.3 setCDKTemplateBox.3 \
	cdk_template.3 setCDKTemplateBoxAttribute.3 \
	cdk_template.3 setCDKTemplateCB.3 \
	cdk_template.3 setCDKTemplateHorizontalChar.3 \
	cdk_template.3 setCDKTemplateLLChar.3 \
	cdk_template.3 setCDKTemplateLRChar.3 \
	cdk_template.3 setCDKTemplateMin.3 \
	cdk_template.3 setCDKTemplatePostProcess.3 \
	cdk_template.3 setCDKTemplatePreProcess.3 \
	cdk_template.3 setCDKTemplateULChar.3 \
	cdk_template.3 setCDKTemplateURChar.3 \
	cdk_template.3 setCDKTemplateValue.3 \
	cdk_template.3 setCDKTemplateVerticalChar.3 \
	cdk_template.3 unmixCDKTemplate.3 \
	cdk_traverse.3 exitCancelCDKScreen.3 \
	cdk_traverse.3 exitCancelCDKScreenOf.3 \
	cdk_traverse.3 exitOKCDKScreen.3 \
	cdk_traverse.3 exitOKCDKScreenOf.3 \
	cdk_traverse.3 resetCDKScreen.3 \
	cdk_traverse.3 resetCDKScreenOf.3 \
	cdk_traverse.3 traverseCDKScreen.3 \
	cdk_viewer.3 activateCDKViewer.3 \
	cdk_viewer.3 cleanCDKViewer.3 \
	cdk_viewer.3 destroyCDKViewer.3 \
	cdk_viewer.3 drawCDKViewer.3 \
	cdk_viewer.3 eraseCDKViewer.3 \
	cdk_viewer.3 getCDKViewerBox.3 \
	cdk_viewer.3 getCDKViewerHighlight.3 \
	cdk_viewer.3 getCDKViewerInfo.3 \
	cdk_viewer.3 getCDKViewerInfoLine.3 \
	cdk_viewer.3 getCDKViewerTitle.3 \
	cdk_viewer.3 moveCDKViewer.3 \
	cdk_viewer.3 newCDKViewer.3 \
	cdk_viewer.3 positionCDKViewer.3 \
	cdk_viewer.3 setCDKViewer.3 \
	cdk_viewer.3 setCDKViewerBackgroundAttrib.3 \
	cdk_viewer.3 setCDKViewerBackgroundColor.3 \
	cdk_viewer.3 setCDKViewerBox.3 \
	cdk_viewer.3 setCDKViewerBoxAttribute.3 \
	cdk_viewer.3 setCDKViewerHighlight.3 \
	cdk_viewer.3 setCDKViewerHorizontalChar.3 \
	cdk_viewer.3 setCDKViewerInfo.3 \
	cdk_viewer.3 setCDKViewerInfoLine.3 \
	cdk_viewer.3 setCDKViewerLLChar.3 \
	cdk_viewer.3 setCDKViewerLRChar.3 \
	cdk_viewer.3 setCDKViewerTitle.3 \
	cdk_viewer.3 setCDKViewerULChar.3 \
	cdk_viewer.3 setCDKViewerURChar.3 \
	cdk_viewer.3 setCDKViewerVerticalChar.3 \
	cdk_uscale.3 activateCDKUScale.3 \
	cdk_uscale.3 destroyCDKUScale.3 \
	cdk_uscale.3 drawCDKUScale.3 \
	cdk_uscale.3 eraseCDKUScale.3 \
	cdk_uscale.3 getCDKUScaleBox.3 \
	cdk_uscale.3 getCDKUScaleHighValue.3 \
	cdk_uscale.3 getCDKUScaleLowValue.3 \
	cdk_uscale.3 getCDKUScaleValue.3 \
	cdk_uscale.3 injectCDKUScale.3 \
	cdk_uscale.3 moveCDKUScale.3 \
	cdk_uscale.3 newCDKUScale.3 \
	cdk_uscale.3 positionCDKUScale.3 \
	cdk_uscale.3 setCDKUScale.3 \
	cdk_uscale.3 setCDKUScaleBackgroundAttrib.3 \
	cdk_uscale.3 setCDKUScaleBackgroundColor.3 \
	cdk_uscale.3 setCDKUScaleBox.3 \
	cdk_uscale.3 setCDKUScaleBoxAttribute.3 \
	cdk_uscale.3 setCDKUScaleHorizontalChar.3 \
	cdk_uscale.3 setCDKUScaleLLChar.3 \
	cdk_uscale.3 setCDKUScaleLRChar.3 \
	cdk_uscale.3 setCDKUScaleLowHigh.3 \
	cdk_uscale.3 setCDKUScalePostProcess.3 \
	cdk_uscale.3 setCDKUScalePreProcess.3 \
	cdk_uscale.3 setCDKUScaleULChar.3 \
	cdk_uscale.3 setCDKUScaleURChar.3 \
	cdk_uscale.3 setCDKUScaleValue.3 \
	cdk_uscale.3 setCDKUScaleVerticalChar.3 \
	cdk_uslider.3 activateCDKUSlider.3 \
	cdk_uslider.3 destroyCDKUSlider.3 \
	cdk_uslider.3 drawCDKUSlider.3 \
	cdk_uslider.3 eraseCDKUSlider.3 \
	cdk_uslider.3 getCDKUSliderBox.3 \
	cdk_uslider.3 getCDKUSliderHighValue.3 \
	cdk_uslider.3 getCDKUSliderLowValue.3 \
	cdk_uslider.3 getCDKUSliderValue.3 \
	cdk_uslider.3 injectCDKUSlider.3 \
	cdk_uslider.3 moveCDKUSlider.3 \
	cdk_uslider.3 newCDKUSlider.3 \
	cdk_uslider.3 positionCDKUSlider.3 \
	cdk_uslider.3 setCDKUSlider.3 \
	cdk_uslider.3 setCDKUSliderBackgroundAttrib.3 \
	cdk_uslider.3 setCDKUSliderBackgroundColor.3 \
	cdk_uslider.3 setCDKUSliderBox.3 \
	cdk_uslider.3 setCDKUSliderBoxAttribute.3 \
	cdk_uslider.3 setCDKUSliderHorizontalChar.3 \
	cdk_uslider.3 setCDKUSliderLLChar.3 \
	cdk_uslider.3 setCDKUSliderLRChar.3 \
	cdk_uslider.3 setCDKUSliderLowHigh.3 \
	cdk_uslider.3 setCDKUSliderPostProcess.3 \
	cdk_uslider.3 setCDKUSliderPreProcess.3 \
	cdk_uslider.3 setCDKUSliderULChar.3 \
	cdk_uslider.3 setCDKUSliderURChar.3 \
	cdk_uslider.3 setCDKUSliderValue.3 \
	cdk_uslider.3 setCDKUSliderVerticalChar.3
