# New ports collection makefile for:	postgresql7-client
# Date created:		18.Nov 2003
# Whom:			dirk.meyer@dinoex.sub.org
#
# $FreeBSD$

CATEGORIES=	databases

MAINTAINER=	dinoex@FreeBSD.org

MASTERDIR?=	${.CURDIR}/../postgresql7
WITHOUT_SERVER=yes

.if exists(${.CURDIR}/Makefile.local)
.include "${.CURDIR}/Makefile.local"
.endif

.include "${MASTERDIR}/Makefile"
