--- build/config/linux/BUILD.gn.orig	2026-08-13 16:48:13 UTC
+++ build/config/linux/BUILD.gn
@@ -40,7 +40,7 @@ config("runtime_library") {
   }
 
   if ((!is_chromeos || default_toolchain != "//build/toolchain/cros:target") &&
-      (!use_custom_libcxx || current_cpu == "mipsel")) {
+      (!use_custom_libcxx || current_cpu == "mipsel") && !is_bsd) {
     libs = [ "atomic" ]
   }
 }
