--- pyproject.toml.orig	2026-06-28 02:09:21 UTC
+++ pyproject.toml
@@ -45,7 +45,7 @@ mutmut = "mutmut.__main__:cli"
 mutmut = "mutmut.__main__:cli"
 
 [build-system]
-requires = ["uv_build>=0.9.5,<0.10.0"]
+requires = ["uv_build>=0.9.5"]
 build-backend = "uv_build"
 
 [tool.uv.build-backend]
