--- pyproject.toml.orig	2026-06-06 23:44:38 UTC
+++ pyproject.toml
@@ -1,5 +1,5 @@
 [build-system]
-requires = ["setuptools>=80.0.0", "setuptools-scm"]
+requires = ["setuptools>=63", "setuptools-scm"]
 build-backend = "setuptools.build_meta"
 
 [project]
@@ -7,7 +7,7 @@ readme = "README.md"
 dynamic = ["version"]
 description = "Logical unification in Python"
 readme = "README.md"
-license = "BSD-3-Clause"
+license = {text = "BSD-3-Clause"}
 authors = [
     { name = "Brandon T. Willard", email = "brandonwillard+unification@gmail.com" },
 ]
