# New ports collection makefile for:	cedet-emacs22
# Date created:				01 Mar 2007
# Whom:					Max N. Boyarov <m.boyarov@bsd.by>
#
# $FreeBSD$

MASTERDIR=	${.CURDIR}/../cedet

MAINTAINER=		m.boyarov@bsd.by

EMACS_PORT_NAME=	emacs22

.include "${MASTERDIR}/Makefile"
