# Created by: lars.eggert@gmx.net
# $FreeBSD$

PORTNAME=	Algorithm-ChooseSubsets
PORTVERSION=	0.02
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	lars.eggert@gmx.net
COMMENT=	Perl algorithm to iterate through subsets of a list

USES=		perl5
USE_PERL5=	configure

MAN3=		Algorithm::ChooseSubsets.3

NO_STAGE=	yes
.include <bsd.port.mk>
