# New ports collection makefile for:    freeze
# Date created:         20 Jul 1996
# Whom:                 lukin@okbmei.msk.su
#
# $FreeBSD$
#

PORTNAME=	freeze
PORTVERSION=	2.5
PORTREVISION=	1
CATEGORIES=	archivers
MASTER_SITES=	ftp://ftp.warwick.ac.uk/pub/compression/

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Compression program - often used in QNX

GNU_CONFIGURE=	yes
ALL_TARGET=	prog
MAN1=		freeze.1 melt.1 unfreeze.1 fcat.1 statist.1
PLIST_FILES=	bin/fcat bin/freeze bin/melt bin/statist bin/unfreeze

.include <bsd.port.mk>
