diff -ur /usr/Arch/Nokia/Gammu/gammu-0.90.0/cfg/config.h ./cfg/config.h
--- /usr/Arch/Nokia/Gammu/gammu-0.90.0/cfg/config.h	Tue Nov 25 19:24:12 2003
+++ ./cfg/config.h	Tue Dec  9 16:59:39 2003
@@ -1,4 +1,4 @@
-/* config.h.  Generated automatically by configure.  */
+/* config.h.  Generated by configure.  */
 
 #ifndef _config_h_
 #define _config_h_
@@ -45,20 +45,20 @@
 #define GSM_ENABLE_ALCABUS 1
 
 /* Infrared. PHONET FBUS */
-#define GSM_ENABLE_IRDAPHONET 1
+/* #undef GSM_ENABLE_IRDAPHONET */
 /* Infrared. AT commands */
-#define GSM_ENABLE_IRDAAT 1
+/* #undef GSM_ENABLE_IRDAAT */
 /* Infrared. OBEX */
-#define GSM_ENABLE_IRDAOBEX 1
+/* #undef GSM_ENABLE_IRDAOBEX */
 
 /* Bluetooth stack (like Bluez). FBUS2 (init done using AT commands) */
-/* #undef GSM_ENABLE_BLUEFBUS2 */
+#define GSM_ENABLE_BLUEFBUS2 1
 /* Bluetooth stack (like Bluez). PHONET FBUS */
-/* #undef GSM_ENABLE_BLUEPHONET */
+#define GSM_ENABLE_BLUEPHONET 1
 /* Blueooth stack (like Bluez). AT commands */
-/* #undef GSM_ENABLE_BLUEAT */
+#define GSM_ENABLE_BLUEAT 1
 /* Blueooth stack (like Bluez). OBEX */
-/* #undef GSM_ENABLE_BLUEOBEX */
+#define GSM_ENABLE_BLUEOBEX 1
 
 /* --------------------------- Phone modules (specific) ----------------- */
 
@@ -93,7 +93,7 @@
 #define GSM_ENABLE_ALCATEL 1
 
 /* OBEX generic models */
-#define GSM_ENABLE_OBEXGEN 1
+/* #undef GSM_ENABLE_OBEXGEN */
 
 /* Symbian with m-router generic models */
 #define GSM_ENABLE_MROUTERGEN 1
