--- pyproject.toml.orig	2023-10-22 17:41:30 UTC
+++ pyproject.toml
@@ -1,5 +1,5 @@
 [build-system]
-requires = ["setuptools >= 64"]
+requires = ["setuptools >= 63"]
 build-backend = "setuptools.build_meta"
 
 [project]
