pgsql/bin/pgaccess
pgsql/bin/pgtclsh
pgsql/bin/pgtksh
pgsql/include/libpgtcl.h
pgsql/lib/libpgtcl.a
pgsql/lib/libpgtcl.so
pgsql/lib/libpgtcl.so.2
pgsql/lib/pltcl.so
share/pgaccess/images/icon_button.gif
share/pgaccess/images/icon_checkbutton.gif
share/pgaccess/images/icon_entry.gif
share/pgaccess/images/icon_frame.gif
share/pgaccess/images/icon_label.gif
share/pgaccess/images/icon_listbox.gif
share/pgaccess/images/icon_query.gif
share/pgaccess/images/icon_radiobutton.gif
share/pgaccess/images/icon_text.gif
share/pgaccess/lib/database.tcl
share/pgaccess/lib/forms.tcl
share/pgaccess/lib/functions.tcl
share/pgaccess/lib/help/abort.hlp
share/pgaccess/lib/help/add_records.hlp
share/pgaccess/lib/help/alter_table.hlp
share/pgaccess/lib/help/alter_user.hlp
share/pgaccess/lib/help/author.hlp
share/pgaccess/lib/help/begin.hlp
share/pgaccess/lib/help/close.hlp
share/pgaccess/lib/help/cluster.hlp
share/pgaccess/lib/help/commit.hlp
share/pgaccess/lib/help/copy.hlp
share/pgaccess/lib/help/copyrights.hlp
share/pgaccess/lib/help/create_aggregate.hlp
share/pgaccess/lib/help/create_database.hlp
share/pgaccess/lib/help/create_function.hlp
share/pgaccess/lib/help/create_index.hlp
share/pgaccess/lib/help/create_language.hlp
share/pgaccess/lib/help/create_operator.hlp
share/pgaccess/lib/help/create_rule.hlp
share/pgaccess/lib/help/create_sequence.hlp
share/pgaccess/lib/help/create_table.hlp
share/pgaccess/lib/help/create_table_as.hlp
share/pgaccess/lib/help/create_trigger.hlp
share/pgaccess/lib/help/create_type.hlp
share/pgaccess/lib/help/create_user.hlp
share/pgaccess/lib/help/create_view.hlp
share/pgaccess/lib/help/data_types.hlp
share/pgaccess/lib/help/datefunc.hlp
share/pgaccess/lib/help/declare.hlp
share/pgaccess/lib/help/delete.hlp
share/pgaccess/lib/help/drop_aggregate.hlp
share/pgaccess/lib/help/drop_database.hlp
share/pgaccess/lib/help/drop_function.hlp
share/pgaccess/lib/help/drop_index.hlp
share/pgaccess/lib/help/drop_language.hlp
share/pgaccess/lib/help/drop_operator.hlp
share/pgaccess/lib/help/drop_rule.hlp
share/pgaccess/lib/help/drop_sequence.hlp
share/pgaccess/lib/help/drop_table.hlp
share/pgaccess/lib/help/drop_trigger.hlp
share/pgaccess/lib/help/drop_type.hlp
share/pgaccess/lib/help/drop_user.hlp
share/pgaccess/lib/help/drop_view.hlp
share/pgaccess/lib/help/explain.hlp
share/pgaccess/lib/help/fetch.hlp
share/pgaccess/lib/help/form_design.hlp
share/pgaccess/lib/help/forms.hlp
share/pgaccess/lib/help/functions.hlp
share/pgaccess/lib/help/geomfunc.hlp
share/pgaccess/lib/help/grant.hlp
share/pgaccess/lib/help/history.hlp
share/pgaccess/lib/help/index.hlp
share/pgaccess/lib/help/inheritance.hlp
share/pgaccess/lib/help/insert.hlp
share/pgaccess/lib/help/ipv4func.hlp
share/pgaccess/lib/help/isolation.hlp
share/pgaccess/lib/help/keywords.hlp
share/pgaccess/lib/help/listen.hlp
share/pgaccess/lib/help/load.hlp
share/pgaccess/lib/help/lock.hlp
share/pgaccess/lib/help/mathfunc.hlp
share/pgaccess/lib/help/move.hlp
share/pgaccess/lib/help/mvcc.hlp
share/pgaccess/lib/help/new_query.hlp
share/pgaccess/lib/help/new_table.hlp
share/pgaccess/lib/help/notify.hlp
share/pgaccess/lib/help/open_query.hlp
share/pgaccess/lib/help/open_table.hlp
share/pgaccess/lib/help/pgfunctions.hlp
share/pgaccess/lib/help/postgresql.hlp
share/pgaccess/lib/help/queries.hlp
share/pgaccess/lib/help/reports.hlp
share/pgaccess/lib/help/reset.hlp
share/pgaccess/lib/help/revoke.hlp
share/pgaccess/lib/help/rollback.hlp
share/pgaccess/lib/help/schema.hlp
share/pgaccess/lib/help/scripts.hlp
share/pgaccess/lib/help/select.hlp
share/pgaccess/lib/help/select_into.hlp
share/pgaccess/lib/help/sequences.hlp
share/pgaccess/lib/help/set.hlp
share/pgaccess/lib/help/show.hlp
share/pgaccess/lib/help/sql_guide.hlp
share/pgaccess/lib/help/sqlfunc.hlp
share/pgaccess/lib/help/stringfunc.hlp
share/pgaccess/lib/help/tables.hlp
share/pgaccess/lib/help/unlisten.hlp
share/pgaccess/lib/help/update.hlp
share/pgaccess/lib/help/users.hlp
share/pgaccess/lib/help/vacuum.hlp
share/pgaccess/lib/help/view_table_structure.hlp
share/pgaccess/lib/help/views.hlp
share/pgaccess/lib/help/visual_designer.hlp
share/pgaccess/lib/help/y2k.hlp
share/pgaccess/lib/help.tcl
share/pgaccess/lib/languages/czech
share/pgaccess/lib/languages/deutsch
share/pgaccess/lib/languages/francais
share/pgaccess/lib/languages/italiano
share/pgaccess/lib/languages/magyar
share/pgaccess/lib/languages/portugues
share/pgaccess/lib/languages/romana
share/pgaccess/lib/languages/russian.koi8r
share/pgaccess/lib/languages/russian_win
share/pgaccess/lib/languages/spanish
share/pgaccess/lib/mainlib.tcl
share/pgaccess/lib/preferences.tcl
share/pgaccess/lib/queries.tcl
share/pgaccess/lib/reports.tcl
share/pgaccess/lib/schema.tcl
share/pgaccess/lib/scripts.tcl
share/pgaccess/lib/sequences.tcl
share/pgaccess/lib/tables.tcl
share/pgaccess/lib/users.tcl
share/pgaccess/lib/views.tcl
share/pgaccess/lib/visualqb.tcl
share/pgaccess/main.tcl
@dirrm pgsql/pgaccess/images
@dirrm pgsql/pgaccess/lib/help
@dirrm pgsql/pgaccess/lib/languages
@dirrm pgsql/pgaccess/lib
@dirrm pgsql/pgaccess
