$FreeBSD$

--- build/make/configure.sh.orig	2014-12-03 18:11:14.000000000 +0100
+++ build/make/configure.sh	2014-12-03 20:20:00.000000000 +0100
@@ -382,6 +382,7 @@
     print_webm_license config.mk "##" ""
     echo '# This file automatically generated by configure. Do not edit!' >> config.mk
     echo "TOOLCHAIN := ${toolchain}" >> config.mk
+    echo "CLANG_NO_IAS=${CLANG_NO_IAS}" >> config.mk
 
     case ${toolchain} in
         *-linux-rvct)
@@ -1019,7 +1019,7 @@ EOF
         bits=32
         enabled x86_64 && bits=64
         check_cpp <<EOF && bits=x32
-#ifndef __ILP32__
+#if !defined(__ILP32__) || !defined(__x86_64__)
 #error "not x32"
 #endif
 EOF
