PORTNAME=	whatmask
PORTVERSION=	1.2
PORTREVISION=	3
CATEGORIES=	net-mgmt
MASTER_SITES=	http://downloads.laffeycomputer.com/current_builds/whatmask/

MAINTAINER=	adamw@FreeBSD.org
COMMENT=	Convert between common subnet mask notations
WWW=		http://www.laffeycomputer.com/whatmask.html

LICENSE=	GPLv2
LICENSE_FILE=	${WRKSRC}/COPYING

GNU_CONFIGURE=	yes
GNU_CONFIGURE_MANPREFIX=	${PREFIX}/share

.include <bsd.port.mk>
