'\" t
.\"     Title: pixz
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 06/06/2013
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "PIXZ" "1" "06/06/2013" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
pixz \- parallel, indexed xz compressor
.SH "SYNOPSIS"
.sp
\fBpixz\fR [\fIOPTIONS\fR] [\fIINPUT\fR [\fIOUTPUT\fR]]
.SH "DESCRIPTION"
.sp
pixz compresses and decompresses files using multiple processors\&. If the input looks like a tar(1) archive, it also creates an index of all the files in the archive\&. This allows the extraction of only a small segment of the tarball, without needing to decompress the entire archive\&.
.SH "OPTIONS"
.sp
By default, pixz uses standard input and output, unless \fIINPUT\fR and \fIOUTPUT\fR arguments are provided\&. If pixz is provided with input but no output, it will delete the input once it\(cqs done\&.
.PP
\fB\-d\fR
.RS 4
Decompress, instead of compress\&.
.RE
.PP
\fB\-t\fR
.RS 4
Force non\-tarball mode\&. By default, pixz auto\-detects tar data, and if found enters tarball mode\&. When compressing in non\-tarball mode, no archive index will be created\&. When decompressing, fast extraction will not be available\&.
.RE
.PP
\fB\-l\fR
.RS 4
List the archive contents\&. In tarball mode, lists the files in the tarball\&. In non\-tarball mode, lists the blocks of compressed data\&.
.RE
.PP
\fB\-x\fR \fIPATH\fR
.RS 4
Extract certain members from an archive, quickly\&. All members whose path begins with
\fIPATH\fR
will be extracted\&.
.RE
.PP
\fB\-i\fR \fIINPUT\fR
.RS 4
Use
\fIINPUT\fR
as the input\&.
.RE
.PP
\fB\-o\fR \fIOUTPUT\fR
.RS 4
Use OUTPUT as the output\&.
.RE
.PP
\fB\-#\fR
.RS 4
Set compression level, from \-0 (lowest compression, fastest) to \-9 (highest compression, slowest)\&.
.RE
.PP
\fB\-e\fR
.RS 4
Use "extreme" compression, which is much slower and only yields a marginal decrease in size\&.
.RE
.PP
\fB\-p\fR \fICPUS\fR
.RS 4
Set the number of CPU cores to use\&. By default pixz will use the number of cores on the system\&.
.RE
.PP
\fB\-f\fR \fIFRACTION\fR
.RS 4
Set the size of each compression block, relative to the LZMA dictionary size (default is 2\&.0)\&. Higher values give better compression ratios, but use more memory and make random access less efficient\&. Values less than 1\&.0 aren\(cqt very efficient\&.
.RE
.PP
\fB\-q\fR \fISIZE\fR
.RS 4
Set the number of blocks to allocate for the compression queue (default is 1\&.3 * cores + 2, rounded up)\&. Higher values give better throughput, up to a point, but use more memory\&. Values less than the number of cores will make some cores sit idle\&.
.RE
.PP
\fB\-h\fR
.RS 4
Show pixz\(cqs online help\&.
.RE
.SH "EXAMPLES"
.PP
pixz < myfile > myfile\&.xz
.RS 4
Compress a file with pixz\&.
.RE
.PP
pixz myfile
.RS 4
Compress to myfile\&.pxz, removing the original\&.
.RE
.PP
tar \-Ipixz \-cf output\&.tpxz directory
.RS 4
Make tar use pixz for compression\&.
.RE
.PP
pixz \-x path/to/file < input\&.tpxz | tar x
.RS 4
Extract one file from an archive, quickly\&.
.RE
.SH "AUTHOR"
.sp
pixz is written by Dave Vasilevsky\&.
.SH "RESOURCES"
.sp
The pixz homepage: https://github\&.com/vasi/pixz/
.sp
Source downloads: http://sourceforge\&.net/projects/pixz/files/
.SH "COPYRIGHT"
.sp
Copyright \(co 2009\-2010 Dave Vasilevsky\&. Use of this software is granted under the FreeBSD License\&.
.SH "SEE ALSO"
.sp
xz(1), tar(1)
