--- ./i3-config-wizard/main.c.orig	2011-12-24 16:25:08.000000000 +0100
+++ ./i3-config-wizard/main.c	2011-12-28 09:38:11.000000000 +0100
@@ -283,10 +283,11 @@
 
     char *line = NULL;
     size_t len = 0;
-#if !defined(__APPLE__)
+#if defined(__APPLE__) || (defined(__FreeBSD__) && __FreeBSD_version < 800000)
+    bool head_of_file = true;
+#else
     ssize_t read;
 #endif
-    bool head_of_file = true;
 
     /* write a header about auto-generation to the output file */
     fputs("# This file has been auto-generated by i3-config-wizard(1).\n", ks_config);
@@ -296,7 +297,7 @@
     fputs("# this file and re-run i3-config-wizard(1).\n", ks_config);
     fputs("#\n", ks_config);
 
-#if defined(__APPLE__)
+#if defined(__APPLE__) || (defined(__FreeBSD__) && __FreeBSD_version < 800000)
     while ((line = fgetln(kc_config, &len)) != NULL) {
 #else
     while ((read = getline(&line, &len, kc_config)) != -1) {
