--- OGLCombinerTNT2.cpp.orig	Fri Aug 29 15:50:40 2003
+++ OGLCombinerTNT2.cpp	Fri Aug 13 21:54:26 2004
@@ -120,6 +120,7 @@
 
 GLenum COGLColorCombinerTNT2::RGBArgsMap[] =
 {
+#ifndef __FreeBSD__
 	{GL_ZERO,					},	//MUX_0
 	{GL_ZERO,					},	//MUX_1
 	{GL_PREVIOUS_EXT,			},	//MUX_COMBINED,
@@ -136,6 +137,24 @@
 	{GL_CONSTANT_EXT,			},	//MUX_ENV_ALPHA,
 	{GL_CONSTANT_EXT,			},	//MUX_LODFRAC,
 	{GL_CONSTANT_EXT,			},	//MUX_PRIMLODFRAC,
+#else
+	GL_ZERO,					//MUX_0
+	GL_ZERO,					//MUX_1
+	GL_PREVIOUS_EXT,				//MUX_COMBINED,
+	GL_TEXTURE0_ARB,				//MUX_TEXEL0,
+	GL_TEXTURE1_ARB,				//MUX_TEXEL1,
+	GL_CONSTANT_EXT,				//MUX_PRIM,
+	GL_PRIMARY_COLOR_EXT,				//MUX_SHADE,
+	GL_CONSTANT_EXT,				//MUX_ENV,
+	GL_PREVIOUS_EXT,				//MUX_COMBALPHA,
+	GL_TEXTURE0_ARB,				//MUX_T0_ALPHA,
+	GL_TEXTURE1_ARB,				//MUX_T1_ALPHA,
+	GL_CONSTANT_EXT,				//MUX_PRIM_ALPHA,
+	GL_PRIMARY_COLOR_EXT,				//MUX_SHADE_ALPHA,
+	GL_CONSTANT_EXT,				//MUX_ENV_ALPHA,
+	GL_CONSTANT_EXT,				//MUX_LODFRAC,
+	GL_CONSTANT_EXT,				//MUX_PRIMLODFRAC,
+#endif
 };
 
 
