--- OGLExtCombiner.cpp.orig	Thu Aug 28 23:31:44 2003
+++ OGLExtCombiner.cpp	Fri Aug 13 21:55:55 2004
@@ -474,6 +474,7 @@
 
 GLenum COGLExtColorCombiner::RGBArgsMap[] =
 {
+#ifndef __FreeBSD__
 	{GL_PRIMARY_COLOR_ARB,		},	//MUX_0
 	{GL_PRIMARY_COLOR_ARB,		},	//MUX_1
 	{GL_PREVIOUS_ARB,			},	//MUX_COMBINED,
@@ -490,6 +491,24 @@
 	{GL_CONSTANT_ARB,			},	//MUX_ENV_ALPHA,
 	{GL_CONSTANT_ARB,			},	//MUX_LODFRAC,
 	{GL_CONSTANT_ARB,			},	//MUX_PRIMLODFRAC,
+#else
+	GL_PRIMARY_COLOR_ARB,				//MUX_0
+	GL_PRIMARY_COLOR_ARB,				//MUX_1
+	GL_PREVIOUS_ARB,				//MUX_COMBINED,
+	GL_TEXTURE0_ARB,				//MUX_TEXEL0,
+	GL_TEXTURE1_ARB,				//MUX_TEXEL1,
+	GL_CONSTANT_ARB,				//MUX_PRIM,
+	GL_PRIMARY_COLOR_ARB,				//MUX_SHADE,
+	GL_CONSTANT_ARB,				//MUX_ENV,
+	GL_PREVIOUS_ARB,				//MUX_COMBALPHA,
+	GL_TEXTURE0_ARB,				//MUX_T0_ALPHA,
+	GL_TEXTURE1_ARB,				//MUX_T1_ALPHA,
+	GL_CONSTANT_ARB,				//MUX_PRIM_ALPHA,
+	GL_PRIMARY_COLOR_ARB,				//MUX_SHADE_ALPHA,
+	GL_CONSTANT_ARB,				//MUX_ENV_ALPHA,
+	GL_CONSTANT_ARB,				//MUX_LODFRAC,
+	GL_CONSTANT_ARB,				//MUX_PRIMLODFRAC,
+#endif
 };
 
 
