--- pyproject.toml.orig	2026-03-23 10:38:45.000000000 -0700
+++ pyproject.toml	2026-04-10 18:32:40.428607000 -0700
@@ -1,5 +1,5 @@
 [build-system]
-requires = ["setuptools >= 66.1.0, <= 82.0.1", "wheel == 0.45.1"]  # lower bound to support controller Python versions, upper bound for latest version tested at release
+requires = ["setuptools >= 63.1.0, <= 82.0.1", "wheel >= 0.45.1"]  # lower bound to support controller Python versions, upper bound for latest version tested at release
 build-backend = "setuptools.build_meta"
 
 [project]
