# $FreeBSD$
#
# READ BEFORE EDITING:
# - Please keep descriptions sorted alphabetically by variable name.
#

Options_Desc_MAINTAINER=	ports@FreeBSD.org

AAC_DESC?=		Enable support for aac/mp4
ALSA_DESC?=		Enable alsa audio support
AMR_DESC?=		Enable OpenCORE AMR 3GPP Speech Codecs
AO_DESC?=		Support libao audio library
ARCHIVE_DESC?=		Support bzip2/zip/iso9660 archive
ARTS_DESC?=		Enable Arts audio system support
AVAHI_DESC?=		Support Zeroconf through Avahi
BDB1_DESC?=		Enable Berkeley DB 1.85 support
BDB_DESC?=		Enable Berkeley DB support
CDDA2WAV_DESC?=		Enable cdda2wav CD ripper
CDPARANOIA_DESC?=	Enable cdparanoia CD ripper
CFITSIO_DESC?=		Enable FITS support via CFITSIO
COMPOSITE_DESC?=	Enable X11 Composite extension
CUE_DESC?=		Support embedded cue sheets
CURL_DESC?=		Enable CURL support
DAGRAB_DESC?=		Enable dagrab CD ripper
DBM_DESC?=		Enable DBM support
DBUS_DESC?=		Enable D-Bus support
DEBUG_DESC?=		Enable debug flags
DOCS_DESC?=		Build and install the documentation
DV_DESC?=		Enable libDV support
ECW_DESC?=		Enable ECW support
ESOUND_DESC?=		Enable Esound sound server support
EXAMPLES_DESC?=		Build and install the examples
EXPAT_DESC?=		Enable Expat support
FAAC_DESC?=		Enable FAAC encoder support
FAAD_DESC?=		Enable FAAD aac decoder support
FFMPEG_DESC?=		Support FFMPEG (wma aiff ac3 ape...)
FLAC_DESC?=		Enable support for flac
FONTCONFIG_DESC?=	Enable Font configuration API for X
FPECTL_DESC?=		Enable floating point exception handling
FREETYPE_DESC?=		Enable TrueType font rendering engine
GDM_DESC?=		Build GDM login manager
GEOS_DESC?=		Enable GEOS support
GEOTIFF_DESC?=		Enable GeoTIFF support
GIF_DESC?=		Enable GIF support
GLADE_DESC?=		Enable Glade interface support
GNOME_DESC?=		Enable GNOME Desktop support
GNUPG_DESC?=		Enable GNU Privacy Guard support
GOGO_DESC?=		Enable gogo mp3 encoder
GRASS_DESC?=		Enable GRASS support
GSTREAMER_DESC?=	Enable multimedia support
GTK2_DESC?=		Enable GTK2 gui toolkit support
GTK3_DESC?=		Enable GTK3 gui toolkit support
GUI_DESC?=		Enable GUI support
GVFS_DESC?=		Enable remote access support
HDF5_DESC?=		Enable HDF-5 support
HTTPD_DESC?=		Support for httpd output streaming
ICONS_DESC?=		Enable Icons theme
ICONV_DESC?=		Enable ICONV support
ID3TAG_DESC?=		Support ID3 v1/v2 tags
ID3_DESC?=		Enable support for id3 tags
IPV6_DESC?=		Enable IPv6 support
JACK_DESC?=		Support JACK audio server
JASPER_DESC?=		Enable JPEG 2000 support via JasPer
JAVA_DESC?=		Enable JAVA platform support
JPEG_DESC?=		Enable JPEG support
KDE4_DESC?=		Enable KDE4 Desktop support
KML_DESC?=		Enable KML support
LADSPA_DESC?=		Enable LDSPA audio support
LAME_DESC?=		Enable lame mp3 encoder support
LASH_DESC?=		Enable LDASH audio support
LASTFM_DESC?=		Support Last.FM stream input
LCMS2_DESC?=		Enable LCMS2 support
LDAP_DESC?=		Enable LDAP support
MAGICK_DESC?=		Enable ImageMagick Library
MIKMOD_DESC?=		Support MOD audio format
MIXER_DESC?=		Enable Mixer support
MMKEYS_DESC?=		Enable multimedia keys support
MMS_DESC?=		Support MMS stream input
MMX_DESC?=		Enable MMX optimized routines
MODPLUG_DESC?=		Support MODPLUG decoder
MP4_DESC?=		Enable support for mp4
MPP_DESC?=		Enable support for musepack
MSQL_DESC?=		Enable msql backend
MULTIBYTE_DESC?=	Enable multibyte character support
MUSEPACK_DESC?=		Support MPC audio format
MYSQL_DESC?=		Enable MySQL backend
NAS_DESC?=		Enable Network Audio System support
NETCDF_DESC?=		Enable NetCDF support
NLS_DESC?=		Build and install the localisation data
NOTIFY_DESC?=		Enable startup notification support
ODBC_DESC?=		Enable ODBC backend
ODF_DESC?=		Enable ODF support
OPENGL_DESC?=		Enable OpenGL support
OPTIMIZED_CFLAGS_DESC?=	Enable compilation optimizations
OSS_DESC?=		Enable Open Sound System support
PCRE_DESC?=		Enable regular expressions using libpcre
PERL_DESC?=		Enable Perl scripting language support
PGSQL_DESC?=		Enable PostgreSQL backend
PHP_DESC?=		Enable PHP binding/support
PIXBUF_DESC?=		Enable gdk-pixbuf support
PNG_DESC?=		Enable PNG support
POPPLER_DESC?=		Enable PDF and PS support
PORTAUDIO_DESC?=	Enable PortAudio support
PRINT_DESC?=		Enable Printer support
PROJ_DESC?=		Enable PROJ.4 support 
PTH_DESC?=		Enable GNU Pth for threading/multiprocessing
PULSEAUDIO_DESC?=	Support PulseAudio sound server
PYMALLOC_DESC?=		Enable python's internal malloc
PYTHON_DESC?=		Enable Python binding/support
QT4_DESC?=		Enable Qt4 gui toolkit support
RAW_DESC?=		Enable RAW support
RUBY_DESC?=		Enable Ruby binding/support
SAMPLERATE_DESC?=	Support sample rate conversion
SDL_DESC?=		Enable Simple Direct Madia Layer support
SEM_DESC?=		Enable POSIX semaphores support
SHOUTCAST_DESC?=	Support for Ogg Icecast and Shoutcast
SIMD_DESC?=		Use cpu-specific optimizations if possible
SNDFILE_DESC?=		Add support for libsndfile
SPEEX_DESC?=		Enable support for speex audio format
SQLITE_DESC?=		Enable SQLite backend
SSE_DESC?=		Enable SSE optimized routines
SSH_DESC?=		Enable SSH support
SSL_DESC?=		Enable SSL support
SVG_DESC?=		Enable SVG image support
STATIC_DESC?=		Build static executable/libraries
SVN_DESC?=		Enable Subversion support
THREADS_DESC?=		Enable thread support
TIDY_DESC?=		Enable tidy html cleaner support
TIFF_DESC?=		Enable TIFF support
TOMCAT5_DESC?=		Enable Tomcat 5.x support
TOMCAT6_DESC?=		Enable Tomcat 6.x support
TOMCAT7_DESC?=		Enable Tomcat 7.x support
TREMOR_DESC?=		Support Tremor
UCS2_DESC?=		Enable Unicode UCS-2 support
UCS4_DESC?=		Enable Unicode UCS-4 support
VORBIS_DESC?=		Enable support for Ogg Vorbis
VPX_DESC?=		Enable VP8 video codec
WAV_DESC?=		Support WAV audio format
WEBP_DESC?=		Enable WebP support
WXGTK_DESC?=		Enable WxGTK gui toolkit
X11_DESC?=		Enable support for X11
X264_DESC?=		Enable H264 video codec using x264
XALAN_DESC?=		Enable Xalan support
XCURSOR_DESC?=		Enable cursor themes support
XERCES_DESC?=		Enable Xerces support
XKLAVIER_DESC?=		Enable Keyboard layout settings
XRANDR_DESC?=		Enable Xrandr support
XSPF_DESC?=		Enable support for XSPF
XVIDEO_DESC?=		Enable the X Video Extension library
XVID_DESC?=		Enable xvid mpeg4 video codec
