define(`confEBINDIR',`%%PREFIX%%/libexec')
define(`confMANROOT',`%%PREFIX%%/man/man')
define(`confMANROOTMAN',`%%PREFIX%%/man/man')
define(`confUBINDIR',`%%PREFIX%%/libexec')
define(`confLIBDIR',`%%PREFIX%%/lib')
define(`confDONT_INSTALL_CATMAN',`True')
