--- CMakeModules/FindOpenEXR.cmake.orig	2021-04-11 22:06:00 UTC
+++ CMakeModules/FindOpenEXR.cmake
@@ -25,7 +25,7 @@ FIND_PATH(OPENEXR_INCLUDE_DIR OpenEXR/ImfIO.h
 )
 
 # Macro to find exr libraries (deduplicating search paths)
-# example: OPENEXR_FIND_VAR(OPENEXR_IlmImf_LIBRARY IlmImf)
+# example: OPENEXR_FIND_VAR(OPENEXR_OpenEXR_LIBRARY OpenEXR)
 MACRO(OPENEXR_FIND_VAR varname libname)
     FIND_LIBRARY( ${varname}
         NAMES ${libname} ${libname}-2_1 ${libname}-2_2
@@ -45,17 +45,17 @@ MACRO(OPENEXR_FIND_VAR varname libname)
 ENDMACRO(OPENEXR_FIND_VAR)
 
 # Macro to find exr libraries (and debug versions)
-# example: OPENEXR_FIND(IlmImf)
+# example: OPENEXR_FIND(OpenEXR)
 MACRO(OPENEXR_FIND libname)
     OPENEXR_FIND_VAR(OPENEXR_${libname}_LIBRARY ${libname})
     OPENEXR_FIND_VAR(OPENEXR_${libname}_LIBRARY_DEBUG ${libname}d)
 ENDMACRO(OPENEXR_FIND)
 
-OPENEXR_FIND(IlmImf)
+OPENEXR_FIND(OpenEXR)
 
 SET(OPENEXR_FOUND "NO")
-IF(OPENEXR_INCLUDE_DIR AND OPENEXR_IlmImf_LIBRARY)
-    SET(OPENEXR_LIBRARIES ${OPENEXR_IlmImf_LIBRARY} )
-    SET(OPENEXR_LIBRARIES_VARS OPENEXR_IlmImf_LIBRARY )
+IF(OPENEXR_INCLUDE_DIR AND OPENEXR_OpenEXR_LIBRARY)
+    SET(OPENEXR_LIBRARIES ${OPENEXR_OpenEXR_LIBRARY} )
+    SET(OPENEXR_LIBRARIES_VARS OPENEXR_OpenEXR_LIBRARY )
     SET(OPENEXR_FOUND "YES")
-ENDIF(OPENEXR_INCLUDE_DIR AND OPENEXR_IlmImf_LIBRARY)
+ENDIF(OPENEXR_INCLUDE_DIR AND OPENEXR_OpenEXR_LIBRARY)
