--- pyproject.toml.orig	2026-02-28 11:27:42 UTC
+++ pyproject.toml
@@ -3,7 +3,6 @@ readme = "README.md"
 version = "3.3.2"
 description = "SSE plugin for Starlette"
 readme = "README.md"
-license = "BSD-3-Clause"
 requires-python = ">=3.10"
 authors = [
     { name = "sysid", email = "sysid@gmx.de" },
