.\" Copyright (c) 2007-2009 Andy Kosela <akosela@andykosela.com>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"
.Dd August 9, 2009
.Dt BPKG 8
.Os
.Sh NAME
.Nm bpkg
.Nd a simple tool for displaying information about ports.
.Sh SYNOPSIS
.Nm
.Op Fl abDdeFfgIijkLMmOopQqrSswz
.Ar pkg-name ...
.Nm
.Op Fl BCchltvZ
.Pp
.Sh DESCRIPTION
.Nm
is a simple tool written in sh(1) for displaying information about ports.  Its 
main goal is to provide a quick way to display all kinds of useful info about 
installed ports and the whole ports tree.
.Sh OPTIONS
The following command line arguments are supported:
.Bl -tag -width F1
.It Fl a
show what dependent ports are, and are not installed.  [portmaster required] 
.It Fl B
create backup packages in /var/tmp/bpkg/ from all locally installed ports.
.It Fl b
create backup package in /var/tmp/bpkg/ from a locally installed port.
.It Fl C
clean all distfiles in /usr/ports/distfiles/* and also all work directories
of the ports tree /usr/ports/*/*/work/ [no arguments]
.It Fl c
clean all distfiles in /usr/ports/distfiles/*  [no arguments]
.It Fl D
display size of port's source files.
.It Fl d
display description of the port.
.It Fl e
configure OPTIONS for the specified port.
.It Fl F
browse www.freshports.org port's entry.  [text WWW browser required]
.It Fl f
show the packing list instructions for the port.
.It Fl g
show files that do not match the recorded checksum in the specified installed
port.
.It Fl h
display help.  [no arguments]
.It Fl i
display info about the port (priority - installed ports). 
.It Fl I
display short info about the port (priority - installed ports).
.It Fl j
search the ports tree according to ports' descriptions.
.It Fl k
show the deinstall script (if any) for the installed port.
.It Fl L
show the files within the installed port.
.It Fl l
display short info about all installed ports.  [no arguments]
.It Fl M
show the install-message file for the installed port.
.It Fl m
display port's Makefile.
.It Fl O
remove config OPTIONS for the specified port.
.It Fl o
display config OPTIONS for the specified port.
.It Fl p
search the ports tree and display short info about the port.
.It Fl Q
display the latest available package in the FreeBSD repository.  [-STABLE]
.It Fl q
display the latest available package in the FreeBSD repository.  [-RELEASE]
.It Fl r
show the list of all port's dependencies.
.It Fl S
search the ports tree and display info about the port.
.It Fl s
show the total size occupied by files installed within the port.
.It Fl t
list all installed ports with dates of their installation.  [no arguments]
.It Fl w
which installed port owns the specified file.
.It Fl v
list all installed ports and possible updates.  [no arguments]
.It Fl Z
display all missing dynamic object dependencies.  [no arguments] 
.It Fl z
display dynamic object dependencies for the specified port.
.El
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
The following is an example of a typical usage
of the
.Nm
command:
.Pp
.Dl "> bpkg -i foo" 
.Pp
Display info about port foo.
.Pp
.Dl "> bpkg -S 'foo[0-9]+$'"
.Pp
Display all ports matching the regular expression.
.Pp
.Dl "> bpkg -t | head"
.Pp
Display 10 most recently installed ports.
.Pp
.Dl "> bpkg -b 'foo bar'"
.Pp
Create backup packages of foo and bar in /var/tmp/bpkg/ directory.
.Sh SEE ALSO
.Xr pkg_add 1 ,
.Xr pkg_create 1 ,
.Xr pkg_delete 1 ,
.Xr pkg_info 1 ,
.Xr pkg_version 1 ,
.Xr ports 7
.Sh AUTHORS
.An Andy Kosela <akosela@andykosela.com>
