--- src/vmime/security/sasl/SASLContext.cpp.orig	2017-01-03 20:00:08 UTC
+++ src/vmime/security/sasl/SASLContext.cpp
@@ -189,8 +189,6 @@ const string SASLContext::getErrorMessage(const string
 	ERROR(GSASL_GSSAPI_ACQUIRE_CRED_ERROR)
 	ERROR(GSASL_GSSAPI_DISPLAY_NAME_ERROR)
 	ERROR(GSASL_GSSAPI_UNSUPPORTED_PROTECTION_ERROR)
-	ERROR(GSASL_KERBEROS_V5_INIT_ERROR)
-	ERROR(GSASL_KERBEROS_V5_INTERNAL_ERROR)
 	ERROR(GSASL_SECURID_SERVER_NEED_ADDITIONAL_PASSCODE)
 	ERROR(GSASL_SECURID_SERVER_NEED_NEW_PIN)
 
