--- libgit2-glib/ggit-types.h.orig	2014-10-19 13:55:09.000000000 +0400
+++ libgit2-glib/ggit-types.h	2015-01-15 14:12:33.000000000 +0300
@@ -963,9 +963,7 @@
 	GGIT_STATUS_OPTION_RENAMES_INDEX_TO_WORKDIR = (1 << 8),
 	GGIT_STATUS_OPTION_SORT_CASE_SENSITIVELY    = (1 << 9),
 	GGIT_STATUS_OPTION_SORT_CASE_INSENSITIVELY  = (1 << 10),
-	GGIT_STATUS_OPTION_DEFAULT                  = GGIT_STATUS_OPTION_INCLUDE_IGNORED |
-	                                              GGIT_STATUS_OPTION_INCLUDE_UNTRACKED |
-	                                              GGIT_STATUS_OPTION_RECURSE_UNTRACKED_DIRS
+	GGIT_STATUS_OPTION_DEFAULT                  = GGIT_STATUS_OPTION_INCLUDE_IGNORED | GGIT_STATUS_OPTION_INCLUDE_UNTRACKED | GGIT_STATUS_OPTION_RECURSE_UNTRACKED_DIRS
 } GgitStatusOption;
 
 /**
@@ -1059,8 +1057,7 @@
 	GGIT_DIFF_FIND_COPIES_FROM_UNMODIFIED     = (1u << 3),
 	GGIT_DIFF_FIND_REWRITES                   = (1u << 4),
 	GGIT_DIFF_BREAK_REWRITES                  = (1u << 5),
-	GGIT_DIFF_FIND_AND_BREAK_REWRITES         = (GGIT_DIFF_FIND_REWRITES |
-	                                             GGIT_DIFF_BREAK_REWRITES),
+	GGIT_DIFF_FIND_AND_BREAK_REWRITES         = (GGIT_DIFF_FIND_REWRITES | GGIT_DIFF_BREAK_REWRITES),
 	GGIT_DIFF_FIND_FOR_UNTRACKED              = (1u << 6),
 	GGIT_DIFF_FIND_ALL                        = (0x0ff),
 	GGIT_DIFF_FIND_IGNORE_LEADING_WHITESPACE  = 0,
