--- pyproject.toml.orig	2026-08-12 04:40:33 UTC
+++ pyproject.toml
@@ -1,10 +1,10 @@
 [build-system]
-requires = ["setuptools >= 77.0"]
+requires = ["setuptools >= 63.1"]
 build-backend = "setuptools.build_meta"
 
 [project]
 name = "aiohttp_socks"
-license = "Apache-2.0"
+license = { text = "Apache-2.0" }
 description = "Proxy connector for aiohttp"
 readme = "README.md"
 authors = [{ name = "Roman Snegirev", email = "snegiryev@gmail.com" }]
