--- pyproject.toml.orig	2026-02-11 19:40:54 UTC
+++ pyproject.toml
@@ -4,8 +4,7 @@ keywords = ["process", "executor", "tests", "orchestra
 description = "Process executor (not only) for tests."
 readme = "README.rst"
 keywords = ["process", "executor", "tests", "orchestration"]
-license = "LGPL-3.0-or-later"
-license-files = ["LICENSE"]
+license = {text = "LGPL-3.0-or-later"}
 authors = [
     {name = "Grzegorz Śliwiński", email = "fizyk+pypi@fizyk.dev"}
 ]
@@ -38,7 +37,7 @@ requires-python = ">= 3.10"
 "Changelog" = "https://github.com/dbfixtures/mirakuru/blob/v3.0.2/CHANGES.rst"
 
 [build-system]
-requires = ["setuptools >= 77.0.3", "wheel"]
+requires = ["setuptools >= 61", "wheel"]
 build-backend = "setuptools.build_meta"
 
 [tool.setuptools]
