--- pyproject.toml.orig	2026-09-04 12:51:25 UTC
+++ pyproject.toml
@@ -36,9 +36,9 @@ documentation = "https://quodlibet.readthedocs.io/"
 repository = "https://github.com/quodlibet/quodlibet"
 documentation = "https://quodlibet.readthedocs.io/"
 
-[project.scripts]
+# [project.scripts]
 # Convenience: `poetry run quodlibet` just runs the app (with no CLI args)
-quodlibet = "quodlibet.main:main"
+# quodlibet = "quodlibet.main:main"
 
 [tool.poetry]
 requires-poetry = '>=2.0'
