# New ports collection makefile for:	kterm
# Version required:	6.1
# Date created:		18 November 1994
# Whom:			asami
#
# $Id: Makefile,v 1.6 1995/03/24 11:09:28 asami Exp $
#

DISTNAME=	kterm-6.1.0
USE_IMAKE=	yes
MASTER_SITES=	ftp://freefall.cdrom.com/pub/FreeBSD/LOCAL_PORTS/
CATEGORIES+=	japanese x11
MAINTAINER=	asami@FreeBSD.ORG

.include <bsd.port.mk>
