--- plugins/org.eclipse.swt/Eclipse SWT PI/gtk/library/os_custom.h	Fri Apr  1 13:55:23 2005
+++ ../files/plugins-swt-gtk-os_custom.h	Wed Mar 30 22:55:24 2005
@@ -21,30 +23,30 @@
 #define PTR_sizeof() sizeof(void *)
 
 /* Libraries for dynamic loaded functions */
-#define gtk_file_chooser_add_filter_LIB "libgtk-x11-2.0.so.0"
-#define gtk_file_chooser_dialog_new_LIB "libgtk-x11-2.0.so.0"
-#define gtk_file_chooser_get_current_folder_LIB "libgtk-x11-2.0.so.0"
-#define gtk_file_chooser_get_filename_LIB "libgtk-x11-2.0.so.0"
-#define gtk_file_chooser_get_filenames_LIB "libgtk-x11-2.0.so.0"
-#define gtk_file_chooser_set_current_folder_LIB "libgtk-x11-2.0.so.0"
-#define gtk_file_chooser_set_current_name_LIB "libgtk-x11-2.0.so.0"
-#define gtk_file_chooser_set_extra_widget_LIB "libgtk-x11-2.0.so.0"
-#define gtk_file_chooser_set_filename_LIB "libgtk-x11-2.0.so.0"
-#define gtk_file_chooser_set_select_multiple_LIB "libgtk-x11-2.0.so.0"
-#define gtk_file_filter_add_pattern_LIB "libgtk-x11-2.0.so.0"
-#define gtk_file_filter_new_LIB "libgtk-x11-2.0.so.0"
-#define gtk_file_filter_set_name_LIB "libgtk-x11-2.0.so.0"
-#define gtk_tree_selection_get_selected_rows_LIB "libgtk-x11-2.0.so.0"
-#define gtk_tree_view_column_cell_get_position_LIB "libgtk-x11-2.0.so.0"
-#define gtk_entry_set_alignment_LIB "libgtk-x11-2.0.so.0"
-#define gdk_draw_pixbuf_LIB "libgdk-x11-2.0.so.0"
-#define gdk_screen_get_default_LIB "libgdk-x11-2.0.so.0"
-#define gdk_screen_get_monitor_at_window_LIB "libgdk-x11-2.0.so.0"
-#define gdk_screen_get_monitor_geometry_LIB "libgdk-x11-2.0.so.0"
-#define gdk_screen_get_n_monitors_LIB "libgdk-x11-2.0.so.0"
-#define gdk_screen_get_number_LIB "libgdk-x11-2.0.so.0"
-#define gdk_window_set_keep_above_LIB "libgdk-x11-2.0.so.0"
-#define gdk_window_set_accept_focus_LIB "libgdk-x11-2.0.so.0"
+#define gtk_file_chooser_add_filter_LIB "libgtk-x11-2.0.so"
+#define gtk_file_chooser_dialog_new_LIB "libgtk-x11-2.0.so"
+#define gtk_file_chooser_get_current_folder_LIB "libgtk-x11-2.0.so"
+#define gtk_file_chooser_get_filename_LIB "libgtk-x11-2.0.so"
+#define gtk_file_chooser_get_filenames_LIB "libgtk-x11-2.0.so"
+#define gtk_file_chooser_set_current_folder_LIB "libgtk-x11-2.0.so"
+#define gtk_file_chooser_set_current_name_LIB "libgtk-x11-2.0.so"
+#define gtk_file_chooser_set_extra_widget_LIB "libgtk-x11-2.0.so"
+#define gtk_file_chooser_set_filename_LIB "libgtk-x11-2.0.so"
+#define gtk_file_chooser_set_select_multiple_LIB "libgtk-x11-2.0.so"
+#define gtk_file_filter_add_pattern_LIB "libgtk-x11-2.0.so"
+#define gtk_file_filter_new_LIB "libgtk-x11-2.0.so"
+#define gtk_file_filter_set_name_LIB "libgtk-x11-2.0.so"
+#define gtk_tree_selection_get_selected_rows_LIB "libgtk-x11-2.0.so"
+#define gtk_tree_view_column_cell_get_position_LIB "libgtk-x11-2.0.so"
+#define gtk_entry_set_alignment_LIB "libgtk-x11-2.0.so"
+#define gdk_draw_pixbuf_LIB "libgdk-x11-2.0.so"
+#define gdk_screen_get_default_LIB "libgdk-x11-2.0.so"
+#define gdk_screen_get_monitor_at_window_LIB "libgdk-x11-2.0.so"
+#define gdk_screen_get_monitor_geometry_LIB "libgdk-x11-2.0.so"
+#define gdk_screen_get_n_monitors_LIB "libgdk-x11-2.0.so"
+#define gdk_screen_get_number_LIB "libgdk-x11-2.0.so"
+#define gdk_window_set_keep_above_LIB "libgdk-x11-2.0.so"
+#define gdk_window_set_accept_focus_LIB "libgdk-x11-2.0.so"
 
 /* Field accessors */
 #define GTK_ACCEL_LABEL_SET_ACCEL_STRING(arg0, arg1) (arg0)->accel_string = arg1
