--- setup.py.orig	2016-02-22 01:30:22 UTC
+++ setup.py
@@ -38,10 +38,10 @@ setup(name=PACKAGE_NAME,
                    'reddit\'s API.'),
       entry_points={'console_scripts': [
           'praw-multiprocess = praw.multiprocess:run']},
-      install_requires=['decorator >=4.0.9, <4.1',
+      install_requires=['decorator >=4.0.9',
                         'requests >=2.3.0',
-                        'six ==1.10',
-                        'update_checker ==0.11'],
+                        'six>=1.10',
+                        'update_checker>=0.11'],
       keywords='reddit api wrapper',
       license='GPLv3',
       long_description=README,
@@ -49,10 +49,10 @@ setup(name=PACKAGE_NAME,
       maintainer_email='bbzbryce@gmail.com',
       package_data={'': ['COPYING'], PACKAGE_NAME: ['*.ini']},
       packages=[PACKAGE_NAME],
-      tests_require=['betamax >=0.5.1, <0.6',
-                     'betamax-matchers >=0.2.0, <0.3',
-                     'betamax-serializers >=0.1.1, <0.2',
-                     'mock ==1.0.1'],
+      tests_require=['betamax >=0.5.1',
+                     'betamax-matchers >=0.2.0',
+                     'betamax-serializers >=0.1.1',
+                     'mock>=1.0.1'],
       test_suite='tests',
       url='https://praw.readthedocs.org/',
       version=VERSION)
