--- cmake/Install.cmake.orig	2020-03-12 12:06:51 UTC
+++ cmake/Install.cmake
@@ -273,12 +273,12 @@ ELSEIF(UNIX)
 
 	SET(DEFAULT_FILE_DESTINATION ${CMAKE_INSTALL_DATADIR}/${VENDOR}/AusweisApp2)
 	SET(TRANSLATION_DESTINATION ${DEFAULT_FILE_DESTINATION}/${TRANSLATION_DESTINATION})
-	INSTALL(TARGETS AusweisApp DESTINATION ${CMAKE_INSTALL_BINDIR} COMPONENT Application)
+        INSTALL(TARGETS AusweisApp DESTINATION ${DESTDIR}${CMAKE_INSTALL_BINDIR} COMPONENT Application)
 	CONFIGURE_FILE(${PACKAGING_DIR}/linux/${BUNDLE_IDENTIFIER}.metainfo.xml.in ${CMAKE_CURRENT_BINARY_DIR}/${BUNDLE_IDENTIFIER}.metainfo.xml @ONLY)
 	CONFIGURE_FILE(${PACKAGING_DIR}/linux/${BUNDLE_IDENTIFIER}.desktop.in ${CMAKE_CURRENT_BINARY_DIR}/${BUNDLE_IDENTIFIER}.desktop @ONLY)
-	INSTALL(FILES ${CMAKE_CURRENT_BINARY_DIR}/${BUNDLE_IDENTIFIER}.metainfo.xml DESTINATION ${CMAKE_INSTALL_DATADIR}/metainfo COMPONENT Application)
-	INSTALL(FILES ${CMAKE_CURRENT_BINARY_DIR}/${BUNDLE_IDENTIFIER}.desktop DESTINATION ${CMAKE_INSTALL_DATADIR}/applications COMPONENT Application)
-	INSTALL(FILES ${RESOURCES_DIR}/images/npa.svg DESTINATION ${DEFAULT_FILE_DESTINATION} COMPONENT Application)
+        INSTALL(FILES ${CMAKE_CURRENT_BINARY_DIR}/${BUNDLE_IDENTIFIER}.metainfo.xml DESTINATION ${DESTDIR}${CMAKE_INSTALL_DATADIR}/metainfo COMPONENT Application)
+        INSTALL(FILES ${CMAKE_CURRENT_BINARY_DIR}/${BUNDLE_IDENTIFIER}.desktop DESTINATION ${DESTDIR}${CMAKE_INSTALL_DATADIR}/applications COMPONENT Application)
+        INSTALL(FILES ${RESOURCES_DIR}/images/npa.svg DESTINATION ${DESTDIR}${DEFAULT_FILE_DESTINATION} COMPONENT Application)
 ENDIF()
 
 
@@ -303,7 +303,7 @@ IF(LINUX OR WIN32 OR MAC)
 ENDIF()
 
 
-IF(LINUX)
+IF(LINUX OR BSD)
 	INSTALL(FILES ${QM_FILES} DESTINATION ${TRANSLATION_DESTINATION} COMPONENT Translations)
 ELSEIF(NOT INTEGRATED_SDK)
 	INSTALL(DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/translations/ DESTINATION ${TRANSLATION_DESTINATION} COMPONENT Translations)
