--- setup.py.orig	2022-01-24 23:01:58 UTC
+++ setup.py
@@ -0,0 +1,49 @@
+#!/usr/bin/env python
+# setup.py generated by flit for tools that don't yet use PEP 517
+
+from distutils.core import setup
+
+packages = [
+    "fastapi_users",
+    "fastapi_users.authentication",
+    "fastapi_users.authentication.strategy",
+    "fastapi_users.authentication.strategy.db",
+    "fastapi_users.authentication.transport",
+    "fastapi_users.db",
+    "fastapi_users.router",
+]
+
+package_data = {"": ["*"]}
+
+install_requires = [
+    "fastapi >=0.65.2,<0.72.0",
+    "passlib[bcrypt] ==1.7.4",
+    "email-validator >=1.1.0,<1.2",
+    "pyjwt ==2.3.0",
+    "python-multipart ==0.0.5",
+    "makefun >=1.11.2,<1.14",
+]
+
+extras_require = {
+    "mongodb": ["fastapi-users-db-mongodb >=1.1.0"],
+    "oauth": ["httpx-oauth >=0.4,<0.5"],
+    "ormar": ["fastapi-users-db-ormar >=1.0.0"],
+    "redis": ["aioredis >=2.0.1,<2.1.0", "hiredis >=2.0.0,<2.1.0"],
+    "sqlalchemy": ["fastapi-users-db-sqlalchemy >=1.1.0,<2.0.0"],
+    "sqlalchemy2": ["fastapi-users-db-sqlalchemy >=2.0.0"],
+    "tortoise-orm": ["fastapi-users-db-tortoise >=1.1.0"],
+}
+
+setup(
+    name="fastapi-users",
+    version="9.2.2",
+    description="Ready-to-use and customizable users management for FastAPI.",
+    author="François Voron",
+    author_email="fvoron@gmail.com",
+    url="https://github.com/fastapi-users/fastapi-users",
+    packages=packages,
+    package_data=package_data,
+    install_requires=install_requires,
+    extras_require=extras_require,
+    python_requires=">=3.7",
+)
