.\" Copyright (c) 2006, 2007 Martin Kammerhofer <mkamm@gmx.net>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" @(#)portless.1,v 1.14 2007/09/21 09:23:00 martin Exp
.\"
.\" Note: The date here should be updated whenever a non-trivial
.\" change is made to the manual page.
.Dd September 21, 2007
.Dt PORTLESS 1
.Os
.Sh NAME
.Nm portless
.Nd "quickly browse port descriptions"
.Sh SYNOPSIS
.Nm
.Op Fl dfIiMmp
.Op Fl gG Ar 'pattern'
.Op Fl P Ar pager
.Ar portglob...
.Nm
.Op Fl IWw
.Op Fl gG Ar 'pattern'
.Ar portglob...
.Sh DESCRIPTION
.Nm
lets FreeBSD users quickly browse port descriptions given the port's
name or a (shell type) glob.
.Pp
The options are as follows:
.Bl -tag -width ".Fl P Ar pager"
.It Fl d
Display the
.Pa pkg-descr
file of the port. This is the default.
.It Fl f
Take the
.Ar portglob
argument literal (not as a shell glob).
.It Fl gG Ar 'pattern'
Filter the list of selected files with
.Xr grep 1
\&. Option
.Fl G
differs from
.Fl g
only by using
.Pa fgrep
rather than
.Pa grep .
.It Fl I
Ignore case when matching
.Ar portglob
against the ports tree. This option is only effective if
.Ar portglob
contains at least one unquoted globbing meta-character (
.Sq Li * ,
.Sq Li \&? ,
or
.Sq Li [
). Used together with
.Fl g
it also greps case insensitively.
.It Fl i
Display the
.Pa distinfo
file of the port.
.It Fl M
Display the
.Pa Makefile
file of the port.
.It Fl m
Display the
.Pa pkg-message
file of the port.
.It Fl p
Display the
.Pa pkg-plist
file of the port.
.It Fl P Ar pager
Use the specified
.Ar pager
program to display matching files. This overrides the setting of the
.Ev PAGER
environment variable.
.It Fl w
Rather than browsing files inside the ports tree just echo the names
of directories matching
.Ar portglob
to stdout.
.It Fl W
Like
.Fl w
but echoes just the last two components of the directory (i.e.\&
.Em category/portname
) to stdout.
.El
.Lp
Options
.Fl W
and
.Fl w
are incompatible with all other options.
.Sh ENVIRONMENT
The
.Nm
command uses the following environment variables:
.Bl -tag -width "Ev PORTSDIR" -compact -offset indent
.It Ev PAGER
defaults to
.Dq Pa less\ -e
.It Ev PORTSDIR
defaults to
.Pa /usr/ports
.El
.Sh FILES
.Bl -tag -width ".Pa /usr/ports/*/*/*" -compact
.It Pa /usr/ports/*/*/*
.El
.Sh EXAMPLES
The following are examples of typical usage of the
.Nm
command:
.Pp
.Dl "portless cvsweb\e*"
.Dl "portless lang/\e*doc"
.Dl "portless 'www/*python*'"
.Sh SEE ALSO
The
.Xr ports_glob 1
command (part of the
.Pa ports-mgmt/portupgrade
port),
.Xr grep 1 .
.Sh AUTHOR
The
.Nm
utility and this manual page were written by
.An Martin Kammerhofer Aq mkamm@gmx.net .
.\" EOF
