--- build/meta.go.orig	2025-08-05 11:35:02 UTC
+++ build/meta.go
@@ -1,5 +1,5 @@
 // Code generated by go generate; DO NOT EDIT.
-// This file was generated by go generate at 2024-08-12T08:54:43-07:00.
+// This file was generated by go generate at 2025-08-05T13:36:42+02:00.
 package build
 
 //go:generate go run gen.go
@@ -9,9 +9,9 @@ const (
 )
 
 const (
-	commit    = "?"
-	version   = "?"
-	buildTime = 0
+	commit = "a8b51bcf"
+	version = "v2.5.0"
+	buildTime = %%BUILDTIME%%
 )
 
 // Commit returns the commit hash of hostd
