--- build/meta.go.orig	2025-06-20 09:27:52 UTC
+++ build/meta.go
@@ -1,5 +1,5 @@
 // Code generated by go generate; DO NOT EDIT.
-// This file was generated by go generate at 2024-08-12T08:54:43-07:00.
+// This file was generated by go generate at 2025-06-20T11:29:36+02:00.
 package build
 
 //go:generate go run gen.go
@@ -9,9 +9,9 @@ const (
 )
 
 const (
-	commit    = "?"
-	version   = "?"
-	buildTime = 0
+	commit = "dfb9329b"
+	version = "v2.3.1"
+	buildTime = %%BUILDTIME%%
 )
 
 // Commit returns the commit hash of hostd
