--- build/meta.go.orig	2026-06-04 10:36:50 UTC
+++ build/meta.go
@@ -1,5 +1,5 @@
 // Code generated by go generate; DO NOT EDIT.
-// This file was generated by go generate at 2024-08-12T08:54:43-07:00.
+// This file was generated by go generate at 2026-06-04T12:36:55+02:00.
 package build
 
 //go:generate go run gen.go
@@ -9,9 +9,9 @@ const (
 )
 
 const (
-	commit    = "?"
-	version   = "?"
-	buildTime = 0
+	commit = "8d7275b3"
+	version = "v2.9.1"
+	buildTime = %%BUILDTIME%%
 )
 
 // Commit returns the commit hash of hostd
