# New ports collection makefile for:	rmsg
# Version required:	1.64
# Date created:		9 October 1995
# Whom:			torstenb@FreeBSD.ORG
#
# $Id: Makefile,v 1.5 1996/11/26 07:51:51 asami Exp $
#

DISTNAME=	rmsg-1.64
CATEGORIES=	net
MASTER_SITES=	ftp://ftp.funet.fi/pub/networking/tcpip/ \
		ftp://proton.elka.pw.edu.pl/pub/unix/network/

MAINTAINER=	torstenb@FreeBSD.org

WRKSRC=		${WRKDIR}/rmsg
MAN1=		rmsg.1
MAN8=		rmsgd.8

.include <bsd.port.mk>
