# Created by: Sergey Skvortsov <skv@protey.ru>
# $FreeBSD$

PORTNAME=	base
PORTVERSION=	2.18
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:RGARCIA
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Set of modules to operate with inheritance and class fields at runtime

USES=		perl5
USE_PERL5=	configure

MAN3=		base.3 fields.3

.include <bsd.port.mk>
