--- cmake/compiler-specific.cmake.orig	2025-11-06 09:29:38 UTC
+++ cmake/compiler-specific.cmake
@@ -149,8 +149,8 @@ elseif(TARGET_ARCH MATCHES "ppc64$")
           "GCC version ${CMAKE_C_COMPILER_VERSION} is too old for ppc64. Try GCC 3.0 or newer."
       )
     endif()
-    # else()
-    #   message(FATAL_ERROR "Unsupported compiler (${CMAKE_C_COMPILER_ID}) for ppc64. Try GCC.")
+  else()
+    message(WARNING "Unsupported compiler (${CMAKE_C_COMPILER_ID}) for ppc64. Try GCC.")
   endif()
 elseif(TARGET_ARCH STREQUAL "ppc")
   # PowerPC 32-bit specific flags
@@ -197,7 +197,7 @@ elseif(TARGET_ARCH STREQUAL "arm7")
       )
     endif()
   else()
-    message(FATAL_ERROR "Unsupported compiler (${CMAKE_C_COMPILER_ID}) for arm7. Try GCC.")
+    message(WARNING "Unsupported compiler (${CMAKE_C_COMPILER_ID}) for arm7. Try GCC.")
   endif()
 elseif(TARGET_ARCH STREQUAL "arm6")
   if(CMAKE_C_COMPILER_ID STREQUAL "GNU")
@@ -235,7 +235,7 @@ elseif(TARGET_ARCH STREQUAL "arm")
       )
     endif()
   else()
-    message(FATAL_ERROR "Unsupported compiler (${CMAKE_C_COMPILER_ID}) for arm. Try GCC.")
+    message(WARNING "Unsupported compiler (${CMAKE_C_COMPILER_ID}) for arm. Try GCC.")
   endif()
 elseif(TARGET_ARCH STREQUAL "sparc64")
   if(CMAKE_C_COMPILER_ID STREQUAL "GNU")
@@ -269,9 +269,7 @@ elseif(TARGET_ARCH STREQUAL "sparc64")
                 -xc99
     )
   else()
-    message(
-      FATAL_ERROR "Unsupported compiler (${CMAKE_C_COMPILER_ID}) for sparc64. Try GCC or Sun."
-    )
+    message(WARNING "Unsupported compiler (${CMAKE_C_COMPILER_ID}) for sparc64. Try GCC or Sun.")
   endif()
 elseif(TARGET_ARCH STREQUAL "sparc")
   if(CMAKE_C_COMPILER_ID STREQUAL "GNU")
@@ -294,7 +292,7 @@ elseif(TARGET_ARCH STREQUAL "sparc")
       common_compiler_flags INTERFACE -xO3 -xtarget=native -xmemalign=4i -fma=fused -fns=yes -xc99
     )
   else()
-    message(FATAL_ERROR "Unsupported compiler (${CMAKE_C_COMPILER_ID}) for sparc. Try GCC or Sun.")
+    message(WARNING "Unsupported compiler (${CMAKE_C_COMPILER_ID}) for sparc. Try GCC or Sun.")
   endif()
 elseif(TARGET_ARCH STREQUAL "mips")
   if(CMAKE_C_COMPILER_ID STREQUAL "GNU")
