--- pyproject.toml.orig	2020-02-02 00:00:00 UTC
+++ pyproject.toml
@@ -4,7 +4,7 @@ build-backend = "hatchling.build"
 
 
 [project]
-name = "fontPens"
+name = "fontpens"
 description = "A collection of classes implementing the pen protocol for manipulating glyphs."
 readme = "README.md"
 authors = [
