--- pyproject.toml.orig	2026-04-29 00:13:44 UTC
+++ pyproject.toml
@@ -13,7 +13,6 @@ dependencies = [
 license = { file = "LICENSE" }
 requires-python = ">=3.9"
 dependencies = [
-    "hypothesis>=6.137.0",
     "crosshair-tool>=0.0.104",
 ]
 classifiers = [
