# $Id: Makefile,v 1.73 1995/07/15 13:57:40 jkh Exp $
#

   SUBDIR += FWF
   SUBDIR += XFree86
   SUBDIR += Xaw3d
   SUBDIR += blt
   SUBDIR += color_xterm
   SUBDIR += ctwm
   SUBDIR += emiclock
   SUBDIR += emu
   SUBDIR += fvwm
   SUBDIR += g3view
   SUBDIR += iv
   SUBDIR += olvwm
   SUBDIR += piewm
   SUBDIR += rxvt
   SUBDIR += sxpc
   SUBDIR += tk
   SUBDIR += tkhfs
   SUBDIR += tkinfo
   BROKEN += tkman
   SUBDIR += tvtwm
   SUBDIR += x3270
   SUBDIR += xbuffy
   SUBDIR += xcb
   SUBDIR += xcolors
   SUBDIR += xdaliclock
   SUBDIR += xdtm
   SUBDIR += xearth
   SUBDIR += xfed
   SUBDIR += xfm
   SUBDIR += xgrab
   SUBDIR += xkeycaps
   SUBDIR += xloadimage
   SUBDIR += xlockmore
   SUBDIR += xphoon
   SUBDIR += xscreensaver
   SUBDIR += xsnow
   SUBDIR += xview-config
   SUBDIR += xview-lib
   SUBDIR += xview-clients

.include <bsd.port.subdir.mk>
