--- pyproject.toml.orig	2026-01-23 21:14:12 UTC
+++ pyproject.toml
@@ -29,7 +29,7 @@ dependencies = [
 ]
 dependencies = [
     "pytest >= 8.2",
-    "port-for >= 0.7.3",
+    "port-for >= 0.4",
     "mirakuru >= 2.6.0",
     "packaging",
     "psycopg >= 3.0.0"
