PORTNAME=	uri
PORTVERSION=	1.1.1
CATEGORIES=	net rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Provide classes to handle Uniform Resource Identifiers
WWW=		https://github.com/ruby/uri

LICENSE=	BSD2CLAUSE RUBY
LICENSE_COMB=	dual
LICENSE_FILE_BSD2CLAUSE=${WRKSRC}/BSDL
LICENSE_FILE_RUBY=	${WRKSRC}/COPYING

USES=		gem

NO_ARCH=	yes

.include <bsd.port.mk>
