PORTNAME=	azure_mgmt_event_grid
PORTVERSION=	0.21.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Microsoft Azure Microsoft Azure Event Grid Services Library for Ruby Client Library for Ruby
WWW=		https://github.com/Azure/azure-sdk-for-ruby/tree/master/management/azure_mgmt_event_grid

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

RUN_DEPENDS=	rubygem-ms_rest_azure>=0.12.0<0.13:devel/rubygem-ms_rest_azure

USES=		gem

NO_ARCH=	yes

.include <bsd.port.mk>
