--- CMakeModules/FindSCOTCH.cmake.orig	2014-10-28 09:12:48 UTC
+++ CMakeModules/FindSCOTCH.cmake
@@ -114,13 +114,14 @@ find_library(PTSCOTCHERR_LIBRARY
   )
 
 #set(SCOTCH_DEBUG 1)
-set(SCOTCH_LIBRARIES ${PTSCOTCH_LIBRARY})
+set(SCOTCH_LIBRARIES ${SCOTCH_LIBRARY} ${SCOTCHERR_LIBRARY} ${PTSCOTCH_LIBRARY})
 if (PTESMUMPS_LIBRARY)
   set(SCOTCH_LIBRARIES ${SCOTCH_LIBRARIES}  ${PTESMUMPS_LIBRARY})
 endif()
 set(SCOTCH_LIBRARIES ${SCOTCH_LIBRARIES} ${PTSCOTCHERR_LIBRARY})
 
 # Try compiling and running test program
+set(DOLFIN_SKIP_BUILD_TESTS 1)
 if (DOLFIN_SKIP_BUILD_TESTS)
   set(SCOTCH_TEST_RUNS TRUE)
 elseif (SCOTCH_INCLUDE_DIRS AND SCOTCH_LIBRARIES)
