# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD$

PORTNAME=	SUPER
PORTVERSION=	1.17
PORTREVISION=	3
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Perl module control superclass method dispatch

BUILD_DEPENDS=	${RUN_DEPENDS}
RUN_DEPENDS=	p5-Sub-Identify>=0.04:devel/p5-Sub-Identify

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
