# New ports collection makefile for:	tvtwm
# Version required:	?
# Date created:		5th December 1994
# Whom:			gpalmer
#
# $Id$
#

DISTNAME=	tvtwm
USE_IMAKE=	yes
INSTALL_MANPAGES=	yes
MASTER_SITES=	ftp://ftp.x.org/pub/R6untarred/contrib/programs/
EXTRACT_SUFX=	.tar.gz

.include <bsd.port.mk>
