.Dd Sep 10, 1992
.Dt ROGUE_S 6
.Sh 名称
.Nm rogue_s
.Nd ローグ・クローンにより運命の洞窟を探検する
.Sh 書式
.Nm rogue_s
.Ar mesg_file
.Op -s
.Op -r
.Op save_file
.Sh 解説
.Pp
このゲームは、バークレイ版 UNIX に付属しているゲーム、
ローグ 5.3 のクローンからメッセージを分離し、自分の好きなメッセージで
楽しむことができるようにしたものです。
.Pp
コマンドキャラクターは標準のローグ 5.3 と同じで、
h, j, k, l, y, u, b, n で1ステップ移動します。
シフトキーと同時に押せば、何かにぶつかるまで移動します。
コントロールキーと同時に押した場合には、何かが見つかるまで
移動することができます。
また ? を入力すれば、使用できるコマンドのリストを表示することができます。
.Pp
プログラムがプレイヤーに何かの選択を要求するときには、
いつでも * を入力して選択できるもののリストを表示させることができます。
しかしながら、場合によっては全リストではなく、巻き物、水薬、武器などだけの
リストを見たいことがあります。その場合には * のかわりに ?!=:/)] の
いずれかを入力することにより、それぞれ巻き物、水薬、指輪、食糧、杖、武器、
よろいの メニューを表示することができます。これは、何か特定の持ち物、
例えば巻き物を落としたいが、それを全リストからではなく、巻き物の中から
探したいようなときに特に有用です。
.Pp
CTRL-A を入力すると、次のような行が表示されます。
.Pp
.Bd -filled -offset indent
基本上昇率: 6.50, 実効上昇率: 7.00 (!: 2, V: 0)
.Ed
.Pp
この行は体力上昇率を表しています。プレイヤーの経験レベルが上がるごとに、
プレイヤーの体力はランダムに選ばれた 10 未満の値だけ上昇します。
CTRL-A コマンドを使えば、自分の幸運度を知ることができます。
上記の例では、基本上昇率はゲーム中の正確な体力上昇値の平均を表し、
有効上昇率は基本上昇率から水薬による上昇分とバンパイヤによる低下分を
差し引いたものです。上記の例では、2 ポイントの体力が体力が回復する薬を
飲んだことによって与えられ、バンパイヤの影響はないことが括弧の中に
示されています。ただし、ここで述べる体力値は体力の上限値を指しています。
すなわち、ローグ画面最下行にあるプレイヤー状態表示行の中の『体力: 15(22)』
という部分の最も右側にある数値です。
.Pp
CTRL-D コマンドは何の入力要求も行わずに rogue.screen というファイルを
カレントディレクトリーに作成します。このファイルの内容は CTRL-D を
入力したときの画面のコピーです。このコマンドはゲーム中のどの時点でも
実行できます。これは、自分がどのように悲惨な状態に陥ったか、
あるいはどれだけすごいゲームだったかを他人に説明するのに便利です。
.Pp
.Nm mesg_file
には読み込ませるメッセージファイル名を書きます。元々のメッセージファイル
(の日本語版)は mesg という名前になっています。ファイルは
カレントディレクトリ、PREFIX/share/rogue ディレクトリの
順に検索されます。
.Nm mesg_file
を指定せずに実行した場合、指定可能なファイル名をそのファイルの説明と共に
表示して終了します。
.Nm -s 
オプションでは、スコアファイルを表示して終了します。
.Nm -r 
オプションは、環境変数 ROGUEOPTS に指定されたセーブファイルから
ゲームを再開します。
.Nm save_file 
を指定した場合には、そのファイルにセーブされたゲームを再開します。
.Pp
これより詳しいことについては、ドキュメント『日本語版ローグ・クローンに
よる『運命の洞窟』への招待』を参照してください。
.Sh 作者
.An Tim Stoehr <tim@zues.TEK.COM>: ローグ・クローン 2
.An 太田 純 <ohta@src.ricoh.co.jp>: 日本語版 1.3
.An 伊藤 康史 <brx@kmc.kyoto-u.ac.jp>: メッセージ分離版
.Sh 関連ファイル
.Bl -tag -width ~/rogue.scores -compact
.It Pa ~/rogue.scores
スコアファイル
.It Pa ~/rogue.screen
画面ダンプファイル
.It Pa PREFIX/share/rogue/mesg*
メッセージファイル
.It Pa PREFIX/share/doc/rogue/*
関連ドキュメント
.Sh 関連項目
日本語版ローグ・クローンによる『運命の洞窟』への招待
(PREFIX/share/doc/rogue/rogue.doc)
