Issutracker : #iXXXXX#
CWS         : N/A
Author      : NAKATA Maho <maho@openoffice.org> (JCA)
Description : contains illigal char

Index: offapi/com/sun/star/rendering/XParametricPolyPolygon2DFactory.idl
===================================================================
RCS file: /cvs/api/offapi/com/sun/star/rendering/XParametricPolyPolygon2DFactory.idl,v
retrieving revision 1.2
diff -u -r1.2 XParametricPolyPolygon2DFactory.idl
--- offapi/com/sun/star/rendering/XParametricPolyPolygon2DFactory.idl	10 Mar 2005 12:35:07 -0000	1.2
+++ offapi/com/sun/star/rendering/XParametricPolyPolygon2DFactory.idl	28 Mar 2005 08:34:51 -0000
@@ -109,7 +109,7 @@
 		linearly between center and endColor via concentric ellipses
 		around the center point. Note that the absolute size of the
 		rectangle given at this method does not matter, only it's
-		aspect ratio: if this aspect ratio ís 1, the gradient is
+		aspect ratio: if this aspect ratio is 1, the gradient is
 		circular. If it's not 1, the gradient is elliptical, with the
 		special twist that the aspect ratio is maintained also for the
 		center color: the gradient will not collapse into a single
@@ -124,7 +124,7 @@
 		linearly between center and endColor via rectangular boxes
 		around the center point. Note that the absolute size of the
 		rectangle given at this method does not matter, only it's
-		aspect ratio: if this aspect ratio ís 1, the gradient is
+		aspect ratio: if this aspect ratio is 1, the gradient is
 		quadratic. If it's not 1, the gradient is rectangular, with
 		the special twist that the aspect ratio is maintained also for
 		the center color: the gradient will not collapse into a single
