--- pyproject.toml.orig	2026-09-12 16:52:03 UTC
+++ pyproject.toml
@@ -27,7 +27,7 @@ dependencies = [
     "quart >= 0.23",
     "trio >= 0.19.0",
 ]
-requires-python = ">=3.13"
+requires-python = ">=3.12"
 
 [project.license]
 text = "MIT"
