--- pyproject.toml.orig	1970-01-01 00:00:00 UTC
+++ pyproject.toml
@@ -1,6 +1,6 @@
 [build-system]
-build-backend = "uv_build"
-requires = ["uv_build>=0.10.0,<0.11.0"]
+requires = ["flit-core >= 3.12"]
+build-backend = "flit_core.buildapi"
 
 [project]
 name = "cucumber-tag-expressions"
