'\" t
.\"     Title: mvxattr
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 08/09/2022
.\"    Manual: User Commands
.\"    Source: Samba 4.16.4
.\"  Language: English
.\"
.TH "MVXATTR" "1" "08/09/2022" "Samba 4\&.16\&.4" "User Commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
mvxattr \- Recursively rename extended attributes
.SH "SYNOPSIS"
.HP \w'\ 'u
mvxattr {\-s\ STRING,\ \-\-from=STRING} {\-d\ STRING,\ \-\-to=STRING} [\-l,\ \-\-follow\-symlinks] [\-p,\ \-\-print] [\-v,\ \-\-verbose] [\-f,\ \-\-force] {PATH\ [PATH\ \&.\&.\&.]}
.SH "DESCRIPTION"
.PP
This tool is part of the
\fBsamba\fR(1)
suite\&.
.PP
mvxattr is a simple utility to recursively rename extended attributes\&.
.PP
By default all symlinks are ignored, use
\fB\-l\fR
to follow them\&.
.SH "OPTIONS"
.PP
\-s STRING, \-\-from=STRING
.RS 4
Source xattr name
.RE
.PP
\-d STRING, \-\-to=STRING
.RS 4
Destination xattr name
.RE
.PP
\-l, \-\-follow\-symlinks
.RS 4
Follow symlinks, the default is to ignore them\&.
.RE
.PP
\-p, \-\-print
.RS 4
Print files where the xattr got renamed\&.
.RE
.PP
\-v, \-\-verbose
.RS 4
Print files as they are checked\&.
.RE
.PP
\-f, \-\-force
.RS 4
Force overwriting of destination xattr\&.
.RE
.SH "VERSION"
.PP
This man page is part of version 4\&.16\&.4 of the Samba suite\&.
.SH "AUTHOR"
.PP
The original Samba software and related utilities were created by Andrew Tridgell\&. Samba is now developed by the Samba Team as an Open Source project similar to the way the Linux kernel is developed\&.
.PP
The mvxattr manpage was written by Ralph Boehme\&.
