--- pyproject.toml.orig	2026-03-05 01:46:20 UTC
+++ pyproject.toml
@@ -5,7 +5,7 @@ readme = "README.md"
 name = "av"
 description = "Pythonic bindings for FFmpeg's libraries."
 readme = "README.md"
-license = "BSD-3-Clause"
+license = {text="BSD-3-Clause"}
 authors = [
     {name = "WyattBlue", email = "wyattblue@auto-editor.com"},
     {name = "Jeremy Lainé", email = "jeremy.laine@m4x.org"},
