# New ports collection makefile for:	gstreamer-plugins-speex
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#

CATEGORIES=	audio
PORTREVISION=	1

COMMENT=	Gstreamer speex voice plugin

GST_PLUGIN=	speex

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
