--- ./src/cronolog.c.orig	2025-07-24 22:02:02 UTC
+++ ./src/cronolog.c
@@ -84,8 +84,8 @@
 
 #ifndef _WIN32
 #define _GNU_SOURCE 1
-#define OPEN_EXCLUSIVE O_WRONLY|O_CREAT|O_EXCL|O_APPEND|O_LARGEFILE
-#define OPEN_SHARED O_WRONLY|O_CREAT|O_APPEND|O_LARGEFILE
+#define OPEN_EXCLUSIVE O_WRONLY|O_CREAT|O_EXCL|O_APPEND
+#define OPEN_SHARED O_WRONLY|O_CREAT|O_APPEND
 #else
 #define OPEN_EXCLUSIVE O_WRONLY|O_CREAT|O_EXCL|O_APPEND
 #define OPEN_SHARED O_WRONLY|O_CREAT|O_APPEND
