Add support for Django 5.2

Obtained from:

https://gitlab.com/mailman/hyperkitty/-/commit/b8b7536c2cb7380ec55ed62140617cff8ae36b1d

--- pyproject.toml.orig	2026-05-11 11:59:00 UTC
+++ pyproject.toml
@@ -23,7 +23,7 @@ dependencies = [
     "django-gravatar2>=1.0.6",
     "django-haystack>=2.8.0",
     "django-q2>=1.0.0",
-    "django>=4.2,<5.1",
+    "django>=4.2,<5.3",
     "django_mailman3>=1.3.13",
     "djangorestframework>=3.0.0",
     "flufl.lock>=4.0",
