--- pyproject.toml.orig	2026-04-24 03:08:54 UTC
+++ pyproject.toml
@@ -31,7 +31,7 @@ dependencies = [
 ]
 dependencies = [
   "pillow",
-  "sphinx>=6", # 6.0.0 out on 2022/12/29
+  "sphinx>=5", # 6.0.0 out on 2022/12/29
 ]
 optional-dependencies.animations = [
   "sphinxcontrib-video",
