--- chrome/browser/resources/settings/appearance_page/appearance_page.ts.orig	2023-10-19 19:58:06 UTC
+++ chrome/browser/resources/settings/appearance_page/appearance_page.ts
@@ -72,7 +72,7 @@ export interface SettingsAppearancePageElement {
 export enum SystemTheme {
   // Either classic or web theme.
   DEFAULT = 0,
-  // <if expr="is_linux">
+  // <if expr="is_posix">
   GTK = 1,
   QT = 2,
   // </if>
@@ -193,7 +193,7 @@ export class SettingsAppearancePageElement extends
             'prefs.autogenerated.theme.policy.color.controlledBy)',
       },
 
-      // <if expr="is_linux">
+      // <if expr="is_posix">
       /**
        * Whether to show the "Custom Chrome Frame" setting.
        */
@@ -229,7 +229,7 @@ export class SettingsAppearancePageElement extends
       'themeChanged_(' +
           'prefs.extensions.theme.id.value, systemTheme_, isForcedTheme_)',
 
-      // <if expr="is_linux">
+      // <if expr="is_posix">
       'systemThemePrefChanged_(prefs.extensions.theme.system_theme.value)',
       // </if>
     ];
@@ -253,7 +253,7 @@ export class SettingsAppearancePageElement extends
   private isForcedTheme_: boolean;
   private showHoverCardImagesOption_: boolean;
 
-  // <if expr="is_linux">
+  // <if expr="is_posix">
   private showCustomChromeFrame_: boolean;
   // </if>
 
@@ -354,7 +354,7 @@ export class SettingsAppearancePageElement extends
     this.appearanceBrowserProxy_.useDefaultTheme();
   }
 
-  // <if expr="is_linux">
+  // <if expr="is_posix">
   private systemThemePrefChanged_(systemTheme: SystemTheme) {
     this.systemTheme_ = systemTheme;
   }
@@ -427,7 +427,7 @@ export class SettingsAppearancePageElement extends
     }
 
     let i18nId;
-    // <if expr="is_linux">
+    // <if expr="is_posix">
     switch (this.systemTheme_) {
       case SystemTheme.GTK:
         i18nId = 'gtkTheme';
@@ -440,7 +440,7 @@ export class SettingsAppearancePageElement extends
         break;
     }
     // </if>
-    // <if expr="not is_linux">
+    // <if expr="not is_posix">
     i18nId = 'chooseFromWebStore';
     // </if>
     this.themeSublabel_ = this.i18n(i18nId);
