--- cmake/Modules/FindBCToolbox.cmake.orig	2026-07-15 12:43:54 UTC
+++ cmake/Modules/FindBCToolbox.cmake
@@ -33,8 +33,8 @@ if(NOT TARGET bctoolbox)
 if(NOT TARGET bctoolbox)
     set(EXPORT_PATH ${LINPHONE_OUTPUT_DIR})
     include(GNUInstallDirs)
-    set(BCToolbox_CMAKE_DIR ${EXPORT_PATH}/${CMAKE_INSTALL_DATADIR}/bctoolbox/cmake)
-    include(${BCToolbox_CMAKE_DIR}/bctoolboxTargets.cmake)
+    set(BCToolbox_CMAKE_DIR ${EXPORT_PATH}/${CMAKE_INSTALL_DATADIR}/BCToolbox/cmake)
+    include(${BCToolbox_CMAKE_DIR}/BCToolboxConfig.cmake)
 endif()
 
 set(_BCToolbox_REQUIRED_VARS BCToolbox_TARGET BCToolbox_CMAKE_DIR BCToolbox_CMAKE_UTILS)
@@ -42,9 +42,12 @@ if(TARGET bctoolbox)
 
 if(TARGET bctoolbox)
 	set(BCToolbox_TARGET bctoolbox)
-	get_target_property(_BCToolbox_SOURCE_DIR ${BCToolbox_TARGET} SOURCE_DIR)
-	set(BCToolbox_CMAKE_DIR "${_BCToolbox_SOURCE_DIR}/../cmake")
-	set(BCToolbox_CMAKE_UTILS "${BCToolbox_CMAKE_DIR}/BCToolboxCMakeUtils.cmake")
+	if(NOT BCToolbox_CMAKE_DIR)
+		set(BCToolbox_CMAKE_DIR "${LINPHONE_OUTPUT_DIR}/${CMAKE_INSTALL_DATADIR}/BCToolbox/cmake")
+	endif()
+	if(NOT BCToolbox_CMAKE_UTILS)
+		set(BCToolbox_CMAKE_UTILS "${BCToolbox_CMAKE_DIR}/BCToolboxCMakeUtils.cmake")
+	endif()
 	if(TARGET bctoolbox-tester)
 		set(BCToolbox_tester_FOUND TRUE)
 		set(BCToolbox_tester_TARGET bctoolbox-tester)
