.TH AFUSE 1 "October 12, 2006"
.SH NAME
AFUSE \- automounting file system implemented in user-space using FUSE
.SH DESCRIPTION
usage: afuse mountpoint [options]
.SS "general options:"
.TP
\fB\-o\fR opt,[opt...]
mount options
.TP
\fB\-h\fR   \fB\-\-help\fR
print help
.TP
\fB\-V\fR   \fB\-\-version\fR
print FUSE version information
.SS "AFUSE options:"
.TP
\fB\-o\fR \fB\ mount_template=CMD\fR
template for CMD to execute to mount (*)
.TP
\fB\-o\fR \fB\ unmount_template=CMD\fR
template for CMD to execute to unmount (*) (**)
.TP
(*) - When executed, %r and %m are expanded in templates to the root
directory name for the new mount point, and the actual directory to
mount onto respectively to mount onto. Both templates are REQUIRED.
.TP
(**)- The unmount command must perform a lazy unmount operation. E.g. the
\-u \-z options to fusermount, or \-l for regular mount.
.SS "FUSE options:"
.TP
\fB\-d\fR   \fB\-o\fR debug
enable debug output (implies \fB\-f\fR)
.TP
\fB\-f\fR
foreground operation
.TP
\fB\-s\fR
disable multi\-threaded operation
.TP
\fB\-o\fR allow_other
allow access to other users
.TP
\fB\-o\fR allow_root
allow access to root
.TP
\fB\-o\fR nonempty
allow mounts over non\-empty file/dir
.HP
\fB\-o\fR default_permissions enable permission checking by kernel
.TP
\fB\-o\fR fsname=NAME
set filesystem name
.TP
\fB\-o\fR large_read
issue large read requests (2.4 only)
.TP
\fB\-o\fR max_read=N
set maximum size of read requests
.TP
\fB\-o\fR hard_remove
immediate removal (don't hide files)
.TP
\fB\-o\fR use_ino
let filesystem set inode numbers
.TP
\fB\-o\fR readdir_ino
try to fill in d_ino in readdir
.TP
\fB\-o\fR direct_io
use direct I/O
.TP
\fB\-o\fR kernel_cache
cache files in kernel
.TP
\fB\-o\fR umask=M
set file permissions (octal)
.TP
\fB\-o\fR uid=N
set file owner
.TP
\fB\-o\fR gid=N
set file group
.TP
\fB\-o\fR entry_timeout=T
cache timeout for names (1.0s)
.TP
\fB\-o\fR negative_timeout=T
cache timeout for deleted names (0.0s)
.TP
\fB\-o\fR attr_timeout=T
cache timeout for attributes (1.0s)
.SH AUTHOR
This manual page was written by Varun Hiremath <varunhiremath@gmail.com>,
for the Debian project (but may be used by others).
