.TH POLYMER 1 "July 29, 2005"
.SH NAME
polymer-config \- configure the Polymer Qt style
.SH SYNOPSIS
.B polymer-config
.SH DESCRIPTION
Polymer (formerly known as Plastique) is a port of the KDE style 
"Plastik", which does not depend on any KDE libraries. This means, that 
you only need Qt 3.x to make your Qt applications look as if you had 
KDE installed.
.PP
\fBpolymer-config\fP is the tool to configure this style to your 
personal preferences in a simmilar way the corresponding KDE control 
panel would allow you too.
.SH AUTHOR
The Polymer Qt style was ported by Adam Jakubek <mig21@static.int.pl>.
.PP
This manual page was written by Mathias Krause 
<mkrause@informatik.tu-cottbus.de>, for the Debian project (but may be 
used by others).
