
$FreeBSD$

--- c_src/gtk_drv_type.c.orig	Tue Nov  4 13:27:55 2003
+++ c_src/gtk_drv_type.c	Tue Nov  4 13:29:00 2003
@@ -316,6 +316,7 @@
     INIT_TYPE(GTK_TYPE_ACCEL_FLAGS);
     INIT_TYPE(GTK_TYPE_CALENDAR_DISPLAY_OPTIONS);
     INIT_TYPE(GTK_TYPE_CELL_TYPE);
+    INIT_TYPE(GTK_TYPE_CLIPBOARD);
     INIT_TYPE(GTK_TYPE_CLIST_DRAG_POS);
     INIT_TYPE(GTK_TYPE_BUTTON_ACTION);
     INIT_TYPE(GTK_TYPE_CTREE_POS);
