--- ./formats/haskell2/HaskellTop.hs.orig	2010-09-15 16:26:38.000000000 +0200
+++ ./formats/haskell2/HaskellTop.hs	2012-05-13 12:29:09.892465893 +0200
@@ -42,7 +42,7 @@
 
 import Char
 import Data.Maybe (fromMaybe,maybe)
-import System
+import System.Exit
 import Monad(when)
 
 -- naming conventions
@@ -235,8 +235,8 @@
 	        ["-- automatically generated by BNF Converter",
 		 "module Main where\n",
 	         "",
-	         "import IO ( stdin, hGetContents )",
-	         "import System ( getArgs, getProgName )",
+	         "import System.IO ( stdin, hGetContents )",
+	         "import System.Environment ( getArgs, getProgName )",
 		 "",
 		 "import " ++ alexFileM     opts,
 		 "import " ++ happyFileM    opts,
@@ -246,7 +246,7 @@
 	         if lay then ("import " ++ layoutFileM opts) else "",
 	         if use_xml then ("import " ++ xmlFileM opts) else "",
 	         if_glr "import Data.FiniteMap(FiniteMap, lookupFM, fmToList)",
-	         if_glr "import Maybe(fromJust)",
+	         if_glr "import Data.Maybe(fromJust)",
 	         "import " ++ errFileM      opts,
 		 "",
 		 if use_glr
