--- pyproject.toml.orig	2026-08-10 08:52:54.000000000 -0700
+++ pyproject.toml	2026-08-11 06:53:29.022878000 -0700
@@ -1,5 +1,5 @@
 [build-system]
-requires = ["setuptools >= 77.0.3, <= 84.0.0"]  # lower bound to support license/license-files (PEP 639), upper bound for latest version tested at release
+requires = ["setuptools >= 63.1.0, <= 84.0.0"]  # lower bound to support license/license-files (PEP 639), upper bound for latest version tested at release
 build-backend = "setuptools.build_meta"
 
 [project]
@@ -10,11 +10,6 @@
 ]
 description = "Radically simple IT automation"
 readme = "README.md"
-license = "GPL-3.0-or-later"
-license-files = [
-    "COPYING",
-    "licenses/*.txt",
-]
 classifiers = [
     "Development Status :: 5 - Production/Stable",
     "Environment :: Console",
