.\"     $OpenBSD: mdoc.template,v 1.10 2007/05/31 22:10:19 jmc Exp $
.Dd $Mdocdate: April 9 2010 $
.Dt IDEA 1
.Os
.Sh NAME
.Nm idea
.Nd launch JetBrains PhpStorm Integrated Development Environment
.Sh SYNOPSIS
.Nm
.Op jvm-args
.Sh DESCRIPTION
.Nm
starts up the JetBrains PhpStorm Integrated Development Environment.
.Sh SEE ALSO
The web site
https://www.jetbrains.com/phpstorm .
