CATEGORIES=	misc docs
PKGNAMEPREFIX=	nl-

MAINTAINER=	doceng@FreeBSD.org
COMMENT=	Dutch translation of the FreeBSD Documentation Project

MASTERDIR=	${.CURDIR}/../freebsd-doc-en
PLIST=		${.CURDIR}/pkg-plist

DOCLANG=	nl

.include "${MASTERDIR}/Makefile"
