--- pyproject.toml.orig	2026-02-08 18:23:02 UTC
+++ pyproject.toml
@@ -9,8 +9,7 @@ description = "Manipulate JSON-like data with NumPy-li
 name = "awkward"
 version = "2.9.0"
 description = "Manipulate JSON-like data with NumPy-like idioms."
-license = "BSD-3-Clause"
-license-files = ["LICENSE"]
+license = { text = "BSD-3-Clause" }
 requires-python = ">=3.10"
 authors = [
     { name = "Jim Pivarski", email = "jpivarski@gmail.com" },
