# configuration file for newsyslog for ntfy
#
# see newsyslog.conf(5) for details
#
# logfilename          [owner:group]    mode count size when  flags [/pid_file] [sig_num]
/var/log/ntfy.log			644  7	  1000 *      JC    /var/run/ntfyd.pid
