--- src/mongo/db/ftdc/BUILD.bazel.orig
+++ src/mongo/db/ftdc/BUILD.bazel
@@ -143,6 +143,7 @@ mongo_cc_library(
             "@platforms//os:windows": "windows",
             "@platforms//os:linux": "linux",
             "@platforms//os:macos": "osx",
+            "@platforms//os:freebsd": "osx",
         }.items()
     }),
     hdrs = [
