--- src/mongo/BUILD.bazel.orig	2026-09-29 00:00:00 UTC
+++ src/mongo/BUILD.bazel
@@ -76,6 +76,9 @@ config_header(
         "//bazel/config:ssl_enabled_linux": {
             "MONGO_CONFIG_SSL_PROVIDER": "MONGO_CONFIG_SSL_PROVIDER_OPENSSL",
         },
+        "//bazel/config:ssl_enabled_freebsd": {
+            "MONGO_CONFIG_SSL_PROVIDER": "MONGO_CONFIG_SSL_PROVIDER_OPENSSL",
+        },
         "//conditions:default": {},
     }) | select({
         "//bazel/config:use_ocsp_stapling_enabled": {
