--- pyproject.toml.orig	2024-10-30 16:04:50 UTC
+++ pyproject.toml
@@ -21,5 +21,5 @@ find = {include = ["chunk*"]}
 "Homepage" = "https://github.com/youknowone/python-deadlib"
 
 [build-system]
-requires = ["setuptools>=75.0"]
+requires = ["setuptools>=61"]
 build-backend = "setuptools.build_meta"
