Support powerpcspe

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=234023

--- build/autoconf/config.sub.orig	2019-01-06 00:10:34.369158000 +0100
+++ build/autoconf/config.sub	2019-01-06 00:12:20.725890000 +0100
@@ -300,7 +300,7 @@
 	| ns16k | ns32k \
 	| open8 | or1k | or1knd | or32 \
 	| pdp10 | pdp11 | pj | pjl \
-	| powerpc | powerpc64 | powerpc64le | powerpcle \
+	| powerpc | powerpc64 | powerpc64le | powerpcle | powerpcspe \
 	| pyramid \
 	| riscv32 | riscv64 \
 	| rl78 | rx \
@@ -427,7 +427,7 @@
 	| or1k*-* \
 	| orion-* \
 	| pdp10-* | pdp11-* | pj-* | pjl-* | pn-* | power-* \
-	| powerpc-* | powerpc64-* | powerpc64le-* | powerpcle-* \
+	| powerpc-* | powerpc64-* | powerpc64le-* | powerpcle-* | powerpcspe-* \
 	| pyramid-* \
 	| riscv32-* | riscv64-* \
 	| rl78-* | romp-* | rs6000-* | rx-* \
