--- programs/Xserver/hw/xfree86/drivers/ati/r128_driver.c.orig	Tue Feb 18 17:19:41 2003
+++ programs/Xserver/hw/xfree86/drivers/ati/r128_driver.c	Thu Mar 13 00:12:12 2003
@@ -275,6 +275,7 @@
     "drmAddMap",
     "drmAgpAcquire",
     "drmAgpAlloc",
+    "drmAgpBase",
     "drmAgpBind",
     "drmAgpDeviceId",
     "drmAgpEnable",
@@ -288,8 +289,11 @@
     "drmCommandRead",
     "drmCommandWrite",
     "drmCommandWriteRead",
+    "drmCtlInstHandler",
+    "drmCtlUninstHandler",
     "drmFreeBufs",
     "drmFreeVersion",
+    "drmGetInterruptFromBusID",
     "drmGetLibVersion",
     "drmGetVersion",
     "drmMap",
@@ -307,6 +311,7 @@
     "DRICreateInfoRec",
     "DRIDestroyInfoRec",
     "DRIFinishScreenInit",
+    "DRIGetDeviceInfo",
     "DRIGetSAREAPrivate",
     "DRILock",
     "DRIQueryVersion",
