--- config.m4.orig	2026-09-08 02:56:58 UTC
+++ config.m4
@@ -91,7 +91,6 @@ if test "$PHP_MUSTACHE" != "no"; then
   PHP_REQUIRE_CXX()
   PHP_CXX_COMPILE_STDCXX(17, mandatory, PHP_MUSTACHE_STDCXX)
   PHP_MUSTACHE_ADD_FLAGS([$PHP_MUSTACHE_STDCXX])
-  PHP_ADD_LIBRARY(stdc++, 1, MUSTACHE_SHARED_LIBADD)
 
   AC_LANG_PUSH([C++])
   PHP_MUSTACHE_SAVED_CXXFLAGS="$CXXFLAGS"
