--- pyproject.toml.orig	2006-07-24 01:21:28 UTC
+++ pyproject.toml
@@ -1,5 +1,5 @@
 [build-system]
-requires = ["maturin>=1.2,<1.14"]
+requires = ["maturin>=1.7,<2.0"]
 build-backend = "maturin"
 
 [project]
