ROOTCHECK_MANAGED_CONF=		120.rootcheck.conf
ROOTCHECK_LOCAL_CONF=		520.rootcheck.local.conf

ROOTCHECK_DESC=			System Audit and Rootkit Detection (rootcheck)

# Basic
ROOTCHECK_BASIC_OPTION=		BASIC_RC
ROOTCHECK_BASIC_PROFILE=	basic
ROOTCHECK_BASIC_DESC=		Basic audit and rootkits
ROOTCHECK_BASIC_DEFINE=		server local agent pushed
ROOTCHECK_BASIC_DEFAULT=	server local pushed
ROOTCHECK_OPTIONS+=		ROOTCHECK_BASIC

# CIS default
ROOTCHECK_CIS_OPTION=		CIS_RC
ROOTCHECK_CIS_PROFILE=		cis
ROOTCHECK_CIS_DESC=		CIS benchmark - Legacy
ROOTCHECK_CIS_DEFINE=		pushed
ROOTCHECK_CIS_DEFAULT=		pushed
ROOTCHECK_OPTIONS+=		ROOTCHECK_CIS

# CIS level 1
ROOTCHECK_CIS_L1_OPTION=	CIS_L1_RC
ROOTCHECK_CIS_L1_PROFILE=	cis-level1
ROOTCHECK_CIS_L1_DESC=		CIS benchmark - Level 1
ROOTCHECK_CIS_L1_DEFINE=	pushed
ROOTCHECK_CIS_L1_DEFAULT=	pushed
ROOTCHECK_OPTIONS+=		ROOTCHECK_CIS_L1

# CIS level 2
ROOTCHECK_CIS_L2_OPTION=	CIS_L2_RC
ROOTCHECK_CIS_L2_PROFILE=	cis-level2
ROOTCHECK_CIS_L2_DESC=		CIS benchmark - Level 2
ROOTCHECK_CIS_L2_DEFINE=	pushed
ROOTCHECK_CIS_L2_DEFAULT=	pushed
ROOTCHECK_OPTIONS+=		ROOTCHECK_CIS_L2
