CMDOUT_MANAGED_CONF=		140.command-output.conf
CMDOUT_LOCAL_CONF=		540.command-output.local.conf

CMDOUT_DESC=			Command Output Monitoring

CMDOUT_SCRIPTS=			last-logins open-ports

# Last logins
CMDOUT_LAST_LOGINS_OPTION=	LOGINS
CMDOUT_LAST_LOGINS_DESC=	Last logins
CMDOUT_LAST_LOGINS_DEFINE=	server local agent
CMDOUT_LAST_LOGINS_DEFAULT=	server local agent
CMDOUT_OPTIONS+=		CMDOUT_LAST_LOGINS

# Open TCP ports
CMDOUT_OPEN_PORTS_TCP_OPTION=	PORTS_TCP
CMDOUT_OPEN_PORTS_TCP_DESC=	Open TCP ports
CMDOUT_OPEN_PORTS_TCP_DEFINE=	server local agent
CMDOUT_OPEN_PORTS_TCP_DEFAULT=	server local agent
CMDOUT_OPTIONS+=		CMDOUT_OPEN_PORTS_TCP

# Open UDP ports
CMDOUT_OPEN_PORTS_UDP_OPTION=	PORTS_UDP
CMDOUT_OPEN_PORTS_UDP_DESC=	Open UDP ports
CMDOUT_OPEN_PORTS_UDP_DEFINE=	server local agent
CMDOUT_OPEN_PORTS_UDP_DEFAULT=	server local agent
CMDOUT_OPTIONS+=		CMDOUT_OPEN_PORTS_UDP
