--- build.properties.orig	2026-04-08 13:02:03 UTC
+++ build.properties
@@ -21,8 +21,8 @@ debug: on
 
 # compilation settings
 debug: on
-target-jvm: 1.5
-source-level: 1.5
+target-jvm: 8
+source-level: 8
 
 # jar generation settings
 jar-compression: true
