# $FreeBSD$
#
    SUBDIR += xtel

    SUBDIR += aspell
    SUBDIR += cups
    SUBDIR += cups-base
    SUBDIR += cups-lpr
    SUBDIR += ispell
    SUBDIR += kde3-i18n
    SUBDIR += linux-netscape6
    SUBDIR += ooodict-fr_FR
    SUBDIR += openoffice
    SUBDIR += php_doc
    SUBDIR += staroffice52

.include <bsd.port.subdir.mk>
