--- build/meta.go.orig	2025-07-01 09:12:25 UTC
+++ build/meta.go
@@ -1,7 +1,9 @@
+// Code generated by go generate; DO NOT EDIT.
+// This file was generated by go generate at 2025-08-05T13:50:15+02:00.
 package build
 
 const (
-	commit    = "?"
-	version   = "?"
-	buildTime = 0
+	commit = "cb81895"
+	version = "v2.10.4"
+	buildTime = %%BUILDTIME%%
 )
