--- build/meta.go.orig	2025-06-20 10:01:03 UTC
+++ build/meta.go
@@ -1,7 +1,9 @@
+// Code generated by go generate; DO NOT EDIT.
+// This file was generated by go generate at 2025-06-20T12:03:30+02:00.
 package build
 
 const (
-	commit    = "?"
-	version   = "?"
-	buildTime = 0
+	commit = "cb49633"
+	version = "v2.10.3"
+	buildTime = %%BUILDTIME%%
 )
