--- cTemplate.cpp.orig	2010-04-21 15:54:07.000000000 +0800
+++ cTemplate.cpp	2010-04-21 15:54:14.000000000 +0800
@@ -171,7 +171,6 @@ PHP_MINIT_FUNCTION(cTemplate)
     REGISTER_LONG_CONSTANT ("TS_EMPTY", TS_EMPTY, CONST_CS | CONST_PERSISTENT);
     REGISTER_LONG_CONSTANT ("TS_ERROR", TS_ERROR, CONST_CS | CONST_PERSISTENT);
     REGISTER_LONG_CONSTANT ("TS_READY", TS_READY, CONST_CS | CONST_PERSISTENT);
-    REGISTER_LONG_CONSTANT ("TS_SHOULD_RELOAD", TS_SHOULD_RELOAD, CONST_CS | CONST_PERSISTENT);
     REGISTER_LONG_CONSTANT ("TC_HTML", TC_HTML, CONST_CS | CONST_PERSISTENT);
     REGISTER_LONG_CONSTANT ("TC_JS", TC_JS, CONST_CS | CONST_PERSISTENT);
     REGISTER_LONG_CONSTANT ("TC_CSS", TC_CSS, CONST_CS | CONST_PERSISTENT);
