--- cmake/modules/ElCheckFunctionExists.cmake.orig	2018-08-17 05:32:25 UTC
+++ cmake/modules/ElCheckFunctionExists.cmake
@@ -93,6 +93,7 @@ macro(EL_CHECK_FUNCTION_EXISTS FUNCTION 
       ${CHECK_FUNCTION_EXISTS_ADD_LIBRARIES}
       CMAKE_FLAGS -DCOMPILE_DEFINITIONS:STRING=${MACRO_CHECK_FUNCTION_DEFINITIONS} ${CHECK_FUNCTION_EXISTS_ADD_LINKER_FLAGS}
       "${CHECK_FUNCTION_EXISTS_ADD_INCLUDES}"
+      LINK_LIBRARIES ${FREEBSD_GCC_LIB}
       OUTPUT_VARIABLE OUTPUT)
     if(${VARIABLE})
       set(${VARIABLE} 1 CACHE INTERNAL "Have function ${FUNCTION}")
