PORTNAME=	Net-BitTorrent-PeerPacket
PORTVERSION=	1.2
PORTREVISION=	1
CATEGORIES=	net-p2p perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Parse/Build Peer Packets from BitTorrent
WWW=		https://metacpan.org/release/Net-BitTorrent-PeerPacket

USES=		perl5
USE_PERL5=	modbuild

DEPRECATED=	Deprecated, no active development in more than a decade so any "new" functionality is missing and interoperability with recent software is very limited if not completely broken
EXPIRATION_DATE=2025-04-30

.include <bsd.port.mk>
