--- pyproject.toml.orig	2025-11-01 02:40:04 UTC
+++ pyproject.toml
@@ -1,17 +1,15 @@
 [build-system]
-requires = ["setuptools", "wheel", "setuptools-git-versioning"]
+requires = ["setuptools", "wheel"]
 build-backend = "setuptools.build_meta"
 
 [tool.setuptools.packages]
 find = {namespaces = false}
 
-[tool.setuptools-git-versioning]
-enabled = true
-
 [project]
 name = "logistro"
+version = "2.0.1"
 description = "Simple wrapper over logging for a couple basic features"
-dynamic = ["version"]
+dynamic = []
 readme = "README.md"
 license = { "file" = "LICENSE" }
 requires-python = ">=3.8"
