# Created by: Johannes Meixner <xmj@chaot.net>
# $FreeBSD$

PORTNAME=	ace-rails-ap
PORTVERSION=	3.0.3
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ajax.org Cloud9 Editor (Ace) for the Rails 3.1 asset pipeline

LICENSE=	MIT

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes
USES=		shebangfix

SHEBANG_FILES=	update.sh

.include <bsd.port.mk>
