.TH ASLINK 1 
.SH NAME
ASLINK \- companion linker for the ASxxxx assemblers.
.SH SYNOPSIS
.B aslink
.I "[options] filenames"
.br
.B link-gbz80
.I "[options] filenames"
.br
.B link-z80
.I "[options] filenames"
.br
.SH WARNING
The information in this man page is an extract from the full
documentation of 
.B SDCC\c
\&, and is limited to the meaning of the options.
.PP
For complete and current documentation, refer to the
.B
ASxxxx Cross Assembler Documentation\c
\&, available in /usr/share/doc/sdcc-doc/aslink.
.SH "DESCRIPTION"
The
.B ASLINK\c
\& is general relocating companion linker for the 
.B ASxxx\c
\& assemblers.
.PP
.B MCS51\c
\& family is supported by
.B aslink\c
\&.
.br
.B Z80\c 
\& family is supported by
.B link-z80\c
\&.
.br
.B GBZ80\c
\& (GameBoy Z80-like CPU) is supported by
.B link-gbz80\c
\&.
.SH OPTIONS
The linker may run in the command line mode or command file modes.  The 
allowed startup linker commands are:  
.TP 
.BI "\-c/\-f"
command line / command file modes 
.TP
.BI "\-p/\-n"
enable/disable echo file.lnk input to stdout 
.PP
If command line mode is selected, all linker commands come from stdin, if the 
command file mode is selected the commands are input from the specified 
file (extension must be .lnk). 
.PP
After invoking the linker the valid options are:
.TP
.BI
.TP
.BI "\-i/\-s"
Intel Hex (file.ihx) or Motorola S19 (file.s19) image output file.
.TP
.BI "\-z"
Specifies that symbol names are case sensitive. 
.TP
.BI "\-m"
Generate a map file (file.map). This file contains a list of the symbols 
(by area) with absolute addresses, sizes of linked areas, and other linking
information.  
.TP
.BI "\-w"
Specifies that a wide listing format be used for the map file.  
.TP
.BI "\-xdq"
Specifies the number radix for the map file (Hexidecimal, Decimal, or 
Octal).  
.TP
.BI "\-u"
Generate an updated listing file (file.rst) derived from the relocated 
addresses and data from the linker.
.TP
.BI "fileN"
Files to be linked. Files may be on the same line as the above options or on a 
separate line(s) one file  per line or multiple files separated by spaces or
tabs.
.TP
.BI "-b " "area = expression" " (one definition per line)"
This specifies an area base address where the expression may contain constants 
and/or defined symbols from the linked files.  
.TP
.BI "-g "  "symbol = expression" " (one definition per line)" 
This specifies the value for the symbol where the expression may contain 
constants and/or defined symbols from the linked files.  
.TP
.BI "-k " "library directory path" " (one  definition  per line)"
This specifies one possible path to an object library.  More than one path is
allowed.  
.TP
.BI "-l " "library file specification" " (one  definition  per  line)"
This specifies a possible library file.  More than one file is allowed.  
.TP
.BI "-e "
or null line, terminates input to the linker.  
.SH SEE ALSO
sdcc(1), asxxxx(1), link-z80(1), link-gbz80(1).
.SH AUTHOR
This manual page was written by Aurelien Jarno <aurel32@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
