.TH ASxxxx 1 
.SH NAME
ASxxxx \- Series of microprocessor cross assemblers for SDCC.
.SH SYNOPSIS
.B asx8051
.I "[options] file1 [file2 file3 ... file6]"
.br
.B as-gbz80
.I "[options] file1 [file2 file3 ... file6]"
.br
.B as-z80
.I "[options] file1 [file2 file3 ... file6]"
.br
.SH WARNING
The information in this man page is an extract from the full
documentation of 
.B SDCC\c
\&, and is limited to the meaning of the options.
.PP
For complete and current documentation, refer to the
.B
ASxxxx Cross Assembler Documentation\c
\&, available in /usr/share/doc/sdcc-doc/aslink.
.SH "DESCRIPTION"
The
.B ASxxxx\c
\& assemblers are a series of microprocessor assemblers. Each assembler has
a device specific section. 
.PP
.B MCS51\c
\& family is supported by
.B asx8051\c
\&.
.br
.B Z80\c 
\& family is supported by
.B as-z80\c
\&.
.br
.B GBZ80\c
\& (GameBoy Z80-like CPU) is supported by
.B as-gbz80\c
\&.
.SH OPTIONS
The  ASxxxx assemblers are command line oriented. The PC assemblers are 
started with the appropriate option(s) and file(s) to assemble following 
the assembler name.
.TP
.BI "\-d"
decimal listing.
.TP
.BI "\-q"
octal listing.
.TP
.BI "\-x"
hex listing (default)
.PP
The listing radix affects the .lst, .rel, and .sym files.
.TP
.BI "\-j"
add line number and debug information to file.
.TP
.BI "\-g"
undefined symbols made global.
.TP
.BI "\-a"
all user symbols made global.
.TP
.BI "\-l"
create list output file1.lst.
.TP
.BI "\-o"
create object output file1.rel.
.TP
.BI "\-s"
create symbol output file1.sym.
.TP
.BI "\-p"
disable listing pagination.
.TP
.BI "\-w"
wide listing format for symbol table.
.TP
.BI "\-z"
enable case sensitivity for symbols.
.TP
.BI "\-f"
flag relocatable references by ` in the listing file.
.TP
.BI "\-ff"
flag relocatable reference by mode in the listing file.
.PP
The file name for the .lst, .rel, and .sym files is the first file name 
specified in the command line. All output files are ascii text files which 
may be edited, copied, etc. The output files are the concatenation of all 
the input files, if files are to be assembled independently invoke the 
assembler for each file.  
.PP
The .rel file contains a radix directive so that the linker will use the 
proper conversion for this file. Linked files may have different radices.  
.PP
If the list 
.B (l)\c
\& option is specified without the symbol table
.B (s)\c
\& option, the symbol table is placed at the end of the listing file.  
.SH SEE ALSO
sdcc(1), aslink(1), asx8051, as-z80(1), as-gbz80(1).
.SH AUTHOR
This manual page was written by Aurelien Jarno <aurel32@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
