.TH MAKEBIN 1 
.SH NAME
makebin \- convert a Intel IHX file to binary
.SH SYNOPSIS
.B makebin
.I "[options] filename"
.SH "DESCRIPTION"
This manual page documents briefly the
.BR makebin
command.
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
Instead, you can read the documentation in
/usr/share/doc/sdcc-doc.
.PP
.B makebin 
convert a Intel IHX file to binary.
.SH OPTIONS
.TP
.B \-h
Show summary of options.
.TP
.B \-p
Pack the file.
.TP
.BI \-s " romsize"
Specify the size of the ROM.
.SH AUTHOR
This manual page was written by Aurelien Jarno <aurel32@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
