.TH PACKIHX 1 
.SH NAME
packihx \-  A tool to pack Intel hex files for SDCC
.SH SYNOPSIS
.B packihx
.SH "DESCRIPTION"
This manual page documents briefly the
.BR sdcdb
command.
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
Instead, you can read the documentation in
/usr/share/doc/sdcc-doc.
.PP
.B SDCC
is a Freeware, retargettable, optimizing ANSI-C compiler
designed for 8 bit Microprocessors.
.SH AUTHOR
This manual page was written by Aurelien Jarno <aurel32@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
