.TH SDCPP 1 
.SH NAME
sdcpp \- C preprocessor for SDCC
.SH SYNOPSIS
.B sdcppold
.I "[options] filename"
.SH "DESCRIPTION"
This manual page documents briefly the
.BR sdccp
command.
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
Instead, you can read the documentation in
/usr/share/doc/sdcc-doc.
.PP
.B SDCC
is a Freeware, retargettable, optimizing ANSI-C compiler
designed for 8 bit Microprocessors.
.SH OPTIONS
.TP
.BI "\-include " "<file>"
Include the contents of
.I <file>\c
\& before other files.
.TP
.BI "\-imacros " "<file>"
Accept definition of macros in 
.I <file>\c
\&.
.TP
.BI "\-iprefix " "<path>"
Specify 
.I <path>\c
\& as a prefix for next two options.
.TP
.BI "\-iwithprefix " "<dir>"
Add 
.I <dir>\c
\& to the end of the system include path.
.TP
.BI "\-iwithprefixbefore " "<dir>"
Add 
.I <dir>\c
\& to the end of the main include path.
.TP
.BI "\-isystem " "<dir>"
Add 
.I <dir>\c
\& to the start of the system include path.
.TP
.BI "\-idirafter " "<dir>"
Add 
.I <dir>\c
\& to the end of the system include path.
.TP
.BI "-I " "<dir>"   
Add 
.I <dir>\c
\& to the end of the main include path.
.TP
.B "\-I\-"
Fine-grained include path control; see info docs.
.TP
.B "\-nostdinc"
Do not search system include directories (dirs specified with 
.B -isystem\c
\& will still be used).
.TP
.B "\-nostdinc++"
Do not search system include directories for C++.
.TP
.BI "-o " "<file>"
Put output into 
.I <file>\c
\&.
.TP
.B "\-pedantic"
Issue all warnings demanded by strict ISO C.
.TP
.B "\-pedantic-errors"
Issue 
.I \-pedantic\c
\& warnings as errors instead.
.TP
.B "\-trigraphs"
Support ISO C trigraphs.
.TP
.B "\-lang-c"
Assume that the input sources are in C.
.TP
.B "\-lang-c89"
Assume that the input sources are in C89.
.TP
.B "\-lang-c++"
Assume that the input sources are in C++.
.TP
.B "\-lang-objc"
Assume that the input sources are in ObjectiveC.
.TP
.B "\-lang-objc++"
Assume that the input sources are in ObjectiveC++.
.TP
.B "\-lang-asm"
Assume that the input sources are in assembler.
.TP
.BI "\-std=" "<std name>"
Specify the conformance standard; one of: 
gnu89, gnu99, c89, c99, iso9899:1990,
iso9899:199409, iso9899:1999
.TP
.B "\-+"
Allow parsing of C++ style features.
.TP
.B "\-w"
Inhibit warning messages.
.TP
.B "\-Wtrigraphs"
Warn if trigraphs are encountered.
.TP
.B "\-Wno-trigraphs"
Do not warn about trigraphs.
.TP
.B "\-Wcomment{s}"
Warn if one comment starts inside another.
.TP
.B "\-Wno-comment{s}"
Do not warn about comments.
.TP
.B "\-Wtraditional"
Warn about features not present in traditional C;
.TP
.B "\-Wno-traditional"
Do not warn about traditional C;
.TP
.B "\-Wundef"
Warn if an undefined macro is used by #if.
.TP
.B "\-Wno-undef"
Do not warn about testing undefined macros.
.TP
.B "\-Wimport"
Warn about the use of the #import directive.
.TP
.B "\-Wno-import"
Do not warn about the use of #import.
.TP
.B "\-Werror"
Treat all warnings as errors.
.TP
.B "\-Wno-error"
Do not treat warnings as errors.
.TP
.B "\-Wsystem-headers"
Do not suppress warnings from system headers.
.TP
.B "\-Wno-system-headers"
Suppress warnings from system headers.
.TP
.B "\-Wall"
Enable all preprocessor warnings.
.TP
.B "\-M"
Generate make dependencies.
.TP
.B "\-MM"                       
As 
.B "\-M"\c
\&, but ignore system header files.
.TP
.BI "\-MF " "<file>"
Write dependency output to the given file.
.TP
.B "\-MG"
Treat missing header file as generated files.
.TP
.B "\-MP"
Generate phony targets for all headers.
.TP
.BI "\-MQ " "<target>"
Add a MAKE-quoted target.
.TP
.BI "\-MT " "<target>"
Add an unquoted target.
.TP
.BI "\-D" "<macro>"                 
Define a 
.I <macro>\c
\& with string '1' as its value.
.TP
.BI "\-D" "<macro>=<val>"           
Define a 
.I <macro>\¢
\& with 
.I <val>\c
\& as its value.
.TP
.BI "\-A" "<question> (<answer>)"   
Assert the 
.I <answer>\c
\& to 
.I <question>\c
\&.
.TP
.BI "\-A\-" "<question> (<answer>)"
Disable
.I <answer>\c
\& to 
.I <question>\c
\&.
.TP 
.BI "-U" "<macro>"
Undefine 
.I <macro>\c
\&.
.TP
.B "\-H"
Print the name of header files as they are used.
.TP
.B "\-C"
Do not discard comments.
.TP
.B "\-dM"
Display a list of macro definitions active at end.
.TP
.B "\-dD"
Preserve macro definitions in output.
.TP
.B "\-dN"
As 
.B \-dD\c
\& except that only the names are preserved.
.TP
.B "\-dI"
Include #include directives in the output.
.TP
.B "\-fpreprocessed"
Treat the input file as already preprocessed.
.TP
.BI "\-ftabstop=" "<number>"
Distance between tab stops for column reporting.
.TP
.B "\-P"
Do not generate #line directives.
.TP
.B "\-$"
Do not allow '$' in identifiers.
.TP
.B "\-remap"
Remap file names when including files.
.TP
.B "\-v or \-\-version"
Display the version number.
.TP
.B "\-h or \-\-help"
Show summary of options.

.SH AUTHOR
This manual page was written by Aurelien Jarno <aurel32@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
