--- pyproject.toml.orig	2026-02-21 11:12:14 UTC
+++ pyproject.toml
@@ -2,7 +2,7 @@ requires = [
 
 [build-system]
 requires = [
-    "setuptools >=79",
+    "setuptools >=61",
     # "setuptools-scm",   # if we want to use git versions for versioning
     # "wheel",  # setuptools doesn't need wheel anymore, see https://pypi.org/project/wheel/
 ]
@@ -15,8 +15,7 @@ readme = "README.md"  # manually copied and cut
            # "readme",
           ]
 readme = "README.md"  # manually copied and cut
-license = "BSD-3-Clause"
-license-files = ["LICENSE"]
+license = { text = "BSD-3-Clause" }
 authors = [
     { name = "Nikolaus Hansen"},
     { name = "Nace Sever" },
