# $FreeBSD$

PORTNAME=	shakespeare
PORTVERSION=	2.0.5
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Toolkit for making compile-time interpolated templates

LICENSE=	MIT

USE_CABAL=	aeson blaze-html blaze-markup exceptions parsec>=2 \
		text>=0.7

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
