--- setup.py.orig	2017-07-10 22:15:07 UTC
+++ setup.py
@@ -38,26 +38,12 @@ setup(name="PuLP",
       #ext_modules = [pulpCOIN],
       package_dir={'':'src'},
       #need the cbc directories here as the executable bit is set
-      packages = ['pulp', 
-      'pulp.solverdir',
-      'pulp.solverdir.cbc.linux.32',
-      'pulp.solverdir.cbc.linux.64',
-      'pulp.solverdir.cbc.win.32',
-      'pulp.solverdir.cbc.win.64',
-      'pulp.solverdir.cbc.osx.64'],
-      package_data = {'pulp' : ["AUTHORS","LICENSE",
-                                "pulp.cfg.linux",
-                                "pulp.cfg.win",
-                                "pulp.cfg.osx",
-                                "LICENSE.CoinMP.txt",
+      packages = ['pulp'],
+      package_data = {'pulp' : ["AUTHORS",
+                                "pulp.cfg.freebsd",
                                 "AUTHORS.CoinMP.txt",
                                 "README.CoinMP.txt",
                                 ],
-                      'pulp.solverdir.cbc.linux.32' : ['*','*.*'],
-                      'pulp.solverdir.cbc.linux.64' : ['*','*.*'],
-                      'pulp.solverdir.cbc.win.32' : ['*','*.*'],
-                      'pulp.solverdir.cbc.win.64' : ['*','*.*'],
-                      'pulp.solverdir.cbc.osx.64' : ['*','*.*'],
                       },
       install_requires = ['pyparsing>=2.0.1'],
       entry_points = ("""
