--- pyproject.toml.orig	2026-08-04 21:34:12 UTC
+++ pyproject.toml
@@ -37,7 +37,7 @@ script-files = ["mat2"]
 script-files = ["mat2"]
 
 [tool.setuptools.packages.find]
-exclude = ["tests*"]
+exclude = ["tests*","doc","doc.*"]
 
 [tool.setuptools.data-files]
 "share/man/man1" = ["doc/mat2.1"]
