--- electron/build/args/all.gn.orig	2026-09-30 08:47:42 UTC
+++ electron/build/args/all.gn
@@ -31,8 +31,8 @@ enable_cdm_host_verification = false
 v8_enable_javascript_promise_hooks = true
 
 enable_cdm_host_verification = false
-ffmpeg_branding = "Chrome"
-proprietary_codecs = true
+# ffmpeg_branding = "Chrome"
+# proprietary_codecs = true
 
 enable_printing = true
 
