# $FreeBSD$

PORTNAME=	rgen
PORTVERSION=	0.8.2
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	romain@FreeBSD.org
COMMENT=	Ruby modeling and generator framework

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/MIT-LICENSE

USES=		gem
USE_RUBY=	yes

.include <bsd.port.mk>
