--- CMakeModules/FindOpenEXR.cmake.orig	2021-04-11 21:39:01 UTC
+++ CMakeModules/FindOpenEXR.cmake
@@ -51,14 +51,14 @@ MACRO(OPENEXR_FIND libname)
     OPENEXR_FIND_VAR(OPENEXR_${libname}_LIBRARY_DEBUG ${libname}d)
 ENDMACRO(OPENEXR_FIND)
 
-OPENEXR_FIND(IlmImf)
+OPENEXR_FIND(OpenEXR)
 OPENEXR_FIND(IlmThread)
 OPENEXR_FIND(Iex)
-OPENEXR_FIND(Half)
+OPENEXR_FIND(Imath)
 
 SET(OPENEXR_FOUND "NO")
-IF(OPENEXR_INCLUDE_DIR AND OPENEXR_IlmImf_LIBRARY AND OPENEXR_IlmThread_LIBRARY AND OPENEXR_Iex_LIBRARY AND OPENEXR_Half_LIBRARY)
-    SET(OPENEXR_LIBRARIES ${OPENEXR_IlmImf_LIBRARY} ${OPENEXR_IlmThread_LIBRARY} ${OPENEXR_Half_LIBRARY} ${OPENEXR_Iex_LIBRARY} )
-    SET(OPENEXR_LIBRARIES_VARS OPENEXR_IlmImf_LIBRARY OPENEXR_IlmThread_LIBRARY OPENEXR_Half_LIBRARY OPENEXR_Iex_LIBRARY )
+IF(OPENEXR_INCLUDE_DIR AND OPENEXR_OpenEXR_LIBRARY AND OPENEXR_IlmThread_LIBRARY AND OPENEXR_Iex_LIBRARY AND OPENEXR_Imath_LIBRARY)
+    SET(OPENEXR_LIBRARIES ${OPENEXR_OpenEXR_LIBRARY} ${OPENEXR_IlmThread_LIBRARY} ${OPENEXR_Imath_LIBRARY} ${OPENEXR_Iex_LIBRARY} )
+    SET(OPENEXR_LIBRARIES_VARS OPENEXR_OpenEXR_LIBRARY OPENEXR_IlmThread_LIBRARY OPENEXR_Imath_LIBRARY OPENEXR_Iex_LIBRARY )
     SET(OPENEXR_FOUND "YES")
-ENDIF(OPENEXR_INCLUDE_DIR AND OPENEXR_IlmImf_LIBRARY AND OPENEXR_IlmThread_LIBRARY AND OPENEXR_Iex_LIBRARY AND OPENEXR_Half_LIBRARY)
+ENDIF(OPENEXR_INCLUDE_DIR AND OPENEXR_OpenEXR_LIBRARY AND OPENEXR_IlmThread_LIBRARY AND OPENEXR_Iex_LIBRARY AND OPENEXR_Imath_LIBRARY)
