# New ports collection makefile for:	File::Sort
# Date created:				30 Dec 2001
# Whom:					Seamus Venasse <svenasse@polaris.ca>
#
# $FreeBSD$
#

PORTNAME=		File-Sort
PORTVERSION=		1.01
CATEGORIES=		misc perl5
MASTER_SITES=		${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	File
PKGNAMEPREFIX=		p5-

MAINTAINER=		svenasse@polaris.ca
COMMENT=	Sort a file or merge sort multiple files

PERL_CONFIGURE=		yes

MAN3=			File::Sort.3

.include <bsd.port.mk>
