#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['sphinx_inline_tabs']

package_data = \
{'': ['*'], 'sphinx_inline_tabs': ['static/*']}

package_dir = \
{'': 'src'}

install_requires = \
['sphinx >= 3']

extras_require = \
{'doc': ['myst-parser', 'furo'],
 'test': ['pytest', 'pytest-cov', 'pytest-xdist']}

setup(name='sphinx_inline_tabs',
      version='%%PORTVERSION%%',
      description='Add inline tabbed content to your Sphinx documentation.',
      author='Pradyun Gedam',
      author_email='mail@pradyunsg.me',
      url='https://github.com/pradyunsg/sphinx-inline-tabs',
      packages=packages,
      package_data=package_data,
      package_dir=package_dir,
      install_requires=install_requires,
      extras_require=extras_require,
      python_requires='>=3.7',
     )
