--- src/Cargo.toml.orig	2026-09-05 22:05:31 UTC
+++ src/Cargo.toml
@@ -72,7 +72,7 @@ itoa = "1"
 log-panics = { version = "2.1.0", features = ["with-backtrace"] }
 scopeguard = "1.2.0"
 itoa = "1"
-rquickjs = { version = "0.11", features = ["full-async"] }
+rquickjs = { version = "0.11", features = ["full-async", "bindgen"] }
 rustix = { version = "1", features = ["all-apis"] }
 
 [target."cfg(unix)".dependencies]
