.Dd February 21, 2002
.Dt ORIONCTL 1
.Os FreeBSD
.Sh NAME
.Nm %%CONTROL_SCRIPT_NAME%%
.Nd %%APP_TITLE%% server control interface
.Sh SYNOPSIS
.Nm
.Op Ar start | Ar restart | Ar stop
.Sh DESCRIPTION
The
.Nm
shell script provides an interface to the %%APP_TITLE%% application server.
.Pp
The script expects exactly one argument, either
.Ar start ,
.Ar restart
or
.Ar stop .
If more than one argument is given, then all arguments but the first are
ignored.
.Bl -tag -width indent
.It Ar start
Start %%APP_TITLE%%, if it is not already running.
.It Ar restart
Restart %%APP_TITLE%%. If it is already running, then it will be stopped and then
started right after that. Otherwise it will just be started up.
.It Ar stop
Stop %%APP_TITLE%%, if it is actually running.
.El
.Sh ERRORS
The following error conditions are detected. They will be checked in the
specified order. In each case where an error message is printed, the name of
the script
.Em ( basename $0 )
will be prepended.
.Pp
If no argument is passed, or if an argument other than
.Ar start ,
.Ar restart
or
.Ar stop
is passed as the first argument, then a simple help message is printed and the
script is exited with error code 64.
.Pp
Other than that, the following errors conditions are defined:
.Bl -tag -width indent
.It Em %%APP_TITLE%% seems to be running already.
Prints an error message and exits the script with error code 1.
.It Em %%APP_TITLE%% home directory cannot be found
Prints an error message and exits the script with error code 2.
.It Em %%APP_TITLE%% script cannot be found
Prints an error message and exits the script with error code 3.
.It Em Java VM cannot be found
Prints an error message and exits the script with error code 4.
.El
.Sh FILES
.Bl -tag -width -indent
.It Pa /var/run/orion.pid
The %%APP_TITLE%% PID file that is used to store the process
ID of the currently running process in. It is deleted as soon as the server is
stopped and recreated when it is started. It should never be writable for anyone but
.Em root ,
.It Pa %%PREFIX%%/etc/rc.d/%%STARTUP_ORDER%%.orion.sh
A script that starts the
.Nm
script. It starts %%APP_TITLE%% at startup time.
.El
.Sh AUTHORS
.An Ernst de Haan Aq znerd@FreeBSD.org
