# Ports collection makefile for:  Gollem
# Date created:			  Sun Dec 16, 2001
# Whom:				  Thierry Thomas (<thierry@pompo.net>)
#
# $FreeBSD$
#

PORTNAME=	gollem
PORTVERSION=	1.1.1
PORTREVISION=	3
CATEGORIES=	ftp www

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Web-based File Manager

USE_HORDE=	base
USE_GETTEXT=	yes
PORTDOCS=	README CHANGES CREDITS INSTALL RELEASE_NOTES

.include "${.CURDIR}/../../www/horde-base/bsd.horde.mk"
.include <bsd.port.mk>
