--- scripts/test/test.fe.orig	Wed Jan  5 08:36:10 2005
+++ scripts/test/test.fe	Wed Oct 19 19:41:02 2005
@@ -17,16 +17,16 @@
 
     a_global_int = 10;
 
-    Console.println( "Printing Out All ext3 Partitions in /etc/fstab" );
+    Console.println( "Printing Out All ufs Partitions in /etc/fstab" );
     testfile = File.open( "/etc/fstab" );
     Console.println( "Here." );
     while( (blam = testfile.readln()) )
     {
-		object reg1 = new Regexp( '(\/dev\/[hs]d[a-g][1-9])   # device entry
+		object reg1 = new Regexp( '(\/dev\/[adw][ad][0-9][0-9]?s?[1-4]?[a-h])   # device entry
                                    [\ \t]*                    # whitespace
                                    (\/[a-z]*(\/[a-z]*)*)      # mount point
                                    [\ \t]*                    # whitespace
-                                   ext3                       # force adherance to ext3', 'xoi' );
+                                   ufs                        # force adherance to ufs', 'xoi' );
 		object reg2 = new Regexp( "[^ \t]+", "" );
 		
 		if( reg1.match( blam ) )
