--- pyproject.toml.orig	2025-07-08 12:23:44 UTC
+++ pyproject.toml
@@ -8,7 +8,7 @@ readme = "README.md"
 version = "2.99"
 description = "Text to Speech (TTS) library for Python 3. Works without internet connection or delay. Supports multiple TTS engines, including Sapi5, nsss, and espeak."
 readme = "README.md"
-license = "MPL-2.0"
+license = {text = "MPL-2.0"}
 keywords = [
   "gtts",
   "ivona",
