# configuration file for newsyslog for filebrowser-quantum
#
# see newsyslog.conf(5) for details
#
# logfilename          [owner:group]    mode count size when  flags [/pid_file] [sig_num]
/var/log/filebrowser-quantum.log			644  7	  1000 *      JC    /var/run/filebrowser-quantumd.pid
