# Created by: Stas Timokhin <devel@stasyan.com>
# $FreeBSD$

PORTREVISION=	6
CATEGORIES=	cad science

MASTERDIR=	${.CURDIR}/../salome

PORTNAME=	salome
PKGNAMESUFFIX=	-light
SAL_MODULE_UPPER=	LIGHT

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
