--- crates/remote_server/Cargo.toml.orig	2026-03-04 15:41:56 UTC
+++ crates/remote_server/Cargo.toml
@@ -27,7 +27,6 @@ collections.workspace = true
 clap.workspace = true
 client.workspace = true
 collections.workspace = true
-crashes.workspace = true
 dap_adapters.workspace = true
 debug_adapter_extension.workspace = true
 env_logger.workspace = true
@@ -74,11 +73,18 @@ uuid = { workspace = true, features = ["v4"] }
 rayon.workspace = true
 uuid = { workspace = true, features = ["v4"] }
 
-[target.'cfg(not(windows))'.dependencies]
+[target.'cfg(not(any(windows, target_os = "freebsd")))'.dependencies]
 crash-handler.workspace = true
 fork.workspace = true
 libc.workspace = true
 minidumper.workspace = true
+
+[target.'cfg(not(target_os = "freebsd"))'.dependencies]
+crashes.workspace = true
+
+[target.'cfg(target_os = "freebsd")'.dependencies]
+fork.workspace = true
+libc.workspace = true
 
 [target.'cfg(windows)'.dependencies]
 windows.workspace = true
