.Dd October 23, 2007
.Os FreeBSD
.Dt yfklog 1
.Sh NAME
.Nm yfklog 
.Nd yfklog Station logger utility
.Sh SYNOPSIS
This program does amateur radio station logging.
.Sh DESCRIPTION
YFKlog is a general purpose logbook to keep track of amateur
radio contacts. This is Version 0.3.4, released on 23. October 2007.
.Pp Project Website, Documentation
The latest version can be found at: http://fkurz.net/ham/yfklog.html
.Pp
Full documentation is at http://fkurz.net/ham/yfklog/doc/
.Sh AUTHORS
Fabian Kurz, DJ1YFK <mail@fkurz.net>
