# $FreeBSD$
#

    SUBDIR += imgvtopgm
    SUBDIR += jpilot
    SUBDIR += kpilot
    SUBDIR += pilot-link
    SUBDIR += pilot_makedoc
    SUBDIR += syncal
    SUBDIR += xcopilot

.include <bsd.port.subdir.mk>
