--- VTPrsTbl.c.orig	2016-11-04 21:41:21 UTC
+++ VTPrsTbl.c
@@ -490,7 +490,7 @@ CASE_GROUND_STATE,
 CASE_GROUND_STATE,
 CASE_GROUND_STATE,
 /*	X		Y		Z		[	*/
-CASE_GROUND_STATE,
+CASE_ECH,
 CASE_GROUND_STATE,
 CASE_GROUND_STATE,
 CASE_GROUND_STATE,
