.Dd December10, 2006
.Dt ipsc 8
.Os
.Sh NAME
.Nm ipsc
.Nd IP Subnet Calculator
.Sh SYNOPSIS
.Nm
.Op Options
.Op addr/mask | addr/offset | addr
.Sh DESCRIPTION
The IP Subnet Calculator is a tool that 
allows network administrators to make calculations that 
will assist in subnetting a network. It also has a number 
of other useful functions.
.Pp
The options are as follows:
.Bl -tag -width identXXXXXX
.It Fl C <class>
Network class (a, b, or c). Must be used with -B
.It Fl B <bits>
Subnet bits (must be used with -C).
.It Fl i <if>
Reverse engineer an interface (e.g. eth0).
.It Fl a
Print all information available.
.It Fl g
Print general information.
.It Fl s
Print all possible subnets.
.It Fl h
Print host information.
.It Fl c
Print CIDR information.
.It Fl v
Print the program version.
.El
