deno's upgrade feature cannot work on FreeBSD, directly disable it

Index: cli/Cargo.toml
--- cli/Cargo.toml.orig
+++ cli/Cargo.toml
@@ -24,7 +24,7 @@ harness = false
 harness = false
 
 [features]
-default = ["upgrade", "__vendored_zlib_ng"]
+default = ["__vendored_zlib_ng"]
 # A feature that enables heap profiling with dhat on Linux.
 # 1. Compile with `cargo build --profile=release-with-debug --features=dhat-heap`
 # 2. Run the executable. It will output a dhat-heap.json file.
@@ -131,7 +131,7 @@ jupyter_runtime.workspace = true
 jsonc-parser = { workspace = true, features = ["cst", "serde"] }
 jupyter-protocol.workspace = true
 jupyter_runtime.workspace = true
-keyring = { version = "3.6.3", features = ["apple-native", "sync-secret-service", "windows-native", "vendored"] }
+keyring = { version = "3.6.3", features = ["apple-native", "sync-secret-service", "windows-native"] }
 lazy-regex.workspace = true
 libc.workspace = true
 libz-sys.workspace = true
