# Created by: James Bailie <jimmy@mammothcheese.ca>
# $FreeBSD$

PORTNAME=	nickleby
PORTVERSION=	2.1
CATEGORIES=	x11-wm
MASTER_SITES=	http://www.mammothcheese.ca/

MAINTAINER=	jimmy@mammothcheese.ca
COMMENT=	Simple window manager

MAN1=	nickleby.1
MANCOMPRESSED=	yes
MAKE_ENV=	X11BASE=${LOCALBASE}
USE_XORG=	x11

PLIST_FILES=	bin/nickleby

NO_STAGE=	yes
.include <bsd.port.mk>
