--- CMake/folly-deps.cmake.orig	2026-10-05 14:18:47 UTC
+++ CMake/folly-deps.cmake
@@ -555,7 +555,7 @@ if (NOT WIN32 AND NOT APPLE)
 set(FOLLY_HAVE_BACKTRACE ${Backtrace_FOUND})
 set(FOLLY_HAVE_DWARF ${LIBDWARF_FOUND})
 if (NOT WIN32 AND NOT APPLE)
-  set(FOLLY_USE_SYMBOLIZER ON)
+  set(FOLLY_USE_SYMBOLIZER ${FREEBSD_FOLLY_USE_SYMBOLIZER})
 endif ()
 message(STATUS "Setting FOLLY_USE_SYMBOLIZER: ${FOLLY_USE_SYMBOLIZER}")
 message(STATUS "Setting FOLLY_HAVE_ELF: ${FOLLY_HAVE_ELF}")
