.\" The following requests are required for all man pages.
.Dd Thu Aug  1 09:36:57 CDT 1996
.Os
.Dt mplex 1
.Sh NAME
.Nm mplex
.Sh SYNOPSIS
.Nm mplex
.Ar file1
.Op file2
.Ar file3
.Sh DESCRIPTION
.Nm mplex
multiplexes MPEG audio and video streams into system layers.

.Sh AUTHORS
mplex was written by Christoph Moar <moar@informatik.tu-muenchen.de>.
This man page was written by Eric L. Hernes <erich@FreeBSD.org>
