--- ucb/source/ucp/webdav/makefile.mk.orig	2021-04-02 12:58:23 UTC
+++ ucb/source/ucp/webdav/makefile.mk
@@ -56,7 +56,7 @@ SERFINCDIR=serf
 #
 
 .IF "$(SYSTEM_APR)" == "YES"
-CFLAGS+= $(APR_CFLAGS)
+INCSYSTEM+= $(APR_CFLAGS)
 SHL1STDLIBS+=$(APR_LIBS)
 .ELSE
 CFLAGS+= -I$(SOLARINCDIR)$/$(APRINCDIR)
@@ -67,7 +67,7 @@ CFLAGS+=\
 .ENDIF
 
 .IF "$(SYSTEM_APR_UTIL)" == "YES"
-CFLAGS+= $(APR_UTIL_CFLAGS)
+INCSYSTEM+= $(APR_UTIL_CFLAGS)
 SHL1STDLIBS+=$(APR_UTIL_LIBS)
 .ELSE
 CFLAGS+= -I$(SOLARINCDIR)$/$(APRUTILINCDIR)
@@ -78,7 +78,7 @@ CFLAGS+=\
 .ENDIF
 
 .IF "$(SYSTEM_SERF)" == "YES"
-CFLAGS+= $(SERF_CFLAGS)
+INCSYSTEM+= $(SERF_CFLAGS)
 SHL1STDLIBS+=$(SERF_LIBS)
 .ELSE
 CFLAGS+= -I$(SOLARINCDIR)$/$(SERFINCDIR)
@@ -89,14 +89,14 @@ CFLAGS+=\
 .ENDIF
 
 .IF "$(SYSTEM_LIBXML)" == "YES"
-CFLAGS+= $(LIBXML_CFLAGS)
+INCSYSTEM+= $(LIBXML_CFLAGS)
 .ELSE
 LIBXMLINCDIR=external$/libxml
 CFLAGS+= -I$(SOLARINCDIR)$/$(LIBXMLINCDIR)
 .ENDIF
 
 .IF "$(SYSTEM_OPENSSL)" == "YES"
-CFLAGS+= -I$(OPENSSL_CFLAGS)
+INCSYSTEM+= -I$(OPENSSL_CFLAGS)
 SHL1STDLIBS+= $(OPENSSLLIB)
 .ELSE
 SHL1STDLIBS+= $(OPENSSLLIBST)
