BSD_PYQT_MK_VERSION=	20110129

PYQT_MAINTAINER=	kde@FreeBSD.org

MASTER_SITE_RIVERBANK=	http://www.riverbankcomputing.com/static/Downloads/
MASTER_SITE_FLUFFY=	http://ns.ael.ru/~fluffy.khv/pyqt/

MASTER_SITES_SIP=	${MASTER_SITE_RIVERBANK}sip4/ \
			${MASTER_SITE_GENTOO:S,%SUBDIR%,distfiles,} \
			${MASTER_SITE_FLUFFY}sip4/
MASTER_SITES_PYQT3=	${MASTER_SITE_RIVERBANK}PyQt3/ \
			${MASTER_SITE_FLUFFY}PyQt3/
MASTER_SITES_PYQT4=	${MASTER_SITE_RIVERBANK}PyQt4/ \
			${MASTER_SITE_GENTOO:S,%SUBDIR%,distfiles,} \
			${MASTER_SITE_FLUFFY}PyQt4/
MASTER_SITES_PYKDE3=	${MASTER_SITE_RIVERBANK}PyKDE3/ \
			${MASTER_SITE_FLUFFY}PyKDE3/
MASTER_SITES_QSCI1=	${MASTER_SITE_RIVERBANK}QScintilla1/ \
			${MASTER_SITE_GENTOO:S,%SUBDIR%,distfiles,} \
			${MASTER_SITE_FLUFFY}QScintilla1/
MASTER_SITES_QSCI2=	${MASTER_SITE_RIVERBANK}QScintilla2/ \
			${MASTER_SITE_GENTOO:S,%SUBDIR%,distfiles,} \
			${MASTER_SITE_FLUFFY}QScintilla2/

SIP_VERSION=		4.12.4
#SIP_SNAP=		-snapshot-20100102
PYQT3_VERSION=		3.18.2
PYQT3_SNAP=		-snapshot-20091119
PYQT4_VERSION=		4.8.5
#PYQT4_SNAP=		-snapshot-20100110
PYKDE3_VERSION=		3.16.7
QSCI1_VERSION=		1.7.1
QSCI2_VERSION=		2.4.6
#QSCI2_SNAP=		-snapshot-20091222

SIP_DISTNAME=		sip-${SIP_VERSION}${SIP_SNAP}
PYQT3_DISTNAME=		PyQt-x11-gpl-${PYQT3_VERSION}${PYQT3_SNAP}
PYQT4_DISTNAME=		PyQt-x11-gpl-${PYQT4_VERSION}${PYQT4_SNAP}
PYQT4_DISTINFO_FILE=	${PORTSDIR}/devel/py-qt4/distinfo
PYKDE3_DISTNAME=	PyKDE-${PYKDE3_VERSION}
QSCI1_DISTNAME=		QScintilla-1.71-gpl-${QSCI1_VERSION}
QSCI2_DISTNAME=		QScintilla-gpl-${QSCI2_VERSION}${QSCI2_SNAP}
QSCI2_DISTINFO_FILE=	${PORTSDIR}/devel/qscintilla2/distinfo
