--- pyproject.toml.orig	2026-04-17 15:46:34 UTC
+++ pyproject.toml
@@ -5,7 +5,7 @@ readme = "README.md"
 [project]
 name = "arviz-stats"
 readme = "README.md"
-requires-python = ">=3.12"
+requires-python = ">=3.11"
 license = {file = "LICENSE"}
 authors = [
     {name = "ArviZ team", email = "arvizdevs@gmail.com"}
@@ -25,7 +25,7 @@ dependencies = [
 ]
 dynamic = ["version", "description"]
 dependencies = [
-  "numpy>=2",
+  "numpy>=1.26.4",
   "scipy>=1.13",
 ]
 
