--- pyproject.toml.orig	2026-07-29 00:31:19 UTC
+++ pyproject.toml
@@ -1,10 +1,14 @@
+[build-system]
+requires = ["setuptools"]
+build-backend = "setuptools.build_meta"
+
 [project]
 name = "multimethod"
 version = "2.1"
 description = "Multiple argument dispatching."
 readme = "README.md"
 requires-python = ">=3.11"
-license = "Apache-2.0"
+license = {text = "Apache-2.0"}
 authors = [{name = "A. Coady"}]
 keywords = ["multiple", "dispatch", "multidispatch", "generic", "functions", "methods", "overload"]
 classifiers = [
