--- pyproject.toml.orig	2025-11-18 01:16:07 UTC
+++ pyproject.toml
@@ -1,10 +1,14 @@
+[build-system]
+requires = ["setuptools"]
+build-backend = "setuptools.build_meta"
+
 [project]
 name = "multimethod"
 version = "2.0.2"
 description = "Multiple argument dispatching."
 readme = "README.md"
 requires-python = ">=3.10"
-license = "Apache-2.0"
+license = {text = "Apache-2.0"}
 authors = [{name = "Aric Coady", email = "aric.coady@gmail.com"}]
 keywords = ["multiple", "dispatch", "multidispatch", "generic", "functions", "methods", "overload"]
 classifiers = [
