.TH SHTTPD 1 
.SH NAME
shttpd \- Simple HTTP Daemon
.SH SYNOPSIS
.PP
.B shttpd
.I [OPTIONS]
.PP
.B http    stream  tcp     nowait  nobody  /usr/local/bin/shttpd shttpd -I -d /var/www
.SH "DESCRIPTION"
.B shttpd
is a simple web server. It supports: CGI, Digest authentication, cookies,
GET, POST, PUT, DELETE methods, SSL. It does not detach from terminal. 
It stores logs in a standard format. If -d option is not given, the document
root is assumed to be the current directory.
.P
.B shttpd
can be embedded into existing application, in order to provide a Web GUI.
To do that, a header file with interface definition is needed, and application
should be compiled with shttpd.c, with -DEMBEDDED compilation flag set.
Refer to http://shttpd.sf.net to get the header file.
.P
.B shttpd
can be run as stand-alone server, or it may be managed by the
.I inetd(8)
superdaemon. In latter case,
.I \-I
option should be specified in inetd configuration line.
.SH OPTIONS
.TP 13
.I \-d directory
document root directory (default .)
.TP 13
.I \-p port
listening port (default 80 for non-SSL, 443 for SSL mode)
.TP 13
.I \-h
display help
.TP 13
.I \-S
use SSL
.TP 13
.I \-s certfile
use SSL certificate file (default shttpd.pem)
.TP 13
.I \-e errfile
error log file (default none)
.TP 13
.I \-l logfile
log file  (default shttpd.log)
.TP 13
.I \-I
inetd mode
.TP 13
.I \-i file1[,file2..]
index file (default index.html,index.cgi)
.TP 13
.I \-c pattern
CGI file pattern (default .cgi)
.TP 13
.I \-P passfile
global auth passwords file (default none)
.TP 13
.I \-u username
switch UID to given username's UID (default none)
.TP 13
.I \-m file
mime types file (default none)
.TP 13
.I \-N realm
authentication realm (default mydomain.com)
.TP 13
.I \-D
forbid directory listing
.SH FILES
.I /etc/inetd.conf
.SH SEE ALSO
.I inetd(8)
.SH COPYRIGHT
.B shttpd
is licensed under the terms of MIT license.
.SH AUTHOR
Sergey Lyubka <valenok@gmail.com>
