# New ports collection makefile for:	php52-sybase_ct
# Date created:			17 Apr 2010
# Whom:				Alex Keda <admin@lissyara.su>
#
# $FreeBSD$
#

CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php52

PKGNAMESUFFIX=	-sybase_ct

.include "${MASTERDIR}/Makefile"
