# New ports collection makefile for:	math/p5-Statistics-Regression
# Date created:				Apr 7,  2007
# Whom:					Cheng-Lung Sung <clsung@FreeBSD.org>
#
# $FreeBSD$
#

PORTNAME=	Statistics-Regression
PORTVERSION=	0.50
CATEGORIES=	math perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Statistics
PKGNAMEPREFIX=	p5-

MAINTAINER=	clsung@FreeBSD.org
COMMENT=	Perl module to perform weighted linear regression

PERL_CONFIGURE=	yes

MAN3=		Statistics::Regression.3

.include <bsd.port.mk>
