PORTNAME=	dexml2
PORTVERSION=	0.5.3
CATEGORIES=	devel python
MASTER_SITES=	PYPI
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Dead-simple Object-XML mapper for Python
WWW=		http://www.rfk.id.au/software/

LICENSE=	MIT

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
