--- commands/elec_ex_corr.cpp.orig	2026-04-20 16:31:08 UTC
+++ commands/elec_ex_corr.cpp
@@ -76,6 +76,7 @@ EnumStringMap<KineticType> kineticDescriptionMap(
 
 #ifdef LIBXC_ENABLED
 #include <xc.h>
+#include <xc_funcs.h>
 #include <xcMap.h> //autogenerated during cmake
 
 //Get description by temporarily initializing functional:
