--- sntp/socket.c.orig	Sun Jul  9 04:01:46 2006
+++ sntp/socket.c	Fri Aug  4 20:56:59 2006
@@ -7,8 +7,10 @@
 the only system that the author uses that has it is Linux. */
 
 
-
+/* XXX config.h not generated by configure script in this directory */
+#if 0
 #include "config.h"
+#endif
 
 #include "header.h"
 #include "internet.h"
