*** raypaint/Makefile.SH.orig	Sat Mar 28 20:31:28 1998
--- raypaint/Makefile.SH	Sat Mar 28 20:31:55 1998
***************
*** 55,65 ****
  
  #
  # If using X11, use:
! #GRAPHICSLIB = -lX11
  
  #
  # If you are using GL, use:
! GRAPHICSLIB = -lgl_s
  
  LIBRAY = $(LIBRAYDIR)/libray.a
  LIBSHADE = $(LIBSHADEDIR)/libshade.a
--- 55,65 ----
  
  #
  # If using X11, use:
! GRAPHICSLIB = -lX11
  
  #
  # If you are using GL, use:
! #GRAPHICSLIB = -lgl_s
  
  LIBRAY = $(LIBRAYDIR)/libray.a
  LIBSHADE = $(LIBSHADEDIR)/libshade.a
