--- pyproject.toml.orig	2026-05-08 04:46:45 UTC
+++ pyproject.toml
@@ -1,12 +1,11 @@ build-backend = "setuptools.build_meta"
 [build-system]
 build-backend = "setuptools.build_meta"
-requires = ["setuptools>=82.0.1"]
+requires = ["setuptools>=61"]
 
 [project]
 name = "types-psutil"
 version = "7.2.2.20260508"
-license = "Apache-2.0"
-license-files = ["LICENSE"]
+license = { text = "Apache-2.0" }
 description = "Typing stubs for psutil"
 readme = { text = """\
 ## Typing stubs for psutil
@@ -46,8 +45,4 @@ dependencies = []
 "Chat" = "https://gitter.im/python/typing"
 
 [tool.setuptools]
-packages = ['psutil-stubs']
 include-package-data = false
-
-[tool.setuptools.package-data]
-'psutil-stubs' = ['__init__.pyi', '_common.pyi', '_ntuples.pyi', '_psaix.pyi', '_psbsd.pyi', '_pslinux.pyi', '_psosx.pyi', '_psposix.pyi', '_pssunos.pyi', '_psutil_aix.pyi', '_psutil_bsd.pyi', '_psutil_linux.pyi', '_psutil_osx.pyi', '_psutil_sunos.pyi', '_psutil_windows.pyi', '_pswindows.pyi', 'METADATA.toml', 'py.typed']
