--- build/meta.go.orig	2025-08-05 10:59:13 UTC
+++ build/meta.go
@@ -1,7 +1,9 @@
+// Code generated by go generate; DO NOT EDIT.
+// This file was generated by go generate at 2025-08-05T13:00:15+02:00.
 package build
 
 const (
-	commit    = ""
-	version   = ""
-	buildTime = 0
+	commit = "a9cbb11"
+	version = "v2.3.6"
+	buildTime = %%BUILDTIME%%
 )
