--- build/meta.go.orig	2025-11-17 10:08:39 UTC
+++ build/meta.go
@@ -1,7 +1,9 @@
+// Code generated by go generate; DO NOT EDIT.
+// This file was generated by go generate at 2025-11-17T11:16:44+01:00.
 package build
 
 const (
-	commit    = ""
-	version   = ""
-	buildTime = 0
+	commit = "4616f43"
+	version = "v2.5.1"
+	buildTime = %%BUILDTIME%%
 )
