--- build/meta.go.orig	2025-03-10 12:07:28 UTC
+++ build/meta.go
@@ -1,7 +1,9 @@
+// Code generated by go generate; DO NOT EDIT.
+// This file was generated by go generate at 2025-03-10T13:09:09+01:00.
 package build
 
 const (
-	commit    = "?"
-	version   = "2.0.0"
-	buildTime = 0
+	commit = "4094916"
+	version = "v2.0.4"
+	buildTime = BUILDTIME
 )
