-- remove jemalloc dependencies from Cargo.lock

--- Cargo.toml.orig	2026-03-12 10:40:39 UTC
+++ Cargo.toml
@@ -160,9 +160,6 @@ collapsible_if = "allow"
 collapsible_if = "allow"
 
 [patch.crates-io]
-# packed_simd_2 = { git = "https://github.com/rust-lang/packed_simd", rev = "e57c7ba11386147e6d2cbad7c88f376aab4bdc86" }
-# simd-json = { git = "https://github.com/ritchie46/simd-json", branch = "alignment" }
-tikv-jemallocator = { git = "https://github.com/pola-rs/jemallocator", rev = "c7991e5bb6b3e9f79db6b0f48dcda67c5c3d2936" }
 object_store = { git = "https://github.com/kdn36/arrow-rs-object-store", branch = "feat_checksum_crc64" }
 color-backtrace = { git = "https://github.com/orlp/color-backtrace", rev = "bb62ccf1e9eb1f6b7af5f16acff1fd7151a876dd" }
 
