# New ports collection makefile for:	devel/p5-Carp-Clan
# Date created:				02 November 2004
# Whom:					Anton Berezin <tobez@FreeBSD.org>
#
# $FreeBSD$
#

PORTNAME=	Carp-Clan
PORTVERSION=	6.00
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Report errors from perspective of caller of a "clan" of modules

PERL_CONFIGURE=	yes

MAN3=	Carp::Clan.3

.include <bsd.port.mk>
