--- pyproject.toml.orig	2026-08-07 17:10:41 UTC
+++ pyproject.toml
@@ -1,5 +1,5 @@
 [build-system]
-requires = ["setuptools>=77.0.1",
+requires = ["setuptools",
             "setuptools_scm",
 ]
 build-backend = 'setuptools.build_meta'
