--- cmd/awslim-gen/main.go.orig	2025-04-11 13:35:01 UTC
+++ cmd/awslim-gen/main.go
@@ -10,8 +10,7 @@ import (
 	"text/template"
 )
 
-//go:generate go run ../awslim-gen-gen/main.go
-//go:generate go get ./...
+//go:generate ${GO_CMD} run ../awslim-gen-gen/main.go
 
 const serviceTemplateStr = `// Code generated by cmd/awslim-gen/main.go; DO NOT EDIT.
 package sdkclient
