%%INSTALL_DIR%%/bin/pgtclsh
%%INSTALL_DIR%%/bin/pgtksh
%%INSTALL_DIR%%/bin/pgaccess
%%INSTALL_DIR%%/lib/libpgtcl.a
%%INSTALL_DIR%%/lib/libpgtcl.so
%%INSTALL_DIR%%/lib/libpgtcl.so.2
%%INSTALL_DIR%%/include/libpgtcl.h
%%INSTALL_DIR%%/pgaccess/images/icon_button.gif
%%INSTALL_DIR%%/pgaccess/images/icon_checkbutton.gif
%%INSTALL_DIR%%/pgaccess/images/icon_entry.gif
%%INSTALL_DIR%%/pgaccess/images/icon_frame.gif
%%INSTALL_DIR%%/pgaccess/images/icon_label.gif
%%INSTALL_DIR%%/pgaccess/images/icon_listbox.gif
%%INSTALL_DIR%%/pgaccess/images/icon_query.gif
%%INSTALL_DIR%%/pgaccess/images/icon_radiobutton.gif
%%INSTALL_DIR%%/pgaccess/images/icon_text.gif
%%INSTALL_DIR%%/pgaccess/lib/help/abort.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/add_records.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/alter_table.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/alter_user.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/author.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/begin.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/close.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/cluster.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/commit.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/copy.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/copyrights.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/create_aggregate.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/create_database.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/create_function.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/create_index.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/create_language.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/create_operator.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/create_rule.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/create_sequence.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/create_table.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/create_table_as.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/create_trigger.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/create_type.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/create_user.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/create_view.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/data_types.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/datefunc.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/declare.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/delete.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/drop_aggregate.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/drop_database.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/drop_function.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/drop_index.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/drop_language.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/drop_operator.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/drop_rule.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/drop_sequence.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/drop_table.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/drop_trigger.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/drop_type.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/drop_user.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/drop_view.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/explain.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/fetch.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/form_design.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/forms.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/functions.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/geomfunc.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/grant.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/history.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/index.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/inheritance.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/insert.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/ipv4func.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/isolation.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/keywords.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/listen.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/load.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/lock.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/mathfunc.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/move.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/mvcc.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/new_query.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/new_table.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/notify.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/open_query.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/open_table.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/pgfunctions.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/postgresql.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/queries.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/reports.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/reset.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/revoke.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/rollback.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/schema.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/scripts.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/select.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/select_into.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/sequences.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/set.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/show.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/sql_guide.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/sqlfunc.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/stringfunc.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/tables.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/unlisten.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/update.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/users.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/vacuum.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/view_table_structure.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/views.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/visual_designer.hlp
%%INSTALL_DIR%%/pgaccess/lib/help/y2k.hlp
%%INSTALL_DIR%%/pgaccess/lib/languages/francais
%%INSTALL_DIR%%/pgaccess/lib/languages/italiano
%%INSTALL_DIR%%/pgaccess/lib/languages/magyar
%%INSTALL_DIR%%/pgaccess/lib/languages/romana
%%INSTALL_DIR%%/pgaccess/main.tcl
%%INSTALL_DIR%%/pgaccess/lib/database.tcl
%%INSTALL_DIR%%/pgaccess/lib/forms.tcl
%%INSTALL_DIR%%/pgaccess/lib/functions.tcl
%%INSTALL_DIR%%/pgaccess/lib/help.tcl
%%INSTALL_DIR%%/pgaccess/lib/mainlib.tcl
%%INSTALL_DIR%%/pgaccess/lib/preferences.tcl
%%INSTALL_DIR%%/pgaccess/lib/queries.tcl
%%INSTALL_DIR%%/pgaccess/lib/reports.tcl
%%INSTALL_DIR%%/pgaccess/lib/schema.tcl
%%INSTALL_DIR%%/pgaccess/lib/scripts.tcl
%%INSTALL_DIR%%/pgaccess/lib/sequences.tcl
%%INSTALL_DIR%%/pgaccess/lib/tables.tcl
%%INSTALL_DIR%%/pgaccess/lib/users.tcl
%%INSTALL_DIR%%/pgaccess/lib/views.tcl
%%INSTALL_DIR%%/pgaccess/lib/visualqb.tcl
