# Created by: Rich Neswold <rneswold@mcs.net>
# $FreeBSD$

PORTNAME=	wmnet
PORTVERSION=	1.2
PORTREVISION=	2
CATEGORIES=	net windowmaker
MASTER_SITES=	ftp://ftp.enteract.com/users/rneswold/ \
		${MASTER_SITE_LOCAL}
MASTER_SITE_SUBDIR=	novel

MAINTAINER=	novel@FreeBSD.org
COMMENT=	Network bandwidth monitor intended for the WindowMaker dock

USE_XORG=	xpm

.include <bsd.port.mk>
