--- cmake/SpheralConfig.cmake.orig	2026-04-01 08:49:15 UTC
+++ cmake/SpheralConfig.cmake
@@ -5,7 +5,7 @@ set(SPHERAL_INSTALL_BIN_DIR "bin" CACHE STRING "")
 set(SPHERAL_INSTALL_CONFIG_DIR "lib" CACHE STRING "")
 set(SPHERAL_INSTALL_LIB_DIR "lib" CACHE STRING "")
 set(SPHERAL_INSTALL_BIN_DIR "bin" CACHE STRING "")
-set(SPHERAL_INSTALL_CMAKE_MODULE_DIR "${SPHERAL_INSTALL_CONFIG_DIR}/cmake" CACHE STRING "")
+set(SPHERAL_INSTALL_CMAKE_MODULE_DIR "${SPHERAL_INSTALL_CONFIG_DIR}/cmake/spheral_cxx" CACHE STRING "")
 set(SPHERAL_INSTALL_PREFIX ${CMAKE_INSTALL_PREFIX} CACHE STRING "" FORCE)
 set(SPHERAL_INSTALL_SPHERAL "Spheral" CACHE STRING "")
 
