--- src/common/core/modsecurity/confs/http/modsecurity.conf.orig	2026-09-21 08:05:39 UTC
+++ src/common/core/modsecurity/confs/http/modsecurity.conf
@@ -1,4 +1,6 @@
+{% if has_modsecurity %}
 {%- if USE_MODSECURITY_GLOBAL_CRS == "yes" and has_service_with(all, {"SERVER_TYPE": "http", "USE_MODSECURITY": "yes"}) -%}
 modsecurity on;
 modsecurity_rules_file {{ NGINX_PREFIX }}http/modsecurity-rules-global-crs.conf.modsec;
 {%- endif %}
+{% endif %}
