--- src/common/confs/init-stream-lua.conf.orig	2026-05-25 18:23:18 UTC
+++ src/common/confs/init-stream-lua.conf
@@ -33,7 +33,7 @@ init_by_lua_block {
 	-- Load plugins from disk
 	logger:log(NOTICE, "loading plugins ...")
 	local new_plugins = {}
-	local plugin_paths = { "/usr/share/bunkerweb/core", "/etc/bunkerweb/plugins", "/etc/bunkerweb/pro/plugins" }
+	local plugin_paths = { "/usr/local/share/bunkerweb/common/core", "/usr/local/etc/bunkerweb/plugins", "/usr/local/etc/bunkerweb/pro/plugins" }
 	for i, plugin_path in ipairs(plugin_paths) do
 		local paths = popen("find -L " .. plugin_path .. " -maxdepth 1 -type d ! -path " .. plugin_path)
 		for path in paths:lines() do
@@ -50,14 +50,14 @@ init_by_lua_block {
 
 	-- Load variables from disk
 	logger:log(NOTICE, "loading variables ...")
-	local file = open("/etc/nginx/variables.env")
+	local file = open("/usr/local/etc/nginx/variables.env")
 	if not file then
-		logger:log(ERR, "can't open /etc/nginx/variables.env file, keeping previous LRU data")
+		logger:log(ERR, "can't open /usr/local/etc/nginx/variables.env file, keeping previous LRU data")
 		return false
 	end
 	file:close()
 	local all_variables = {}
-	for line in io.lines("/etc/nginx/variables.env") do
+	for line in io.lines("/usr/local/etc/nginx/variables.env") do
 		local variable, value = line:match("^([^=]+)=(.*)$")
 		if variable then
 			all_variables[variable] = value
