--- src/common/core/modsecurity/confs/server-http/modsecurity.conf.orig	2026-05-10 11:05:38 UTC
+++ src/common/core/modsecurity/confs/server-http/modsecurity.conf
@@ -1,10 +1,6 @@
 {% if USE_MODSECURITY == "yes" %}
-modsecurity on;
     {% if USE_MODSECURITY_GLOBAL_CRS == "yes" %}
-modsecurity_rules_file {{ NGINX_PREFIX }}server-http/modsecurity-rules-global-crs.conf.modsec;
     {% else %}
-modsecurity_rules_file {{ NGINX_PREFIX }}server-http/modsecurity-rules.conf.modsec;
     {% endif %}
 {% else %}
-modsecurity off;
 {% endif %}
