--- src/common/core/errors/confs/default-server-http/errors.conf.orig	2026-09-21 08:05:39 UTC
+++ src/common/core/errors/confs/default-server-http/errors.conf
@@ -8,9 +8,11 @@
 location {% if intercepted_error_code == "400" %}= /{% else %} @{% endif %}bwerror{{ intercepted_error_code }} {
     auth_basic off;
     internal;
+    {% if has_modsecurity %}
     modsecurity off;
+    {% endif %}
     default_type 'text/html';
-    root /usr/share/bunkerweb/core/errors/files;
+    root /usr/local/share/bunkerweb/common/core/errors/files;
     content_by_lua_block {
         local logger = require "bunkerweb.logger"
         local cerrors = require "errors.errors"
