--- src/common/confs/api.conf.orig	2026-05-10 11:17:17 UTC
+++ src/common/confs/api.conf
@@ -25,7 +25,6 @@ server {
 	ssl_ecdh_curve X25519:prime256v1:secp384r1;
 	ssl_certificate /var/cache/bunkerweb/jobs/api-server-cert.pem;
 	ssl_certificate_key /var/cache/bunkerweb/jobs/api-server-cert.key;
-	http2 on;
 	listen {{ API_LISTEN_IP }}:{{ API_HTTPS_PORT }} ssl reuseport;
 		{% if API_LISTEN_IP != "127.0.0.1" +%}
 	listen 127.0.0.1:{{ API_HTTPS_PORT }} ssl reuseport;
