--- src/common/core/grpc/confs/server-http/grpc.conf.orig	2026-05-10 11:05:38 UTC
+++ src/common/core/grpc/confs/server-http/grpc.conf
@@ -40,7 +40,6 @@ location {{ url }} {
 			{% set includes = all[k.replace("HOST", "INCLUDES")] if k.replace("HOST", "INCLUDES") in all else "" %}
 location {{ url }} {
 			{% if USE_MODSECURITY == "yes" %}
-	modsecurity off;
 			{% endif %}
 	set $grpc_backend{{ index }} "{{ host }}";
 	grpc_pass $grpc_backend{{ index }};
