--- src/common/core/modsecurity/confs/http/modsecurity.conf.orig	2026-05-10 11:05:38 UTC
+++ src/common/core/modsecurity/confs/http/modsecurity.conf
@@ -1,4 +1,2 @@
 {%- if USE_MODSECURITY == "yes" and USE_MODSECURITY_GLOBAL_CRS == "yes" -%}
-modsecurity on;
-modsecurity_rules_file {{ NGINX_PREFIX }}http/modsecurity-rules-global-crs.conf.modsec;
 {%- endif %}
