--- src/common/confs/server-stream/ssl-certificate-stream-lua.conf.orig	2026-05-10 09:52:37 UTC
+++ src/common/confs/server-stream/ssl-certificate-stream-lua.conf
@@ -17,7 +17,7 @@ ssl_ecdh_curve {{ resolve_ssl_ecdh_curve(SSL_ECDH_CURV
 {% endif %}
 ssl_ecdh_curve {{ resolve_ssl_ecdh_curve(SSL_ECDH_CURVE) }};
 {% if "TLSv1.2" in SSL_PROTOCOLS +%}
-ssl_dhparam /etc/nginx/dhparam;
+ssl_dhparam /usr/local/etc/nginx/dhparam;
 	{% if SSL_CIPHERS_CUSTOM|default('')|trim != "" %}
 ssl_ciphers {{ SSL_CIPHERS_CUSTOM }};
 	{% else %}
