--- src/common/core/misc/confs/default-server-http/page.conf.orig	2026-09-21 08:05:39 UTC
+++ src/common/core/misc/confs/default-server-http/page.conf
@@ -9,7 +9,7 @@
 	add_header Last-Modified "";
 	server_tokens off;
 	default_type 'text/html';
-	root /usr/share/bunkerweb/core/misc/files;
+	root /usr/local/share/bunkerweb/common/core/misc/files;
 	content_by_lua_block {
 			local utils = require "bunkerweb.utils"
 			local rand = utils.rand
