--- src/common/confs/server-http/server.conf.orig	2026-05-25 18:23:18 UTC
+++ src/common/confs/server-http/server.conf
@@ -33,9 +33,9 @@ server {
 	index index.php index.html index.htm;
 
 	# custom config
-	include /etc/bunkerweb/configs/server-http/*.conf;
+	include /usr/local/etc/bunkerweb/configs/server-http/*.conf;
 {% if MULTISITE == "yes" +%}
-	include /etc/bunkerweb/configs/server-http/{{ SERVER_NAME.split(" ")[0] }}/*.conf;
+	include /usr/local/etc/bunkerweb/configs/server-http/{{ SERVER_NAME.split(" ")[0] }}/*.conf;
 {% endif %}
 
 	# include config files
