--- src/common/core/securitytxt/confs/server-http/securitytxt.conf.orig	2026-09-21 08:05:39 UTC
+++ src/common/core/securitytxt/confs/server-http/securitytxt.conf
@@ -1,7 +1,7 @@
 {%- if USE_SECURITYTXT == "yes" and SECURITYTXT_CONTACT != "" -%}
 location = {{ SECURITYTXT_URI }} {
 	default_type 'text/plain; charset=utf-8';
-	root /usr/share/bunkerweb/core/securitytxt/files;
+	root /usr/local/share/bunkerweb/common/core/securitytxt/files;
 	content_by_lua_block {
 		local logger   = require "bunkerweb.logger":new("SECURITYTXT")
 		local helpers  = require "bunkerweb.helpers"
