--- src/common/confs/init-worker-lua.conf.orig	2026-05-29 08:21:28 UTC
+++ src/common/confs/init-worker-lua.conf
@@ -284,7 +284,7 @@ init_worker_by_lua_block {
 		logger:log(INFO, "init phase ended")
 
 		local res, err = remove("/var/tmp/bunkerweb_reloading")
-		if not res and err ~= "No such file or directory" then
+		if not res and err and not err:find("No such file or directory", 1, true) then
 			logger:log(WARN, "unable to remove /var/tmp/bunkerweb_reloading file: " .. err)
 		end
 
