--- src/common/core/errors/confs/default-server-http/errors.conf.orig	2026-05-25 18:23:18 UTC
+++ src/common/core/errors/confs/default-server-http/errors.conf
@@ -8,7 +8,6 @@ location {% if intercepted_error_code == "400" %}= /{%
 location {% if intercepted_error_code == "400" %}= /{% else %} @{% endif %}bwerror{{ intercepted_error_code }} {
     auth_basic off;
     internal;
-    modsecurity off;
     default_type 'text/html';
     root /usr/share/bunkerweb/core/errors/files;
     content_by_lua_block {
