--- src/common/core/grpc/confs/server-http/grpc.conf.orig	2026-09-21 08:05:39 UTC
+++ src/common/core/grpc/confs/server-http/grpc.conf
@@ -98,7 +98,6 @@
 location {% if url_modifier %}{{ url_modifier }} {% endif %}"{{ quoted_url }}" {
 			{% if USE_MODSECURITY == "yes" %}
 	# ModSecurity does not reliably support gRPC traffic patterns, it is always disabled on gRPC locations.
-	modsecurity off;
 			{% endif %}
 			{% if max_client_size != "" %}
 	client_max_body_size {{ max_client_size }};
