--- src/common/confs/server-stream/server-stream.conf.orig	2026-05-10 09:52:37 UTC
+++ src/common/confs/server-stream/server-stream.conf
@@ -32,9 +32,9 @@ server {
 {% endif %}
 
 	# custom config
-	include /etc/bunkerweb/configs/server-stream/*.conf;
+	include /usr/local/etc/bunkerweb/configs/server-stream/*.conf;
 {% if MULTISITE == "yes" +%}
-	include /etc/bunkerweb/configs/server-stream/{{ SERVER_NAME.split(" ")[0] }}/*.conf;
+	include /usr/local/etc/bunkerweb/configs/server-stream/{{ SERVER_NAME.split(" ")[0] }}/*.conf;
 {% endif %}
 
 	# include config files
