--- src/common/confs/default-server-http.conf.orig	2026-05-25 18:23:18 UTC
+++ src/common/confs/default-server-http.conf
@@ -45,7 +45,7 @@ server {
 	{% endif %}
 	ssl_ecdh_curve {{ resolve_ssl_ecdh_curve(SSL_ECDH_CURVE) }};
 	{% if "TLSv1.2" in SSL_PROTOCOLS +%}
-	ssl_dhparam /etc/nginx/dhparam;
+	ssl_dhparam /usr/local/etc/nginx/dhparam;
 		{% if SSL_CIPHERS_CUSTOM != "" %}
 	ssl_ciphers {{ SSL_CIPHERS_CUSTOM }};
 		{% else %}
@@ -61,7 +61,6 @@ server {
 	ssl_certificate /var/cache/bunkerweb/misc/default-server-cert.pem;
 	ssl_certificate_key /var/cache/bunkerweb/misc/default-server-cert.key;
 	{% if HTTP2 == "yes" %}
-	http2 on;
 	{% endif %}
 	{% set common_options = " ssl default_server" %}
 	{% if USE_PROXY_PROTOCOL == "yes" %}
@@ -75,14 +74,10 @@ server {
 	{% endfor %}
 
 	{% if "TLSv1.3" in SSL_PROTOCOLS and HTTP3 == "yes" and USE_PROXY_PROTOCOL == "no" %}
-	http3 on;
 		{% for k, port in all.items() if k.startswith("HTTPS_PORT") %}
-	listen 0.0.0.0:{{ port }} quic reuseport default_server;
 			{% if USE_IPV6 == "yes" %}
-	listen [::]:{{ port }} quic reuseport default_server;
 			{% endif %}
 		{% endfor %}
-	add_header Alt-Svc 'h3=":{{ HTTP3_ALT_SVC_PORT }}"; ma=86400';
 	{% endif %}
 
 	ssl_client_hello_by_lua_block {
@@ -233,10 +228,10 @@ server {
 {% endif %}
 
 	# include core and plugins default-server configurations
-	include /etc/nginx/default-server-http/*.conf;
+	include /usr/local/etc/nginx/default-server-http/*.conf;
 
 	# include custom default-server configurations
-	include /etc/bunkerweb/configs/default-server-http/*.conf;
+	include /usr/local/etc/bunkerweb/configs/default-server-http/*.conf;
 
 	log_by_lua_block {
 
