# $FreeBSD$

PORTNAME=	cpputest
PORTVERSION=	3.7.1
DISTVERSIONPREFIX=	v
CATEGORIES=	devel

MAINTAINER=	akos.somfai@gmail.com
COMMENT=	Unit testing and mocking framework for C/C++

LICENSE=	BSD3CLAUSE

USE_GITHUB=	yes

USES=		autoreconf libtool
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
