%%PG_PREFIX%%bin/pgaccess
%%PG_PREFIX%%bin/pgtclsh
%%PG_PREFIX%%bin/pgtksh
%%PG_INCLUDE%%/libpgtcl.h
%%PG_PREFIX%%lib/libpgtcl.a
%%PG_PREFIX%%lib/libpgtcl.so
%%PG_PREFIX%%lib/libpgtcl.so.2
%%PG_PREFIX%%lib/pltcl.so
lib/tcl%%WITH_TCL%%/Pgtcl1.3/pkgIndex.tcl
share/postgresql/pgaccess/images/icon_button.gif
share/postgresql/pgaccess/images/icon_checkbutton.gif
share/postgresql/pgaccess/images/icon_entry.gif
share/postgresql/pgaccess/images/icon_frame.gif
share/postgresql/pgaccess/images/icon_label.gif
share/postgresql/pgaccess/images/icon_listbox.gif
share/postgresql/pgaccess/images/icon_query.gif
share/postgresql/pgaccess/images/icon_radiobutton.gif
share/postgresql/pgaccess/images/icon_text.gif
share/postgresql/pgaccess/lib/database.tcl
share/postgresql/pgaccess/lib/forms.tcl
share/postgresql/pgaccess/lib/functions.tcl
share/postgresql/pgaccess/lib/help/abort.hlp
share/postgresql/pgaccess/lib/help/add_records.hlp
share/postgresql/pgaccess/lib/help/alter_table.hlp
share/postgresql/pgaccess/lib/help/alter_user.hlp
share/postgresql/pgaccess/lib/help/author.hlp
share/postgresql/pgaccess/lib/help/begin.hlp
share/postgresql/pgaccess/lib/help/close.hlp
share/postgresql/pgaccess/lib/help/cluster.hlp
share/postgresql/pgaccess/lib/help/commit.hlp
share/postgresql/pgaccess/lib/help/copy.hlp
share/postgresql/pgaccess/lib/help/copyrights.hlp
share/postgresql/pgaccess/lib/help/create_aggregate.hlp
share/postgresql/pgaccess/lib/help/create_database.hlp
share/postgresql/pgaccess/lib/help/create_function.hlp
share/postgresql/pgaccess/lib/help/create_index.hlp
share/postgresql/pgaccess/lib/help/create_language.hlp
share/postgresql/pgaccess/lib/help/create_operator.hlp
share/postgresql/pgaccess/lib/help/create_rule.hlp
share/postgresql/pgaccess/lib/help/create_sequence.hlp
share/postgresql/pgaccess/lib/help/create_table.hlp
share/postgresql/pgaccess/lib/help/create_table_as.hlp
share/postgresql/pgaccess/lib/help/create_trigger.hlp
share/postgresql/pgaccess/lib/help/create_type.hlp
share/postgresql/pgaccess/lib/help/create_user.hlp
share/postgresql/pgaccess/lib/help/create_view.hlp
share/postgresql/pgaccess/lib/help/data_types.hlp
share/postgresql/pgaccess/lib/help/datefunc.hlp
share/postgresql/pgaccess/lib/help/declare.hlp
share/postgresql/pgaccess/lib/help/delete.hlp
share/postgresql/pgaccess/lib/help/drop_aggregate.hlp
share/postgresql/pgaccess/lib/help/drop_database.hlp
share/postgresql/pgaccess/lib/help/drop_function.hlp
share/postgresql/pgaccess/lib/help/drop_index.hlp
share/postgresql/pgaccess/lib/help/drop_language.hlp
share/postgresql/pgaccess/lib/help/drop_operator.hlp
share/postgresql/pgaccess/lib/help/drop_rule.hlp
share/postgresql/pgaccess/lib/help/drop_sequence.hlp
share/postgresql/pgaccess/lib/help/drop_table.hlp
share/postgresql/pgaccess/lib/help/drop_trigger.hlp
share/postgresql/pgaccess/lib/help/drop_type.hlp
share/postgresql/pgaccess/lib/help/drop_user.hlp
share/postgresql/pgaccess/lib/help/drop_view.hlp
share/postgresql/pgaccess/lib/help/explain.hlp
share/postgresql/pgaccess/lib/help/fetch.hlp
share/postgresql/pgaccess/lib/help/form_design.hlp
share/postgresql/pgaccess/lib/help/forms.hlp
share/postgresql/pgaccess/lib/help/functions.hlp
share/postgresql/pgaccess/lib/help/geomfunc.hlp
share/postgresql/pgaccess/lib/help/grant.hlp
share/postgresql/pgaccess/lib/help/history.hlp
share/postgresql/pgaccess/lib/help/index.hlp
share/postgresql/pgaccess/lib/help/inheritance.hlp
share/postgresql/pgaccess/lib/help/insert.hlp
share/postgresql/pgaccess/lib/help/ipv4func.hlp
share/postgresql/pgaccess/lib/help/isolation.hlp
share/postgresql/pgaccess/lib/help/keywords.hlp
share/postgresql/pgaccess/lib/help/listen.hlp
share/postgresql/pgaccess/lib/help/load.hlp
share/postgresql/pgaccess/lib/help/lock.hlp
share/postgresql/pgaccess/lib/help/mathfunc.hlp
share/postgresql/pgaccess/lib/help/move.hlp
share/postgresql/pgaccess/lib/help/mvcc.hlp
share/postgresql/pgaccess/lib/help/new_query.hlp
share/postgresql/pgaccess/lib/help/new_table.hlp
share/postgresql/pgaccess/lib/help/notify.hlp
share/postgresql/pgaccess/lib/help/open_query.hlp
share/postgresql/pgaccess/lib/help/open_table.hlp
share/postgresql/pgaccess/lib/help/pgfunctions.hlp
share/postgresql/pgaccess/lib/help/postgresql.hlp
share/postgresql/pgaccess/lib/help/queries.hlp
share/postgresql/pgaccess/lib/help/reports.hlp
share/postgresql/pgaccess/lib/help/reset.hlp
share/postgresql/pgaccess/lib/help/revoke.hlp
share/postgresql/pgaccess/lib/help/rollback.hlp
share/postgresql/pgaccess/lib/help/schema.hlp
share/postgresql/pgaccess/lib/help/scripts.hlp
share/postgresql/pgaccess/lib/help/select.hlp
share/postgresql/pgaccess/lib/help/select_into.hlp
share/postgresql/pgaccess/lib/help/sequences.hlp
share/postgresql/pgaccess/lib/help/set.hlp
share/postgresql/pgaccess/lib/help/show.hlp
share/postgresql/pgaccess/lib/help/sql_guide.hlp
share/postgresql/pgaccess/lib/help/sqlfunc.hlp
share/postgresql/pgaccess/lib/help/stringfunc.hlp
share/postgresql/pgaccess/lib/help/tables.hlp
share/postgresql/pgaccess/lib/help/unlisten.hlp
share/postgresql/pgaccess/lib/help/update.hlp
share/postgresql/pgaccess/lib/help/users.hlp
share/postgresql/pgaccess/lib/help/vacuum.hlp
share/postgresql/pgaccess/lib/help/view_table_structure.hlp
share/postgresql/pgaccess/lib/help/views.hlp
share/postgresql/pgaccess/lib/help/visual_designer.hlp
share/postgresql/pgaccess/lib/help/y2k.hlp
share/postgresql/pgaccess/lib/help.tcl
share/postgresql/pgaccess/lib/languages/czech
share/postgresql/pgaccess/lib/languages/chinese_big5
share/postgresql/pgaccess/lib/languages/chinese_gb
share/postgresql/pgaccess/lib/languages/deutsch
share/postgresql/pgaccess/lib/languages/euskara
share/postgresql/pgaccess/lib/languages/francais
share/postgresql/pgaccess/lib/languages/italiano
share/postgresql/pgaccess/lib/languages/japanese
share/postgresql/pgaccess/lib/languages/magyar
share/postgresql/pgaccess/lib/languages/nederlands
share/postgresql/pgaccess/lib/languages/portugues
share/postgresql/pgaccess/lib/languages/romana
share/postgresql/pgaccess/lib/languages/russian.koi8r
share/postgresql/pgaccess/lib/languages/russian_win
share/postgresql/pgaccess/lib/languages/spanish
share/postgresql/pgaccess/lib/mainlib.tcl
share/postgresql/pgaccess/lib/preferences.tcl
share/postgresql/pgaccess/lib/queries.tcl
share/postgresql/pgaccess/lib/reports.tcl
share/postgresql/pgaccess/lib/schema.tcl
share/postgresql/pgaccess/lib/scripts.tcl
share/postgresql/pgaccess/lib/sequences.tcl
share/postgresql/pgaccess/lib/tables.tcl
share/postgresql/pgaccess/lib/users.tcl
share/postgresql/pgaccess/lib/views.tcl
share/postgresql/pgaccess/lib/visualqb.tcl
share/postgresql/pgaccess/main.tcl
@dirrm share/postgresql/pgaccess/images
@dirrm share/postgresql/pgaccess/lib/help
@dirrm share/postgresql/pgaccess/lib/languages
@dirrm share/postgresql/pgaccess/lib
@dirrm share/postgresql/pgaccess
@dirrm lib/tcl%%WITH_TCL%%/Pgtcl1.3
