--- gitlab-markup.gemspec.orig	2018-10-30 12:09:22 UTC
+++ gitlab-markup.gemspec
@@ -12,8 +12,8 @@ Gem::Specification.new do |s|
   s.date = "2018-06-08"
   s.description = "This gem is used by GitLab to render any non Markdown markup".freeze
   s.email = "chris@ozmm.org".freeze
-  s.executables = ["github-markup".freeze]
-  s.files = [".gitignore".freeze, ".gitlab-ci.yml".freeze, ".kick".freeze, ".travis.yml".freeze, "CONTRIBUTING.md".freeze, "Gemfile".freeze, "HISTORY.md".freeze, "LICENSE".freeze, "README.md".freeze, "Rakefile".freeze, "bin/github-markup".freeze, "gitlab-markup.gemspec".freeze, "lib/github-markup.rb".freeze, "lib/github/commands/rest2html".freeze, "lib/github/markup.rb".freeze, "lib/github/markup/command_implementation.rb".freeze, "lib/github/markup/gem_implementation.rb".freeze, "lib/github/markup/implementation.rb".freeze, "lib/github/markup/markdown.rb".freeze, "lib/github/markup/rdoc.rb".freeze, "lib/github/markups.rb".freeze, "script/bootstrap".freeze, "script/cibuild".freeze, "test/fixtures/fail.sh".freeze, "test/markup_test.rb".freeze, "test/markups/README.asciidoc".freeze, "test/markups/README.asciidoc.html".freeze, "test/markups/README.creole".freeze, "test/markups/README.creole.html".freeze, "test/markups/README.litcoffee".freeze, "test/markups/README.litcoffee.html".freeze, "test/markups/README.markdown".freeze, "test/markups/README.markdown.html".freeze, "test/markups/README.mediawiki".freeze, "test/markups/README.mediawiki.html".freeze, "test/markups/README.noformat".freeze, "test/markups/README.noformat.html".freeze, "test/markups/README.org".freeze, "test/markups/README.org.html".freeze, "test/markups/README.pod".freeze, "test/markups/README.pod.html".freeze, "test/markups/README.rdoc".freeze, "test/markups/README.rdoc.html".freeze, "test/markups/README.rmd".freeze, "test/markups/README.rmd.html".freeze, "test/markups/README.rst".freeze, "test/markups/README.rst.html".freeze, "test/markups/README.rst.txt".freeze, "test/markups/README.rst.txt.html".freeze, "test/markups/README.textile".freeze, "test/markups/README.textile.html".freeze, "test/markups/README.toc.rst".freeze, "test/markups/README.toc.rst.html".freeze, "test/markups/README.txt".freeze, "test/markups/README.txt.html".freeze]
+  s.executables = ["gitlab-markup".freeze]
+  s.files = [".gitignore".freeze, ".gitlab-ci.yml".freeze, ".kick".freeze, ".travis.yml".freeze, "CONTRIBUTING.md".freeze, "Gemfile".freeze, "HISTORY.md".freeze, "LICENSE".freeze, "README.md".freeze, "Rakefile".freeze, "bin/gitlab-markup".freeze, "gitlab-markup.gemspec".freeze, "lib/github-markup.rb".freeze, "lib/github/commands/rest2html".freeze, "lib/github/markup.rb".freeze, "lib/github/markup/command_implementation.rb".freeze, "lib/github/markup/gem_implementation.rb".freeze, "lib/github/markup/implementation.rb".freeze, "lib/github/markup/markdown.rb".freeze, "lib/github/markup/rdoc.rb".freeze, "lib/github/markups.rb".freeze, "script/bootstrap".freeze, "script/cibuild".freeze, "test/fixtures/fail.sh".freeze, "test/markup_test.rb".freeze, "test/markups/README.asciidoc".freeze, "test/markups/README.asciidoc.html".freeze, "test/markups/README.creole".freeze, "test/markups/README.creole.html".freeze, "test/markups/README.litcoffee".freeze, "test/markups/README.litcoffee.html".freeze, "test/markups/README.markdown".freeze, "test/markups/README.markdown.html".freeze, "test/markups/README.mediawiki".freeze, "test/markups/README.mediawiki.html".freeze, "test/markups/README.noformat".freeze, "test/markups/README.noformat.html".freeze, "test/markups/README.org".freeze, "test/markups/README.org.html".freeze, "test/markups/README.pod".freeze, "test/markups/README.pod.html".freeze, "test/markups/README.rdoc".freeze, "test/markups/README.rdoc.html".freeze, "test/markups/README.rmd".freeze, "test/markups/README.rmd.html".freeze, "test/markups/README.rst".freeze, "test/markups/README.rst.html".freeze, "test/markups/README.rst.txt".freeze, "test/markups/README.rst.txt.html".freeze, "test/markups/README.textile".freeze, "test/markups/README.textile.html".freeze, "test/markups/README.toc.rst".freeze, "test/markups/README.toc.rst.html".freeze, "test/markups/README.txt".freeze, "test/markups/README.txt.html".freeze]
   s.homepage = "https://gitlab.com/gitlab-org/gitlab-markup".freeze
   s.licenses = ["MIT".freeze]
   s.rubygems_version = "2.7.7".freeze
