# $Id: Makefile,v 1.21 1997/08/19 07:17:51 fenner Exp $
#
    SUBDIR += db
    SUBDIR += gdbm
    SUBDIR += gnats
    SUBDIR += msql
    SUBDIR += mysql
    SUBDIR += p5-DBD-Pg
    SUBDIR += p5-DBD-mysql
    SUBDIR += p5-DBI
    SUBDIR += p5-Msql
    SUBDIR += p5-Mysql
    SUBDIR += p5-Pg
    SUBDIR += postgresql
    SUBDIR += typhoon
    SUBDIR += xmbase-grok

.include <bsd.port.subdir.mk>
