# New ports collection makefile for:	p5-Sys-Hostname-Long
# Date created:				March 6th, 2004
# Whom:					Tim Bishop <tim@bishnet.net>
#
# $FreeBSD$
#

PORTNAME=	Sys-Hostname-Long
PORTVERSION=	1.4
CATEGORIES=	sysutils perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Sys
PKGNAMEPREFIX=	p5-

MAINTAINER=	tdb@FreeBSD.org
COMMENT=	Try every conceivable way to get full hostname

PERL_CONFIGURE=	yes

MAN3=		Sys::Hostname::Long.3

.include <bsd.port.mk>
