# New ports collection makefile for:	php4-crack
# Date created:			7 Jul 2004
# Whom:				Alex Dupre <ale@FreeBSD.org>
#
# $FreeBSD$
#

CATEGORIES=	security

MASTERDIR=	${.CURDIR}/../../lang/php4

PKGNAMESUFFIX=	-crack

.include "${MASTERDIR}/Makefile"
