--- pyproject.toml.orig	2026-04-01 18:51:28 UTC
+++ pyproject.toml
@@ -1,8 +1,8 @@ requires = [
 [build-system]
 requires = [
-    "setuptools >= 65",
+    "setuptools",
     "setuptools_scm[toml] >= 7",
-    "wheel >= 0.29.0",
+    "wheel",
 ]
 build-backend = "setuptools.build_meta"
 
