# New ports collection makefile for:	german/acroread8
# Date created:			27 December 2007
# Whom:				hrs
#
# $FreeBSD$
#

CATEGORIES=	german print linux

MASTERDIR=	${.CURDIR}/../../print/acroread8
DISTINFO_FILE=	${.CURDIR}/distinfo

ADOBE_LANG=	DEU

.include "${MASTERDIR}/Makefile"
