# New ports collection makefile for:	GNU make
# Version required:	3.71
# Date created:		11 September 1994
# Whom:			jkh
#
# $Id: Makefile,v 1.3 1994/09/14 14:11:39 jkh Exp $
#

DISTNAME=	make-3.71
GNU_CONFIGURE=	yes
MASTER_SITES=	ftp://prep.ai.mit.edu/pub/gnu/

.include <bsd.port.mk>
