PORTNAME=	Plack-Middleware-Headers
DISTVERSION=	0.11
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl extension to modify HTTP response headers
WWW=		https://metacpan.org/pod/Plack::Middleware::Headers

LICENSE=	ARTPERL10
LICENSE_FILE=	${WRKSRC}/LICENSE

BUILD_DEPENDS=	${RUN_DEPENDS}
RUN_DEPENDS=	\
	p5-Plack>0:www/p5-Plack

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
