# New ports collection makefile for:	xautolock
# Version required:	1pl13
# Date created:		20 Jul 1996
# Whom:			Eric Blood <eblood@cs.unr.edu>
#
# $Id: Makefile,v 1.4 1998/08/18 03:11:35 vanilla Exp $
#

DISTNAME=	xautolock-pl13
PKGNAME=	xautolock-1.13
CATEGORIES=	x11
MASTER_SITES=	${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR=	applications
EXTRACT_SUFX=	.tz

MAINTAINER=	eblood@cs.unr.edu

BROKEN=		fetch

USE_IMAKE=	yes
WRKSRC=		${WRKDIR}/xautolock-pl13

.include <bsd.port.mk>
