# New ports collection makefile for:    font-cronyx-cyrillic
# Date created:		28 Aug 2005
# Whom:			Pawel Worach
#
# $FreeBSD$
#

PORTNAME=	font-cronyx-cyrillic
PORTVERSION=	1.0.3
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org Cronyx Cyrillic font

XORG_CAT=	font

.include <bsd.port.mk>
