--- pyproject.toml.orig	2026-09-14 12:56:31 UTC
+++ pyproject.toml
@@ -1,5 +1,5 @@
 [build-system]
-requires = ["setuptools>=70.0"]
+requires = ["setuptools>=61"]
 build-backend = "setuptools.build_meta"
 
 [project.entry-points."mkdocs.plugins"]
