# New ports collection makefile for:	xlife
# Version required:	3.0
# Date created:		15 March 1995
# Whom:			asami
#
# $FreeBSD$
#

DISTNAME=	xlife
PKGNAME=	xlife-3.0
CATEGORIES=	games
MASTER_SITES=	ftp://ftp.x.org/R5contrib/ \
		ftp://ftp.cdrom.com/pub/X11/R5contrib/
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	ports@FreeBSD.org

USE_IMAKE=	yes
INSTALL_TARGET=	install install.patterns
MAN1=		xlife.1

.include <bsd.port.mk>
