# Created by: Wen Heping<wen@FreeBSD.org>
# $FreeBSD$

PORTNAME=	System-Command
PORTVERSION=	1.110
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Object for running system commands

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

TEST_DEPENDS=	p5-Test-Command>=0:${PORTSDIR}/devel/p5-Test-Command \
		p5-Test-Output>=0:${PORTSDIR}/devel/p5-Test-Output

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
