--- base/acme/conf/configsources.conf.orig	2025-08-05 19:20:05 UTC
+++ base/acme/conf/configsources.conf
@@ -12,4 +12,4 @@ engine.class=org.dogtagpki.acme.server.ACMEEngineConfi
 
 # The 'filename' parameter tells the ACMEEngineConfigFileSource
 # where to read the engine configuration from.
-engine.filename=/var/lib/pki/pki-tomcat/conf/acme/engine.conf
+engine.filename=/var/db/pki/pki-tomcat/conf/acme/engine.conf
