--- pyproject.toml.orig	2020-02-02 00:00:00 UTC
+++ pyproject.toml
@@ -99,7 +99,7 @@ pydantic-v2 = [
 ]
 
 [build-system]
-requires = ["hatchling==1.26.3", "hatch-fancy-pypi-readme>=22.4, <26"]
+requires = ["hatchling>=1.26.3", "hatch-fancy-pypi-readme>=22.4, <26"]
 build-backend = "hatchling.build"
 
 [tool.hatch.build]
