--- setup.py	2021-06-01 04:03:35.971744800 -0500
+++ setup.py	2021-06-14 23:12:32.397135000 -0500
@@ -9,64 +9,7 @@
  'gvm.protocols.gmpv208.system',
  'gvm.protocols.gmpv214',
  'gvm.protocols.gmpv214.entities',
- 'gvm.protocols.gmpv214.system',
- 'tests',
- 'tests.connections',
- 'tests.protocols',
- 'tests.protocols.gmp',
- 'tests.protocols.gmpv208',
- 'tests.protocols.gmpv208.entities',
- 'tests.protocols.gmpv208.entities.alerts',
- 'tests.protocols.gmpv208.entities.audits',
- 'tests.protocols.gmpv208.entities.credentials',
- 'tests.protocols.gmpv208.entities.filters',
- 'tests.protocols.gmpv208.entities.groups',
- 'tests.protocols.gmpv208.entities.hosts',
- 'tests.protocols.gmpv208.entities.notes',
- 'tests.protocols.gmpv208.entities.operating_systems',
- 'tests.protocols.gmpv208.entities.overrides',
- 'tests.protocols.gmpv208.entities.permissions',
- 'tests.protocols.gmpv208.entities.policies',
- 'tests.protocols.gmpv208.entities.port_lists',
- 'tests.protocols.gmpv208.entities.report_formats',
- 'tests.protocols.gmpv208.entities.reports',
- 'tests.protocols.gmpv208.entities.results',
- 'tests.protocols.gmpv208.entities.roles',
- 'tests.protocols.gmpv208.entities.scan_configs',
- 'tests.protocols.gmpv208.entities.scanners',
- 'tests.protocols.gmpv208.entities.schedules',
- 'tests.protocols.gmpv208.entities.secinfo',
- 'tests.protocols.gmpv208.entities.tags',
- 'tests.protocols.gmpv208.entities.targets',
- 'tests.protocols.gmpv208.entities.tasks',
- 'tests.protocols.gmpv208.entities.tickets',
- 'tests.protocols.gmpv208.entities.tls_certificates',
- 'tests.protocols.gmpv208.entities.users',
- 'tests.protocols.gmpv208.entities.vulnerabilities',
- 'tests.protocols.gmpv208.enums',
- 'tests.protocols.gmpv208.system',
- 'tests.protocols.gmpv208.system.aggregates',
- 'tests.protocols.gmpv208.system.authentication',
- 'tests.protocols.gmpv208.system.feed',
- 'tests.protocols.gmpv208.system.help',
- 'tests.protocols.gmpv208.system.system_reports',
- 'tests.protocols.gmpv208.system.trashcan',
- 'tests.protocols.gmpv208.system.user_settings',
- 'tests.protocols.gmpv208.system.versions',
- 'tests.protocols.gmpv214',
- 'tests.protocols.gmpv214.entities',
- 'tests.protocols.gmpv214.entities.notes',
- 'tests.protocols.gmpv214.entities.overrides',
- 'tests.protocols.gmpv214.entities.scanners',
- 'tests.protocols.gmpv214.entities.targets',
- 'tests.protocols.gmpv214.entities.users',
- 'tests.protocols.gmpv214.enums',
- 'tests.protocols.gmpv214.system',
- 'tests.protocols.gmpv214.system.versions',
- 'tests.protocols.osp',
- 'tests.transforms',
- 'tests.utils',
- 'tests.xml']
+ 'gvm.protocols.gmpv214.system']
 
 package_data = \
 {'': ['*']}
