--- src/libcec/cmake/SetBuildInfo.cmake.orig	2025-02-26 09:40:16 UTC
+++ src/libcec/cmake/SetBuildInfo.cmake
@@ -34,7 +34,7 @@ else()
     set(BUILD_USER "(reproducible)")
   else()
     if(HAVE_WHOAMI_BIN)
-      execute_process(COMMAND bash -c "whoami" OUTPUT_VARIABLE BUILD_USER)
+      execute_process(COMMAND sh -c "whoami" OUTPUT_VARIABLE BUILD_USER)
       string(STRIP ${BUILD_USER} BUILD_USER)
       set(LIB_INFO "${LIB_INFO} by ${BUILD_USER}")
     else()
@@ -48,9 +48,9 @@ else()
   else()
     find_program(HAVE_HOSTNAME_BIN hostname /bin /usr/bin /usr/local/bin)
     if(HAVE_HOSTNAME_BIN)
-      execute_process(COMMAND bash -c "hostname" ARGS -f OUTPUT_VARIABLE BUILD_HOST RESULT_VARIABLE RETURN_HOST)
+      execute_process(COMMAND sh -c "hostname" ARGS -f OUTPUT_VARIABLE BUILD_HOST RESULT_VARIABLE RETURN_HOST)
       if (RETURN_HOST)
-        execute_process(COMMAND bash -c "hostname" OUTPUT_VARIABLE BUILD_HOST)
+        execute_process(COMMAND sh -c "hostname" OUTPUT_VARIABLE BUILD_HOST)
       endif()
       string(STRIP ${BUILD_HOST} BUILD_HOST)
       set(LIB_INFO "${LIB_INFO}@${BUILD_HOST}")
@@ -60,9 +60,9 @@ else()
   # add host info on which this was built to compile info
   find_program(HAVE_UNAME_BIN uname /bin /usr/bin /usr/local/bin)
   if(HAVE_UNAME_BIN)
-    execute_process(COMMAND bash -c "uname" ARGS -s OUTPUT_VARIABLE BUILD_SYSNAME)
-    execute_process(COMMAND bash -c "uname" ARGS -r OUTPUT_VARIABLE BUILD_SYSVER)
-    execute_process(COMMAND bash -c "uname" ARGS -m OUTPUT_VARIABLE BUILD_SYSARCH)
+    execute_process(COMMAND sh -c "uname" ARGS -s OUTPUT_VARIABLE BUILD_SYSNAME)
+    execute_process(COMMAND sh -c "uname" ARGS -r OUTPUT_VARIABLE BUILD_SYSVER)
+    execute_process(COMMAND sh -c "uname" ARGS -m OUTPUT_VARIABLE BUILD_SYSARCH)
     string(STRIP ${BUILD_SYSNAME} BUILD_SYSNAME)
     string(STRIP ${BUILD_SYSVER} BUILD_SYSVER)
     string(STRIP ${BUILD_SYSARCH} BUILD_SYSARCH)
