/*
 * This file is generated by gdbus-codegen, do not modify it.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from. Note that it links to GLib, so must comply with the
 * LGPL linking clauses.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "gf-consolekit-manager-gen.h"

#include <string.h>
#ifdef G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  guint use_gvariant : 1;
  guint emits_changed_signal : 1;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        {
          /* Avoid -Wfloat-equal warnings by doing a direct bit compare */
          gdouble da = g_value_get_double (a);
          gdouble db = g_value_get_double (b);
          ret = memcmp (&da, &db, sizeof (gdouble)) == 0;
        }
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

/* ------------------------------------------------------------------------
 * Code for interface org.freedesktop.ConsoleKit.Manager
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:GfConsoleKitManagerGen
 * @title: GfConsoleKitManagerGen
 * @short_description: Generated C code for the org.freedesktop.ConsoleKit.Manager D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-org-freedesktop-ConsoleKit-Manager.top_of_page">org.freedesktop.ConsoleKit.Manager</link> D-Bus interface in C.
 */

/* ---- Introspection data for org.freedesktop.ConsoleKit.Manager ---- */

static const _ExtendedGDBusArgInfo _gf_console_kit_manager_gen_method_info_get_session_for_cookie_IN_ARG_session_id =
{
  {
    -1,
    (gchar *) "session_id",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const GDBusArgInfo * const _gf_console_kit_manager_gen_method_info_get_session_for_cookie_IN_ARG_pointers[] =
{
  &_gf_console_kit_manager_gen_method_info_get_session_for_cookie_IN_ARG_session_id.parent_struct,
  NULL
};

static const _ExtendedGDBusArgInfo _gf_console_kit_manager_gen_method_info_get_session_for_cookie_OUT_ARG_object_path =
{
  {
    -1,
    (gchar *) "object_path",
    (gchar *) "o",
    NULL
  },
  FALSE
};

static const GDBusArgInfo * const _gf_console_kit_manager_gen_method_info_get_session_for_cookie_OUT_ARG_pointers[] =
{
  &_gf_console_kit_manager_gen_method_info_get_session_for_cookie_OUT_ARG_object_path.parent_struct,
  NULL
};

static const _ExtendedGDBusMethodInfo _gf_console_kit_manager_gen_method_info_get_session_for_cookie =
{
  {
    -1,
    (gchar *) "GetSessionForCookie",
    (GDBusArgInfo **) &_gf_console_kit_manager_gen_method_info_get_session_for_cookie_IN_ARG_pointers,
    (GDBusArgInfo **) &_gf_console_kit_manager_gen_method_info_get_session_for_cookie_OUT_ARG_pointers,
    NULL
  },
  "handle-get-session-for-cookie",
  FALSE
};

static const _ExtendedGDBusArgInfo _gf_console_kit_manager_gen_method_info_inhibit_IN_ARG_what =
{
  {
    -1,
    (gchar *) "what",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _gf_console_kit_manager_gen_method_info_inhibit_IN_ARG_who =
{
  {
    -1,
    (gchar *) "who",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _gf_console_kit_manager_gen_method_info_inhibit_IN_ARG_why =
{
  {
    -1,
    (gchar *) "why",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _gf_console_kit_manager_gen_method_info_inhibit_IN_ARG_mode =
{
  {
    -1,
    (gchar *) "mode",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const GDBusArgInfo * const _gf_console_kit_manager_gen_method_info_inhibit_IN_ARG_pointers[] =
{
  &_gf_console_kit_manager_gen_method_info_inhibit_IN_ARG_what.parent_struct,
  &_gf_console_kit_manager_gen_method_info_inhibit_IN_ARG_who.parent_struct,
  &_gf_console_kit_manager_gen_method_info_inhibit_IN_ARG_why.parent_struct,
  &_gf_console_kit_manager_gen_method_info_inhibit_IN_ARG_mode.parent_struct,
  NULL
};

static const _ExtendedGDBusArgInfo _gf_console_kit_manager_gen_method_info_inhibit_OUT_ARG_pipe_fd =
{
  {
    -1,
    (gchar *) "pipe_fd",
    (gchar *) "h",
    NULL
  },
  FALSE
};

static const GDBusArgInfo * const _gf_console_kit_manager_gen_method_info_inhibit_OUT_ARG_pointers[] =
{
  &_gf_console_kit_manager_gen_method_info_inhibit_OUT_ARG_pipe_fd.parent_struct,
  NULL
};

static const _ExtendedGDBusMethodInfo _gf_console_kit_manager_gen_method_info_inhibit =
{
  {
    -1,
    (gchar *) "Inhibit",
    (GDBusArgInfo **) &_gf_console_kit_manager_gen_method_info_inhibit_IN_ARG_pointers,
    (GDBusArgInfo **) &_gf_console_kit_manager_gen_method_info_inhibit_OUT_ARG_pointers,
    NULL
  },
  "handle-inhibit",
  TRUE
};

static const GDBusMethodInfo * const _gf_console_kit_manager_gen_method_info_pointers[] =
{
  &_gf_console_kit_manager_gen_method_info_get_session_for_cookie.parent_struct,
  &_gf_console_kit_manager_gen_method_info_inhibit.parent_struct,
  NULL
};

static const _ExtendedGDBusArgInfo _gf_console_kit_manager_gen_signal_info_prepare_for_sleep_ARG_start =
{
  {
    -1,
    (gchar *) "start",
    (gchar *) "b",
    NULL
  },
  FALSE
};

static const GDBusArgInfo * const _gf_console_kit_manager_gen_signal_info_prepare_for_sleep_ARG_pointers[] =
{
  &_gf_console_kit_manager_gen_signal_info_prepare_for_sleep_ARG_start.parent_struct,
  NULL
};

static const _ExtendedGDBusSignalInfo _gf_console_kit_manager_gen_signal_info_prepare_for_sleep =
{
  {
    -1,
    (gchar *) "PrepareForSleep",
    (GDBusArgInfo **) &_gf_console_kit_manager_gen_signal_info_prepare_for_sleep_ARG_pointers,
    NULL
  },
  "prepare-for-sleep"
};

static const GDBusSignalInfo * const _gf_console_kit_manager_gen_signal_info_pointers[] =
{
  &_gf_console_kit_manager_gen_signal_info_prepare_for_sleep.parent_struct,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _gf_console_kit_manager_gen_interface_info =
{
  {
    -1,
    (gchar *) "org.freedesktop.ConsoleKit.Manager",
    (GDBusMethodInfo **) &_gf_console_kit_manager_gen_method_info_pointers,
    (GDBusSignalInfo **) &_gf_console_kit_manager_gen_signal_info_pointers,
    NULL,
    NULL
  },
  "console-kit-manager-gen",
};


/**
 * gf_console_kit_manager_gen_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-org-freedesktop-ConsoleKit-Manager.top_of_page">org.freedesktop.ConsoleKit.Manager</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
gf_console_kit_manager_gen_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_gf_console_kit_manager_gen_interface_info.parent_struct;
}

/**
 * gf_console_kit_manager_gen_override_properties:
 * @klass: The class structure for a #GObject derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #GfConsoleKitManagerGen interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
gf_console_kit_manager_gen_override_properties (GObjectClass *klass G_GNUC_UNUSED, guint property_id_begin)
{
  return property_id_begin - 1;
}



/**
 * GfConsoleKitManagerGen:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-org-freedesktop-ConsoleKit-Manager.top_of_page">org.freedesktop.ConsoleKit.Manager</link>.
 */

/**
 * GfConsoleKitManagerGenIface:
 * @parent_iface: The parent interface.
 * @handle_get_session_for_cookie: Handler for the #GfConsoleKitManagerGen::handle-get-session-for-cookie signal.
 * @handle_inhibit: Handler for the #GfConsoleKitManagerGen::handle-inhibit signal.
 * @prepare_for_sleep: Handler for the #GfConsoleKitManagerGen::prepare-for-sleep signal.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-org-freedesktop-ConsoleKit-Manager.top_of_page">org.freedesktop.ConsoleKit.Manager</link>.
 */

typedef GfConsoleKitManagerGenIface GfConsoleKitManagerGenInterface;
G_DEFINE_INTERFACE (GfConsoleKitManagerGen, gf_console_kit_manager_gen, G_TYPE_OBJECT)

static void
gf_console_kit_manager_gen_default_init (GfConsoleKitManagerGenIface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * GfConsoleKitManagerGen::handle-get-session-for-cookie:
   * @object: A #GfConsoleKitManagerGen.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_session_id: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-freedesktop-ConsoleKit-Manager.GetSessionForCookie">GetSessionForCookie()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call gf_console_kit_manager_gen_complete_get_session_for_cookie() or e.g. g_dbus_method_invocation_return_error() on it) and no other signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %G_DBUS_METHOD_INVOCATION_HANDLED or %TRUE if the invocation was handled, %G_DBUS_METHOD_INVOCATION_UNHANDLED or %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-get-session-for-cookie",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (GfConsoleKitManagerGenIface, handle_get_session_for_cookie),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING);

  /**
   * GfConsoleKitManagerGen::handle-inhibit:
   * @object: A #GfConsoleKitManagerGen.
   * @invocation: A #GDBusMethodInvocation.
   * @fd_list: (nullable): A #GUnixFDList or %NULL.
   * @arg_what: Argument passed by remote caller.
   * @arg_who: Argument passed by remote caller.
   * @arg_why: Argument passed by remote caller.
   * @arg_mode: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-freedesktop-ConsoleKit-Manager.Inhibit">Inhibit()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call gf_console_kit_manager_gen_complete_inhibit() or e.g. g_dbus_method_invocation_return_error() on it) and no other signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %G_DBUS_METHOD_INVOCATION_HANDLED or %TRUE if the invocation was handled, %G_DBUS_METHOD_INVOCATION_UNHANDLED or %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-inhibit",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (GfConsoleKitManagerGenIface, handle_inhibit),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    6,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_UNIX_FD_LIST, G_TYPE_STRING, G_TYPE_STRING, G_TYPE_STRING, G_TYPE_STRING);

  /* GObject signals for received D-Bus signals: */
  /**
   * GfConsoleKitManagerGen::prepare-for-sleep:
   * @object: A #GfConsoleKitManagerGen.
   * @arg_start: Argument.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-org-freedesktop-ConsoleKit-Manager.PrepareForSleep">"PrepareForSleep"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  g_signal_new ("prepare-for-sleep",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (GfConsoleKitManagerGenIface, prepare_for_sleep),
    NULL,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_NONE,
    1, G_TYPE_BOOLEAN);

}

/**
 * gf_console_kit_manager_gen_emit_prepare_for_sleep:
 * @object: A #GfConsoleKitManagerGen.
 * @arg_start: Argument to pass with the signal.
 *
 * Emits the <link linkend="gdbus-signal-org-freedesktop-ConsoleKit-Manager.PrepareForSleep">"PrepareForSleep"</link> D-Bus signal.
 */
void
gf_console_kit_manager_gen_emit_prepare_for_sleep (
    GfConsoleKitManagerGen *object,
    gboolean arg_start)
{
  g_signal_emit_by_name (object, "prepare-for-sleep", arg_start);
}

/**
 * gf_console_kit_manager_gen_call_get_session_for_cookie:
 * @proxy: A #GfConsoleKitManagerGenProxy.
 * @arg_session_id: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-freedesktop-ConsoleKit-Manager.GetSessionForCookie">GetSessionForCookie()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
 * You can then call gf_console_kit_manager_gen_call_get_session_for_cookie_finish() to get the result of the operation.
 *
 * See gf_console_kit_manager_gen_call_get_session_for_cookie_sync() for the synchronous, blocking version of this method.
 */
void
gf_console_kit_manager_gen_call_get_session_for_cookie (
    GfConsoleKitManagerGen *proxy,
    const gchar *arg_session_id,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "GetSessionForCookie",
    g_variant_new ("(s)",
                   arg_session_id),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * gf_console_kit_manager_gen_call_get_session_for_cookie_finish:
 * @proxy: A #GfConsoleKitManagerGenProxy.
 * @out_object_path: (out) (optional): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to gf_console_kit_manager_gen_call_get_session_for_cookie().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with gf_console_kit_manager_gen_call_get_session_for_cookie().
 *
 * Returns: (skip): %TRUE if the call succeeded, %FALSE if @error is set.
 */
gboolean
gf_console_kit_manager_gen_call_get_session_for_cookie_finish (
    GfConsoleKitManagerGen *proxy,
    gchar **out_object_path,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(o)",
                 out_object_path);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * gf_console_kit_manager_gen_call_get_session_for_cookie_sync:
 * @proxy: A #GfConsoleKitManagerGenProxy.
 * @arg_session_id: Argument to pass with the method invocation.
 * @out_object_path: (out) (optional): Return location for return parameter or %NULL to ignore.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-freedesktop-ConsoleKit-Manager.GetSessionForCookie">GetSessionForCookie()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See gf_console_kit_manager_gen_call_get_session_for_cookie() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeeded, %FALSE if @error is set.
 */
gboolean
gf_console_kit_manager_gen_call_get_session_for_cookie_sync (
    GfConsoleKitManagerGen *proxy,
    const gchar *arg_session_id,
    gchar **out_object_path,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "GetSessionForCookie",
    g_variant_new ("(s)",
                   arg_session_id),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(o)",
                 out_object_path);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * gf_console_kit_manager_gen_call_inhibit:
 * @proxy: A #GfConsoleKitManagerGenProxy.
 * @arg_what: Argument to pass with the method invocation.
 * @arg_who: Argument to pass with the method invocation.
 * @arg_why: Argument to pass with the method invocation.
 * @arg_mode: Argument to pass with the method invocation.
 * @fd_list: (nullable): A #GUnixFDList or %NULL.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-freedesktop-ConsoleKit-Manager.Inhibit">Inhibit()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
 * You can then call gf_console_kit_manager_gen_call_inhibit_finish() to get the result of the operation.
 *
 * See gf_console_kit_manager_gen_call_inhibit_sync() for the synchronous, blocking version of this method.
 */
void
gf_console_kit_manager_gen_call_inhibit (
    GfConsoleKitManagerGen *proxy,
    const gchar *arg_what,
    const gchar *arg_who,
    const gchar *arg_why,
    const gchar *arg_mode,
    GUnixFDList *fd_list,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call_with_unix_fd_list (G_DBUS_PROXY (proxy),
    "Inhibit",
    g_variant_new ("(ssss)",
                   arg_what,
                   arg_who,
                   arg_why,
                   arg_mode),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    fd_list,
    cancellable,
    callback,
    user_data);
}

/**
 * gf_console_kit_manager_gen_call_inhibit_finish:
 * @proxy: A #GfConsoleKitManagerGenProxy.
 * @out_pipe_fd: (out) (optional): Return location for return parameter or %NULL to ignore.
 * @out_fd_list: (out) (optional): Return location for a #GUnixFDList or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to gf_console_kit_manager_gen_call_inhibit().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with gf_console_kit_manager_gen_call_inhibit().
 *
 * Returns: (skip): %TRUE if the call succeeded, %FALSE if @error is set.
 */
gboolean
gf_console_kit_manager_gen_call_inhibit_finish (
    GfConsoleKitManagerGen *proxy,
    GVariant **out_pipe_fd,
    GUnixFDList **out_fd_list,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_with_unix_fd_list_finish (G_DBUS_PROXY (proxy), out_fd_list, res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(@h)",
                 out_pipe_fd);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * gf_console_kit_manager_gen_call_inhibit_sync:
 * @proxy: A #GfConsoleKitManagerGenProxy.
 * @arg_what: Argument to pass with the method invocation.
 * @arg_who: Argument to pass with the method invocation.
 * @arg_why: Argument to pass with the method invocation.
 * @arg_mode: Argument to pass with the method invocation.
 * @fd_list: (nullable): A #GUnixFDList or %NULL.
 * @out_pipe_fd: (out) (optional): Return location for return parameter or %NULL to ignore.
 * @out_fd_list: (out): Return location for a #GUnixFDList or %NULL.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-freedesktop-ConsoleKit-Manager.Inhibit">Inhibit()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See gf_console_kit_manager_gen_call_inhibit() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeeded, %FALSE if @error is set.
 */
gboolean
gf_console_kit_manager_gen_call_inhibit_sync (
    GfConsoleKitManagerGen *proxy,
    const gchar *arg_what,
    const gchar *arg_who,
    const gchar *arg_why,
    const gchar *arg_mode,
    GUnixFDList  *fd_list,
    GVariant **out_pipe_fd,
    GUnixFDList **out_fd_list,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_with_unix_fd_list_sync (G_DBUS_PROXY (proxy),
    "Inhibit",
    g_variant_new ("(ssss)",
                   arg_what,
                   arg_who,
                   arg_why,
                   arg_mode),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    fd_list,
    out_fd_list,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(@h)",
                 out_pipe_fd);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * gf_console_kit_manager_gen_complete_get_session_for_cookie:
 * @object: A #GfConsoleKitManagerGen.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @object_path: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-freedesktop-ConsoleKit-Manager.GetSessionForCookie">GetSessionForCookie()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
gf_console_kit_manager_gen_complete_get_session_for_cookie (
    GfConsoleKitManagerGen *object G_GNUC_UNUSED,
    GDBusMethodInvocation *invocation,
    const gchar *object_path)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(o)",
                   object_path));
}

/**
 * gf_console_kit_manager_gen_complete_inhibit:
 * @object: A #GfConsoleKitManagerGen.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @fd_list: (nullable): A #GUnixFDList or %NULL.
 * @pipe_fd: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-freedesktop-ConsoleKit-Manager.Inhibit">Inhibit()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
gf_console_kit_manager_gen_complete_inhibit (
    GfConsoleKitManagerGen *object G_GNUC_UNUSED,
    GDBusMethodInvocation *invocation,
    GUnixFDList *fd_list,
    GVariant *pipe_fd)
{
  g_dbus_method_invocation_return_value_with_unix_fd_list (invocation,
    g_variant_new ("(@h)",
                   pipe_fd),
    fd_list);
}

/* ------------------------------------------------------------------------ */

/**
 * GfConsoleKitManagerGenProxy:
 *
 * The #GfConsoleKitManagerGenProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * GfConsoleKitManagerGenProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #GfConsoleKitManagerGenProxy.
 */

struct _GfConsoleKitManagerGenProxyPrivate
{
  GData *qdata;
};

static void gf_console_kit_manager_gen_proxy_iface_init (GfConsoleKitManagerGenIface *iface);

#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (GfConsoleKitManagerGenProxy, gf_console_kit_manager_gen_proxy, G_TYPE_DBUS_PROXY,
                         G_ADD_PRIVATE (GfConsoleKitManagerGenProxy)
                         G_IMPLEMENT_INTERFACE (GF_TYPE_CONSOLE_KIT_MANAGER_GEN, gf_console_kit_manager_gen_proxy_iface_init))

#else
G_DEFINE_TYPE_WITH_CODE (GfConsoleKitManagerGenProxy, gf_console_kit_manager_gen_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (GF_TYPE_CONSOLE_KIT_MANAGER_GEN, gf_console_kit_manager_gen_proxy_iface_init))

#endif
static void
gf_console_kit_manager_gen_proxy_finalize (GObject *object)
{
  GfConsoleKitManagerGenProxy *proxy = GF_CONSOLE_KIT_MANAGER_GEN_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (gf_console_kit_manager_gen_proxy_parent_class)->finalize (object);
}

static void
gf_console_kit_manager_gen_proxy_get_property (GObject      *object G_GNUC_UNUSED,
  guint         prop_id G_GNUC_UNUSED,
  GValue       *value G_GNUC_UNUSED,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
}

static void
gf_console_kit_manager_gen_proxy_set_property (GObject      *object G_GNUC_UNUSED,
  guint         prop_id G_GNUC_UNUSED,
  const GValue *value G_GNUC_UNUSED,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
}

static void
gf_console_kit_manager_gen_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name G_GNUC_UNUSED,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  gsize num_params;
  gsize n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_gf_console_kit_manager_gen_interface_info.parent_struct, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], GF_TYPE_CONSOLE_KIT_MANAGER_GEN);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, GF_TYPE_CONSOLE_KIT_MANAGER_GEN);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
gf_console_kit_manager_gen_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  GfConsoleKitManagerGenProxy *proxy = GF_CONSOLE_KIT_MANAGER_GEN_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_gf_console_kit_manager_gen_interface_info.parent_struct, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_gf_console_kit_manager_gen_interface_info.parent_struct, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static void
gf_console_kit_manager_gen_proxy_init (GfConsoleKitManagerGenProxy *proxy)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  proxy->priv = gf_console_kit_manager_gen_proxy_get_instance_private (proxy);
#else
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, GF_TYPE_CONSOLE_KIT_MANAGER_GEN_PROXY, GfConsoleKitManagerGenProxyPrivate);
#endif

  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), gf_console_kit_manager_gen_interface_info ());
}

static void
gf_console_kit_manager_gen_proxy_class_init (GfConsoleKitManagerGenProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = gf_console_kit_manager_gen_proxy_finalize;
  gobject_class->get_property = gf_console_kit_manager_gen_proxy_get_property;
  gobject_class->set_property = gf_console_kit_manager_gen_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = gf_console_kit_manager_gen_proxy_g_signal;
  proxy_class->g_properties_changed = gf_console_kit_manager_gen_proxy_g_properties_changed;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (GfConsoleKitManagerGenProxyPrivate));
#endif
}

static void
gf_console_kit_manager_gen_proxy_iface_init (GfConsoleKitManagerGenIface *iface G_GNUC_UNUSED)
{
}

/**
 * gf_console_kit_manager_gen_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (nullable): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-freedesktop-ConsoleKit-Manager.top_of_page">org.freedesktop.ConsoleKit.Manager</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
 * You can then call gf_console_kit_manager_gen_proxy_new_finish() to get the result of the operation.
 *
 * See gf_console_kit_manager_gen_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
gf_console_kit_manager_gen_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (GF_TYPE_CONSOLE_KIT_MANAGER_GEN_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.freedesktop.ConsoleKit.Manager", NULL);
}

/**
 * gf_console_kit_manager_gen_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to gf_console_kit_manager_gen_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with gf_console_kit_manager_gen_proxy_new().
 *
 * Returns: (transfer full) (type GfConsoleKitManagerGenProxy): The constructed proxy object or %NULL if @error is set.
 */
GfConsoleKitManagerGen *
gf_console_kit_manager_gen_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return GF_CONSOLE_KIT_MANAGER_GEN (ret);
  else
    return NULL;
}

/**
 * gf_console_kit_manager_gen_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (nullable): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-freedesktop-ConsoleKit-Manager.top_of_page">org.freedesktop.ConsoleKit.Manager</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See gf_console_kit_manager_gen_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type GfConsoleKitManagerGenProxy): The constructed proxy object or %NULL if @error is set.
 */
GfConsoleKitManagerGen *
gf_console_kit_manager_gen_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (GF_TYPE_CONSOLE_KIT_MANAGER_GEN_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.freedesktop.ConsoleKit.Manager", NULL);
  if (ret != NULL)
    return GF_CONSOLE_KIT_MANAGER_GEN (ret);
  else
    return NULL;
}


/**
 * gf_console_kit_manager_gen_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like gf_console_kit_manager_gen_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
 * You can then call gf_console_kit_manager_gen_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See gf_console_kit_manager_gen_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
gf_console_kit_manager_gen_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (GF_TYPE_CONSOLE_KIT_MANAGER_GEN_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.freedesktop.ConsoleKit.Manager", NULL);
}

/**
 * gf_console_kit_manager_gen_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to gf_console_kit_manager_gen_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with gf_console_kit_manager_gen_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type GfConsoleKitManagerGenProxy): The constructed proxy object or %NULL if @error is set.
 */
GfConsoleKitManagerGen *
gf_console_kit_manager_gen_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return GF_CONSOLE_KIT_MANAGER_GEN (ret);
  else
    return NULL;
}

/**
 * gf_console_kit_manager_gen_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like gf_console_kit_manager_gen_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See gf_console_kit_manager_gen_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type GfConsoleKitManagerGenProxy): The constructed proxy object or %NULL if @error is set.
 */
GfConsoleKitManagerGen *
gf_console_kit_manager_gen_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (GF_TYPE_CONSOLE_KIT_MANAGER_GEN_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.freedesktop.ConsoleKit.Manager", NULL);
  if (ret != NULL)
    return GF_CONSOLE_KIT_MANAGER_GEN (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * GfConsoleKitManagerGenSkeleton:
 *
 * The #GfConsoleKitManagerGenSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * GfConsoleKitManagerGenSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #GfConsoleKitManagerGenSkeleton.
 */

struct _GfConsoleKitManagerGenSkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_gf_console_kit_manager_gen_skeleton_handle_method_call (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  GfConsoleKitManagerGenSkeleton *skeleton = GF_CONSOLE_KIT_MANAGER_GEN_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  gsize num_params;
  guint num_extra;
  gsize n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], GF_TYPE_CONSOLE_KIT_MANAGER_GEN);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, GF_TYPE_CONSOLE_KIT_MANAGER_GEN);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_gf_console_kit_manager_gen_skeleton_handle_get_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  GfConsoleKitManagerGenSkeleton *skeleton = GF_CONSOLE_KIT_MANAGER_GEN_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_gf_console_kit_manager_gen_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_gf_console_kit_manager_gen_skeleton_handle_set_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  GfConsoleKitManagerGenSkeleton *skeleton = GF_CONSOLE_KIT_MANAGER_GEN_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_gf_console_kit_manager_gen_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _gf_console_kit_manager_gen_skeleton_vtable =
{
  _gf_console_kit_manager_gen_skeleton_handle_method_call,
  _gf_console_kit_manager_gen_skeleton_handle_get_property,
  _gf_console_kit_manager_gen_skeleton_handle_set_property,
  {NULL}
};

static GDBusInterfaceInfo *
gf_console_kit_manager_gen_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return gf_console_kit_manager_gen_interface_info ();
}

static GDBusInterfaceVTable *
gf_console_kit_manager_gen_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return (GDBusInterfaceVTable *) &_gf_console_kit_manager_gen_skeleton_vtable;
}

static GVariant *
gf_console_kit_manager_gen_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  GfConsoleKitManagerGenSkeleton *skeleton = GF_CONSOLE_KIT_MANAGER_GEN_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_gf_console_kit_manager_gen_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _gf_console_kit_manager_gen_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _gf_console_kit_manager_gen_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _gf_console_kit_manager_gen_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.freedesktop.ConsoleKit.Manager", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static void
gf_console_kit_manager_gen_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton G_GNUC_UNUSED)
{
}

static void
_gf_console_kit_manager_gen_on_signal_prepare_for_sleep (
    GfConsoleKitManagerGen *object,
    gboolean arg_start)
{
  GfConsoleKitManagerGenSkeleton *skeleton = GF_CONSOLE_KIT_MANAGER_GEN_SKELETON (object);

  GList      *connections, *l;
  GVariant   *signal_variant;
  connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));

  signal_variant = g_variant_ref_sink (g_variant_new ("(b)",
                   arg_start));
  for (l = connections; l != NULL; l = l->next)
    {
      GDBusConnection *connection = l->data;
      g_dbus_connection_emit_signal (connection,
        NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.freedesktop.ConsoleKit.Manager", "PrepareForSleep",
        signal_variant, NULL);
    }
  g_variant_unref (signal_variant);
  g_list_free_full (connections, g_object_unref);
}

static void gf_console_kit_manager_gen_skeleton_iface_init (GfConsoleKitManagerGenIface *iface);
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (GfConsoleKitManagerGenSkeleton, gf_console_kit_manager_gen_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_ADD_PRIVATE (GfConsoleKitManagerGenSkeleton)
                         G_IMPLEMENT_INTERFACE (GF_TYPE_CONSOLE_KIT_MANAGER_GEN, gf_console_kit_manager_gen_skeleton_iface_init))

#else
G_DEFINE_TYPE_WITH_CODE (GfConsoleKitManagerGenSkeleton, gf_console_kit_manager_gen_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (GF_TYPE_CONSOLE_KIT_MANAGER_GEN, gf_console_kit_manager_gen_skeleton_iface_init))

#endif
static void
gf_console_kit_manager_gen_skeleton_finalize (GObject *object)
{
  GfConsoleKitManagerGenSkeleton *skeleton = GF_CONSOLE_KIT_MANAGER_GEN_SKELETON (object);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (gf_console_kit_manager_gen_skeleton_parent_class)->finalize (object);
}

static void
gf_console_kit_manager_gen_skeleton_init (GfConsoleKitManagerGenSkeleton *skeleton)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  skeleton->priv = gf_console_kit_manager_gen_skeleton_get_instance_private (skeleton);
#else
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, GF_TYPE_CONSOLE_KIT_MANAGER_GEN_SKELETON, GfConsoleKitManagerGenSkeletonPrivate);
#endif

  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
}

static void
gf_console_kit_manager_gen_skeleton_class_init (GfConsoleKitManagerGenSkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = gf_console_kit_manager_gen_skeleton_finalize;

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = gf_console_kit_manager_gen_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = gf_console_kit_manager_gen_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = gf_console_kit_manager_gen_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = gf_console_kit_manager_gen_skeleton_dbus_interface_get_vtable;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (GfConsoleKitManagerGenSkeletonPrivate));
#endif
}

static void
gf_console_kit_manager_gen_skeleton_iface_init (GfConsoleKitManagerGenIface *iface)
{
  iface->prepare_for_sleep = _gf_console_kit_manager_gen_on_signal_prepare_for_sleep;
}

/**
 * gf_console_kit_manager_gen_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-org-freedesktop-ConsoleKit-Manager.top_of_page">org.freedesktop.ConsoleKit.Manager</link>.
 *
 * Returns: (transfer full) (type GfConsoleKitManagerGenSkeleton): The skeleton object.
 */
GfConsoleKitManagerGen *
gf_console_kit_manager_gen_skeleton_new (void)
{
  return GF_CONSOLE_KIT_MANAGER_GEN (g_object_new (GF_TYPE_CONSOLE_KIT_MANAGER_GEN_SKELETON, NULL));
}

