--- src/SWIG_files/wrapper/DE.pyi.orig	2026-08-09 14:32:48 UTC
+++ src/SWIG_files/wrapper/DE.pyi
@@ -112,9 +112,9 @@ class DE_Wrapper(Standard_Transient):
     @overload
     def Read(self, thePath: str, theShape: TopoDS_Shape, theProgress: Optional[Message_ProgressRange] = Message_ProgressRange()) -> bool: ...
     @overload
-    def Save(self, theResourcePath: str, theIsRecursive: Optional[bool] = true, theFormats: Optional[TColStd_ListOfAsciiString] = NCollection_List<TCollection_AsciiString>(), theVendors: Optional[TColStd_ListOfAsciiString] = NCollection_List<TCollection_AsciiString>()) -> bool: ...
+    def Save(self, theResourcePath: str, theIsRecursive: Optional[bool] = true, theFormats: Optional[TColStd_ListOfAsciiString] = TColStd_ListOfAsciiString(), theVendors: Optional[TColStd_ListOfAsciiString] = TColStd_ListOfAsciiString()) -> bool: ...
     @overload
-    def Save(self, theIsRecursive: Optional[bool] = true, theFormats: Optional[TColStd_ListOfAsciiString] = NCollection_List<TCollection_AsciiString>(), theVendors: Optional[TColStd_ListOfAsciiString] = NCollection_List<TCollection_AsciiString>()) -> str: ...
+    def Save(self, theIsRecursive: Optional[bool] = true, theFormats: Optional[TColStd_ListOfAsciiString] = TColStd_ListOfAsciiString(), theVendors: Optional[TColStd_ListOfAsciiString] = TColStd_ListOfAsciiString()) -> str: ...
     @staticmethod
     def SetGlobalWrapper(theWrapper: DE_Wrapper) -> None: ...
     def SetKeepUpdates(self, theToKeepUpdates: bool) -> None: ...
