--- src/SWIG_files/wrapper/StepGeom.pyi.orig	2026-08-09 14:32:48 UTC
+++ src/SWIG_files/wrapper/StepGeom.pyi
@@ -1,5 +1,5 @@ from enum import IntEnum
 from enum import IntEnum
-from typing import overload, NewType, Optional, Tuple
+from typing import Any, overload, NewType, Optional, Tuple
 
 from OCC.Core.Standard import *
 from OCC.Core.NCollection import *
@@ -1045,56 +1045,56 @@ class StepGeom_OuterBoundaryCurve(StepGeom_BoundaryCur
 
 # harray1 classes
 
-class StepGeom_HArray1OfBoundaryCurve(NCollection_Array1<opencascade::handle<StepGeom_BoundaryCurve>>, Standard_Transient):
+class StepGeom_HArray1OfBoundaryCurve(StepGeom_Array1OfBoundaryCurve, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<opencascade::handle<StepGeom_BoundaryCurve>>: ...
+    def Array1(self) -> StepGeom_Array1OfBoundaryCurve: ...
 
 
-class StepGeom_HArray1OfCartesianPoint(NCollection_Array1<opencascade::handle<StepGeom_CartesianPoint>>, Standard_Transient):
+class StepGeom_HArray1OfCartesianPoint(StepGeom_Array1OfCartesianPoint, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<opencascade::handle<StepGeom_CartesianPoint>>: ...
+    def Array1(self) -> StepGeom_Array1OfCartesianPoint: ...
 
 
-class StepGeom_HArray1OfCompositeCurveSegment(NCollection_Array1<opencascade::handle<StepGeom_CompositeCurveSegment>>, Standard_Transient):
+class StepGeom_HArray1OfCompositeCurveSegment(StepGeom_Array1OfCompositeCurveSegment, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<opencascade::handle<StepGeom_CompositeCurveSegment>>: ...
+    def Array1(self) -> StepGeom_Array1OfCompositeCurveSegment: ...
 
 
-class StepGeom_HArray1OfCurve(NCollection_Array1<opencascade::handle<StepGeom_Curve>>, Standard_Transient):
+class StepGeom_HArray1OfCurve(StepGeom_Array1OfCurve, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<opencascade::handle<StepGeom_Curve>>: ...
+    def Array1(self) -> StepGeom_Array1OfCurve: ...
 
 
-class StepGeom_HArray1OfPcurveOrSurface(NCollection_Array1<StepGeom_PcurveOrSurface>, Standard_Transient):
+class StepGeom_HArray1OfPcurveOrSurface(StepGeom_Array1OfPcurveOrSurface, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepGeom_PcurveOrSurface>: ...
+    def Array1(self) -> StepGeom_Array1OfPcurveOrSurface: ...
 
 
-class StepGeom_HArray1OfSurfaceBoundary(NCollection_Array1<StepGeom_SurfaceBoundary>, Standard_Transient):
+class StepGeom_HArray1OfSurfaceBoundary(StepGeom_Array1OfSurfaceBoundary, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepGeom_SurfaceBoundary>: ...
+    def Array1(self) -> StepGeom_Array1OfSurfaceBoundary: ...
 
 
-class StepGeom_HArray1OfTrimmingSelect(NCollection_Array1<StepGeom_TrimmingSelect>, Standard_Transient):
+class StepGeom_HArray1OfTrimmingSelect(StepGeom_Array1OfTrimmingSelect, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepGeom_TrimmingSelect>: ...
+    def Array1(self) -> StepGeom_Array1OfTrimmingSelect: ...
 
 # harray2 classes
 
-class StepGeom_HArray2OfCartesianPoint(NCollection_Array2<opencascade::handle<StepGeom_CartesianPoint>>, Standard_Transient):
+class StepGeom_HArray2OfCartesianPoint(Any, Standard_Transient):
     @overload
     def __init__(self, theRowLow: int, theRowUpp: int, theColLow: int, theColUpp: int) -> None: ...
     @overload
-    def __init__(self, theOther: NCollection_Array2<opencascade::handle<StepGeom_CartesianPoint>>) -> None: ...
-    def Array2(self) -> NCollection_Array2<opencascade::handle<StepGeom_CartesianPoint>>: ...
+    def __init__(self, theOther: Any) -> None: ...
+    def Array2(self) -> Any: ...
 
 
-class StepGeom_HArray2OfSurfacePatch(NCollection_Array2<opencascade::handle<StepGeom_SurfacePatch>>, Standard_Transient):
+class StepGeom_HArray2OfSurfacePatch(Any, Standard_Transient):
     @overload
     def __init__(self, theRowLow: int, theRowUpp: int, theColLow: int, theColUpp: int) -> None: ...
     @overload
-    def __init__(self, theOther: NCollection_Array2<opencascade::handle<StepGeom_SurfacePatch>>) -> None: ...
-    def Array2(self) -> NCollection_Array2<opencascade::handle<StepGeom_SurfacePatch>>: ...
+    def __init__(self, theOther: Any) -> None: ...
+    def Array2(self) -> Any: ...
 
 # hsequence classes
 
