--- src/SWIG_files/wrapper/HLRAlgo.pyi.orig	2026-08-09 14:32:48 UTC
+++ src/SWIG_files/wrapper/HLRAlgo.pyi
@@ -1,5 +1,5 @@ from enum import IntEnum
 from enum import IntEnum
-from typing import overload, NewType, Optional, Tuple
+from typing import Any, overload, NewType, Optional, Tuple
 
 from OCC.Core.Standard import *
 from OCC.Core.NCollection import *
@@ -445,24 +445,24 @@ class HLRAlgo_PolyHidingData: ...
 
 # harray1 classes
 
-class HLRAlgo_HArray1OfPHDat(NCollection_Array1<HLRAlgo_PolyHidingData>, Standard_Transient):
+class HLRAlgo_HArray1OfPHDat(HLRAlgo_Array1OfPHDat, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<HLRAlgo_PolyHidingData>: ...
+    def Array1(self) -> HLRAlgo_Array1OfPHDat: ...
 
 
-class HLRAlgo_HArray1OfPINod(NCollection_Array1<opencascade::handle<HLRAlgo_PolyInternalNode>>, Standard_Transient):
+class HLRAlgo_HArray1OfPINod(HLRAlgo_Array1OfPINod, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<opencascade::handle<HLRAlgo_PolyInternalNode>>: ...
+    def Array1(self) -> HLRAlgo_Array1OfPINod: ...
 
 
-class HLRAlgo_HArray1OfPISeg(NCollection_Array1<HLRAlgo_PolyInternalSegment>, Standard_Transient):
+class HLRAlgo_HArray1OfPISeg(HLRAlgo_Array1OfPISeg, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<HLRAlgo_PolyInternalSegment>: ...
+    def Array1(self) -> HLRAlgo_Array1OfPISeg: ...
 
 
-class HLRAlgo_HArray1OfTData(NCollection_Array1<HLRAlgo_TriangleData>, Standard_Transient):
+class HLRAlgo_HArray1OfTData(HLRAlgo_Array1OfTData, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<HLRAlgo_TriangleData>: ...
+    def Array1(self) -> HLRAlgo_Array1OfTData: ...
 
 # harray2 classes
 # hsequence classes
