--- src/SWIG_files/wrapper/StepFEA.pyi.orig	2026-08-09 14:32:48 UTC
+++ src/SWIG_files/wrapper/StepFEA.pyi
@@ -1,5 +1,5 @@ from enum import IntEnum
 from enum import IntEnum
-from typing import overload, NewType, Optional, Tuple
+from typing import Any, overload, NewType, Optional, Tuple
 
 from OCC.Core.Standard import *
 from OCC.Core.NCollection import *
@@ -667,71 +667,71 @@ class StepFEA_NodeWithVector(StepFEA_Node):
 
 # harray1 classes
 
-class StepFEA_HArray1OfCurveElementEndOffset(NCollection_Array1<opencascade::handle<StepFEA_CurveElementEndOffset>>, Standard_Transient):
+class StepFEA_HArray1OfCurveElementEndOffset(StepFEA_Array1OfCurveElementEndOffset, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<opencascade::handle<StepFEA_CurveElementEndOffset>>: ...
+    def Array1(self) -> StepFEA_Array1OfCurveElementEndOffset: ...
 
 
-class StepFEA_HArray1OfCurveElementEndRelease(NCollection_Array1<opencascade::handle<StepFEA_CurveElementEndRelease>>, Standard_Transient):
+class StepFEA_HArray1OfCurveElementEndRelease(StepFEA_Array1OfCurveElementEndRelease, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<opencascade::handle<StepFEA_CurveElementEndRelease>>: ...
+    def Array1(self) -> StepFEA_Array1OfCurveElementEndRelease: ...
 
 
-class StepFEA_HArray1OfCurveElementInterval(NCollection_Array1<opencascade::handle<StepFEA_CurveElementInterval>>, Standard_Transient):
+class StepFEA_HArray1OfCurveElementInterval(StepFEA_Array1OfCurveElementInterval, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<opencascade::handle<StepFEA_CurveElementInterval>>: ...
+    def Array1(self) -> StepFEA_Array1OfCurveElementInterval: ...
 
 
-class StepFEA_HArray1OfDegreeOfFreedom(NCollection_Array1<StepFEA_DegreeOfFreedom>, Standard_Transient):
+class StepFEA_HArray1OfDegreeOfFreedom(StepFEA_Array1OfDegreeOfFreedom, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepFEA_DegreeOfFreedom>: ...
+    def Array1(self) -> StepFEA_Array1OfDegreeOfFreedom: ...
 
 
-class StepFEA_HArray1OfElementRepresentation(NCollection_Array1<opencascade::handle<StepFEA_ElementRepresentation>>, Standard_Transient):
+class StepFEA_HArray1OfElementRepresentation(StepFEA_Array1OfElementRepresentation, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<opencascade::handle<StepFEA_ElementRepresentation>>: ...
+    def Array1(self) -> StepFEA_Array1OfElementRepresentation: ...
 
 
-class StepFEA_HArray1OfNodeRepresentation(NCollection_Array1<opencascade::handle<StepFEA_NodeRepresentation>>, Standard_Transient):
+class StepFEA_HArray1OfNodeRepresentation(StepFEA_Array1OfNodeRepresentation, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<opencascade::handle<StepFEA_NodeRepresentation>>: ...
+    def Array1(self) -> StepFEA_Array1OfNodeRepresentation: ...
 
 # harray2 classes
 # hsequence classes
 
-class StepFEA_HSequenceOfCurve3dElementProperty(NCollection_Sequence<opencascade::handle<StepFEA_Curve3dElementProperty>>, Standard_Transient):
+class StepFEA_HSequenceOfCurve3dElementProperty(StepFEA_SequenceOfCurve3dElementProperty, Standard_Transient):
     @overload
     def __init__(self) -> None: ...
     @overload
-    def __init__(self, other: NCollection_Sequence<opencascade::handle<StepFEA_Curve3dElementProperty>>) -> None: ...
-    def Sequence(self) -> NCollection_Sequence<opencascade::handle<StepFEA_Curve3dElementProperty>>: ...
-    def Append(self, theSequence: NCollection_Sequence<opencascade::handle<StepFEA_Curve3dElementProperty>>) -> None: ...
+    def __init__(self, other: StepFEA_SequenceOfCurve3dElementProperty) -> None: ...
+    def Sequence(self) -> StepFEA_SequenceOfCurve3dElementProperty: ...
+    def Append(self, theSequence: StepFEA_SequenceOfCurve3dElementProperty) -> None: ...
 
 
-class StepFEA_HSequenceOfElementGeometricRelationship(NCollection_Sequence<opencascade::handle<StepFEA_ElementGeometricRelationship>>, Standard_Transient):
+class StepFEA_HSequenceOfElementGeometricRelationship(StepFEA_SequenceOfElementGeometricRelationship, Standard_Transient):
     @overload
     def __init__(self) -> None: ...
     @overload
-    def __init__(self, other: NCollection_Sequence<opencascade::handle<StepFEA_ElementGeometricRelationship>>) -> None: ...
-    def Sequence(self) -> NCollection_Sequence<opencascade::handle<StepFEA_ElementGeometricRelationship>>: ...
-    def Append(self, theSequence: NCollection_Sequence<opencascade::handle<StepFEA_ElementGeometricRelationship>>) -> None: ...
+    def __init__(self, other: StepFEA_SequenceOfElementGeometricRelationship) -> None: ...
+    def Sequence(self) -> StepFEA_SequenceOfElementGeometricRelationship: ...
+    def Append(self, theSequence: StepFEA_SequenceOfElementGeometricRelationship) -> None: ...
 
 
-class StepFEA_HSequenceOfElementRepresentation(NCollection_Sequence<opencascade::handle<StepFEA_ElementRepresentation>>, Standard_Transient):
+class StepFEA_HSequenceOfElementRepresentation(StepFEA_SequenceOfElementRepresentation, Standard_Transient):
     @overload
     def __init__(self) -> None: ...
     @overload
-    def __init__(self, other: NCollection_Sequence<opencascade::handle<StepFEA_ElementRepresentation>>) -> None: ...
-    def Sequence(self) -> NCollection_Sequence<opencascade::handle<StepFEA_ElementRepresentation>>: ...
-    def Append(self, theSequence: NCollection_Sequence<opencascade::handle<StepFEA_ElementRepresentation>>) -> None: ...
+    def __init__(self, other: StepFEA_SequenceOfElementRepresentation) -> None: ...
+    def Sequence(self) -> StepFEA_SequenceOfElementRepresentation: ...
+    def Append(self, theSequence: StepFEA_SequenceOfElementRepresentation) -> None: ...
 
 
-class StepFEA_HSequenceOfNodeRepresentation(NCollection_Sequence<opencascade::handle<StepFEA_NodeRepresentation>>, Standard_Transient):
+class StepFEA_HSequenceOfNodeRepresentation(StepFEA_SequenceOfNodeRepresentation, Standard_Transient):
     @overload
     def __init__(self) -> None: ...
     @overload
-    def __init__(self, other: NCollection_Sequence<opencascade::handle<StepFEA_NodeRepresentation>>) -> None: ...
-    def Sequence(self) -> NCollection_Sequence<opencascade::handle<StepFEA_NodeRepresentation>>: ...
-    def Append(self, theSequence: NCollection_Sequence<opencascade::handle<StepFEA_NodeRepresentation>>) -> None: ...
+    def __init__(self, other: StepFEA_SequenceOfNodeRepresentation) -> None: ...
+    def Sequence(self) -> StepFEA_SequenceOfNodeRepresentation: ...
+    def Append(self, theSequence: StepFEA_SequenceOfNodeRepresentation) -> None: ...
 
 
