--- src/SWIG_files/wrapper/GeomPlate.pyi.orig	2026-08-09 14:32:48 UTC
+++ src/SWIG_files/wrapper/GeomPlate.pyi
@@ -1,5 +1,5 @@ from enum import IntEnum
 from enum import IntEnum
-from typing import overload, NewType, Optional, Tuple
+from typing import Any, overload, NewType, Optional, Tuple
 
 from OCC.Core.Standard import *
 from OCC.Core.NCollection import *
@@ -271,33 +271,33 @@ class GeomPlate_Surface(Geom_Surface):
 
 # harray1 classes
 
-class GeomPlate_HArray1OfHCurve(NCollection_Array1<opencascade::handle<Adaptor3d_Curve>>, Standard_Transient):
+class GeomPlate_HArray1OfHCurve(GeomPlate_Array1OfHCurve, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<opencascade::handle<Adaptor3d_Curve>>: ...
+    def Array1(self) -> GeomPlate_Array1OfHCurve: ...
 
 
-class GeomPlate_HArray1OfSequenceOfReal(NCollection_Array1<TColStd_SequenceOfReal>, Standard_Transient):
+class GeomPlate_HArray1OfSequenceOfReal(GeomPlate_Array1OfSequenceOfReal, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<TColStd_SequenceOfReal>: ...
+    def Array1(self) -> GeomPlate_Array1OfSequenceOfReal: ...
 
 # harray2 classes
 # hsequence classes
 
-class GeomPlate_HSequenceOfCurveConstraint(NCollection_Sequence<opencascade::handle<GeomPlate_CurveConstraint>>, Standard_Transient):
+class GeomPlate_HSequenceOfCurveConstraint(GeomPlate_SequenceOfCurveConstraint, Standard_Transient):
     @overload
     def __init__(self) -> None: ...
     @overload
-    def __init__(self, other: NCollection_Sequence<opencascade::handle<GeomPlate_CurveConstraint>>) -> None: ...
-    def Sequence(self) -> NCollection_Sequence<opencascade::handle<GeomPlate_CurveConstraint>>: ...
-    def Append(self, theSequence: NCollection_Sequence<opencascade::handle<GeomPlate_CurveConstraint>>) -> None: ...
+    def __init__(self, other: GeomPlate_SequenceOfCurveConstraint) -> None: ...
+    def Sequence(self) -> GeomPlate_SequenceOfCurveConstraint: ...
+    def Append(self, theSequence: GeomPlate_SequenceOfCurveConstraint) -> None: ...
 
 
-class GeomPlate_HSequenceOfPointConstraint(NCollection_Sequence<opencascade::handle<GeomPlate_PointConstraint>>, Standard_Transient):
+class GeomPlate_HSequenceOfPointConstraint(GeomPlate_SequenceOfPointConstraint, Standard_Transient):
     @overload
     def __init__(self) -> None: ...
     @overload
-    def __init__(self, other: NCollection_Sequence<opencascade::handle<GeomPlate_PointConstraint>>) -> None: ...
-    def Sequence(self) -> NCollection_Sequence<opencascade::handle<GeomPlate_PointConstraint>>: ...
-    def Append(self, theSequence: NCollection_Sequence<opencascade::handle<GeomPlate_PointConstraint>>) -> None: ...
+    def __init__(self, other: GeomPlate_SequenceOfPointConstraint) -> None: ...
+    def Sequence(self) -> GeomPlate_SequenceOfPointConstraint: ...
+    def Append(self, theSequence: GeomPlate_SequenceOfPointConstraint) -> None: ...
 
 
