--- src/SWIG_files/wrapper/Units.pyi.orig	2026-08-09 14:32:48 UTC
+++ src/SWIG_files/wrapper/Units.pyi
@@ -1,5 +1,5 @@ from enum import IntEnum
 from enum import IntEnum
-from typing import overload, NewType, Optional, Tuple
+from typing import Any, overload, NewType, Optional, Tuple
 
 from OCC.Core.Standard import *
 from OCC.Core.NCollection import *
@@ -357,30 +357,30 @@ class Units_UnitsLexicon(Units_Lexicon):
 # harray2 classes
 # hsequence classes
 
-class Units_QuantitiesSequence(NCollection_Sequence<opencascade::handle<Units_Quantity>>, Standard_Transient):
+class Units_QuantitiesSequence(Units_QtsSequence, Standard_Transient):
     @overload
     def __init__(self) -> None: ...
     @overload
-    def __init__(self, other: NCollection_Sequence<opencascade::handle<Units_Quantity>>) -> None: ...
-    def Sequence(self) -> NCollection_Sequence<opencascade::handle<Units_Quantity>>: ...
-    def Append(self, theSequence: NCollection_Sequence<opencascade::handle<Units_Quantity>>) -> None: ...
+    def __init__(self, other: Units_QtsSequence) -> None: ...
+    def Sequence(self) -> Units_QtsSequence: ...
+    def Append(self, theSequence: Units_QtsSequence) -> None: ...
 
 
-class Units_TokensSequence(NCollection_Sequence<opencascade::handle<Units_Token>>, Standard_Transient):
+class Units_TokensSequence(Units_TksSequence, Standard_Transient):
     @overload
     def __init__(self) -> None: ...
     @overload
-    def __init__(self, other: NCollection_Sequence<opencascade::handle<Units_Token>>) -> None: ...
-    def Sequence(self) -> NCollection_Sequence<opencascade::handle<Units_Token>>: ...
-    def Append(self, theSequence: NCollection_Sequence<opencascade::handle<Units_Token>>) -> None: ...
+    def __init__(self, other: Units_TksSequence) -> None: ...
+    def Sequence(self) -> Units_TksSequence: ...
+    def Append(self, theSequence: Units_TksSequence) -> None: ...
 
 
-class Units_UnitsSequence(NCollection_Sequence<opencascade::handle<Units_Unit>>, Standard_Transient):
+class Units_UnitsSequence(Units_UtsSequence, Standard_Transient):
     @overload
     def __init__(self) -> None: ...
     @overload
-    def __init__(self, other: NCollection_Sequence<opencascade::handle<Units_Unit>>) -> None: ...
-    def Sequence(self) -> NCollection_Sequence<opencascade::handle<Units_Unit>>: ...
-    def Append(self, theSequence: NCollection_Sequence<opencascade::handle<Units_Unit>>) -> None: ...
+    def __init__(self, other: Units_UtsSequence) -> None: ...
+    def Sequence(self) -> Units_UtsSequence: ...
+    def Append(self, theSequence: Units_UtsSequence) -> None: ...
 
 
