--- src/SWIG_files/wrapper/TColGeom.pyi.orig	2026-08-09 14:32:48 UTC
+++ src/SWIG_files/wrapper/TColGeom.pyi
@@ -1,5 +1,5 @@ from enum import IntEnum
 from enum import IntEnum
-from typing import overload, NewType, Optional, Tuple
+from typing import Any, overload, NewType, Optional, Tuple
 
 from OCC.Core.Standard import *
 from OCC.Core.NCollection import *
@@ -167,51 +167,51 @@ class TColGeom_SequenceOfSurface:
 
 # harray1 classes
 
-class TColGeom_HArray1OfSurface(NCollection_Array1<opencascade::handle<Geom_Surface>>, Standard_Transient):
+class TColGeom_HArray1OfSurface(TColGeom_Array1OfSurface, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<opencascade::handle<Geom_Surface>>: ...
+    def Array1(self) -> TColGeom_Array1OfSurface: ...
 
 
-class TColGeom_HArray1OfBezierCurve(NCollection_Array1<opencascade::handle<Geom_BezierCurve>>, Standard_Transient):
+class TColGeom_HArray1OfBezierCurve(TColGeom_Array1OfBezierCurve, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<opencascade::handle<Geom_BezierCurve>>: ...
+    def Array1(self) -> TColGeom_Array1OfBezierCurve: ...
 
 
-class TColGeom_HArray1OfCurve(NCollection_Array1<opencascade::handle<Geom_Curve>>, Standard_Transient):
+class TColGeom_HArray1OfCurve(TColGeom_Array1OfCurve, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<opencascade::handle<Geom_Curve>>: ...
+    def Array1(self) -> TColGeom_Array1OfCurve: ...
 
 
-class TColGeom_HArray1OfBSplineCurve(NCollection_Array1<opencascade::handle<Geom_BSplineCurve>>, Standard_Transient):
+class TColGeom_HArray1OfBSplineCurve(TColGeom_Array1OfBSplineCurve, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<opencascade::handle<Geom_BSplineCurve>>: ...
+    def Array1(self) -> TColGeom_Array1OfBSplineCurve: ...
 
 # harray2 classes
 
-class TColGeom_HArray2OfSurface(NCollection_Array2<opencascade::handle<Geom_Surface>>, Standard_Transient):
+class TColGeom_HArray2OfSurface(TColGeom_Array2OfSurface, Standard_Transient):
     @overload
     def __init__(self, theRowLow: int, theRowUpp: int, theColLow: int, theColUpp: int) -> None: ...
     @overload
-    def __init__(self, theOther: NCollection_Array2<opencascade::handle<Geom_Surface>>) -> None: ...
-    def Array2(self) -> NCollection_Array2<opencascade::handle<Geom_Surface>>: ...
+    def __init__(self, theOther: TColGeom_Array2OfSurface) -> None: ...
+    def Array2(self) -> TColGeom_Array2OfSurface: ...
 
 # hsequence classes
 
-class TColGeom_HSequenceOfBoundedCurve(NCollection_Sequence<opencascade::handle<Geom_BoundedCurve>>, Standard_Transient):
+class TColGeom_HSequenceOfBoundedCurve(TColGeom_SequenceOfBoundedCurve, Standard_Transient):
     @overload
     def __init__(self) -> None: ...
     @overload
-    def __init__(self, other: NCollection_Sequence<opencascade::handle<Geom_BoundedCurve>>) -> None: ...
-    def Sequence(self) -> NCollection_Sequence<opencascade::handle<Geom_BoundedCurve>>: ...
-    def Append(self, theSequence: NCollection_Sequence<opencascade::handle<Geom_BoundedCurve>>) -> None: ...
+    def __init__(self, other: TColGeom_SequenceOfBoundedCurve) -> None: ...
+    def Sequence(self) -> TColGeom_SequenceOfBoundedCurve: ...
+    def Append(self, theSequence: TColGeom_SequenceOfBoundedCurve) -> None: ...
 
 
-class TColGeom_HSequenceOfCurve(NCollection_Sequence<opencascade::handle<Geom_Curve>>, Standard_Transient):
+class TColGeom_HSequenceOfCurve(TColGeom_SequenceOfCurve, Standard_Transient):
     @overload
     def __init__(self) -> None: ...
     @overload
-    def __init__(self, other: NCollection_Sequence<opencascade::handle<Geom_Curve>>) -> None: ...
-    def Sequence(self) -> NCollection_Sequence<opencascade::handle<Geom_Curve>>: ...
-    def Append(self, theSequence: NCollection_Sequence<opencascade::handle<Geom_Curve>>) -> None: ...
+    def __init__(self, other: TColGeom_SequenceOfCurve) -> None: ...
+    def Sequence(self) -> TColGeom_SequenceOfCurve: ...
+    def Append(self, theSequence: TColGeom_SequenceOfCurve) -> None: ...
 
 
