--- src/SWIG_files/wrapper/StepAP214.pyi.orig	2026-08-09 14:32:48 UTC
+++ src/SWIG_files/wrapper/StepAP214.pyi
@@ -1,5 +1,5 @@ from enum import IntEnum
 from enum import IntEnum
-from typing import overload, NewType, Optional, Tuple
+from typing import Any, overload, NewType, Optional, Tuple
 
 from OCC.Core.Standard import *
 from OCC.Core.NCollection import *
@@ -840,89 +840,89 @@ class StepAP214_SecurityClassificationItem(StepAP214_A
 
 # harray1 classes
 
-class StepAP214_HArray1OfApprovalItem(NCollection_Array1<StepAP214_ApprovalItem>, Standard_Transient):
+class StepAP214_HArray1OfApprovalItem(StepAP214_Array1OfApprovalItem, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepAP214_ApprovalItem>: ...
+    def Array1(self) -> StepAP214_Array1OfApprovalItem: ...
 
 
-class StepAP214_HArray1OfAutoDesignDateAndPersonItem(NCollection_Array1<StepAP214_AutoDesignDateAndPersonItem>, Standard_Transient):
+class StepAP214_HArray1OfAutoDesignDateAndPersonItem(StepAP214_Array1OfAutoDesignDateAndPersonItem, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepAP214_AutoDesignDateAndPersonItem>: ...
+    def Array1(self) -> StepAP214_Array1OfAutoDesignDateAndPersonItem: ...
 
 
-class StepAP214_HArray1OfAutoDesignDateAndTimeItem(NCollection_Array1<StepAP214_AutoDesignDateAndTimeItem>, Standard_Transient):
+class StepAP214_HArray1OfAutoDesignDateAndTimeItem(StepAP214_Array1OfAutoDesignDateAndTimeItem, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepAP214_AutoDesignDateAndTimeItem>: ...
+    def Array1(self) -> StepAP214_Array1OfAutoDesignDateAndTimeItem: ...
 
 
-class StepAP214_HArray1OfAutoDesignDatedItem(NCollection_Array1<StepAP214_AutoDesignDatedItem>, Standard_Transient):
+class StepAP214_HArray1OfAutoDesignDatedItem(StepAP214_Array1OfAutoDesignDatedItem, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepAP214_AutoDesignDatedItem>: ...
+    def Array1(self) -> StepAP214_Array1OfAutoDesignDatedItem: ...
 
 
-class StepAP214_HArray1OfAutoDesignGeneralOrgItem(NCollection_Array1<StepAP214_AutoDesignGeneralOrgItem>, Standard_Transient):
+class StepAP214_HArray1OfAutoDesignGeneralOrgItem(StepAP214_Array1OfAutoDesignGeneralOrgItem, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepAP214_AutoDesignGeneralOrgItem>: ...
+    def Array1(self) -> StepAP214_Array1OfAutoDesignGeneralOrgItem: ...
 
 
-class StepAP214_HArray1OfAutoDesignGroupedItem(NCollection_Array1<StepAP214_AutoDesignGroupedItem>, Standard_Transient):
+class StepAP214_HArray1OfAutoDesignGroupedItem(StepAP214_Array1OfAutoDesignGroupedItem, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepAP214_AutoDesignGroupedItem>: ...
+    def Array1(self) -> StepAP214_Array1OfAutoDesignGroupedItem: ...
 
 
-class StepAP214_HArray1OfAutoDesignPresentedItemSelect(NCollection_Array1<StepAP214_AutoDesignPresentedItemSelect>, Standard_Transient):
+class StepAP214_HArray1OfAutoDesignPresentedItemSelect(StepAP214_Array1OfAutoDesignPresentedItemSelect, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepAP214_AutoDesignPresentedItemSelect>: ...
+    def Array1(self) -> StepAP214_Array1OfAutoDesignPresentedItemSelect: ...
 
 
-class StepAP214_HArray1OfAutoDesignReferencingItem(NCollection_Array1<StepAP214_AutoDesignReferencingItem>, Standard_Transient):
+class StepAP214_HArray1OfAutoDesignReferencingItem(StepAP214_Array1OfAutoDesignReferencingItem, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepAP214_AutoDesignReferencingItem>: ...
+    def Array1(self) -> StepAP214_Array1OfAutoDesignReferencingItem: ...
 
 
-class StepAP214_HArray1OfDateAndTimeItem(NCollection_Array1<StepAP214_DateAndTimeItem>, Standard_Transient):
+class StepAP214_HArray1OfDateAndTimeItem(StepAP214_Array1OfDateAndTimeItem, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepAP214_DateAndTimeItem>: ...
+    def Array1(self) -> StepAP214_Array1OfDateAndTimeItem: ...
 
 
-class StepAP214_HArray1OfDateItem(NCollection_Array1<StepAP214_DateItem>, Standard_Transient):
+class StepAP214_HArray1OfDateItem(StepAP214_Array1OfDateItem, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepAP214_DateItem>: ...
+    def Array1(self) -> StepAP214_Array1OfDateItem: ...
 
 
-class StepAP214_HArray1OfDocumentReferenceItem(NCollection_Array1<StepAP214_DocumentReferenceItem>, Standard_Transient):
+class StepAP214_HArray1OfDocumentReferenceItem(StepAP214_Array1OfDocumentReferenceItem, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepAP214_DocumentReferenceItem>: ...
+    def Array1(self) -> StepAP214_Array1OfDocumentReferenceItem: ...
 
 
-class StepAP214_HArray1OfExternalIdentificationItem(NCollection_Array1<StepAP214_ExternalIdentificationItem>, Standard_Transient):
+class StepAP214_HArray1OfExternalIdentificationItem(StepAP214_Array1OfExternalIdentificationItem, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepAP214_ExternalIdentificationItem>: ...
+    def Array1(self) -> StepAP214_Array1OfExternalIdentificationItem: ...
 
 
-class StepAP214_HArray1OfGroupItem(NCollection_Array1<StepAP214_GroupItem>, Standard_Transient):
+class StepAP214_HArray1OfGroupItem(StepAP214_Array1OfGroupItem, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepAP214_GroupItem>: ...
+    def Array1(self) -> StepAP214_Array1OfGroupItem: ...
 
 
-class StepAP214_HArray1OfOrganizationItem(NCollection_Array1<StepAP214_OrganizationItem>, Standard_Transient):
+class StepAP214_HArray1OfOrganizationItem(StepAP214_Array1OfOrganizationItem, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepAP214_OrganizationItem>: ...
+    def Array1(self) -> StepAP214_Array1OfOrganizationItem: ...
 
 
-class StepAP214_HArray1OfPersonAndOrganizationItem(NCollection_Array1<StepAP214_PersonAndOrganizationItem>, Standard_Transient):
+class StepAP214_HArray1OfPersonAndOrganizationItem(StepAP214_Array1OfPersonAndOrganizationItem, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepAP214_PersonAndOrganizationItem>: ...
+    def Array1(self) -> StepAP214_Array1OfPersonAndOrganizationItem: ...
 
 
-class StepAP214_HArray1OfPresentedItemSelect(NCollection_Array1<StepAP214_PresentedItemSelect>, Standard_Transient):
+class StepAP214_HArray1OfPresentedItemSelect(StepAP214_Array1OfPresentedItemSelect, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepAP214_PresentedItemSelect>: ...
+    def Array1(self) -> StepAP214_Array1OfPresentedItemSelect: ...
 
 
-class StepAP214_HArray1OfSecurityClassificationItem(NCollection_Array1<StepAP214_SecurityClassificationItem>, Standard_Transient):
+class StepAP214_HArray1OfSecurityClassificationItem(StepAP214_Array1OfSecurityClassificationItem, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepAP214_SecurityClassificationItem>: ...
+    def Array1(self) -> StepAP214_Array1OfSecurityClassificationItem: ...
 
 # harray2 classes
 # hsequence classes
