--- src/SWIG_files/wrapper/StepElement.pyi.orig	2026-08-09 14:32:48 UTC
+++ src/SWIG_files/wrapper/StepElement.pyi
@@ -1,5 +1,5 @@ from enum import IntEnum
 from enum import IntEnum
-from typing import overload, NewType, Optional, Tuple
+from typing import Any, overload, NewType, Optional, Tuple
 
 from OCC.Core.Standard import *
 from OCC.Core.NCollection import *
@@ -589,95 +589,95 @@ class StepElement_Volume3dElementDescriptor(StepElemen
 
 # harray1 classes
 
-class StepElement_HArray1OfCurveElementEndReleasePacket(NCollection_Array1<opencascade::handle<StepElement_CurveElementEndReleasePacket>>, Standard_Transient):
+class StepElement_HArray1OfCurveElementEndReleasePacket(StepElement_Array1OfCurveElementEndReleasePacket, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<opencascade::handle<StepElement_CurveElementEndReleasePacket>>: ...
+    def Array1(self) -> StepElement_Array1OfCurveElementEndReleasePacket: ...
 
 
-class StepElement_HArray1OfCurveElementSectionDefinition(NCollection_Array1<opencascade::handle<StepElement_CurveElementSectionDefinition>>, Standard_Transient):
+class StepElement_HArray1OfCurveElementSectionDefinition(StepElement_Array1OfCurveElementSectionDefinition, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<opencascade::handle<StepElement_CurveElementSectionDefinition>>: ...
+    def Array1(self) -> StepElement_Array1OfCurveElementSectionDefinition: ...
 
 
-class StepElement_HArray1OfMeasureOrUnspecifiedValue(NCollection_Array1<StepElement_MeasureOrUnspecifiedValue>, Standard_Transient):
+class StepElement_HArray1OfMeasureOrUnspecifiedValue(StepElement_Array1OfMeasureOrUnspecifiedValue, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepElement_MeasureOrUnspecifiedValue>: ...
+    def Array1(self) -> StepElement_Array1OfMeasureOrUnspecifiedValue: ...
 
 
-class StepElement_HArray1OfSurfaceSection(NCollection_Array1<opencascade::handle<StepElement_SurfaceSection>>, Standard_Transient):
+class StepElement_HArray1OfSurfaceSection(StepElement_Array1OfSurfaceSection, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<opencascade::handle<StepElement_SurfaceSection>>: ...
+    def Array1(self) -> StepElement_Array1OfSurfaceSection: ...
 
 
-class StepElement_HArray1OfVolumeElementPurpose(NCollection_Array1<StepElement_VolumeElementPurpose>, Standard_Transient):
+class StepElement_HArray1OfVolumeElementPurpose(StepElement_Array1OfVolumeElementPurpose, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepElement_VolumeElementPurpose>: ...
+    def Array1(self) -> StepElement_Array1OfVolumeElementPurpose: ...
 
 
-class StepElement_HArray1OfVolumeElementPurposeMember(NCollection_Array1<opencascade::handle<StepElement_VolumeElementPurposeMember>>, Standard_Transient):
+class StepElement_HArray1OfVolumeElementPurposeMember(StepElement_Array1OfVolumeElementPurposeMember, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<opencascade::handle<StepElement_VolumeElementPurposeMember>>: ...
+    def Array1(self) -> StepElement_Array1OfVolumeElementPurposeMember: ...
 
 # harray2 classes
 
-class StepElement_HArray2OfCurveElementPurposeMember(NCollection_Array2<opencascade::handle<StepElement_CurveElementPurposeMember>>, Standard_Transient):
+class StepElement_HArray2OfCurveElementPurposeMember(Any, Standard_Transient):
     @overload
     def __init__(self, theRowLow: int, theRowUpp: int, theColLow: int, theColUpp: int) -> None: ...
     @overload
-    def __init__(self, theOther: NCollection_Array2<opencascade::handle<StepElement_CurveElementPurposeMember>>) -> None: ...
-    def Array2(self) -> NCollection_Array2<opencascade::handle<StepElement_CurveElementPurposeMember>>: ...
+    def __init__(self, theOther: Any) -> None: ...
+    def Array2(self) -> Any: ...
 
 
-class StepElement_HArray2OfSurfaceElementPurpose(NCollection_Array2<StepElement_SurfaceElementPurpose>, Standard_Transient):
+class StepElement_HArray2OfSurfaceElementPurpose(Any, Standard_Transient):
     @overload
     def __init__(self, theRowLow: int, theRowUpp: int, theColLow: int, theColUpp: int) -> None: ...
     @overload
-    def __init__(self, theOther: NCollection_Array2<StepElement_SurfaceElementPurpose>) -> None: ...
-    def Array2(self) -> NCollection_Array2<StepElement_SurfaceElementPurpose>: ...
+    def __init__(self, theOther: Any) -> None: ...
+    def Array2(self) -> Any: ...
 
 
-class StepElement_HArray2OfSurfaceElementPurposeMember(NCollection_Array2<opencascade::handle<StepElement_SurfaceElementPurposeMember>>, Standard_Transient):
+class StepElement_HArray2OfSurfaceElementPurposeMember(Any, Standard_Transient):
     @overload
     def __init__(self, theRowLow: int, theRowUpp: int, theColLow: int, theColUpp: int) -> None: ...
     @overload
-    def __init__(self, theOther: NCollection_Array2<opencascade::handle<StepElement_SurfaceElementPurposeMember>>) -> None: ...
-    def Array2(self) -> NCollection_Array2<opencascade::handle<StepElement_SurfaceElementPurposeMember>>: ...
+    def __init__(self, theOther: Any) -> None: ...
+    def Array2(self) -> Any: ...
 
 # hsequence classes
 
-class StepElement_HSequenceOfCurveElementPurposeMember(NCollection_Sequence<opencascade::handle<StepElement_CurveElementPurposeMember>>, Standard_Transient):
+class StepElement_HSequenceOfCurveElementPurposeMember(StepElement_SequenceOfCurveElementPurposeMember, Standard_Transient):
     @overload
     def __init__(self) -> None: ...
     @overload
-    def __init__(self, other: NCollection_Sequence<opencascade::handle<StepElement_CurveElementPurposeMember>>) -> None: ...
-    def Sequence(self) -> NCollection_Sequence<opencascade::handle<StepElement_CurveElementPurposeMember>>: ...
-    def Append(self, theSequence: NCollection_Sequence<opencascade::handle<StepElement_CurveElementPurposeMember>>) -> None: ...
+    def __init__(self, other: StepElement_SequenceOfCurveElementPurposeMember) -> None: ...
+    def Sequence(self) -> StepElement_SequenceOfCurveElementPurposeMember: ...
+    def Append(self, theSequence: StepElement_SequenceOfCurveElementPurposeMember) -> None: ...
 
 
-class StepElement_HSequenceOfCurveElementSectionDefinition(NCollection_Sequence<opencascade::handle<StepElement_CurveElementSectionDefinition>>, Standard_Transient):
+class StepElement_HSequenceOfCurveElementSectionDefinition(StepElement_SequenceOfCurveElementSectionDefinition, Standard_Transient):
     @overload
     def __init__(self) -> None: ...
     @overload
-    def __init__(self, other: NCollection_Sequence<opencascade::handle<StepElement_CurveElementSectionDefinition>>) -> None: ...
-    def Sequence(self) -> NCollection_Sequence<opencascade::handle<StepElement_CurveElementSectionDefinition>>: ...
-    def Append(self, theSequence: NCollection_Sequence<opencascade::handle<StepElement_CurveElementSectionDefinition>>) -> None: ...
+    def __init__(self, other: StepElement_SequenceOfCurveElementSectionDefinition) -> None: ...
+    def Sequence(self) -> StepElement_SequenceOfCurveElementSectionDefinition: ...
+    def Append(self, theSequence: StepElement_SequenceOfCurveElementSectionDefinition) -> None: ...
 
 
-class StepElement_HSequenceOfElementMaterial(NCollection_Sequence<opencascade::handle<StepElement_ElementMaterial>>, Standard_Transient):
+class StepElement_HSequenceOfElementMaterial(StepElement_SequenceOfElementMaterial, Standard_Transient):
     @overload
     def __init__(self) -> None: ...
     @overload
-    def __init__(self, other: NCollection_Sequence<opencascade::handle<StepElement_ElementMaterial>>) -> None: ...
-    def Sequence(self) -> NCollection_Sequence<opencascade::handle<StepElement_ElementMaterial>>: ...
-    def Append(self, theSequence: NCollection_Sequence<opencascade::handle<StepElement_ElementMaterial>>) -> None: ...
+    def __init__(self, other: StepElement_SequenceOfElementMaterial) -> None: ...
+    def Sequence(self) -> StepElement_SequenceOfElementMaterial: ...
+    def Append(self, theSequence: StepElement_SequenceOfElementMaterial) -> None: ...
 
 
-class StepElement_HSequenceOfSurfaceElementPurposeMember(NCollection_Sequence<opencascade::handle<StepElement_SurfaceElementPurposeMember>>, Standard_Transient):
+class StepElement_HSequenceOfSurfaceElementPurposeMember(StepElement_SequenceOfSurfaceElementPurposeMember, Standard_Transient):
     @overload
     def __init__(self) -> None: ...
     @overload
-    def __init__(self, other: NCollection_Sequence<opencascade::handle<StepElement_SurfaceElementPurposeMember>>) -> None: ...
-    def Sequence(self) -> NCollection_Sequence<opencascade::handle<StepElement_SurfaceElementPurposeMember>>: ...
-    def Append(self, theSequence: NCollection_Sequence<opencascade::handle<StepElement_SurfaceElementPurposeMember>>) -> None: ...
+    def __init__(self, other: StepElement_SequenceOfSurfaceElementPurposeMember) -> None: ...
+    def Sequence(self) -> StepElement_SequenceOfSurfaceElementPurposeMember: ...
+    def Append(self, theSequence: StepElement_SequenceOfSurfaceElementPurposeMember) -> None: ...
 
 
