--- src/SWIG_files/wrapper/TColStd.pyi.orig	2026-08-09 14:32:48 UTC
+++ src/SWIG_files/wrapper/TColStd.pyi
@@ -1,5 +1,5 @@ from enum import IntEnum
 from enum import IntEnum
-from typing import overload, NewType, Optional, Tuple
+from typing import Any, overload, NewType, Optional, Tuple
 
 from OCC.Core.Standard import *
 from OCC.Core.NCollection import *
@@ -481,153 +481,153 @@ class TColStd_HPackedMapOfInteger(Standard_Transient):
 
 # harray1 classes
 
-class TColStd_HArray1OfCharacter(NCollection_Array1<char>, Standard_Transient):
+class TColStd_HArray1OfCharacter(TColStd_Array1OfCharacter, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<char>: ...
+    def Array1(self) -> TColStd_Array1OfCharacter: ...
 
 
-class TColStd_HArray1OfReal(NCollection_Array1<double>, Standard_Transient):
+class TColStd_HArray1OfReal(Any, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<double>: ...
+    def Array1(self) -> Any: ...
 
 
-class TColStd_HArray1OfByte(NCollection_Array1<uint8_t>, Standard_Transient):
+class TColStd_HArray1OfByte(TColStd_Array1OfByte, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<uint8_t>: ...
+    def Array1(self) -> TColStd_Array1OfByte: ...
 
 
-class TColStd_HArray1OfBoolean(NCollection_Array1<bool>, Standard_Transient):
+class TColStd_HArray1OfBoolean(TColStd_Array1OfBoolean, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<bool>: ...
+    def Array1(self) -> TColStd_Array1OfBoolean: ...
 
 
-class TColStd_HArray1OfInteger(NCollection_Array1<int>, Standard_Transient):
+class TColStd_HArray1OfInteger(Any, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<int>: ...
+    def Array1(self) -> Any: ...
 
 
-class TColStd_HArray1OfAsciiString(NCollection_Array1<TCollection_AsciiString>, Standard_Transient):
+class TColStd_HArray1OfAsciiString(TColStd_Array1OfAsciiString, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<TCollection_AsciiString>: ...
+    def Array1(self) -> TColStd_Array1OfAsciiString: ...
 
 
-class TColStd_HArray1OfTransient(NCollection_Array1<opencascade::handle<Standard_Transient>>, Standard_Transient):
+class TColStd_HArray1OfTransient(TColStd_Array1OfTransient, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<opencascade::handle<Standard_Transient>>: ...
+    def Array1(self) -> TColStd_Array1OfTransient: ...
 
 
-class TColStd_HArray1OfListOfInteger(NCollection_Array1<TColStd_ListOfInteger>, Standard_Transient):
+class TColStd_HArray1OfListOfInteger(Any, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<TColStd_ListOfInteger>: ...
+    def Array1(self) -> Any: ...
 
 
-class TColStd_HArray1OfExtendedString(NCollection_Array1<TCollection_ExtendedString>, Standard_Transient):
+class TColStd_HArray1OfExtendedString(TColStd_Array1OfExtendedString, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<TCollection_ExtendedString>: ...
+    def Array1(self) -> TColStd_Array1OfExtendedString: ...
 
 # harray2 classes
 
-class TColStd_HArray2OfReal(NCollection_Array2<double>, Standard_Transient):
+class TColStd_HArray2OfReal(Any, Standard_Transient):
     @overload
     def __init__(self, theRowLow: int, theRowUpp: int, theColLow: int, theColUpp: int) -> None: ...
     @overload
-    def __init__(self, theOther: NCollection_Array2<double>) -> None: ...
-    def Array2(self) -> NCollection_Array2<double>: ...
+    def __init__(self, theOther: Any) -> None: ...
+    def Array2(self) -> Any: ...
 
 
-class TColStd_HArray2OfInteger(NCollection_Array2<int>, Standard_Transient):
+class TColStd_HArray2OfInteger(Any, Standard_Transient):
     @overload
     def __init__(self, theRowLow: int, theRowUpp: int, theColLow: int, theColUpp: int) -> None: ...
     @overload
-    def __init__(self, theOther: NCollection_Array2<int>) -> None: ...
-    def Array2(self) -> NCollection_Array2<int>: ...
+    def __init__(self, theOther: Any) -> None: ...
+    def Array2(self) -> Any: ...
 
 
-class TColStd_HArray2OfTransient(NCollection_Array2<opencascade::handle<Standard_Transient>>, Standard_Transient):
+class TColStd_HArray2OfTransient(TColStd_Array2OfTransient, Standard_Transient):
     @overload
     def __init__(self, theRowLow: int, theRowUpp: int, theColLow: int, theColUpp: int) -> None: ...
     @overload
-    def __init__(self, theOther: NCollection_Array2<opencascade::handle<Standard_Transient>>) -> None: ...
-    def Array2(self) -> NCollection_Array2<opencascade::handle<Standard_Transient>>: ...
+    def __init__(self, theOther: TColStd_Array2OfTransient) -> None: ...
+    def Array2(self) -> TColStd_Array2OfTransient: ...
 
 
-class TColStd_HArray2OfBoolean(NCollection_Array2<bool>, Standard_Transient):
+class TColStd_HArray2OfBoolean(TColStd_Array2OfBoolean, Standard_Transient):
     @overload
     def __init__(self, theRowLow: int, theRowUpp: int, theColLow: int, theColUpp: int) -> None: ...
     @overload
-    def __init__(self, theOther: NCollection_Array2<bool>) -> None: ...
-    def Array2(self) -> NCollection_Array2<bool>: ...
+    def __init__(self, theOther: TColStd_Array2OfBoolean) -> None: ...
+    def Array2(self) -> TColStd_Array2OfBoolean: ...
 
 
-class TColStd_HArray2OfCharacter(NCollection_Array2<char>, Standard_Transient):
+class TColStd_HArray2OfCharacter(TColStd_Array2OfCharacter, Standard_Transient):
     @overload
     def __init__(self, theRowLow: int, theRowUpp: int, theColLow: int, theColUpp: int) -> None: ...
     @overload
-    def __init__(self, theOther: NCollection_Array2<char>) -> None: ...
-    def Array2(self) -> NCollection_Array2<char>: ...
+    def __init__(self, theOther: TColStd_Array2OfCharacter) -> None: ...
+    def Array2(self) -> TColStd_Array2OfCharacter: ...
 
 # hsequence classes
 
-class TColStd_HSequenceOfReal(NCollection_Sequence<double>, Standard_Transient):
+class TColStd_HSequenceOfReal(TColStd_SequenceOfReal, Standard_Transient):
     @overload
     def __init__(self) -> None: ...
     @overload
-    def __init__(self, other: NCollection_Sequence<double>) -> None: ...
-    def Sequence(self) -> NCollection_Sequence<double>: ...
-    def Append(self, theSequence: NCollection_Sequence<double>) -> None: ...
+    def __init__(self, other: TColStd_SequenceOfReal) -> None: ...
+    def Sequence(self) -> TColStd_SequenceOfReal: ...
+    def Append(self, theSequence: TColStd_SequenceOfReal) -> None: ...
 
 
-class TColStd_HSequenceOfTransient(NCollection_Sequence<opencascade::handle<Standard_Transient>>, Standard_Transient):
+class TColStd_HSequenceOfTransient(TColStd_SequenceOfTransient, Standard_Transient):
     @overload
     def __init__(self) -> None: ...
     @overload
-    def __init__(self, other: NCollection_Sequence<opencascade::handle<Standard_Transient>>) -> None: ...
-    def Sequence(self) -> NCollection_Sequence<opencascade::handle<Standard_Transient>>: ...
-    def Append(self, theSequence: NCollection_Sequence<opencascade::handle<Standard_Transient>>) -> None: ...
+    def __init__(self, other: TColStd_SequenceOfTransient) -> None: ...
+    def Sequence(self) -> TColStd_SequenceOfTransient: ...
+    def Append(self, theSequence: TColStd_SequenceOfTransient) -> None: ...
 
 
-class TColStd_HSequenceOfInteger(NCollection_Sequence<int>, Standard_Transient):
+class TColStd_HSequenceOfInteger(TColStd_SequenceOfInteger, Standard_Transient):
     @overload
     def __init__(self) -> None: ...
     @overload
-    def __init__(self, other: NCollection_Sequence<int>) -> None: ...
-    def Sequence(self) -> NCollection_Sequence<int>: ...
-    def Append(self, theSequence: NCollection_Sequence<int>) -> None: ...
+    def __init__(self, other: TColStd_SequenceOfInteger) -> None: ...
+    def Sequence(self) -> TColStd_SequenceOfInteger: ...
+    def Append(self, theSequence: TColStd_SequenceOfInteger) -> None: ...
 
 
-class TColStd_HSequenceOfExtendedString(NCollection_Sequence<TCollection_ExtendedString>, Standard_Transient):
+class TColStd_HSequenceOfExtendedString(TColStd_SequenceOfExtendedString, Standard_Transient):
     @overload
     def __init__(self) -> None: ...
     @overload
-    def __init__(self, other: NCollection_Sequence<TCollection_ExtendedString>) -> None: ...
-    def Sequence(self) -> NCollection_Sequence<TCollection_ExtendedString>: ...
-    def Append(self, theSequence: NCollection_Sequence<TCollection_ExtendedString>) -> None: ...
+    def __init__(self, other: TColStd_SequenceOfExtendedString) -> None: ...
+    def Sequence(self) -> TColStd_SequenceOfExtendedString: ...
+    def Append(self, theSequence: TColStd_SequenceOfExtendedString) -> None: ...
 
 
-class TColStd_HSequenceOfHAsciiString(NCollection_Sequence<opencascade::handle<TCollection_HAsciiString>>, Standard_Transient):
+class TColStd_HSequenceOfHAsciiString(TColStd_SequenceOfHAsciiString, Standard_Transient):
     @overload
     def __init__(self) -> None: ...
     @overload
-    def __init__(self, other: NCollection_Sequence<opencascade::handle<TCollection_HAsciiString>>) -> None: ...
-    def Sequence(self) -> NCollection_Sequence<opencascade::handle<TCollection_HAsciiString>>: ...
-    def Append(self, theSequence: NCollection_Sequence<opencascade::handle<TCollection_HAsciiString>>) -> None: ...
+    def __init__(self, other: TColStd_SequenceOfHAsciiString) -> None: ...
+    def Sequence(self) -> TColStd_SequenceOfHAsciiString: ...
+    def Append(self, theSequence: TColStd_SequenceOfHAsciiString) -> None: ...
 
 
-class TColStd_HSequenceOfHExtendedString(NCollection_Sequence<opencascade::handle<TCollection_HExtendedString>>, Standard_Transient):
+class TColStd_HSequenceOfHExtendedString(TColStd_SequenceOfHExtendedString, Standard_Transient):
     @overload
     def __init__(self) -> None: ...
     @overload
-    def __init__(self, other: NCollection_Sequence<opencascade::handle<TCollection_HExtendedString>>) -> None: ...
-    def Sequence(self) -> NCollection_Sequence<opencascade::handle<TCollection_HExtendedString>>: ...
-    def Append(self, theSequence: NCollection_Sequence<opencascade::handle<TCollection_HExtendedString>>) -> None: ...
+    def __init__(self, other: TColStd_SequenceOfHExtendedString) -> None: ...
+    def Sequence(self) -> TColStd_SequenceOfHExtendedString: ...
+    def Append(self, theSequence: TColStd_SequenceOfHExtendedString) -> None: ...
 
 
-class TColStd_HSequenceOfAsciiString(NCollection_Sequence<TCollection_AsciiString>, Standard_Transient):
+class TColStd_HSequenceOfAsciiString(TColStd_SequenceOfAsciiString, Standard_Transient):
     @overload
     def __init__(self) -> None: ...
     @overload
-    def __init__(self, other: NCollection_Sequence<TCollection_AsciiString>) -> None: ...
-    def Sequence(self) -> NCollection_Sequence<TCollection_AsciiString>: ...
-    def Append(self, theSequence: NCollection_Sequence<TCollection_AsciiString>) -> None: ...
+    def __init__(self, other: TColStd_SequenceOfAsciiString) -> None: ...
+    def Sequence(self) -> TColStd_SequenceOfAsciiString: ...
+    def Append(self, theSequence: TColStd_SequenceOfAsciiString) -> None: ...
 
 
