--- src/SWIG_files/wrapper/StepAP203.pyi.orig	2026-08-09 14:32:48 UTC
+++ src/SWIG_files/wrapper/StepAP203.pyi
@@ -1,5 +1,5 @@ from enum import IntEnum
 from enum import IntEnum
-from typing import overload, NewType, Optional, Tuple
+from typing import Any, overload, NewType, Optional, Tuple
 
 from OCC.Core.Standard import *
 from OCC.Core.NCollection import *
@@ -394,54 +394,54 @@ class StepAP203_WorkItem(StepData_SelectType):
 
 # harray1 classes
 
-class StepAP203_HArray1OfApprovedItem(NCollection_Array1<StepAP203_ApprovedItem>, Standard_Transient):
+class StepAP203_HArray1OfApprovedItem(StepAP203_Array1OfApprovedItem, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepAP203_ApprovedItem>: ...
+    def Array1(self) -> StepAP203_Array1OfApprovedItem: ...
 
 
-class StepAP203_HArray1OfCertifiedItem(NCollection_Array1<StepAP203_CertifiedItem>, Standard_Transient):
+class StepAP203_HArray1OfCertifiedItem(StepAP203_Array1OfCertifiedItem, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepAP203_CertifiedItem>: ...
+    def Array1(self) -> StepAP203_Array1OfCertifiedItem: ...
 
 
-class StepAP203_HArray1OfChangeRequestItem(NCollection_Array1<StepAP203_ChangeRequestItem>, Standard_Transient):
+class StepAP203_HArray1OfChangeRequestItem(StepAP203_Array1OfChangeRequestItem, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepAP203_ChangeRequestItem>: ...
+    def Array1(self) -> StepAP203_Array1OfChangeRequestItem: ...
 
 
-class StepAP203_HArray1OfClassifiedItem(NCollection_Array1<StepAP203_ClassifiedItem>, Standard_Transient):
+class StepAP203_HArray1OfClassifiedItem(StepAP203_Array1OfClassifiedItem, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepAP203_ClassifiedItem>: ...
+    def Array1(self) -> StepAP203_Array1OfClassifiedItem: ...
 
 
-class StepAP203_HArray1OfContractedItem(NCollection_Array1<StepAP203_ContractedItem>, Standard_Transient):
+class StepAP203_HArray1OfContractedItem(StepAP203_Array1OfContractedItem, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepAP203_ContractedItem>: ...
+    def Array1(self) -> StepAP203_Array1OfContractedItem: ...
 
 
-class StepAP203_HArray1OfDateTimeItem(NCollection_Array1<StepAP203_DateTimeItem>, Standard_Transient):
+class StepAP203_HArray1OfDateTimeItem(StepAP203_Array1OfDateTimeItem, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepAP203_DateTimeItem>: ...
+    def Array1(self) -> StepAP203_Array1OfDateTimeItem: ...
 
 
-class StepAP203_HArray1OfPersonOrganizationItem(NCollection_Array1<StepAP203_PersonOrganizationItem>, Standard_Transient):
+class StepAP203_HArray1OfPersonOrganizationItem(StepAP203_Array1OfPersonOrganizationItem, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepAP203_PersonOrganizationItem>: ...
+    def Array1(self) -> StepAP203_Array1OfPersonOrganizationItem: ...
 
 
-class StepAP203_HArray1OfSpecifiedItem(NCollection_Array1<StepAP203_SpecifiedItem>, Standard_Transient):
+class StepAP203_HArray1OfSpecifiedItem(StepAP203_Array1OfSpecifiedItem, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepAP203_SpecifiedItem>: ...
+    def Array1(self) -> StepAP203_Array1OfSpecifiedItem: ...
 
 
-class StepAP203_HArray1OfStartRequestItem(NCollection_Array1<StepAP203_StartRequestItem>, Standard_Transient):
+class StepAP203_HArray1OfStartRequestItem(StepAP203_Array1OfStartRequestItem, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepAP203_StartRequestItem>: ...
+    def Array1(self) -> StepAP203_Array1OfStartRequestItem: ...
 
 
-class StepAP203_HArray1OfWorkItem(NCollection_Array1<StepAP203_WorkItem>, Standard_Transient):
+class StepAP203_HArray1OfWorkItem(StepAP203_Array1OfWorkItem, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepAP203_WorkItem>: ...
+    def Array1(self) -> StepAP203_Array1OfWorkItem: ...
 
 # harray2 classes
 # hsequence classes
