--- src/SWIG_files/wrapper/ShapeAnalysis.pyi.orig	2026-08-09 14:32:48 UTC
+++ src/SWIG_files/wrapper/ShapeAnalysis.pyi
@@ -1,5 +1,5 @@ from enum import IntEnum
 from enum import IntEnum
-from typing import overload, NewType, Optional, Tuple
+from typing import Any, overload, NewType, Optional, Tuple
 
 from OCC.Core.Standard import *
 from OCC.Core.NCollection import *
@@ -539,12 +539,12 @@ class ShapeCustom_ConvertToRevolution: ...
 # harray2 classes
 # hsequence classes
 
-class ShapeAnalysis_HSequenceOfFreeBounds(NCollection_Sequence<opencascade::handle<ShapeAnalysis_FreeBoundData>>, Standard_Transient):
+class ShapeAnalysis_HSequenceOfFreeBounds(ShapeAnalysis_SequenceOfFreeBounds, Standard_Transient):
     @overload
     def __init__(self) -> None: ...
     @overload
-    def __init__(self, other: NCollection_Sequence<opencascade::handle<ShapeAnalysis_FreeBoundData>>) -> None: ...
-    def Sequence(self) -> NCollection_Sequence<opencascade::handle<ShapeAnalysis_FreeBoundData>>: ...
-    def Append(self, theSequence: NCollection_Sequence<opencascade::handle<ShapeAnalysis_FreeBoundData>>) -> None: ...
+    def __init__(self, other: ShapeAnalysis_SequenceOfFreeBounds) -> None: ...
+    def Sequence(self) -> ShapeAnalysis_SequenceOfFreeBounds: ...
+    def Append(self, theSequence: ShapeAnalysis_SequenceOfFreeBounds) -> None: ...
 
 
