--- src/SWIG_files/wrapper/TColgp.pyi.orig	2026-08-09 14:32:48 UTC
+++ src/SWIG_files/wrapper/TColgp.pyi
@@ -1,5 +1,5 @@ from enum import IntEnum
 from enum import IntEnum
-from typing import overload, NewType, Optional, Tuple
+from typing import Any, overload, NewType, Optional, Tuple
 
 from OCC.Core.Standard import *
 from OCC.Core.NCollection import *
@@ -473,207 +473,207 @@ class TColgp_SequenceOfXYZ:
 
 # harray1 classes
 
-class TColgp_HArray1OfLin2d(NCollection_Array1<gp_Lin2d>, Standard_Transient):
+class TColgp_HArray1OfLin2d(TColgp_Array1OfLin2d, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<gp_Lin2d>: ...
+    def Array1(self) -> TColgp_Array1OfLin2d: ...
 
 
-class TColgp_HArray1OfVec2d(NCollection_Array1<gp_Vec2d>, Standard_Transient):
+class TColgp_HArray1OfVec2d(Any, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<gp_Vec2d>: ...
+    def Array1(self) -> Any: ...
 
 
-class TColgp_HArray1OfXY(NCollection_Array1<gp_XY>, Standard_Transient):
+class TColgp_HArray1OfXY(Any, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<gp_XY>: ...
+    def Array1(self) -> Any: ...
 
 
-class TColgp_HArray1OfPnt(NCollection_Array1<gp_Pnt>, Standard_Transient):
+class TColgp_HArray1OfPnt(Any, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<gp_Pnt>: ...
+    def Array1(self) -> Any: ...
 
 
-class TColgp_HArray1OfXYZ(NCollection_Array1<gp_XYZ>, Standard_Transient):
+class TColgp_HArray1OfXYZ(Any, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<gp_XYZ>: ...
+    def Array1(self) -> Any: ...
 
 
-class TColgp_HArray1OfDir2d(NCollection_Array1<gp_Dir2d>, Standard_Transient):
+class TColgp_HArray1OfDir2d(Any, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<gp_Dir2d>: ...
+    def Array1(self) -> Any: ...
 
 
-class TColgp_HArray1OfVec(NCollection_Array1<gp_Vec>, Standard_Transient):
+class TColgp_HArray1OfVec(Any, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<gp_Vec>: ...
+    def Array1(self) -> Any: ...
 
 
-class TColgp_HArray1OfDir(NCollection_Array1<gp_Dir>, Standard_Transient):
+class TColgp_HArray1OfDir(Any, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<gp_Dir>: ...
+    def Array1(self) -> Any: ...
 
 
-class TColgp_HArray1OfPnt2d(NCollection_Array1<gp_Pnt2d>, Standard_Transient):
+class TColgp_HArray1OfPnt2d(Any, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<gp_Pnt2d>: ...
+    def Array1(self) -> Any: ...
 
 
-class TColgp_HArray1OfCirc2d(NCollection_Array1<gp_Circ2d>, Standard_Transient):
+class TColgp_HArray1OfCirc2d(TColgp_Array1OfCirc2d, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<gp_Circ2d>: ...
+    def Array1(self) -> TColgp_Array1OfCirc2d: ...
 
 # harray2 classes
 
-class TColgp_HArray2OfDir2d(NCollection_Array2<gp_Dir2d>, Standard_Transient):
+class TColgp_HArray2OfDir2d(Any, Standard_Transient):
     @overload
     def __init__(self, theRowLow: int, theRowUpp: int, theColLow: int, theColUpp: int) -> None: ...
     @overload
-    def __init__(self, theOther: NCollection_Array2<gp_Dir2d>) -> None: ...
-    def Array2(self) -> NCollection_Array2<gp_Dir2d>: ...
+    def __init__(self, theOther: Any) -> None: ...
+    def Array2(self) -> Any: ...
 
 
-class TColgp_HArray2OfVec2d(NCollection_Array2<gp_Vec2d>, Standard_Transient):
+class TColgp_HArray2OfVec2d(Any, Standard_Transient):
     @overload
     def __init__(self, theRowLow: int, theRowUpp: int, theColLow: int, theColUpp: int) -> None: ...
     @overload
-    def __init__(self, theOther: NCollection_Array2<gp_Vec2d>) -> None: ...
-    def Array2(self) -> NCollection_Array2<gp_Vec2d>: ...
+    def __init__(self, theOther: Any) -> None: ...
+    def Array2(self) -> Any: ...
 
 
-class TColgp_HArray2OfVec(NCollection_Array2<gp_Vec>, Standard_Transient):
+class TColgp_HArray2OfVec(Any, Standard_Transient):
     @overload
     def __init__(self, theRowLow: int, theRowUpp: int, theColLow: int, theColUpp: int) -> None: ...
     @overload
-    def __init__(self, theOther: NCollection_Array2<gp_Vec>) -> None: ...
-    def Array2(self) -> NCollection_Array2<gp_Vec>: ...
+    def __init__(self, theOther: Any) -> None: ...
+    def Array2(self) -> Any: ...
 
 
-class TColgp_HArray2OfPnt2d(NCollection_Array2<gp_Pnt2d>, Standard_Transient):
+class TColgp_HArray2OfPnt2d(Any, Standard_Transient):
     @overload
     def __init__(self, theRowLow: int, theRowUpp: int, theColLow: int, theColUpp: int) -> None: ...
     @overload
-    def __init__(self, theOther: NCollection_Array2<gp_Pnt2d>) -> None: ...
-    def Array2(self) -> NCollection_Array2<gp_Pnt2d>: ...
+    def __init__(self, theOther: Any) -> None: ...
+    def Array2(self) -> Any: ...
 
 
-class TColgp_HArray2OfPnt(NCollection_Array2<gp_Pnt>, Standard_Transient):
+class TColgp_HArray2OfPnt(Any, Standard_Transient):
     @overload
     def __init__(self, theRowLow: int, theRowUpp: int, theColLow: int, theColUpp: int) -> None: ...
     @overload
-    def __init__(self, theOther: NCollection_Array2<gp_Pnt>) -> None: ...
-    def Array2(self) -> NCollection_Array2<gp_Pnt>: ...
+    def __init__(self, theOther: Any) -> None: ...
+    def Array2(self) -> Any: ...
 
 
-class TColgp_HArray2OfXYZ(NCollection_Array2<gp_XYZ>, Standard_Transient):
+class TColgp_HArray2OfXYZ(Any, Standard_Transient):
     @overload
     def __init__(self, theRowLow: int, theRowUpp: int, theColLow: int, theColUpp: int) -> None: ...
     @overload
-    def __init__(self, theOther: NCollection_Array2<gp_XYZ>) -> None: ...
-    def Array2(self) -> NCollection_Array2<gp_XYZ>: ...
+    def __init__(self, theOther: Any) -> None: ...
+    def Array2(self) -> Any: ...
 
 
-class TColgp_HArray2OfLin2d(NCollection_Array2<gp_Lin2d>, Standard_Transient):
+class TColgp_HArray2OfLin2d(TColgp_Array2OfLin2d, Standard_Transient):
     @overload
     def __init__(self, theRowLow: int, theRowUpp: int, theColLow: int, theColUpp: int) -> None: ...
     @overload
-    def __init__(self, theOther: NCollection_Array2<gp_Lin2d>) -> None: ...
-    def Array2(self) -> NCollection_Array2<gp_Lin2d>: ...
+    def __init__(self, theOther: TColgp_Array2OfLin2d) -> None: ...
+    def Array2(self) -> TColgp_Array2OfLin2d: ...
 
 
-class TColgp_HArray2OfXY(NCollection_Array2<gp_XY>, Standard_Transient):
+class TColgp_HArray2OfXY(Any, Standard_Transient):
     @overload
     def __init__(self, theRowLow: int, theRowUpp: int, theColLow: int, theColUpp: int) -> None: ...
     @overload
-    def __init__(self, theOther: NCollection_Array2<gp_XY>) -> None: ...
-    def Array2(self) -> NCollection_Array2<gp_XY>: ...
+    def __init__(self, theOther: Any) -> None: ...
+    def Array2(self) -> Any: ...
 
 
-class TColgp_HArray2OfDir(NCollection_Array2<gp_Dir>, Standard_Transient):
+class TColgp_HArray2OfDir(Any, Standard_Transient):
     @overload
     def __init__(self, theRowLow: int, theRowUpp: int, theColLow: int, theColUpp: int) -> None: ...
     @overload
-    def __init__(self, theOther: NCollection_Array2<gp_Dir>) -> None: ...
-    def Array2(self) -> NCollection_Array2<gp_Dir>: ...
+    def __init__(self, theOther: Any) -> None: ...
+    def Array2(self) -> Any: ...
 
 
-class TColgp_HArray2OfCirc2d(NCollection_Array2<gp_Circ2d>, Standard_Transient):
+class TColgp_HArray2OfCirc2d(TColgp_Array2OfCirc2d, Standard_Transient):
     @overload
     def __init__(self, theRowLow: int, theRowUpp: int, theColLow: int, theColUpp: int) -> None: ...
     @overload
-    def __init__(self, theOther: NCollection_Array2<gp_Circ2d>) -> None: ...
-    def Array2(self) -> NCollection_Array2<gp_Circ2d>: ...
+    def __init__(self, theOther: TColgp_Array2OfCirc2d) -> None: ...
+    def Array2(self) -> TColgp_Array2OfCirc2d: ...
 
 # hsequence classes
 
-class TColgp_HSequenceOfXY(NCollection_Sequence<gp_XY>, Standard_Transient):
+class TColgp_HSequenceOfXY(TColgp_SequenceOfXY, Standard_Transient):
     @overload
     def __init__(self) -> None: ...
     @overload
-    def __init__(self, other: NCollection_Sequence<gp_XY>) -> None: ...
-    def Sequence(self) -> NCollection_Sequence<gp_XY>: ...
-    def Append(self, theSequence: NCollection_Sequence<gp_XY>) -> None: ...
+    def __init__(self, other: TColgp_SequenceOfXY) -> None: ...
+    def Sequence(self) -> TColgp_SequenceOfXY: ...
+    def Append(self, theSequence: TColgp_SequenceOfXY) -> None: ...
 
 
-class TColgp_HSequenceOfPnt2d(NCollection_Sequence<gp_Pnt2d>, Standard_Transient):
+class TColgp_HSequenceOfPnt2d(TColgp_SequenceOfPnt2d, Standard_Transient):
     @overload
     def __init__(self) -> None: ...
     @overload
-    def __init__(self, other: NCollection_Sequence<gp_Pnt2d>) -> None: ...
-    def Sequence(self) -> NCollection_Sequence<gp_Pnt2d>: ...
-    def Append(self, theSequence: NCollection_Sequence<gp_Pnt2d>) -> None: ...
+    def __init__(self, other: TColgp_SequenceOfPnt2d) -> None: ...
+    def Sequence(self) -> TColgp_SequenceOfPnt2d: ...
+    def Append(self, theSequence: TColgp_SequenceOfPnt2d) -> None: ...
 
 
-class TColgp_HSequenceOfDir2d(NCollection_Sequence<gp_Dir2d>, Standard_Transient):
+class TColgp_HSequenceOfDir2d(TColgp_SequenceOfDir2d, Standard_Transient):
     @overload
     def __init__(self) -> None: ...
     @overload
-    def __init__(self, other: NCollection_Sequence<gp_Dir2d>) -> None: ...
-    def Sequence(self) -> NCollection_Sequence<gp_Dir2d>: ...
-    def Append(self, theSequence: NCollection_Sequence<gp_Dir2d>) -> None: ...
+    def __init__(self, other: TColgp_SequenceOfDir2d) -> None: ...
+    def Sequence(self) -> TColgp_SequenceOfDir2d: ...
+    def Append(self, theSequence: TColgp_SequenceOfDir2d) -> None: ...
 
 
-class TColgp_HSequenceOfPnt(NCollection_Sequence<gp_Pnt>, Standard_Transient):
+class TColgp_HSequenceOfPnt(TColgp_SequenceOfPnt, Standard_Transient):
     @overload
     def __init__(self) -> None: ...
     @overload
-    def __init__(self, other: NCollection_Sequence<gp_Pnt>) -> None: ...
-    def Sequence(self) -> NCollection_Sequence<gp_Pnt>: ...
-    def Append(self, theSequence: NCollection_Sequence<gp_Pnt>) -> None: ...
+    def __init__(self, other: TColgp_SequenceOfPnt) -> None: ...
+    def Sequence(self) -> TColgp_SequenceOfPnt: ...
+    def Append(self, theSequence: TColgp_SequenceOfPnt) -> None: ...
 
 
-class TColgp_HSequenceOfVec(NCollection_Sequence<gp_Vec>, Standard_Transient):
+class TColgp_HSequenceOfVec(TColgp_SequenceOfVec, Standard_Transient):
     @overload
     def __init__(self) -> None: ...
     @overload
-    def __init__(self, other: NCollection_Sequence<gp_Vec>) -> None: ...
-    def Sequence(self) -> NCollection_Sequence<gp_Vec>: ...
-    def Append(self, theSequence: NCollection_Sequence<gp_Vec>) -> None: ...
+    def __init__(self, other: TColgp_SequenceOfVec) -> None: ...
+    def Sequence(self) -> TColgp_SequenceOfVec: ...
+    def Append(self, theSequence: TColgp_SequenceOfVec) -> None: ...
 
 
-class TColgp_HSequenceOfXYZ(NCollection_Sequence<gp_XYZ>, Standard_Transient):
+class TColgp_HSequenceOfXYZ(TColgp_SequenceOfXYZ, Standard_Transient):
     @overload
     def __init__(self) -> None: ...
     @overload
-    def __init__(self, other: NCollection_Sequence<gp_XYZ>) -> None: ...
-    def Sequence(self) -> NCollection_Sequence<gp_XYZ>: ...
-    def Append(self, theSequence: NCollection_Sequence<gp_XYZ>) -> None: ...
+    def __init__(self, other: TColgp_SequenceOfXYZ) -> None: ...
+    def Sequence(self) -> TColgp_SequenceOfXYZ: ...
+    def Append(self, theSequence: TColgp_SequenceOfXYZ) -> None: ...
 
 
-class TColgp_HSequenceOfDir(NCollection_Sequence<gp_Dir>, Standard_Transient):
+class TColgp_HSequenceOfDir(TColgp_SequenceOfDir, Standard_Transient):
     @overload
     def __init__(self) -> None: ...
     @overload
-    def __init__(self, other: NCollection_Sequence<gp_Dir>) -> None: ...
-    def Sequence(self) -> NCollection_Sequence<gp_Dir>: ...
-    def Append(self, theSequence: NCollection_Sequence<gp_Dir>) -> None: ...
+    def __init__(self, other: TColgp_SequenceOfDir) -> None: ...
+    def Sequence(self) -> TColgp_SequenceOfDir: ...
+    def Append(self, theSequence: TColgp_SequenceOfDir) -> None: ...
 
 
-class TColgp_HSequenceOfVec2d(NCollection_Sequence<gp_Vec2d>, Standard_Transient):
+class TColgp_HSequenceOfVec2d(TColgp_SequenceOfVec2d, Standard_Transient):
     @overload
     def __init__(self) -> None: ...
     @overload
-    def __init__(self, other: NCollection_Sequence<gp_Vec2d>) -> None: ...
-    def Sequence(self) -> NCollection_Sequence<gp_Vec2d>: ...
-    def Append(self, theSequence: NCollection_Sequence<gp_Vec2d>) -> None: ...
+    def __init__(self, other: TColgp_SequenceOfVec2d) -> None: ...
+    def Sequence(self) -> TColgp_SequenceOfVec2d: ...
+    def Append(self, theSequence: TColgp_SequenceOfVec2d) -> None: ...
 
 
