--- src/SWIG_files/wrapper/StepVisual.pyi.orig	2026-08-09 14:32:48 UTC
+++ src/SWIG_files/wrapper/StepVisual.pyi
@@ -1,5 +1,5 @@ from enum import IntEnum
 from enum import IntEnum
-from typing import overload, NewType, Optional, Tuple
+from typing import Any, overload, NewType, Optional, Tuple
 
 from OCC.Core.Standard import *
 from OCC.Core.NCollection import *
@@ -1434,94 +1434,94 @@ class StepVisual_TriangulatedFace(StepVisual_Tessellat
 
 # harray1 classes
 
-class StepVisual_HArray1OfAnnotationPlaneElement(NCollection_Array1<StepVisual_AnnotationPlaneElement>, Standard_Transient):
+class StepVisual_HArray1OfAnnotationPlaneElement(StepVisual_Array1OfAnnotationPlaneElement, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepVisual_AnnotationPlaneElement>: ...
+    def Array1(self) -> StepVisual_Array1OfAnnotationPlaneElement: ...
 
 
-class StepVisual_HArray1OfBoxCharacteristicSelect(NCollection_Array1<StepVisual_BoxCharacteristicSelect>, Standard_Transient):
+class StepVisual_HArray1OfBoxCharacteristicSelect(StepVisual_Array1OfBoxCharacteristicSelect, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepVisual_BoxCharacteristicSelect>: ...
+    def Array1(self) -> StepVisual_Array1OfBoxCharacteristicSelect: ...
 
 
-class StepVisual_HArray1OfCameraModelD3MultiClippingInterectionSelect(NCollection_Array1<StepVisual_CameraModelD3MultiClippingInterectionSelect>, Standard_Transient):
+class StepVisual_HArray1OfCameraModelD3MultiClippingInterectionSelect(StepVisual_Array1OfCameraModelD3MultiClippingInterectionSelect, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepVisual_CameraModelD3MultiClippingInterectionSelect>: ...
+    def Array1(self) -> StepVisual_Array1OfCameraModelD3MultiClippingInterectionSelect: ...
 
 
-class StepVisual_HArray1OfCameraModelD3MultiClippingUnionSelect(NCollection_Array1<StepVisual_CameraModelD3MultiClippingUnionSelect>, Standard_Transient):
+class StepVisual_HArray1OfCameraModelD3MultiClippingUnionSelect(StepVisual_Array1OfCameraModelD3MultiClippingUnionSelect, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepVisual_CameraModelD3MultiClippingUnionSelect>: ...
+    def Array1(self) -> StepVisual_Array1OfCameraModelD3MultiClippingUnionSelect: ...
 
 
-class StepVisual_HArray1OfCurveStyleFontPattern(NCollection_Array1<opencascade::handle<StepVisual_CurveStyleFontPattern>>, Standard_Transient):
+class StepVisual_HArray1OfCurveStyleFontPattern(StepVisual_Array1OfCurveStyleFontPattern, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<opencascade::handle<StepVisual_CurveStyleFontPattern>>: ...
+    def Array1(self) -> StepVisual_Array1OfCurveStyleFontPattern: ...
 
 
-class StepVisual_HArray1OfDirectionCountSelect(NCollection_Array1<StepVisual_DirectionCountSelect>, Standard_Transient):
+class StepVisual_HArray1OfDirectionCountSelect(StepVisual_Array1OfDirectionCountSelect, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepVisual_DirectionCountSelect>: ...
+    def Array1(self) -> StepVisual_Array1OfDirectionCountSelect: ...
 
 
-class StepVisual_HArray1OfDraughtingCalloutElement(NCollection_Array1<StepVisual_DraughtingCalloutElement>, Standard_Transient):
+class StepVisual_HArray1OfDraughtingCalloutElement(StepVisual_Array1OfDraughtingCalloutElement, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepVisual_DraughtingCalloutElement>: ...
+    def Array1(self) -> StepVisual_Array1OfDraughtingCalloutElement: ...
 
 
-class StepVisual_HArray1OfFillStyleSelect(NCollection_Array1<StepVisual_FillStyleSelect>, Standard_Transient):
+class StepVisual_HArray1OfFillStyleSelect(StepVisual_Array1OfFillStyleSelect, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepVisual_FillStyleSelect>: ...
+    def Array1(self) -> StepVisual_Array1OfFillStyleSelect: ...
 
 
-class StepVisual_HArray1OfInvisibleItem(NCollection_Array1<StepVisual_InvisibleItem>, Standard_Transient):
+class StepVisual_HArray1OfInvisibleItem(StepVisual_Array1OfInvisibleItem, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepVisual_InvisibleItem>: ...
+    def Array1(self) -> StepVisual_Array1OfInvisibleItem: ...
 
 
-class StepVisual_HArray1OfLayeredItem(NCollection_Array1<StepVisual_LayeredItem>, Standard_Transient):
+class StepVisual_HArray1OfLayeredItem(StepVisual_Array1OfLayeredItem, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepVisual_LayeredItem>: ...
+    def Array1(self) -> StepVisual_Array1OfLayeredItem: ...
 
 
-class StepVisual_HArray1OfPresentationStyleAssignment(NCollection_Array1<opencascade::handle<StepVisual_PresentationStyleAssignment>>, Standard_Transient):
+class StepVisual_HArray1OfPresentationStyleAssignment(StepVisual_Array1OfPresentationStyleAssignment, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<opencascade::handle<StepVisual_PresentationStyleAssignment>>: ...
+    def Array1(self) -> StepVisual_Array1OfPresentationStyleAssignment: ...
 
 
-class StepVisual_HArray1OfPresentationStyleSelect(NCollection_Array1<StepVisual_PresentationStyleSelect>, Standard_Transient):
+class StepVisual_HArray1OfPresentationStyleSelect(StepVisual_Array1OfPresentationStyleSelect, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepVisual_PresentationStyleSelect>: ...
+    def Array1(self) -> StepVisual_Array1OfPresentationStyleSelect: ...
 
 
-class StepVisual_HArray1OfRenderingPropertiesSelect(NCollection_Array1<StepVisual_RenderingPropertiesSelect>, Standard_Transient):
+class StepVisual_HArray1OfRenderingPropertiesSelect(StepVisual_Array1OfRenderingPropertiesSelect, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepVisual_RenderingPropertiesSelect>: ...
+    def Array1(self) -> StepVisual_Array1OfRenderingPropertiesSelect: ...
 
 
-class StepVisual_HArray1OfStyleContextSelect(NCollection_Array1<StepVisual_StyleContextSelect>, Standard_Transient):
+class StepVisual_HArray1OfStyleContextSelect(StepVisual_Array1OfStyleContextSelect, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepVisual_StyleContextSelect>: ...
+    def Array1(self) -> StepVisual_Array1OfStyleContextSelect: ...
 
 
-class StepVisual_HArray1OfSurfaceStyleElementSelect(NCollection_Array1<StepVisual_SurfaceStyleElementSelect>, Standard_Transient):
+class StepVisual_HArray1OfSurfaceStyleElementSelect(StepVisual_Array1OfSurfaceStyleElementSelect, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepVisual_SurfaceStyleElementSelect>: ...
+    def Array1(self) -> StepVisual_Array1OfSurfaceStyleElementSelect: ...
 
 
-class StepVisual_HArray1OfTessellatedEdgeOrVertex(NCollection_Array1<StepVisual_TessellatedEdgeOrVertex>, Standard_Transient):
+class StepVisual_HArray1OfTessellatedEdgeOrVertex(StepVisual_Array1OfTessellatedEdgeOrVertex, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepVisual_TessellatedEdgeOrVertex>: ...
+    def Array1(self) -> StepVisual_Array1OfTessellatedEdgeOrVertex: ...
 
 
-class StepVisual_HArray1OfTessellatedStructuredItem(NCollection_Array1<opencascade::handle<StepVisual_TessellatedStructuredItem>>, Standard_Transient):
+class StepVisual_HArray1OfTessellatedStructuredItem(StepVisual_Array1OfTessellatedStructuredItem, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<opencascade::handle<StepVisual_TessellatedStructuredItem>>: ...
+    def Array1(self) -> StepVisual_Array1OfTessellatedStructuredItem: ...
 
 
-class StepVisual_HArray1OfTextOrCharacter(NCollection_Array1<StepVisual_TextOrCharacter>, Standard_Transient):
+class StepVisual_HArray1OfTextOrCharacter(StepVisual_Array1OfTextOrCharacter, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepVisual_TextOrCharacter>: ...
+    def Array1(self) -> StepVisual_Array1OfTextOrCharacter: ...
 
 # harray2 classes
 # hsequence classes
