--- src/SWIG_files/wrapper/TopTools.pyi.orig	2026-08-09 14:32:48 UTC
+++ src/SWIG_files/wrapper/TopTools.pyi
@@ -1,5 +1,5 @@ from enum import IntEnum
 from enum import IntEnum
-from typing import overload, NewType, Optional, Tuple
+from typing import Any, overload, NewType, Optional, Tuple
 
 from OCC.Core.Standard import *
 from OCC.Core.NCollection import *
@@ -183,32 +183,32 @@ class TopTools_ShapeSet:
 
 # harray1 classes
 
-class TopTools_HArray1OfShape(NCollection_Array1<TopoDS_Shape>, Standard_Transient):
+class TopTools_HArray1OfShape(TopTools_Array1OfShape, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<TopoDS_Shape>: ...
+    def Array1(self) -> TopTools_Array1OfShape: ...
 
 
-class TopTools_HArray1OfListOfShape(NCollection_Array1<TopTools_ListOfShape>, Standard_Transient):
+class TopTools_HArray1OfListOfShape(Any, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<TopTools_ListOfShape>: ...
+    def Array1(self) -> Any: ...
 
 # harray2 classes
 
-class TopTools_HArray2OfShape(NCollection_Array2<TopoDS_Shape>, Standard_Transient):
+class TopTools_HArray2OfShape(TopTools_Array2OfShape, Standard_Transient):
     @overload
     def __init__(self, theRowLow: int, theRowUpp: int, theColLow: int, theColUpp: int) -> None: ...
     @overload
-    def __init__(self, theOther: NCollection_Array2<TopoDS_Shape>) -> None: ...
-    def Array2(self) -> NCollection_Array2<TopoDS_Shape>: ...
+    def __init__(self, theOther: TopTools_Array2OfShape) -> None: ...
+    def Array2(self) -> TopTools_Array2OfShape: ...
 
 # hsequence classes
 
-class TopTools_HSequenceOfShape(NCollection_Sequence<TopoDS_Shape>, Standard_Transient):
+class TopTools_HSequenceOfShape(TopTools_SequenceOfShape, Standard_Transient):
     @overload
     def __init__(self) -> None: ...
     @overload
-    def __init__(self, other: NCollection_Sequence<TopoDS_Shape>) -> None: ...
-    def Sequence(self) -> NCollection_Sequence<TopoDS_Shape>: ...
-    def Append(self, theSequence: NCollection_Sequence<TopoDS_Shape>) -> None: ...
+    def __init__(self, other: TopTools_SequenceOfShape) -> None: ...
+    def Sequence(self) -> TopTools_SequenceOfShape: ...
+    def Append(self, theSequence: TopTools_SequenceOfShape) -> None: ...
 
 
