--- src/SWIG_files/wrapper/Extrema.pyi.orig	2026-08-09 14:32:48 UTC
+++ src/SWIG_files/wrapper/Extrema.pyi
@@ -1,5 +1,5 @@ from enum import IntEnum
 from enum import IntEnum
-from typing import overload, NewType, Optional, Tuple
+from typing import Any, overload, NewType, Optional, Tuple
 
 from OCC.Core.Standard import *
 from OCC.Core.NCollection import *
@@ -895,44 +895,44 @@ class Extrema_POnSurfParams(Extrema_POnSurf):
 
 # harray1 classes
 
-class Extrema_HArray1OfPOnCurv(NCollection_Array1<Extrema_POnCurv>, Standard_Transient):
+class Extrema_HArray1OfPOnCurv(Extrema_Array1OfPOnCurv, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<Extrema_POnCurv>: ...
+    def Array1(self) -> Extrema_Array1OfPOnCurv: ...
 
 
-class Extrema_HArray1OfPOnCurv2d(NCollection_Array1<Extrema_POnCurv2d>, Standard_Transient):
+class Extrema_HArray1OfPOnCurv2d(Extrema_Array1OfPOnCurv2d, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<Extrema_POnCurv2d>: ...
+    def Array1(self) -> Extrema_Array1OfPOnCurv2d: ...
 
 
-class Extrema_HArray1OfPOnSurf(NCollection_Array1<Extrema_POnSurf>, Standard_Transient):
+class Extrema_HArray1OfPOnSurf(Extrema_Array1OfPOnSurf, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<Extrema_POnSurf>: ...
+    def Array1(self) -> Extrema_Array1OfPOnSurf: ...
 
 # harray2 classes
 
-class Extrema_HArray2OfPOnCurv(NCollection_Array2<Extrema_POnCurv>, Standard_Transient):
+class Extrema_HArray2OfPOnCurv(Any, Standard_Transient):
     @overload
     def __init__(self, theRowLow: int, theRowUpp: int, theColLow: int, theColUpp: int) -> None: ...
     @overload
-    def __init__(self, theOther: NCollection_Array2<Extrema_POnCurv>) -> None: ...
-    def Array2(self) -> NCollection_Array2<Extrema_POnCurv>: ...
+    def __init__(self, theOther: Any) -> None: ...
+    def Array2(self) -> Any: ...
 
 
-class Extrema_HArray2OfPOnCurv2d(NCollection_Array2<Extrema_POnCurv2d>, Standard_Transient):
+class Extrema_HArray2OfPOnCurv2d(Any, Standard_Transient):
     @overload
     def __init__(self, theRowLow: int, theRowUpp: int, theColLow: int, theColUpp: int) -> None: ...
     @overload
-    def __init__(self, theOther: NCollection_Array2<Extrema_POnCurv2d>) -> None: ...
-    def Array2(self) -> NCollection_Array2<Extrema_POnCurv2d>: ...
+    def __init__(self, theOther: Any) -> None: ...
+    def Array2(self) -> Any: ...
 
 
-class Extrema_HArray2OfPOnSurf(NCollection_Array2<Extrema_POnSurf>, Standard_Transient):
+class Extrema_HArray2OfPOnSurf(Any, Standard_Transient):
     @overload
     def __init__(self, theRowLow: int, theRowUpp: int, theColLow: int, theColUpp: int) -> None: ...
     @overload
-    def __init__(self, theOther: NCollection_Array2<Extrema_POnSurf>) -> None: ...
-    def Array2(self) -> NCollection_Array2<Extrema_POnSurf>: ...
+    def __init__(self, theOther: Any) -> None: ...
+    def Array2(self) -> Any: ...
 
 # hsequence classes
 
