--- src/SWIG_files/wrapper/Message.pyi.orig	2026-08-09 14:32:48 UTC
+++ src/SWIG_files/wrapper/Message.pyi
@@ -1,5 +1,5 @@ from enum import IntEnum
 from enum import IntEnum
-from typing import overload, NewType, Optional, Tuple
+from typing import Any, overload, NewType, Optional, Tuple
 
 from OCC.Core.Standard import *
 from OCC.Core.NCollection import *
@@ -449,7 +449,7 @@ class Message_Attribute(Standard_Transient):
     def SetStatus(self, theStat: Message_Status, theMsg: Message_Msg) -> None: ...
 
 class Message_Attribute(Standard_Transient):
-    def __init__(self, theName: Optional[str] = TCollection_AsciiString::EmptyString()) -> None: ...
+    def __init__(self, theName: Optional[str] = ...) -> None: ...
     def DumpJson(self, depth: Optional[int]=-1) -> str: ...
     def GetMessageKey(self) -> str: ...
     def GetName(self) -> str: ...
@@ -507,7 +507,7 @@ class Message_Level:
     def TypeOfStatus(theStatus: Message_Status) -> Message_StatusType: ...
 
 class Message_Level:
-    def __init__(self, theName: Optional[str] = TCollection_AsciiString::EmptyString()) -> None: ...
+    def __init__(self, theName: Optional[str] = ...) -> None: ...
     def AddAlert(self, theGravity: Message_Gravity, theAlert: Message_Alert) -> bool: ...
     def RootAlert(self) -> Message_AlertExtended: ...
     def SetRootAlert(self, theAlert: Message_AlertExtended, isRequiredToStart: bool) -> None: ...
@@ -656,7 +656,7 @@ class Message_AttributeMeter(Message_Attribute):
     def SupportsMerge(self) -> bool: ...
 
 class Message_AttributeMeter(Message_Attribute):
-    def __init__(self, theName: Optional[str] = TCollection_AsciiString::EmptyString()) -> None: ...
+    def __init__(self, theName: Optional[str] = ...) -> None: ...
     def DumpJson(self, depth: Optional[int]=-1) -> str: ...
     def HasMetric(self, theMetric: Message_MetricType) -> bool: ...
     def IsMetricValid(self, theMetric: Message_MetricType) -> bool: ...
@@ -674,7 +674,7 @@ class Message_AttributeObject(Message_Attribute):
     def UndefinedMetricValue() -> False: ...
 
 class Message_AttributeObject(Message_Attribute):
-    def __init__(self, theObject: Standard_Transient, theName: Optional[str] = TCollection_AsciiString::EmptyString()) -> None: ...
+    def __init__(self, theObject: Standard_Transient, theName: Optional[str] = ...) -> None: ...
     def DumpJson(self, depth: Optional[int]=-1) -> str: ...
     def Object(self) -> Standard_Transient: ...
     def SetObject(self, theObject: Standard_Transient) -> None: ...
