--- src/SWIG_files/wrapper/Standard.pyi.orig	2026-08-09 14:32:48 UTC
+++ src/SWIG_files/wrapper/Standard.pyi
@@ -1,5 +1,5 @@ from enum import IntEnum
 from enum import IntEnum
-from typing import overload, NewType, Optional, Tuple
+from typing import Any, overload, NewType, Optional, Tuple
 
 from OCC.Core.NCollection import *
 
@@ -59,7 +59,7 @@ class Standard_ErrorHandler:
 class Standard_ErrorHandler:
     def __init__(self) -> None: ...
     def Destroy(self) -> None: ...
-    def Error(self) -> OSD_SIGBUS,: ...
+    def Error(self) -> Any: ...
     @staticmethod
     def IsInTryBlock() -> bool: ...
     def Raise(self) -> None: ...
