--- src/SWIG_files/wrapper/TColGeom2d.pyi.orig	2026-08-09 14:32:48 UTC
+++ src/SWIG_files/wrapper/TColGeom2d.pyi
@@ -1,5 +1,5 @@ from enum import IntEnum
 from enum import IntEnum
-from typing import overload, NewType, Optional, Tuple
+from typing import Any, overload, NewType, Optional, Tuple
 
 from OCC.Core.Standard import *
 from OCC.Core.NCollection import *
@@ -135,38 +135,38 @@ class TColGeom2d_SequenceOfGeometry:
 
 # harray1 classes
 
-class TColGeom2d_HArray1OfBSplineCurve(NCollection_Array1<opencascade::handle<Geom2d_BSplineCurve>>, Standard_Transient):
+class TColGeom2d_HArray1OfBSplineCurve(TColGeom2d_Array1OfBSplineCurve, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<opencascade::handle<Geom2d_BSplineCurve>>: ...
+    def Array1(self) -> TColGeom2d_Array1OfBSplineCurve: ...
 
 
-class TColGeom2d_HArray1OfBezierCurve(NCollection_Array1<opencascade::handle<Geom2d_BezierCurve>>, Standard_Transient):
+class TColGeom2d_HArray1OfBezierCurve(TColGeom2d_Array1OfBezierCurve, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<opencascade::handle<Geom2d_BezierCurve>>: ...
+    def Array1(self) -> TColGeom2d_Array1OfBezierCurve: ...
 
 
-class TColGeom2d_HArray1OfCurve(NCollection_Array1<opencascade::handle<Geom2d_Curve>>, Standard_Transient):
+class TColGeom2d_HArray1OfCurve(TColGeom2d_Array1OfCurve, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<opencascade::handle<Geom2d_Curve>>: ...
+    def Array1(self) -> TColGeom2d_Array1OfCurve: ...
 
 # harray2 classes
 # hsequence classes
 
-class TColGeom2d_HSequenceOfBoundedCurve(NCollection_Sequence<opencascade::handle<Geom2d_BoundedCurve>>, Standard_Transient):
+class TColGeom2d_HSequenceOfBoundedCurve(TColGeom2d_SequenceOfBoundedCurve, Standard_Transient):
     @overload
     def __init__(self) -> None: ...
     @overload
-    def __init__(self, other: NCollection_Sequence<opencascade::handle<Geom2d_BoundedCurve>>) -> None: ...
-    def Sequence(self) -> NCollection_Sequence<opencascade::handle<Geom2d_BoundedCurve>>: ...
-    def Append(self, theSequence: NCollection_Sequence<opencascade::handle<Geom2d_BoundedCurve>>) -> None: ...
+    def __init__(self, other: TColGeom2d_SequenceOfBoundedCurve) -> None: ...
+    def Sequence(self) -> TColGeom2d_SequenceOfBoundedCurve: ...
+    def Append(self, theSequence: TColGeom2d_SequenceOfBoundedCurve) -> None: ...
 
 
-class TColGeom2d_HSequenceOfCurve(NCollection_Sequence<opencascade::handle<Geom2d_Curve>>, Standard_Transient):
+class TColGeom2d_HSequenceOfCurve(TColGeom2d_SequenceOfCurve, Standard_Transient):
     @overload
     def __init__(self) -> None: ...
     @overload
-    def __init__(self, other: NCollection_Sequence<opencascade::handle<Geom2d_Curve>>) -> None: ...
-    def Sequence(self) -> NCollection_Sequence<opencascade::handle<Geom2d_Curve>>: ...
-    def Append(self, theSequence: NCollection_Sequence<opencascade::handle<Geom2d_Curve>>) -> None: ...
+    def __init__(self, other: TColGeom2d_SequenceOfCurve) -> None: ...
+    def Sequence(self) -> TColGeom2d_SequenceOfCurve: ...
+    def Append(self, theSequence: TColGeom2d_SequenceOfCurve) -> None: ...
 
 
