--- src/SWIG_files/wrapper/StepShape.pyi.orig	2026-08-09 14:32:48 UTC
+++ src/SWIG_files/wrapper/StepShape.pyi
@@ -1,5 +1,5 @@ from enum import IntEnum
 from enum import IntEnum
-from typing import overload, NewType, Optional, Tuple
+from typing import Any, overload, NewType, Optional, Tuple
 
 from OCC.Core.Standard import *
 from OCC.Core.NCollection import *
@@ -991,59 +991,59 @@ class StepShape_SeamEdge(StepShape_OrientedEdge):
 
 # harray1 classes
 
-class StepShape_HArray1OfConnectedEdgeSet(NCollection_Array1<opencascade::handle<StepShape_ConnectedEdgeSet>>, Standard_Transient):
+class StepShape_HArray1OfConnectedEdgeSet(StepShape_Array1OfConnectedEdgeSet, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<opencascade::handle<StepShape_ConnectedEdgeSet>>: ...
+    def Array1(self) -> StepShape_Array1OfConnectedEdgeSet: ...
 
 
-class StepShape_HArray1OfConnectedFaceSet(NCollection_Array1<opencascade::handle<StepShape_ConnectedFaceSet>>, Standard_Transient):
+class StepShape_HArray1OfConnectedFaceSet(StepShape_Array1OfConnectedFaceSet, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<opencascade::handle<StepShape_ConnectedFaceSet>>: ...
+    def Array1(self) -> StepShape_Array1OfConnectedFaceSet: ...
 
 
-class StepShape_HArray1OfEdge(NCollection_Array1<opencascade::handle<StepShape_Edge>>, Standard_Transient):
+class StepShape_HArray1OfEdge(StepShape_Array1OfEdge, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<opencascade::handle<StepShape_Edge>>: ...
+    def Array1(self) -> StepShape_Array1OfEdge: ...
 
 
-class StepShape_HArray1OfFace(NCollection_Array1<opencascade::handle<StepShape_Face>>, Standard_Transient):
+class StepShape_HArray1OfFace(StepShape_Array1OfFace, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<opencascade::handle<StepShape_Face>>: ...
+    def Array1(self) -> StepShape_Array1OfFace: ...
 
 
-class StepShape_HArray1OfFaceBound(NCollection_Array1<opencascade::handle<StepShape_FaceBound>>, Standard_Transient):
+class StepShape_HArray1OfFaceBound(StepShape_Array1OfFaceBound, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<opencascade::handle<StepShape_FaceBound>>: ...
+    def Array1(self) -> StepShape_Array1OfFaceBound: ...
 
 
-class StepShape_HArray1OfGeometricSetSelect(NCollection_Array1<StepShape_GeometricSetSelect>, Standard_Transient):
+class StepShape_HArray1OfGeometricSetSelect(StepShape_Array1OfGeometricSetSelect, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepShape_GeometricSetSelect>: ...
+    def Array1(self) -> StepShape_Array1OfGeometricSetSelect: ...
 
 
-class StepShape_HArray1OfOrientedClosedShell(NCollection_Array1<opencascade::handle<StepShape_OrientedClosedShell>>, Standard_Transient):
+class StepShape_HArray1OfOrientedClosedShell(StepShape_Array1OfOrientedClosedShell, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<opencascade::handle<StepShape_OrientedClosedShell>>: ...
+    def Array1(self) -> StepShape_Array1OfOrientedClosedShell: ...
 
 
-class StepShape_HArray1OfOrientedEdge(NCollection_Array1<opencascade::handle<StepShape_OrientedEdge>>, Standard_Transient):
+class StepShape_HArray1OfOrientedEdge(StepShape_Array1OfOrientedEdge, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<opencascade::handle<StepShape_OrientedEdge>>: ...
+    def Array1(self) -> StepShape_Array1OfOrientedEdge: ...
 
 
-class StepShape_HArray1OfShapeDimensionRepresentationItem(NCollection_Array1<StepShape_ShapeDimensionRepresentationItem>, Standard_Transient):
+class StepShape_HArray1OfShapeDimensionRepresentationItem(StepShape_Array1OfShapeDimensionRepresentationItem, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepShape_ShapeDimensionRepresentationItem>: ...
+    def Array1(self) -> StepShape_Array1OfShapeDimensionRepresentationItem: ...
 
 
-class StepShape_HArray1OfShell(NCollection_Array1<StepShape_Shell>, Standard_Transient):
+class StepShape_HArray1OfShell(StepShape_Array1OfShell, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepShape_Shell>: ...
+    def Array1(self) -> StepShape_Array1OfShell: ...
 
 
-class StepShape_HArray1OfValueQualifier(NCollection_Array1<StepShape_ValueQualifier>, Standard_Transient):
+class StepShape_HArray1OfValueQualifier(StepShape_Array1OfValueQualifier, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepShape_ValueQualifier>: ...
+    def Array1(self) -> StepShape_Array1OfValueQualifier: ...
 
 # harray2 classes
 # hsequence classes
