--- src/SWIG_files/wrapper/StepBasic.pyi.orig	2026-08-09 14:32:48 UTC
+++ src/SWIG_files/wrapper/StepBasic.pyi
@@ -1,5 +1,5 @@ from enum import IntEnum
 from enum import IntEnum
-from typing import overload, NewType, Optional, Tuple
+from typing import Any, overload, NewType, Optional, Tuple
 
 from OCC.Core.Standard import *
 from OCC.Core.NCollection import *
@@ -1520,54 +1520,54 @@ class StepRepr_MakeFromUsageOption: ...
 
 # harray1 classes
 
-class StepBasic_HArray1OfApproval(NCollection_Array1<opencascade::handle<StepBasic_Approval>>, Standard_Transient):
+class StepBasic_HArray1OfApproval(StepBasic_Array1OfApproval, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<opencascade::handle<StepBasic_Approval>>: ...
+    def Array1(self) -> StepBasic_Array1OfApproval: ...
 
 
-class StepBasic_HArray1OfDerivedUnitElement(NCollection_Array1<opencascade::handle<StepBasic_DerivedUnitElement>>, Standard_Transient):
+class StepBasic_HArray1OfDerivedUnitElement(StepBasic_Array1OfDerivedUnitElement, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<opencascade::handle<StepBasic_DerivedUnitElement>>: ...
+    def Array1(self) -> StepBasic_Array1OfDerivedUnitElement: ...
 
 
-class StepBasic_HArray1OfDocument(NCollection_Array1<opencascade::handle<StepBasic_Document>>, Standard_Transient):
+class StepBasic_HArray1OfDocument(StepBasic_Array1OfDocument, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<opencascade::handle<StepBasic_Document>>: ...
+    def Array1(self) -> StepBasic_Array1OfDocument: ...
 
 
-class StepBasic_HArray1OfNamedUnit(NCollection_Array1<opencascade::handle<StepBasic_NamedUnit>>, Standard_Transient):
+class StepBasic_HArray1OfNamedUnit(StepBasic_Array1OfNamedUnit, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<opencascade::handle<StepBasic_NamedUnit>>: ...
+    def Array1(self) -> StepBasic_Array1OfNamedUnit: ...
 
 
-class StepBasic_HArray1OfOrganization(NCollection_Array1<opencascade::handle<StepBasic_Organization>>, Standard_Transient):
+class StepBasic_HArray1OfOrganization(StepBasic_Array1OfOrganization, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<opencascade::handle<StepBasic_Organization>>: ...
+    def Array1(self) -> StepBasic_Array1OfOrganization: ...
 
 
-class StepBasic_HArray1OfPerson(NCollection_Array1<opencascade::handle<StepBasic_Person>>, Standard_Transient):
+class StepBasic_HArray1OfPerson(StepBasic_Array1OfPerson, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<opencascade::handle<StepBasic_Person>>: ...
+    def Array1(self) -> StepBasic_Array1OfPerson: ...
 
 
-class StepBasic_HArray1OfProduct(NCollection_Array1<opencascade::handle<StepBasic_Product>>, Standard_Transient):
+class StepBasic_HArray1OfProduct(StepBasic_Array1OfProduct, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<opencascade::handle<StepBasic_Product>>: ...
+    def Array1(self) -> StepBasic_Array1OfProduct: ...
 
 
-class StepBasic_HArray1OfProductContext(NCollection_Array1<opencascade::handle<StepBasic_ProductContext>>, Standard_Transient):
+class StepBasic_HArray1OfProductContext(StepBasic_Array1OfProductContext, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<opencascade::handle<StepBasic_ProductContext>>: ...
+    def Array1(self) -> StepBasic_Array1OfProductContext: ...
 
 
-class StepBasic_HArray1OfProductDefinition(NCollection_Array1<opencascade::handle<StepBasic_ProductDefinition>>, Standard_Transient):
+class StepBasic_HArray1OfProductDefinition(StepBasic_Array1OfProductDefinition, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<opencascade::handle<StepBasic_ProductDefinition>>: ...
+    def Array1(self) -> StepBasic_Array1OfProductDefinition: ...
 
 
-class StepBasic_HArray1OfUncertaintyMeasureWithUnit(NCollection_Array1<opencascade::handle<StepBasic_UncertaintyMeasureWithUnit>>, Standard_Transient):
+class StepBasic_HArray1OfUncertaintyMeasureWithUnit(StepBasic_Array1OfUncertaintyMeasureWithUnit, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<opencascade::handle<StepBasic_UncertaintyMeasureWithUnit>>: ...
+    def Array1(self) -> StepBasic_Array1OfUncertaintyMeasureWithUnit: ...
 
 # harray2 classes
 # hsequence classes
