--- src/SWIG_files/wrapper/TShort.pyi.orig	2026-08-09 14:32:48 UTC
+++ src/SWIG_files/wrapper/TShort.pyi
@@ -1,5 +1,5 @@ from enum import IntEnum
 from enum import IntEnum
-from typing import overload, NewType, Optional, Tuple
+from typing import Any, overload, NewType, Optional, Tuple
 
 from OCC.Core.Standard import *
 from OCC.Core.NCollection import *
@@ -54,27 +54,27 @@ class TShort_SequenceOfShortReal:
 
 # harray1 classes
 
-class TShort_HArray1OfShortReal(NCollection_Array1<float>, Standard_Transient):
+class TShort_HArray1OfShortReal(Any, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<float>: ...
+    def Array1(self) -> Any: ...
 
 # harray2 classes
 
-class TShort_HArray2OfShortReal(NCollection_Array2<float>, Standard_Transient):
+class TShort_HArray2OfShortReal(Any, Standard_Transient):
     @overload
     def __init__(self, theRowLow: int, theRowUpp: int, theColLow: int, theColUpp: int) -> None: ...
     @overload
-    def __init__(self, theOther: NCollection_Array2<float>) -> None: ...
-    def Array2(self) -> NCollection_Array2<float>: ...
+    def __init__(self, theOther: Any) -> None: ...
+    def Array2(self) -> Any: ...
 
 # hsequence classes
 
-class TShort_HSequenceOfShortReal(NCollection_Sequence<float>, Standard_Transient):
+class TShort_HSequenceOfShortReal(TShort_SequenceOfShortReal, Standard_Transient):
     @overload
     def __init__(self) -> None: ...
     @overload
-    def __init__(self, other: NCollection_Sequence<float>) -> None: ...
-    def Sequence(self) -> NCollection_Sequence<float>: ...
-    def Append(self, theSequence: NCollection_Sequence<float>) -> None: ...
+    def __init__(self, other: TShort_SequenceOfShortReal) -> None: ...
+    def Sequence(self) -> TShort_SequenceOfShortReal: ...
+    def Append(self, theSequence: TShort_SequenceOfShortReal) -> None: ...
 
 
