--- src/SWIG_files/wrapper/StepDimTol.pyi.orig	2026-08-09 14:32:48 UTC
+++ src/SWIG_files/wrapper/StepDimTol.pyi
@@ -1,5 +1,5 @@ from enum import IntEnum
 from enum import IntEnum
-from typing import overload, NewType, Optional, Tuple
+from typing import Any, overload, NewType, Optional, Tuple
 
 from OCC.Core.Standard import *
 from OCC.Core.NCollection import *
@@ -675,39 +675,39 @@ class StepDimTol_TotalRunoutTolerance(StepDimTol_Geome
 
 # harray1 classes
 
-class StepDimTol_HArray1OfDatumReference(NCollection_Array1<opencascade::handle<StepDimTol_DatumReference>>, Standard_Transient):
+class StepDimTol_HArray1OfDatumReference(StepDimTol_Array1OfDatumReference, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<opencascade::handle<StepDimTol_DatumReference>>: ...
+    def Array1(self) -> StepDimTol_Array1OfDatumReference: ...
 
 
-class StepDimTol_HArray1OfDatumReferenceCompartment(NCollection_Array1<opencascade::handle<StepDimTol_DatumReferenceCompartment>>, Standard_Transient):
+class StepDimTol_HArray1OfDatumReferenceCompartment(StepDimTol_Array1OfDatumReferenceCompartment, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<opencascade::handle<StepDimTol_DatumReferenceCompartment>>: ...
+    def Array1(self) -> StepDimTol_Array1OfDatumReferenceCompartment: ...
 
 
-class StepDimTol_HArray1OfDatumReferenceElement(NCollection_Array1<opencascade::handle<StepDimTol_DatumReferenceElement>>, Standard_Transient):
+class StepDimTol_HArray1OfDatumReferenceElement(StepDimTol_Array1OfDatumReferenceElement, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<opencascade::handle<StepDimTol_DatumReferenceElement>>: ...
+    def Array1(self) -> StepDimTol_Array1OfDatumReferenceElement: ...
 
 
-class StepDimTol_HArray1OfDatumReferenceModifier(NCollection_Array1<StepDimTol_DatumReferenceModifier>, Standard_Transient):
+class StepDimTol_HArray1OfDatumReferenceModifier(StepDimTol_Array1OfDatumReferenceModifier, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepDimTol_DatumReferenceModifier>: ...
+    def Array1(self) -> StepDimTol_Array1OfDatumReferenceModifier: ...
 
 
-class StepDimTol_HArray1OfDatumSystemOrReference(NCollection_Array1<StepDimTol_DatumSystemOrReference>, Standard_Transient):
+class StepDimTol_HArray1OfDatumSystemOrReference(StepDimTol_Array1OfDatumSystemOrReference, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepDimTol_DatumSystemOrReference>: ...
+    def Array1(self) -> StepDimTol_Array1OfDatumSystemOrReference: ...
 
 
-class StepDimTol_HArray1OfGeometricToleranceModifier(NCollection_Array1<StepDimTol_GeometricToleranceModifier>, Standard_Transient):
+class StepDimTol_HArray1OfGeometricToleranceModifier(Any, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepDimTol_GeometricToleranceModifier>: ...
+    def Array1(self) -> Any: ...
 
 
-class StepDimTol_HArray1OfToleranceZoneTarget(NCollection_Array1<StepDimTol_ToleranceZoneTarget>, Standard_Transient):
+class StepDimTol_HArray1OfToleranceZoneTarget(StepDimTol_Array1OfToleranceZoneTarget, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<StepDimTol_ToleranceZoneTarget>: ...
+    def Array1(self) -> StepDimTol_Array1OfToleranceZoneTarget: ...
 
 # harray2 classes
 # hsequence classes
