--- src/SWIG_files/wrapper/Transfer.pyi.orig	2026-08-09 14:32:48 UTC
+++ src/SWIG_files/wrapper/Transfer.pyi
@@ -1,5 +1,5 @@ from enum import IntEnum
 from enum import IntEnum
-from typing import overload, NewType, Optional, Tuple
+from typing import Any, overload, NewType, Optional, Tuple
 
 from OCC.Core.Standard import *
 from OCC.Core.NCollection import *
@@ -468,21 +468,21 @@ class Transfer_ProcessForFinder: ...
 # harray2 classes
 # hsequence classes
 
-class Transfer_HSequenceOfBinder(NCollection_Sequence<opencascade::handle<Transfer_Binder>>, Standard_Transient):
+class Transfer_HSequenceOfBinder(Transfer_SequenceOfBinder, Standard_Transient):
     @overload
     def __init__(self) -> None: ...
     @overload
-    def __init__(self, other: NCollection_Sequence<opencascade::handle<Transfer_Binder>>) -> None: ...
-    def Sequence(self) -> NCollection_Sequence<opencascade::handle<Transfer_Binder>>: ...
-    def Append(self, theSequence: NCollection_Sequence<opencascade::handle<Transfer_Binder>>) -> None: ...
+    def __init__(self, other: Transfer_SequenceOfBinder) -> None: ...
+    def Sequence(self) -> Transfer_SequenceOfBinder: ...
+    def Append(self, theSequence: Transfer_SequenceOfBinder) -> None: ...
 
 
-class Transfer_HSequenceOfFinder(NCollection_Sequence<opencascade::handle<Transfer_Finder>>, Standard_Transient):
+class Transfer_HSequenceOfFinder(Transfer_SequenceOfFinder, Standard_Transient):
     @overload
     def __init__(self) -> None: ...
     @overload
-    def __init__(self, other: NCollection_Sequence<opencascade::handle<Transfer_Finder>>) -> None: ...
-    def Sequence(self) -> NCollection_Sequence<opencascade::handle<Transfer_Finder>>: ...
-    def Append(self, theSequence: NCollection_Sequence<opencascade::handle<Transfer_Finder>>) -> None: ...
+    def __init__(self, other: Transfer_SequenceOfFinder) -> None: ...
+    def Sequence(self) -> Transfer_SequenceOfFinder: ...
+    def Append(self, theSequence: Transfer_SequenceOfFinder) -> None: ...
 
 
