--- src/SWIG_files/wrapper/Storage.pyi.orig	2026-08-09 14:32:48 UTC
+++ src/SWIG_files/wrapper/Storage.pyi
@@ -1,5 +1,5 @@ from enum import IntEnum
 from enum import IntEnum
-from typing import overload, NewType, Optional, Tuple
+from typing import Any, overload, NewType, Optional, Tuple
 
 from OCC.Core.Standard import *
 from OCC.Core.NCollection import *
@@ -153,29 +153,29 @@ class Storage_TypedCallBack: ...
 
 # harray1 classes
 
-class Storage_HArrayOfCallBack(NCollection_Array1<opencascade::handle<Storage_CallBack>>, Standard_Transient):
+class Storage_HArrayOfCallBack(Storage_ArrayOfCallBack, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<opencascade::handle<Storage_CallBack>>: ...
+    def Array1(self) -> Storage_ArrayOfCallBack: ...
 
 
-class Storage_HArrayOfSchema(NCollection_Array1<opencascade::handle<Storage_Schema>>, Standard_Transient):
+class Storage_HArrayOfSchema(Any, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<opencascade::handle<Storage_Schema>>: ...
+    def Array1(self) -> Any: ...
 
 
-class Storage_HPArray(NCollection_Array1<opencascade::handle<Standard_Persistent>>, Standard_Transient):
+class Storage_HPArray(Any, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<opencascade::handle<Standard_Persistent>>: ...
+    def Array1(self) -> Any: ...
 
 # harray2 classes
 # hsequence classes
 
-class Storage_HSeqOfRoot(NCollection_Sequence<opencascade::handle<Storage_Root>>, Standard_Transient):
+class Storage_HSeqOfRoot(Storage_SeqOfRoot, Standard_Transient):
     @overload
     def __init__(self) -> None: ...
     @overload
-    def __init__(self, other: NCollection_Sequence<opencascade::handle<Storage_Root>>) -> None: ...
-    def Sequence(self) -> NCollection_Sequence<opencascade::handle<Storage_Root>>: ...
-    def Append(self, theSequence: NCollection_Sequence<opencascade::handle<Storage_Root>>) -> None: ...
+    def __init__(self, other: Storage_SeqOfRoot) -> None: ...
+    def Sequence(self) -> Storage_SeqOfRoot: ...
+    def Append(self, theSequence: Storage_SeqOfRoot) -> None: ...
 
 
