--- src/SWIG_files/wrapper/TopoDS.pyi.orig	2026-08-09 14:32:48 UTC
+++ src/SWIG_files/wrapper/TopoDS.pyi
@@ -10,7 +10,7 @@ class TopoDS_AlertAttribute(Message_AttributeStream):
 
 
 class TopoDS_AlertAttribute(Message_AttributeStream):
-    def __init__(self, theShape: TopoDS_Shape, theName: Optional[str] = TCollection_AsciiString::EmptyString()) -> None: ...
+    def __init__(self, theShape: TopoDS_Shape, theName: Optional[str] = ...) -> None: ...
     def DumpJson(self, depth: Optional[int]=-1) -> str: ...
     def GetShape(self) -> TopoDS_Shape: ...
     @staticmethod
