--- src/SWIG_files/wrapper/StepRepr.pyi.orig	2026-08-09 14:32:48 UTC
+++ src/SWIG_files/wrapper/StepRepr.pyi
@@ -1,5 +1,5 @@ from enum import IntEnum
 from enum import IntEnum
-from typing import overload, NewType, Optional, Tuple
+from typing import Any, overload, NewType, Optional, Tuple
 
 from OCC.Core.Standard import *
 from OCC.Core.NCollection import *
@@ -662,43 +662,43 @@ class StepRepr_ReprItemAndMeasureWithUnitAndQRI: ...
 
 # harray1 classes
 
-class StepRepr_HArray1OfMaterialPropertyRepresentation(NCollection_Array1<opencascade::handle<StepRepr_MaterialPropertyRepresentation>>, Standard_Transient):
+class StepRepr_HArray1OfMaterialPropertyRepresentation(StepRepr_Array1OfMaterialPropertyRepresentation, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<opencascade::handle<StepRepr_MaterialPropertyRepresentation>>: ...
+    def Array1(self) -> StepRepr_Array1OfMaterialPropertyRepresentation: ...
 
 
-class StepRepr_HArray1OfPropertyDefinitionRepresentation(NCollection_Array1<opencascade::handle<StepRepr_PropertyDefinitionRepresentation>>, Standard_Transient):
+class StepRepr_HArray1OfPropertyDefinitionRepresentation(StepRepr_Array1OfPropertyDefinitionRepresentation, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<opencascade::handle<StepRepr_PropertyDefinitionRepresentation>>: ...
+    def Array1(self) -> StepRepr_Array1OfPropertyDefinitionRepresentation: ...
 
 
-class StepRepr_HArray1OfRepresentationItem(NCollection_Array1<opencascade::handle<StepRepr_RepresentationItem>>, Standard_Transient):
+class StepRepr_HArray1OfRepresentationItem(StepRepr_Array1OfRepresentationItem, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<opencascade::handle<StepRepr_RepresentationItem>>: ...
+    def Array1(self) -> StepRepr_Array1OfRepresentationItem: ...
 
 
-class StepRepr_HArray1OfShapeAspect(NCollection_Array1<opencascade::handle<StepRepr_ShapeAspect>>, Standard_Transient):
+class StepRepr_HArray1OfShapeAspect(StepRepr_Array1OfShapeAspect, Standard_Transient):
     def __init__(self, theLower: int, theUpper: int) -> None: ...
-    def Array1(self) -> NCollection_Array1<opencascade::handle<StepRepr_ShapeAspect>>: ...
+    def Array1(self) -> StepRepr_Array1OfShapeAspect: ...
 
 # harray2 classes
 # hsequence classes
 
-class StepRepr_HSequenceOfMaterialPropertyRepresentation(NCollection_Sequence<opencascade::handle<StepRepr_MaterialPropertyRepresentation>>, Standard_Transient):
+class StepRepr_HSequenceOfMaterialPropertyRepresentation(StepRepr_SequenceOfMaterialPropertyRepresentation, Standard_Transient):
     @overload
     def __init__(self) -> None: ...
     @overload
-    def __init__(self, other: NCollection_Sequence<opencascade::handle<StepRepr_MaterialPropertyRepresentation>>) -> None: ...
-    def Sequence(self) -> NCollection_Sequence<opencascade::handle<StepRepr_MaterialPropertyRepresentation>>: ...
-    def Append(self, theSequence: NCollection_Sequence<opencascade::handle<StepRepr_MaterialPropertyRepresentation>>) -> None: ...
+    def __init__(self, other: StepRepr_SequenceOfMaterialPropertyRepresentation) -> None: ...
+    def Sequence(self) -> StepRepr_SequenceOfMaterialPropertyRepresentation: ...
+    def Append(self, theSequence: StepRepr_SequenceOfMaterialPropertyRepresentation) -> None: ...
 
 
-class StepRepr_HSequenceOfRepresentationItem(NCollection_Sequence<opencascade::handle<StepRepr_RepresentationItem>>, Standard_Transient):
+class StepRepr_HSequenceOfRepresentationItem(StepRepr_SequenceOfRepresentationItem, Standard_Transient):
     @overload
     def __init__(self) -> None: ...
     @overload
-    def __init__(self, other: NCollection_Sequence<opencascade::handle<StepRepr_RepresentationItem>>) -> None: ...
-    def Sequence(self) -> NCollection_Sequence<opencascade::handle<StepRepr_RepresentationItem>>: ...
-    def Append(self, theSequence: NCollection_Sequence<opencascade::handle<StepRepr_RepresentationItem>>) -> None: ...
+    def __init__(self, other: StepRepr_SequenceOfRepresentationItem) -> None: ...
+    def Sequence(self) -> StepRepr_SequenceOfRepresentationItem: ...
+    def Append(self, theSequence: StepRepr_SequenceOfRepresentationItem) -> None: ...
 
 
