--- build-outputs.mk.orig	Tue Sep 12 15:16:30 2006
+++ build-outputs.mk	Tue Sep 12 15:17:04 2006
@@ -32,7 +32,7 @@
 
 TEST_PROGRAMS = subversion/tests/libsvn_subr/compat-test$(EXEEXT) subversion/tests/libsvn_subr/config-test$(EXEEXT) subversion/tests/libsvn_diff/diff-diff3-test$(EXEEXT) subversion/tests/libsvn_fs/fs-test$(EXEEXT) subversion/tests/libsvn_subr/hashdump-test$(EXEEXT) subversion/tests/libsvn_fs/locks-test$(EXEEXT) subversion/tests/libsvn_subr/opt-test$(EXEEXT) subversion/tests/libsvn_subr/path-test$(EXEEXT) subversion/tests/libsvn_ra_local/ra-local-test$(EXEEXT) subversion/tests/libsvn_delta/random-test$(EXEEXT) subversion/tests/libsvn_repos/repos-test$(EXEEXT) subversion/tests/libsvn_subr/stream-test$(EXEEXT) subversion/tests/libsvn_subr/string-test$(EXEEXT) subversion/tests/libsvn_subr/time-test$(EXEEXT) subversion/tests/libsvn_wc/translate-test$(EXEEXT) subversion/tests/libsvn_subr/utf-test$(EXEEXT) subversion/tests/libsvn_subr/target-test.py subversion/tests/cmdline/getopt_tests.py subversion/tests/cmdline/basic_tests.py subversion/tests/cmdline/commit_tests.py subversion/tests/cmdline/update_tests.py subversion/tests/cmdline/switch_tests.py subversion/tests/cmdline/prop_tests.py subversion/tests/cmdline/schedule_tests.py subversion/tests/cmdline/log_tests.py subversion/tests/cmdline/copy_tests.py subversion/tests/cmdline/diff_tests.py subversion/tests/cmdline/export_tests.py subversion/tests/cmdline/externals_tests.py subversion/tests/cmdline/merge_tests.py subversion/tests/cmdline/revert_tests.py subversion/tests/cmdline/stat_tests.py subversion/tests/cmdline/trans_tests.py subversion/tests/cmdline/autoprop_tests.py subversion/tests/cmdline/blame_tests.py subversion/tests/cmdline/special_tests.py subversion/tests/cmdline/svnadmin_tests.py subversion/tests/cmdline/svnlook_tests.py subversion/tests/cmdline/svnversion_tests.py subversion/tests/cmdline/utf8_tests.py subversion/tests/cmdline/history_tests.py subversion/tests/cmdline/lock_tests.py subversion/tests/cmdline/cat_tests.py subversion/tests/cmdline/import_tests.py subversion/tests/cmdline/svnsync_tests.py subversion/tests/cmdline/authz_tests.py
 
-MANPAGES = subversion/svn/svn.1 subversion/svnadmin/svnadmin.1 subversion/svndumpfilter/svndumpfilter.1 subversion/svnlook/svnlook.1 subversion/svnserve/svnserve.8 subversion/svnserve/svnserve.conf.5 subversion/svnversion/svnsync.1 subversion/svnversion/svnversion.1
+MANPAGES = subversion/svn/svn.1 subversion/svnadmin/svnadmin.1 subversion/svndumpfilter/svndumpfilter.1 subversion/svnlook/svnlook.1 subversion/svnserve/svnserve.8 subversion/svnserve/svnserve.conf.5 subversion/svnsync/svnsync.1 subversion/svnversion/svnversion.1
 
 CLEAN_FILES = contrib/client-side/mucc$(EXEEXT) contrib/client-side/svn-push/svn-push$(EXEEXT) subversion/svn/svn$(EXEEXT) subversion/svnadmin/svnadmin$(EXEEXT) subversion/svndumpfilter/svndumpfilter$(EXEEXT) subversion/svnlook/svnlook$(EXEEXT) subversion/svnserve/svnserve$(EXEEXT) subversion/svnsync/svnsync$(EXEEXT) subversion/svnversion/svnversion$(EXEEXT) subversion/tests/libsvn_delta/random-test$(EXEEXT) subversion/tests/libsvn_delta/svndiff-test$(EXEEXT) subversion/tests/libsvn_delta/vdelta-test$(EXEEXT) subversion/tests/libsvn_diff/diff-diff3-test$(EXEEXT) subversion/tests/libsvn_fs/fs-test$(EXEEXT) subversion/tests/libsvn_fs/locks-test$(EXEEXT) subversion/tests/libsvn_fs_base/changes-test$(EXEEXT) subversion/tests/libsvn_fs_base/fs-base-test$(EXEEXT) subversion/tests/libsvn_fs_base/key-test$(EXEEXT) subversion/tests/libsvn_fs_base/skel-test$(EXEEXT) subversion/tests/libsvn_fs_base/strings-reps-test$(EXEEXT) subversion/tests/libsvn_ra_local/ra-local-test$(EXEEXT) subversion/tests/libsvn_repos/repos-test$(EXEEXT) subversion/tests/libsvn_subr/compat-test$(EXEEXT) subversion/tests/libsvn_subr/config-test$(EXEEXT) subversion/tests/libsvn_subr/hashdump-test$(EXEEXT) subversion/tests/libsvn_subr/opt-test$(EXEEXT) subversion/tests/libsvn_subr/path-test$(EXEEXT) subversion/tests/libsvn_subr/stream-test$(EXEEXT) subversion/tests/libsvn_subr/string-test$(EXEEXT) subversion/tests/libsvn_subr/target-test$(EXEEXT) subversion/tests/libsvn_subr/time-test$(EXEEXT) subversion/tests/libsvn_subr/utf-test$(EXEEXT) subversion/tests/libsvn_wc/translate-test$(EXEEXT) tools/diff/diff$(EXEEXT) tools/diff/diff3$(EXEEXT) tools/diff/diff4$(EXEEXT) tools/server-side/svnauthz-validate$(EXEEXT)
 
