'\" t
.\"     Title: ctdb_diagnostics
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 11/20/2017
.\"    Manual: CTDB - clustered TDB database
.\"    Source: ctdb
.\"  Language: English
.\"
.TH "CTDB_DIAGNOSTICS" "1" "11/20/2017" "ctdb" "CTDB \- clustered TDB database"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ctdb_diagnostics \- dump diagnostic information about CTDB/Samba installation
.SH "SYNOPSIS"
.HP \w'\fBctdb_diagnostics\fR\ 'u
\fBctdb_diagnostics\fR [OPTIONS] \&.\&.\&.
.SH "DESCRIPTION"
.PP
ctdb_diagnostics is used to dump diagnostic information about a clustered Samba installation\&. This includes configuration files, output of relevant commands and logs\&. This information can be used to check the correctness of the configuration and to diagnose problems\&.
.SH "OPTIONS"
.PP
\-n <nodes>
.RS 4
Comma separated list of nodes to operate on
.RE
.PP
\-c
.RS 4
Ignore comment lines (starting with \*(Aq#\*(Aq) in file comparisons
.RE
.PP
\-w
.RS 4
Ignore whitespace in file comparisons
.RE
.PP
\-\-no\-ads
.RS 4
Do not use commands that assume an Active Directory Server
.RE
.SH "SEE ALSO"
.PP
\fBctdb\fR(1),
\fBctdb\fR(7),
\m[blue]\fB\%https://ctdb.samba.org/\fR\m[]
.SH "AUTHOR"
.br
.PP
This documentation was written by Martijn van Brummelen
.SH "COPYRIGHT"
.br
Copyright \(co 2015 Martijn van Brummelen
.br
.PP
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 3 of the License, or (at your option) any later version\&.
.PP
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU General Public License for more details\&.
.PP
You should have received a copy of the GNU General Public License along with this program; if not, see
\m[blue]\fB\%http://www.gnu.org/licenses\fR\m[]\&.
.sp
