# New ports collection makefile for:	p5-Mojo
# Date created:		2008-12-29
# Whom:			Murilo Opsfelder <mopsfelder@gmail.com>
#
# $FreeBSD$
#

PORTNAME=	Mojo
PORTVERSION=	0.9
PORTREVISION=	1
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	Test
PKGNAMEPREFIX=	p5-

MAINTAINER=	mopsfelder@gmail.com
COMMENT=	A high level MVC web framework written in Perl

PERL_CONFIGURE=	yes

MAN3=		Mojo.3 \
		Mojo::Base.3 \
		Mojo::Buffer.3 \
		Mojo::ByteStream.3 \
		Mojo::Client.3 \
		Mojo::Content.3 \
		Mojo::Content::MultiPart.3 \
		Mojo::Cookie.3 \
		Mojo::Cookie::Request.3 \
		Mojo::Cookie::Response.3 \
		Mojo::Date.3 \
		Mojo::File.3 \
		Mojo::File::Memory.3 \
		Mojo::Filter.3 \
		Mojo::Filter::Chunked.3 \
		Mojo::Headers.3 \
		Mojo::HelloWorld.3 \
		Mojo::Home.3 \
		Mojo::Loader.3 \
		Mojo::Log.3 \
		Mojo::Manual.3 \
		Mojo::Manual::CodingGuidelines.3 \
		Mojo::Manual::Cookbook.3 \
		Mojo::Manual::Deployment.3 \
		Mojo::Manual::FAQ.3 \
		Mojo::Manual::FrameworkBuilding.3 \
		Mojo::Manual::GettingStarted.3 \
		Mojo::Manual::HTTPGuide.3 \
		Mojo::Manual::Mojolicious.3 \
		Mojo::Message.3 \
		Mojo::Message::Request.3 \
		Mojo::Message::Response.3 \
		Mojo::Parameters.3 \
		Mojo::Path.3 \
		Mojo::Script::Cgi.3 \
		Mojo::Script::Daemon.3 \
		Mojo::Script::DaemonPrefork.3 \
		Mojo::Script::Fastcgi.3 \
		Mojo::Script::Generate.3 \
		Mojo::Script::Generate::App.3 \
		Mojo::Script::Test.3 \
		Mojo::Script.3 \
		Mojo::Scripts.3 \
		Mojo::Server.3 \
		Mojo::Server::CGI.3 \
		Mojo::Server::Daemon.3 \
		Mojo::Server::Daemon::Prefork.3 \
		Mojo::Server::FastCGI.3 \
		Mojo::Stateful.3 \
		Mojo::Template.3 \
		Mojo::Transaction.3 \
		Mojo::Upload.3 \
		Mojo::URL.3 \
		Mojolicious.3 \
		Mojolicious::Context.3 \
		Mojolicious::Controller.3 \
		Mojolicious::Dispatcher.3 \
		Mojolicious::Renderer.3 \
		Mojolicious::Script::Daemon.3 \
		Mojolicious::Script::Generate.3 \
		Mojolicious::Script::Generate::App.3 \
		Mojolicious::Script::Mojo.3 \
		Mojolicious::Scripts.3 \
		Mojolicious::Script::Test.3 \
		MojoX::Context.3 \
		MojoX::Dispatcher::Routes.3 \
		MojoX::Dispatcher::Routes::Context.3 \
		MojoX::Dispatcher::Routes::Controller.3 \
		MojoX::Dispatcher::Static.3 \
		MojoX::Renderer.3 \
		MojoX::Routes.3 \
		MojoX::Routes::Match.3 \
		MojoX::Routes::Pattern.3 \
		MojoX::Types.3 \
		Test::Mojo::Server.3

.include <bsd.port.mk>
