--- src/netstat.c.orig	2005-05-08 06:55:00 UTC
+++ src/netstat.c
@@ -40,7 +40,6 @@ EXPCONST(int IFF_BROADCAST)
 EXPCONST(int IFF_DEBUG)
 EXPCONST(int IFF_LOOPBACK)
 EXPCONST(int IFF_POINTOPOINT)
-EXPCONST(int IFF_SMART)
 EXPCONST(int IFF_RUNNING)
 EXPCONST(int IFF_NOARP)
 EXPCONST(int IFF_PROMISC)
