--- pyproject.toml.orig	2026-08-21 01:10:40 UTC
+++ pyproject.toml
@@ -50,7 +50,7 @@ Funding = "https://github.com/sponsors/typeddjango"
 "Release notes" = "https://github.com/typeddjango/django-stubs/releases"
 
 [build-system]
-requires = ["uv_build>=0.12.0,<0.13.0"]
+requires = ["uv_build"]
 build-backend = "uv_build"
 
 [tool.uv.build-backend]
