--- build/top.mk.orig	Mon Apr 12 20:21:07 2004
+++ build/top.mk	Wed May  5 12:49:13 2004
@@ -194,6 +194,8 @@
 SLAPD_LIBS = @SLAPD_LIBS@ @SLAPD_PERL_LDFLAGS@ @SLAPD_SQL_LDFLAGS@ @SLAPD_SQL_LIBS@ @SLAPD_SLP_LIBS@
 SLURPD_LIBS = @SLURPD_LIBS@
 
+SLAPI_LIBS = @SLAPI_LIBS@
+
 # Our Defaults
 CC = $(AC_CC)
 DEFS = $(LDAP_INCPATH) $(XINCPATH) $(XDEFS) $(AC_DEFS) $(DEFINES)
