# Created by: Dryice Liu <dryice@FreeBSD.org>
# $FreeBSD$

PORTNAME=	beaker
PORTVERSION=	1.7.0
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	Beaker-${PORTVERSION}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Session and Caching library with WSGI Middleware

LICENSE=	BSD3CLAUSE

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
