# Created by: Wen Heping<wenheping@gmail.com>
# $FreeBSD$

PORTNAME=	sequel
PORTVERSION=	4.0.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	The Database Toolkit for Ruby

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=yes

PLIST_FILES=	bin/sequel

.include <bsd.port.mk>
