--- pyproject.toml.orig	2026-03-05 00:01:01 UTC
+++ pyproject.toml
@@ -1,11 +1,11 @@
 [build-system]
-requires = ["setuptools>=77.0.3"]
+requires = ["setuptools>=63"]
 build-backend = "setuptools.build_meta"
 
 [project]
-name = "Django"
+name = "django"
 dynamic = ["version"]
-requires-python = ">= 3.12"
+requires-python = ">= 3.11"
 dependencies = [
     "asgiref>=3.9.1",
     "sqlparse>=0.5.0",
@@ -16,8 +16,8 @@ readme = "README.rst"
 ]
 description = "A high-level Python web framework that encourages rapid development and clean, pragmatic design."
 readme = "README.rst"
-license = "BSD-3-Clause"
-license-files = ["LICENSE", "LICENSE.python", "AUTHORS"]
+license = {text="BSD-3-Clause"}
+#license-files = ["LICENSE", "LICENSE.python", "AUTHORS"]
 classifiers = [
     "Development Status :: 5 - Production/Stable",
     "Environment :: Web Environment",
