--- pyproject.toml.orig	2026-01-17 20:20:14 UTC
+++ pyproject.toml
@@ -1,2 +1,2 @@
 [build-system]
-requires = ["setuptools", "scikit-build", "cmake", "ninja", "py-cpuinfo"]
+requires = ["setuptools", "scikit-build", "py-cpuinfo2"]
