--- cargo-crates/minidumper-0.8.3/Cargo.toml.orig	1970-01-01 00:00:01 UTC
+++ cargo-crates/minidumper-0.8.3/Cargo.toml
@@ -65,6 +65,9 @@ version = "0.4"
 [target."cfg(any(target_os = \"linux\", target_os = \"android\"))".dependencies.uds]
 version = "0.4"
 
+[target."cfg(target_os = \"freebsd\")".dependencies.uds]
+version = "0.4"
+
 [target."cfg(any(target_os = \"windows\", target_os = \"macos\"))".dependencies.scroll]
 version = "0.12"
 features = ["derive"]
