# New ports collection makefile for:   pybookreader
# Date created:        30 September 2006
# Whom:                Valeri Vassiliev
#
# $FreeBSD$
#

PORTNAME=	pybookreader
PORTVERSION=	0.5.0
CATEGORIES=	deskutils python
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE}
MASTER_SITE_SUBDIR=	${PORTNAME}
DISTNAME=	PyBookReader-${PORTVERSION}

MAINTAINER=	valeri_ufo@web.de
COMMENT=	Program for reading e-books

USE_PYTHON=	2.2+
USE_PYDISTUTILS=	yes
USE_GNOME=	pygtk2

.include <bsd.port.mk>
