--- .gn.orig	2026-09-30 03:53:08 UTC
+++ .gn
@@ -9,11 +9,7 @@ buildconfig = "//build/config/BUILDCONFIG.gn"
 
 # The hermetic Python interpreter to use by default. Platforms without a
 # hermetic CPython CIPD package fallback to the system python3 on $PATH.
-if (host_cpu == "s390x" || host_cpu == "ppc64" || host_os == "zos") {
-  script_executable = "python3"
-} else {
-  script_executable = "//third_party/cpython3/host/bin/python3"
-}
+script_executable = "python3"
 
 # These are the targets to check headers for by default. The files in targets
 # matching these patterns (see "gn help label_pattern" for format) will have
