#define GL_EXT_abgr
#define GL_EXT_blend_color
#define GL_EXT_blend_logic_op
#define GL_EXT_blend_minmax
#define GL_EXT_blend_subtract
#undef GL_EXT_color_table
#define GL_EXT_paletted_texture
#define GL_EXT_point_parameters
#define GL_EXT_polygon_offset
#define GL_EXT_rescale_normal
#define GL_EXT_shared_texture_palette
#define GL_EXT_subtexture
#define GL_EXT_texture3D
#define GL_EXT_texture_object
#define GL_EXT_vertex_array
#undef GL_SGIS_multisample
#define GL_MESA_resize_buffers
#define GL_MESA_window_pos
#define OPENGL_1_0
#define OPENGL_1_1
#define OPENGL_1_2
#define OPENGL_1_3
