# New ports collection makefile for:	gpsk31
# Date created:		2005-05-27
# Whom:				Søren Straarup <xride@x12.dk>
#
# $FreeBSD$

PORTNAME=	gpsk31
PORTVERSION=	0.2.4a
CATEGORIES=	comms
MASTER_SITES=	http://ftp.iasi.roedu.net/mirrors/ftp.1409.org/gpsk31/

MAINTAINER=	xride@x12.dk
COMMENT=	A gtk psk31 client

USE_GNOME=	gtk12
GNU_CONFIGURE=	yes
USE_X_PREFIX=	yes

.include <bsd.port.mk>
