--- make/common.make.orig	Tue Feb  3 13:41:55 1998
+++ make/common.make	Sun May 13 14:57:48 2001
@@ -28,7 +28,7 @@
 # Installation.
 INSTALL = @INSTALL@
 INSTALL_PROGRAM = @INSTALL_PROGRAM@
-INSTALL_SCRIPT = $(INSTALL_PROGRAM)
+INSTALL_SCRIPT = @INSTALL_SCRIPT@
 INSTALL_DATA = @INSTALL_DATA@
 INSTALL_LIBTOOL_LIBS = INSTALL_DATA='$(INSTALL_DATA)' $(LIBTOOL) install-lib
 INSTALL_LIBTOOL_PROG = INSTALL_PROGRAM='$(INSTALL_PROGRAM)' $(LIBTOOL) install-prog
