--- pyproject.toml.orig	2026-05-08 04:46:14 UTC
+++ pyproject.toml
@@ -1,12 +1,11 @@ build-backend = "setuptools.build_meta"
 [build-system]
 build-backend = "setuptools.build_meta"
-requires = ["setuptools>=82.0.1"]
+requires = ["setuptools>=61"]
 
 [project]
 name = "types-protobuf"
 version = "7.34.1.20260508"
-license = "Apache-2.0"
-license-files = ["LICENSE"]
+license = { text = "Apache-2.0" }
 description = "Typing stubs for protobuf"
 readme = { text = """\
 ## Typing stubs for protobuf
@@ -52,8 +51,4 @@ dependencies = []
 "Chat" = "https://gitter.im/python/typing"
 
 [tool.setuptools]
-packages = ['google-stubs']
 include-package-data = false
-
-[tool.setuptools.package-data]
-'google-stubs' = ['_upb/_message.pyi', 'protobuf/__init__.pyi', 'protobuf/any.pyi', 'protobuf/any_pb2.pyi', 'protobuf/api_pb2.pyi', 'protobuf/compiler/__init__.pyi', 'protobuf/compiler/plugin_pb2.pyi', 'protobuf/descriptor.pyi', 'protobuf/descriptor_database.pyi', 'protobuf/descriptor_pb2.pyi', 'protobuf/descriptor_pool.pyi', 'protobuf/duration.pyi', 'protobuf/duration_pb2.pyi', 'protobuf/empty_pb2.pyi', 'protobuf/field_mask_pb2.pyi', 'protobuf/internal/__init__.pyi', 'protobuf/internal/api_implementation.pyi', 'protobuf/internal/builder.pyi', 'protobuf/internal/containers.pyi', 'protobuf/internal/decoder.pyi', 'protobuf/internal/encoder.pyi', 'protobuf/internal/enum_type_wrapper.pyi', 'protobuf/internal/extension_dict.pyi', 'protobuf/internal/field_mask.pyi', 'protobuf/internal/message_listener.pyi', 'protobuf/internal/python_edition_defaults.pyi', 'protobuf/internal/python_message.pyi', 'protobuf/internal/testing_refleaks.pyi', 'protobuf/internal/type_checkers.pyi', 'protobuf/internal/well_known_types.pyi', 'protobuf/internal/wire_format.pyi', 'protobuf/json_format.pyi', 'protobuf/message.pyi', 'protobuf/message_factory.pyi', 'protobuf/proto.pyi', 'protobuf/proto_builder.pyi', 'protobuf/proto_json.pyi', 'protobuf/proto_text.pyi', 'protobuf/reflection.pyi', 'protobuf/runtime_version.pyi', 'protobuf/service_reflection.pyi', 'protobuf/source_context_pb2.pyi', 'protobuf/struct_pb2.pyi', 'protobuf/symbol_database.pyi', 'protobuf/text_encoding.pyi', 'protobuf/text_format.pyi', 'protobuf/timestamp.pyi', 'protobuf/timestamp_pb2.pyi', 'protobuf/type_pb2.pyi', 'protobuf/unknown_fields.pyi', 'protobuf/util/__init__.pyi', 'protobuf/wrappers_pb2.pyi', 'METADATA.toml', 'protobuf/py.typed']
