--- ./cmake/FindGObject.cmake.orig	2008-11-24 20:11:55.000000000 +0300
+++ ./cmake/FindGObject.cmake	2009-02-21 01:19:39.000000000 +0300
@@ -23,14 +23,16 @@
    # in the FIND_PATH() and FIND_LIBRARY() calls
    PKG_CHECK_MODULES(PKG_GOBJECT2 REQUIRED gobject-2.0)
    SET(GOBJECT_DEFINITIONS ${PKG_GOBJECT2_CFLAGS})
+   PKG_CHECK_MODULES(PKG_GLIB REQUIRED glib-2.0)
 ENDIF (NOT WIN32)
 
 FIND_PATH(GOBJECT_INCLUDE_DIR gobject.h
    PATHS
+   ${PKG_GLIB_INCLUDE_DIRS}
    ${PKG_GOBJECT2_INCLUDE_DIRS}
    ${PKG_GOBJECT2_INCLUDE_DIRS}/glib-2.0/gobject/
    /usr/include/glib-2.0/gobject/
-   #PATH_SUFFIXES gst
+   PATH_SUFFIXES gobject
    )
 
 FIND_LIBRARY(_GObjectLibs NAMES gobject-2.0
@@ -50,7 +52,7 @@
    ${PKG_GOBJECT2_LIBRARY_DIRS}
    )
 
-SET( GOBJECT_LIBRARIES ${PKG_GOBJECT2_LIBRARIES} )
+SET( GOBJECT_LIBRARIES ${_GObjectLibs} )
 
 IF (GOBJECT_INCLUDE_DIR AND GOBJECT_LIBRARIES)
    SET(GOBJECT_FOUND TRUE)
