--- CMake/Packages/FindOpenEXR.cmake.orig	2019-04-24 16:21:46 UTC
+++ CMake/Packages/FindOpenEXR.cmake
@@ -25,7 +25,7 @@ FIND_PATH(OPENEXR_INCLUDE_DIR OpenEXR/ImfIO.h
 )
 
 # Macro to find exr libraries (deduplicating search paths)
-# example: OPENEXR_FIND_VAR(OPENEXR_IlmImf_LIBRARY IlmImf)
+# example: OPENEXR_FIND_VAR(OPENEXR_OpenEXR_LIBRARY OpenEXR)
 MACRO(OPENEXR_FIND_VAR varname libname)
     FIND_LIBRARY( ${varname}
         NAMES ${libname}
@@ -45,20 +45,20 @@ MACRO(OPENEXR_FIND_VAR varname libname)
 ENDMACRO(OPENEXR_FIND_VAR)
 
 # Macro to find exr libraries (and debug versions)
-# example: OPENEXR_FIND(IlmImf)
+# example: OPENEXR_FIND(OpenEXR)
 MACRO(OPENEXR_FIND libname)
     OPENEXR_FIND_VAR(OPENEXR_${libname}_LIBRARY ${libname})
     OPENEXR_FIND_VAR(OPENEXR_${libname}_LIBRARY_DEBUG ${libname}d)
 ENDMACRO(OPENEXR_FIND)
 
-OPENEXR_FIND(IlmImf)
+OPENEXR_FIND(OpenEXR)
 OPENEXR_FIND(IlmThread)
 OPENEXR_FIND(Iex)
-OPENEXR_FIND(Half)
+OPENEXR_FIND(Imath)
 
 SET(OPENEXR_FOUND NO)
-IF(OPENEXR_INCLUDE_DIR AND OPENEXR_IlmImf_LIBRARY AND OPENEXR_IlmThread_LIBRARY AND OPENEXR_Iex_LIBRARY AND OPENEXR_Half_LIBRARY)
-    SET(OPENEXR_LIBRARIES ${OPENEXR_IlmImf_LIBRARY} ${OPENEXR_IlmThread_LIBRARY} ${OPENEXR_Half_LIBRARY} ${OPENEXR_Iex_LIBRARY} )
-    SET(OPENEXR_LIBRARIES_VARS OPENEXR_IlmImf_LIBRARY OPENEXR_IlmThread_LIBRARY OPENEXR_Half_LIBRARY OPENEXR_Iex_LIBRARY )
+IF(OPENEXR_INCLUDE_DIR AND OPENEXR_OpenEXR_LIBRARY AND OPENEXR_IlmThread_LIBRARY AND OPENEXR_Iex_LIBRARY AND OPENEXR_Imath_LIBRARY)
+    SET(OPENEXR_LIBRARIES ${OPENEXR_OpenEXR_LIBRARY} ${OPENEXR_IlmThread_LIBRARY} ${OPENEXR_Imath_LIBRARY} ${OPENEXR_Iex_LIBRARY} )
+    SET(OPENEXR_LIBRARIES_VARS OPENEXR_OpenEXR_LIBRARY OPENEXR_IlmThread_LIBRARY OPENEXR_Imath_LIBRARY OPENEXR_Iex_LIBRARY )
     SET(OPENEXR_FOUND YES)
-ENDIF(OPENEXR_INCLUDE_DIR AND OPENEXR_IlmImf_LIBRARY AND OPENEXR_IlmThread_LIBRARY AND OPENEXR_Iex_LIBRARY AND OPENEXR_Half_LIBRARY)
+ENDIF(OPENEXR_INCLUDE_DIR AND OPENEXR_OpenEXR_LIBRARY AND OPENEXR_IlmThread_LIBRARY AND OPENEXR_Iex_LIBRARY AND OPENEXR_Imath_LIBRARY)
