# $FreeBSD$

CATEGORIES=	print

MAINTAINER=	ports@FreeBSD.org

MASTERDIR?=	${.CURDIR}/../cups-base
 
CUPS_IMAGE=	yes

NO_STAGE=	yes

.sinclude "${.CURDIR}/Makefile.local"
.include "${MASTERDIR}/Makefile"
