'\" t
.\"     Title: ntdbbackup
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 03/12/2014
.\"    Manual: System Administration tools
.\"    Source: Samba 4.1
.\"  Language: English
.\"
.TH "NTDBBACKUP" "8" "03/12/2014" "Samba 4\&.1" "System Administration tools"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ntdbbackup \- tool for backing up and for validating the integrity of samba \&.ntdb files
.SH "SYNOPSIS"
.HP \w'\fBntdbbackup\fR\ 'u
\fBntdbbackup\fR [\-s\ suffix] [\-v] [\-h]
.SH "DESCRIPTION"
.PP
This tool is part of the
\fBsamba\fR(1)
suite\&.
.PP
\fBntdbbackup\fR
is a tool that may be used to backup samba \&.ntdb files\&. This tool may also be used to verify the integrity of the \&.ntdb files prior to samba startup or during normal operation\&. If it finds file damage and it finds a prior backup the backup file will be restored\&.
.SH "OPTIONS"
.PP
\-h
.RS 4
Get help information\&.
.RE
.PP
\-s suffix
.RS 4
The
\fB\-s\fR
option allows the administrator to specify a file backup extension\&. This way it is possible to keep a history of ntdb backup files by using a new suffix for each backup\&.
.RE
.PP
\-v
.RS 4
The
\fB\-v\fR
will check the database for damages (corrupt data) which if detected causes the backup to be restored\&.
.RE
.SH "COMMANDS"
.PP
\fIGENERAL INFORMATION\fR
.PP
The
\fBntdbbackup\fR
utility can safely be run at any time\&. It was designed so that it can be used at any time to validate the integrity of ntdb files, even during Samba operation\&. Typical usage for the command will be:
.PP
ntdbbackup [\-s suffix] *\&.ntdb
.PP
Before restarting samba the following command may be run to validate \&.ntdb files:
.PP
ntdbbackup \-v [\-s suffix] *\&.ntdb
.PP
Note that Samba 4 can use \&.tdb files instead, so you should use
\fBtdbbackup\fR
on those files\&.
.PP
Samba \&.tdb and \&.ntdb files are stored in various locations, be sure to run backup all \&.(n)tdb files on the system\&. Important files includes:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBsecrets\&.(n)tdb\fR
\- usual location is in the /usr/local/samba/private directory, or on some systems in /etc/samba\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fBpassdb\&.(n)tdb\fR
\- usual location is in the /usr/local/samba/private directory, or on some systems in /etc/samba\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fB*\&.tdb\fR
and
\fB*\&.ntdb\fR
located in the /usr/local/samba/var directory or on some systems in the /var/cache or /var/lib/samba directories\&.
.RE
.SH "VERSION"
.PP
This man page is correct for version 4 of the Samba suite\&.
.SH "SEE ALSO"
.PP
tdbbackup(8), ntdbrestore(8)
.SH "AUTHOR"
.PP
The original Samba software and related utilities were created by Andrew Tridgell\&. Samba is now developed by the Samba Team as an Open Source project similar to the way the Linux kernel is developed\&.
.PP
The ntdbbackup man page was written by Rusty Russell, based on the tdbbackup man page by John H Terpstra\&.
