'\" t
.\"     Title: ntdbrestore
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 03/12/2014
.\"    Manual: System Administration tools
.\"    Source: Samba 4.1
.\"  Language: English
.\"
.TH "NTDBRESTORE" "8" "03/12/2014" "Samba 4\&.1" "System Administration tools"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ntdbrestore \- tool for creating a NTDB file out of a ntdbdump output
.SH "SYNOPSIS"
.HP \w'\fBntdbrestore\fR\ 'u
\fBntdbrestore\fR {ntdbfilename}
.SH "DESCRIPTION"
.PP
This tool is part of the
\fBsamba\fR(1)
suite\&.
.PP
\fBntdbrestore\fR
is a very simple utility that \*(Aqrestores\*(Aq the contents of dump file into NTDB (New Trivial DataBase) file\&. The dump file is obtained from the ntdbdump or tdbdump commands\&.
.PP
This tool wait on the standard input for the content of the dump and will write the ntdb in the ntdbfilename parameter\&.
.PP
This tool can be used to translate between ntdb and tdb files by dumping and restoring\&.
.SH "VERSION"
.PP
This man page is correct for version 4 of the Samba suite\&.
.SH "SEE ALSO"
.PP
ntdbdump(8), tdbrestore(8)
.SH "AUTHOR"
.PP
The original Samba software and related utilities were created by Andrew Tridgell\&. Samba is now developed by the Samba Team as an Open Source project similar to the way the Linux kernel is developed\&. ntdbrestore was written by Rusty Russell based on tdbrestore, which was initially written by Volker Lendecke based on an idea by Simon McVittie\&.
.PP
The ntdbrestore man page was written by Rusty Russell, based on the tdbrestore man page by Matthieu Patou\&.
