# ex:ts=8
# New ports collection makefile for:	p5-CDB_Fiile
# Date created:			24 June 2001
# Whom:				Jon Nistor <nistor@snickers.org>
#
# $FreeBSD$
#

PORTNAME=	CDB_File
PORTVERSION=	0.94
CATEGORIES=	databases perl5
MASTER_SITES=	$(MASTER_SITE_PERL_CPAN)
MASTER_SITE_SUBDIR=	CDB_File
PKGNAMEPREFIX=	p5-

MAINTAINER=	nistor@snickers.org
COMMENT=	Perl5 interface to the CDB package

PERL_CONFIGURE=	yes

MAN3=		CDB_File.3

.include <bsd.port.mk>
