-- Remove version constraint on setuptools to be compatible with the port.
--- pyproject.toml.orig	2025-12-20 19:58:30 UTC
+++ pyproject.toml
@@ -1,5 +1,5 @@
 [build-system]
-requires = ["setuptools>=64.0"]
+requires = ["setuptools"]
 build-backend = "setuptools.build_meta"
 
 [project]
