# New ports collection makefile for:	calctool-2.4pl13
# Version required:			1.14.5
# Date created:				2 Dec 1996
# Whom:					nsayer@quack.kfu.com
#
# $Id: Makefile,v 1.1.1.1 1996/12/12 03:46:31 erich Exp $
#
 
DISTNAME=       calctool-2.4pl13
PKGNAME=        calctool-2.4.13
CATEGORIES=     math
MASTER_SITES=   ftp://ftp.kfu.com/pub/
 
MAINTAINER=     nsayer@quack.kfu.com

USE_X11=		yes
MAN1=		calctool.1

.include <bsd.port.mk>
