--- pyproject.toml.orig	2026-09-26 17:58:25 UTC
+++ pyproject.toml
@@ -6,8 +6,8 @@ dependencies = [
 name = "deepdiff"
 version = "9.1.0"
 dependencies = [
-  "cachebox>=5.2,<6",
-  "orderly-set>=5.5.0,<6",
+  "cachebox>=5.2",
+  "orderly-set>=5.5.0",
 ]
 requires-python = ">=3.10"
 authors = [
