--- properties/omada.properties.orig	2026-06-24 17:16:12 UTC
+++ properties/omada.properties
@@ -76,4 +76,8 @@ local.cluster.shard.hashAlgorithmStrategy=0
 #mongo.node.remote.ip=192.168.0.136
 #mongo.node.remote.port=27217
 ## Only one node can be true
-#mongo.node.start.init.enable=true
\ No newline at end of file
+#mongo.node.start.init.enable=true
+
+# FreeBSD: we must use an external mongodb
+mongo.external=true
+eap.mongod.uri=mongodb://localhost:27017/omada
