--- src/dictionary/user_dictionary_storage.h.orig	2019-03-04 18:35:55 UTC
+++ src/dictionary/user_dictionary_storage.h
@@ -72,13 +72,15 @@ namespace mozc {
 class Mutex;
 class ProcessMutex;
 
-// Inherit from ProtocolBuffer
-// TODO(hidehiko): Get rid of this implementation.
-class UserDictionaryStorage : public user_dictionary::UserDictionaryStorage {
+class UserDictionaryStorage {
  public:
   typedef user_dictionary::UserDictionary UserDictionary;
   typedef user_dictionary::UserDictionary::Entry UserDictionaryEntry;
 
+  // Instance of base class generated by Protocol Buffers compiler.
+  // Regular inheritance strongly discouraged.
+  user_dictionary::UserDictionaryStorage user_dictionary_storage_base;
+
   enum UserDictionaryStorageErrorType {
     USER_DICTIONARY_STORAGE_NO_ERROR = 0,  // default
     FILE_NOT_EXISTS,
