--- dlib/serialize.h.orig	2022-05-08 14:35:36 UTC
+++ dlib/serialize.h
@@ -626,6 +626,7 @@ namespace dlib
     USE_DEFAULT_INT_SERIALIZATION_FOR(unsigned long)
     USE_DEFAULT_INT_SERIALIZATION_FOR(uint64)
     USE_DEFAULT_INT_SERIALIZATION_FOR(int64)
+    USE_DEFAULT_INT_SERIALIZATION_FOR(char32_t)
 
     USE_DEFAULT_BYTE_SERIALIZATION_FOR(char)
     USE_DEFAULT_BYTE_SERIALIZATION_FOR(signed char)
