.\" Man page for ja-netscape
.\"
.\" Copyright (c) 1998, SADA Kenji
.\"
.\" $FreeBSD$
.\"
.Dd Oct 07, 1998
.Dt JA-NETSCAPE 1
.Sh 名称
.Nm ja-netscape
.Nd ネットスケープ製 WWW ブラウザの日本語対応版
.Sh 書式
.Nm ja-communicator, ja-navigator
.Op Ar url
.Nm netscape
.Op Ar url
.Sh 解説
.Nm ja-communicator/ja-navigator
はネットスケープ社が配布している FreeBSD 用の Communicator/Navigator に
日本語リソースを適用し、メニュー、ブックマーク、フォーム部品に日本語の表示を
可能とし、フォントの大きさの調整をするものです。
.Sh 構成 ports
.Dl 日本語化 Communicator version 4.08: japanese/communicator-4.08
.Dl 日本語化 Navigator version 4.08: japanese/navigator-4.08
.Dl 日本語化 Communicator version 4.5: japanese/communicator-4.5
.Dl 日本語化 Navigator version 4.5: japanese/communicator-4.5
.Dl フォントの設定 : japanese/netscape-fonts-1.0
.Sh 注意
FreeBSD 3.0-current + XFree86 3.3.3 で動作確認をしています。
.Pp
既存の ~/.netscape を継続して使用すると不具合があるかもしれません。
.Pp
起動用コマンド `/usr/X11R6/bin/netscape' は最後にインストールしたものの
起動コマンドの実体にリンクされて放置されます。
別のバージョンを起動したい場合は手で変更してください。
.Pp
Netscape Communicator / Navigator では、
ヘルプメニューを日本語で表示する場合には
/usr/lib/ 以下のディレクトリに設定ファイル
netscape.cfg を置かなくてはいけませんが、
FreeBSD ports の規約ではこのディレクトリ以下の内容を変更することはできません。
当 ports では、
環境の JA_NETSCAPE_INSTALL_CFG が空文字列以外の内容で設定されていたとき、
この設定を強行するようになっています。
.Pp
XFree86 3.3.2 から継続して使っていて、小さい文字が潰れる場合は、
/etc/XF86Config の Section "Files" に
FontPath "/usr/X11R6/lib/X11/fonts/local"
という行が含まれていなければ追加してください。
