.\"
.\" Copyright (C) 2005 Greg Lewis. All rights reserved.
.\" 
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" $FreeBSD$
.\"
.Dd February 24, 2005
.Os
.Dt CHECKVMS 1
.Sh NAME
.Nm checkvms
.Nd sanity check registered Java VMs
.Sh SYNOPSIS
.Nm checkvms
.Sh DESCRIPTION
Each registered Java VM is checked to ensure that it exists and that
all appropriate symbolic links for it have been created.
Non-existent Java VMs are unregistered and missing symbolic links are created.
The Java VMs are also sorted using a hard-coded ordering that will
sort them by version and affinity with
.Fx .
.Sh FILES
.Bl -tag -width indent
.It Pa %%PREFIX%%/etc/javavms
The location of the Java VM wrapper configuration file.
.El
.Sh SEE ALSO
.Xr javavm 1 ,
.Xr registervm 1 ,
.Xr unregistervm 1 ,
.Xr javavms 5
.Sh BUGS
The
.Nm
utility removes both blank lines and purely comment lines from
the Java VM wrapper configuration file.
