.\"
.\" Copyright (C) 2005 Greg Lewis. All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" $FreeBSD$
.\"
.Dd November 12, 2019
.Os
.Dt REGISTERVM 1
.Sh NAME
.Nm registervm ,
.Nm unregistervm
.Nd register/unregister a Java VM
.Sh SYNOPSIS
.Nm
.Ar /path/to/java
.Nm unregistervm
.Ar /path/to/java
.Sh DESCRIPTION
The
.Nm registervm
and
.Nm unregistervm
utilities allow a Java VM to be registered and unregistered as a possible
Java VM that
.Nm javavm
can use.
The registration process places the registered VM in the Java VM wrapper
configuration file in sorted order.
When unregistering the Java VM is removed from the Java VM wrapper
configuration file and will no longer be a possible choice for
.Nm javavm .
.Sh FILES
.Bl -tag -width indent
.It Pa %%PREFIX%%/etc/javavms
The location of the Java VM wrapper configuration file.
.El
.Sh EXAMPLES
.Bl -tag -width indent
.It %%PREFIX%%/bin/registervm %%LOCALBASE%%/openjdk11/bin/java
Register %%LOCALBASE%%/openjdk11/bin/java as a possible choice of
Java VM for
.Nm javavm .
.It %%PREFIX%%/bin/unregistervm %%LOCALBASE%%/openjdk11/bin/java
Remove %%LOCALBASE%%/openjdk11/bin/java as a possible choice of
Java VM for
.Nm javavm .
.El
.Sh SEE ALSO
.Xr checkvms 1 ,
.Xr javavm 1 ,
.Xr javavms 5
.Sh BUGS
The
.Nm
and
.Nm unregistervm
utilities remove both blank lines and purely comment lines from
the Java VM wrapper configuration file.
