# $FreeBSD$

PORTNAME=	xstdcmap
PORTVERSION=	1.0.3
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X standard colormap utility

LICENSE=	MIT

XORG_CAT=	app
USE_XORG=	xmu x11

PLIST_FILES=	bin/xstdcmap man/man1/xstdcmap.1.gz
.include <bsd.port.mk>
