# Created by: Kelly Yancey <kbyanc@posi.net>
# $FreeBSD$

PORTNAME=	LEGO-RCX
PORTVERSION=	1.01
CATEGORIES=	misc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Perl module for communicating with the Lego RCX brick via the IR tower

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
