--- pyproject.toml.orig	2024-02-05 21:17:48 UTC
+++ pyproject.toml
@@ -1,8 +1,8 @@ requires = [
 [build-system]
 build-backend = "mesonpy"
 requires = [
-    "Cython>=0.29.34,<3.1",
-    "meson-python>=0.15.0,<0.16.0",
+    "Cython>=0.29.34",
+    "meson-python>=0.15.0",
 ]
 
 [project]
@@ -43,6 +43,7 @@ f2py = 'numpy.f2py.f2py2e:main'
 
 [project.scripts]
 f2py = 'numpy.f2py.f2py2e:main'
+numpy-config = 'numpy._configtool:main'
 
 [project.entry-points.array_api]
 numpy = 'numpy.array_api'
