Obtained from:	https://github.com/dbt-labs/dbt-semantic-interfaces/commit/6a6176e08c6e36ad8f9b47c6364aaa8cbc408fe0

--- pyproject.toml.orig	2020-02-02 00:00:00 UTC
+++ pyproject.toml
@@ -25,8 +25,7 @@ dependencies = [
   "PyYAML>=6.0,<7",
   "more-itertools>=8.0,<11.0",
   "Jinja2>=3.1.6,<4",
-  # click 8.3 breaks our hatch install in strange ways
-  "click>=7.0,<8.3",
+  "click>=7.0,<8.4",
   "python-dateutil>=2.0,<3",
   "importlib_metadata>=6.0,<9",
   "typing-extensions>=4.4,<5",
