--- cmake/ETLVersion.cmake	2026-05-18 08:54:24.000000000 -0700
+++ cmake/ETLVersion.cmake	2026-05-29 23:29:49.996113000 -0700
@@ -97,13 +97,15 @@
 endmacro(GENERATENUMBER)
 
 
-if(DEFINED ENV{CI_ETL_DESCRIBE})
-	set(GIT_DESCRIBE $ENV{CI_ETL_DESCRIBE})
-else()
-	execute_process(COMMAND git describe --abbrev=7
-		WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
-		OUTPUT_STRIP_TRAILING_WHITESPACE
-		OUTPUT_VARIABLE GIT_DESCRIBE)
+if(NOT CMAKE_SYSTEM MATCHES "FreeBSD")
+	if(DEFINED ENV{CI_ETL_DESCRIBE})
+		set(GIT_DESCRIBE $ENV{CI_ETL_DESCRIBE})
+	else()
+		execute_process(COMMAND git describe --abbrev=7
+			WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
+			OUTPUT_STRIP_TRAILING_WHITESPACE
+			OUTPUT_VARIABLE GIT_DESCRIBE)
+	endif()
 endif()
 
 if(DEFINED ENV{CI_ETL_TAG})
