--- build/toolchain/toolchain.gni.orig	2025-01-01 00:00:00 UTC
+++ build/toolchain/toolchain.gni
@@ -64,7 +64,7 @@
   host_shlib_extension = ".dylib"
 } else if (host_os == "win") {
   host_shlib_extension = ".dll"
-} else if (host_os == "linux" || host_os == "aix" || host_os == "zos") {
+} else if (host_os == "linux" || host_os == "freebsd" || host_os == "aix" || host_os == "zos") {
   host_shlib_extension = ".so"
 } else {
   assert(false, "Host platform not supported")
