#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['flit_core',
 'flit_core.tests',
 'flit_core.tests.samples.ns1-pkg.ns1.pkg',
 'flit_core.tests.samples.package1',
 'flit_core.tests.samples.package1.subpkg',
 'flit_core.tests.samples.package1.subpkg2',
 'flit_core.vendor',
 'flit_core.vendor.tomli']

package_data = \
{'': ['*'],
 'flit_core.tests': ['samples/*',
                     'samples/conflicting_modules/*',
                     'samples/conflicting_modules/src/*',
                     'samples/constructed_version/*',
                     'samples/inclusion/*',
                     'samples/inclusion/LICENSES/*',
                     'samples/inclusion/doc/*',
                     'samples/inclusion/doc/subdir/*',
                     'samples/ns1-pkg/*',
                     'samples/ns1-pkg/ns1/*',
                     'samples/pep517/*',
                     'samples/pep621/*',
                     'samples/pep621_nodynamic/*'],
 'flit_core.tests.samples.package1': ['data_dir/*'],
 'flit_core.tests.samples.package1.subpkg': ['sp_data_dir/*'],
 'flit_core.vendor': ['tomli-1.2.3.dist-info/*']}

setup(name='flit_core',
      version='%%PORTVERSION%%',
      description='Distribution-building parts of Flit. See flit package for more information',
      author=None,
      author_email='Thomas Kluyver & contributors <thomas@kluyver.me.uk>',
      url=None,
      packages=packages,
      package_data=package_data,
      python_requires='>=3.6',
     )
