PORTNAME=	Data-Visitor-Tiny
PORTVERSION=	0.001
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	dgeo@centrale-med.fr
COMMENT=	Recursively walk data structures
WWW=		https://metacpan.org/release/Data-Visitor-Tiny

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

NO_ARCH=	yes

.include <bsd.port.mk>
