--- libcurl.vapi.orig	2016-09-25 11:53:37 UTC
+++ libcurl.vapi
@@ -236,7 +236,6 @@ namespace Native.Curl {
 		TOO_MANY_REDIRECTS,
 		UNKNOWN_OPTION,
 		TELNET_OPTION_SYNTAX,
-		PEER_FAILED_VERIFICATION,
 		GOT_NOTHING,
 		SSL_ENGINE_NOTFOUND,
 		SSL_ENGINE_SETFAILED,
@@ -244,7 +243,7 @@ namespace Native.Curl {
 		RECV_ERROR,
 		SSL_CERTPROBLEM,
 		SSL_CIPHER,
-		SSL_CACERT,
+		PEER_FAILED_VERIFICATION,
 		BAD_CONTENT_ENCODING,
 		LDAP_INVALID_URL,
 		FILESIZE_EXCEEDED,
