--- pyproject.toml.orig	2026-05-20 09:00:49 UTC
+++ pyproject.toml
@@ -9,7 +9,7 @@ readme = {file = "README.rst", content-type = "text/x-
     {name = "OpenStack", email = "openstack-discuss@lists.openstack.org"},
 ]
 readme = {file = "README.rst", content-type = "text/x-rst"}
-license = "Apache-2.0"
+license = {text = "Apache-2.0"}
 dynamic = ["version", "dependencies"]
 requires-python = ">=3.11"
 classifiers = [
