# ex:ts=8
# New ports collection makefile for:	ftpcube
# Date created:			Dec 13, 2001
# Whom:				ijliao
#
# $FreeBSD$
#

PORTNAME=	ftpcube
PORTVERSION=	0.3.2
CATEGORIES=	ftp python
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE}
MASTER_SITE_SUBDIR=	${PORTNAME}

MAINTAINER=	ports@FreeBSD.org

RUN_DEPENDS=	${PYTHON_SITELIBDIR}/gtk-1.2/gtk.py:${PORTSDIR}/x11-toolkits/py-gtk

USE_PYTHON=	yes
USE_PYDISTUTILS=	yes

.include <bsd.port.mk>
