--- pyproject.toml.orig	2022-11-09 12:37:21 UTC
+++ pyproject.toml
@@ -35,11 +35,7 @@ readme = {file = "README.md", content-type = "text/mar
 requires-python = ">=3.10"
 description = "Python library for Apache Arrow"
 readme = {file = "README.md", content-type = "text/markdown"}
-license = "Apache-2.0"
-license-files = [
-    "LICENSE.txt",
-    "NOTICE.txt",
-]
+license = {text = "Apache-2.0"}
 classifiers  = [
     'Programming Language :: Python :: 3.10',
     'Programming Language :: Python :: 3.11',
