# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD$

PORTNAME=	Contact_Vcard_Build
PORTVERSION=	1.1.2
CATEGORIES=	mail www pear

MAINTAINER=	joneum@FreeBSD.org
COMMENT=	PEAR class to build (create) and fetch vCard 2.1 and 3.0 text blocks

USES=	pear

.include <bsd.port.mk>
