'\" t
.\"     Title: SAMBA_GPOUPDATE
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 2017-07-11
.\"    Manual: System Administration tools
.\"    Source: Samba 4.8.0
.\"  Language: English
.\"
.TH "SAMBA_GPOUPDATE" "8" "2017\-07\-11" "Samba 4\&.8\&.0" "System Administration tools"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
samba_gpoupdate \- apply group policy
.SH "SYNOPSIS"
.HP \w'\fBsamba_gpoupdate\fR\ 'u
\fBsamba_gpoupdate\fR
.HP \w'\fBsamba_gpoupdate\fR\ 'u
\fBsamba_gpoupdate\fR [\fIoptions\fR]
.SH "DESCRIPTION"
.PP
This tool is part of the
\fBsamba\fR(1)
suite\&.
.PP
\fBsamba_gpoupdate\fR
a script for applying and unapplying Group Policy\&. Group Policy application is experimental\&. Currently this applies password policies (minimum/maximum password age, minimum password length, and password complexity) and kerberos policies (user/service ticket lifetime and renew lifetime)\&.
.SH "OPTIONS"
.PP
\fB\-h\fR,
\fB\-\-help\fR
show this help message and exit
.PP
\fB\-H \fRURL,
\fB\-\-url\fR=\fIURL\fR
URL for the samdb
.PP
\fB\-X\fR,
\fB\-\-unapply\fR
Unapply Group Policy
.PP
Samba Common Options:
.PP
\fB\-s \fRFILE,
\fB\-\-configfile\fR=\fIFILE\fR
Configuration file
.PP
\fB\-d \fRDEBUGLEVEL,
\fB\-\-debuglevel\fR=\fIDEBUGLEVEL\fR
debug level
.PP
\fB\-\-option\fR=\fIOPTION\fR
set smb\&.conf option from command line
.PP
\fB\-\-realm\fR=\fIREALM\fR
set the realm name
.PP
Version Options:
.PP
\fB\-V\fR,
\fB\-\-version\fR
Display version number
.PP
Credentials Options:
.PP
\fB\-\-simple\-bind\-dn\fR=\fIDN\fR
DN to use for a simple bind
.PP
\fB\-\-password\fR=\fIPASSWORD\fR
Password
.PP
\fB\-U \fRUSERNAME,
\fB\-\-username\fR=\fIUSERNAME\fR
Username
.PP
\fB\-W \fRWORKGROUP,
\fB\-\-workgroup\fR=\fIWORKGROUP\fR
Workgroup
.PP
\fB\-N\fR,
\fB\-\-no\-pass\fR
Don\*(Aqt ask for a password
.PP
\fB\-k \fRKERBEROS,
\fB\-\-kerberos\fR=\fIKERBEROS\fR
Use Kerberos
.PP
\fB\-\-ipaddress\fR=\fIIPADDRESS\fR
IP address of server
.PP
\fB\-P\fR,
\fB\-\-machine\-pass\fR
Use stored machine account password
.SH "AUTHOR"
.PP
The original Samba software and related utilities were created by Andrew Tridgell\&. Samba is now developed by the Samba Team as an Open Source project similar to the way the Linux kernel is developed\&.
