--- cmake/findDependencies.cmake.orig	2022-03-19 11:35:06 UTC
+++ cmake/findDependencies.cmake
@@ -1,15 +1,15 @@
 if (BUILD_GUI)
     if (BUILD_TESTS)
         if (NOT WITH_QCHART)
             find_package(Qt5 COMPONENTS Core Gui Widgets PrintSupport LinguistTools Help Test REQUIRED)
         else()
             find_package(Qt5 COMPONENTS Core Gui Widgets PrintSupport LinguistTools Help Test Charts REQUIRED)
         endif()
     else()
         if (NOT WITH_QCHART)
             find_package(Qt5 COMPONENTS Core Gui Widgets PrintSupport LinguistTools Help REQUIRED)
         else()
             find_package(Qt5 COMPONENTS Core Gui Widgets PrintSupport LinguistTools Help Charts REQUIRED)
         endif()
     endif()
 endif()
@@ -47,7 +43,7 @@ if (NOT USE_MATCHCOMPILER_OPT MATCHES "Off")
 endif()
 
 if (NOT USE_BUNDLED_TINYXML2)
-    find_package(tinyxml2 QUIET)
+    find_package(tinyxml2 REQUIRED)
     if (NOT tinyxml2_FOUND)
         find_library(tinyxml2_LIBRARIES tinyxml2)
         if (NOT tinyxml2_LIBRARIES)
@@ -56,5 +52,7 @@ if (NOT USE_BUNDLED_TINYXML2)
             message(STATUS "tinyxml2_LIBRARY: ${tinyxml2_LIBRARY}")
             set(tinyxml2_FOUND 1)
         endif()
+    else()
+        set(tinyxml2_LIBRARIES tinyxml2::tinyxml2)
     endif()
 endif()
