--- cmake/versions.cmake.orig	2020-05-10 09:31:19 UTC
+++ cmake/versions.cmake
@@ -1,5 +1,5 @@
 # Version for libraries CPP
-SET(VERSION "2.0")
+SET(VERSION "2.0.0")
 STRING(REGEX MATCHALL "[0-9]" VERSION_PARTS "${VERSION}")
 LIST(GET VERSION_PARTS 0 VERSION_MAJOR)
 LIST(GET VERSION_PARTS 1 VERSION_MINOR)
