--- mk-constants.py.orig	Sun Mar 19 17:21:07 2006
+++ mk-constants.py	Sun Mar 19 17:21:41 2006
@@ -79,6 +79,7 @@
 rcs = '   $Id: mk-constants.py,v 1.2 2004/06/07 05:34:49 wiml Exp $\n'
 fp.write(string.replace(rcs, '$', ''))
 fp.write('   Do not edit this file directly, it will be overwritten \n*/\n\n')
+fp.write('#define SWIG_PY_INT 1\n')
 fp.write('static struct swig_const_info const pcapmodule_DLT[] = {\n')
 for dlt in linktypes:
     fp.write('#ifdef %s\n' % (dlt,))
