PORTREVISION=	1
PKGNAMESUFFIX=	-lite

OPTIONS_EXCLUDE=	CAJA DBUS

MASTERDIR=	${.CURDIR}/../../graphics/atril
SLAVEPORT=	lite
DESCR=		${.CURDIR}/pkg-descr
PLIST=		${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
