--- comp/lexer.c.orig	2007-11-02 10:58:59.000000000 +0100
+++ comp/lexer.c	2009-03-03 23:33:08.000000000 +0100
@@ -2,7 +2,6 @@
 
 #line 4 "lexer.c"
 
-#define __STDC_VERSION__ 199901L
 #define  YY_INT_ALIGNED short int
 
 /* A lexical scanner generated by flex */
