--- asana.gemspec.orig	2015-12-13 14:23:30 UTC
+++ asana.gemspec
@@ -12,7 +12,7 @@ Gem::Specification.new do |s|
   s.date = "2015-12-03"
   s.description = "Official Ruby client for the Asana API"
   s.email = ["me@txus.io"]
-  s.files = [".codeclimate.yml", ".gitignore", ".rspec", ".rubocop.yml", ".travis.yml", ".yardopts", "CODE_OF_CONDUCT.md", "Gemfile", "Guardfile", "LICENSE.txt", "README.md", "Rakefile", "asana.gemspec", "bin/console", "bin/setup", "examples/Gemfile", "examples/Gemfile.lock", "examples/cli_app.rb", "examples/events.rb", "examples/omniauth_integration.rb", "examples/personal_access_token.rb", "lib/asana.rb", "lib/asana/authentication.rb", "lib/asana/authentication/oauth2.rb", "lib/asana/authentication/oauth2/access_token_authentication.rb", "lib/asana/authentication/oauth2/bearer_token_authentication.rb", "lib/asana/authentication/oauth2/client.rb", "lib/asana/authentication/token_authentication.rb", "lib/asana/client.rb", "lib/asana/client/configuration.rb", "lib/asana/errors.rb", "lib/asana/http_client.rb", "lib/asana/http_client/environment_info.rb", "lib/asana/http_client/error_handling.rb", "lib/asana/http_client/response.rb", "lib/asana/resource_includes/attachment_uploading.rb", "lib/asana/resource_includes/collection.rb", "lib/asana/resource_includes/event.rb", "lib/asana/resource_includes/event_subscription.rb", "lib/asana/resource_includes/events.rb", "lib/asana/resource_includes/registry.rb", "lib/asana/resource_includes/resource.rb", "lib/asana/resource_includes/response_helper.rb", "lib/asana/resources.rb", "lib/asana/resources/attachment.rb", "lib/asana/resources/project.rb", "lib/asana/resources/story.rb", "lib/asana/resources/tag.rb", "lib/asana/resources/task.rb", "lib/asana/resources/team.rb", "lib/asana/resources/user.rb", "lib/asana/resources/webhook.rb", "lib/asana/resources/workspace.rb", "lib/asana/ruby2_0_0_compatibility.rb", "lib/asana/version.rb", "lib/templates/index.js", "lib/templates/resource.ejs", "package.json"]
+  s.files = [".codeclimate.yml", ".gitignore", ".rspec", ".rubocop.yml", ".travis.yml", ".yardopts", "CODE_OF_CONDUCT.md", "Gemfile", "Guardfile", "LICENSE.txt", "README.md", "Rakefile", "asana.gemspec", "examples/Gemfile", "examples/Gemfile.lock", "examples/cli_app.rb", "examples/events.rb", "examples/omniauth_integration.rb", "examples/personal_access_token.rb", "lib/asana.rb", "lib/asana/authentication.rb", "lib/asana/authentication/oauth2.rb", "lib/asana/authentication/oauth2/access_token_authentication.rb", "lib/asana/authentication/oauth2/bearer_token_authentication.rb", "lib/asana/authentication/oauth2/client.rb", "lib/asana/authentication/token_authentication.rb", "lib/asana/client.rb", "lib/asana/client/configuration.rb", "lib/asana/errors.rb", "lib/asana/http_client.rb", "lib/asana/http_client/environment_info.rb", "lib/asana/http_client/error_handling.rb", "lib/asana/http_client/response.rb", "lib/asana/resource_includes/attachment_uploading.rb", "lib/asana/resource_includes/collection.rb", "lib/asana/resource_includes/event.rb", "lib/asana/resource_includes/event_subscription.rb", "lib/asana/resource_includes/events.rb", "lib/asana/resource_includes/registry.rb", "lib/asana/resource_includes/resource.rb", "lib/asana/resource_includes/response_helper.rb", "lib/asana/resources.rb", "lib/asana/resources/attachment.rb", "lib/asana/resources/project.rb", "lib/asana/resources/story.rb", "lib/asana/resources/tag.rb", "lib/asana/resources/task.rb", "lib/asana/resources/team.rb", "lib/asana/resources/user.rb", "lib/asana/resources/webhook.rb", "lib/asana/resources/workspace.rb", "lib/asana/ruby2_0_0_compatibility.rb", "lib/asana/version.rb", "lib/templates/index.js", "lib/templates/resource.ejs", "package.json"]
   s.homepage = "https://github.com/asana/ruby-asana"
   s.licenses = ["MIT"]
   s.required_ruby_version = Gem::Requirement.new("~> 2.0")
