# New ports collection makefile for:    pl-aspell
# Date created:                         3 September 2002
# Whom:                                 Thierry Thomas <thierry@pompo.net>
#
# $FreeBSD$
#

PORTNAME=	aspell
CATEGORIES=	polish

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Aspell with Polish dictionary

MASTERDIR=	${.CURDIR}/../../textproc/aspell

ASPELL_PL=	tak

.include "${MASTERDIR}/Makefile"
