.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH "BTRENAME" 1 "Jan 18 2003"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
btrename \- change the suggested filename inside a bittorrent file
.SH SYNOPSIS
\fBbttrack\fP \fItorrent\fP \fInewfilename\fP
.SH DESCRIPTION
This manual page documents briefly the \fBbtrename\fP
command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBbtrename\fP is a program which will change the suggested 
filename presented to the user for a bittorrent file. This 
will make the downloader save it as a different name by default.
The torrent specified by the \fItorrent\fP option is modified 
in-place, changing the suggested filename to \fInewfilename\fP.

.SH SEE ALSO
.BR bittorrent-downloader (1),
.BR btmakemetafile (1),
.BR btreannounce (1).
.br
.SH AUTHOR
This manual page was written by Michael Janssen <jamuraa@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
