# Created by: Michael Moll <kvedulv at kvedulv.de>
# $FreeBSD$

PORTNAME=	kafo_parsers
PORTVERSION=	0.1.5
CATEGORIES=	devel ruby
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Parser for puppet modules

LICENSE=	GPLv3

RUN_DEPENDS=	rubygem-json>=0:devel/rubygem-json

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
