# New ports collection makefile for:	zh-dia
# Date created:			6 March 2001
# Whom:				Jing-Tang Keith Jang <keith@FreeBSD.org>
#
# $FreeBSD$
#

CATEGORIES=	chinese graphics gnome

PATCH_SITES=	ftp://freebsd.sinica.edu.tw/pub/keith/
PATCHFILES=	zh-dia-0.86.diff.gz

MAINTAINER=	keith@FreeBSD.org

MASTERDIR=	${.CURDIR}/../../graphics/dia

MD5_FILE=	${.CURDIR}/distinfo

# For png output
USE_GNOMELIBS=	yes

.include "${MASTERDIR}/Makefile"
