--- pyproject.toml.orig	2026-03-05 18:09:51 UTC
+++ pyproject.toml
@@ -5,7 +5,7 @@ requires-python = ">=3.9"
 description = "Fix common misspellings in text files"
 readme = { file = "README.rst", content-type = "text/x-rst" }
 requires-python = ">=3.9"
-license = "GPL-2.0-only"
+license = { text = "GPL-2.0-only" }
 authors = [
     {name = "Lucas De Marchi", email = "lucas.de.marchi@gmail.com"},
 ]
@@ -65,7 +65,7 @@ build-backend = "setuptools.build_meta"
 
 [build-system]
 build-backend = "setuptools.build_meta"
-requires = ["setuptools>=77", "setuptools_scm[toml]>=6.2, != 8.0.0"]
+requires = ["setuptools>=61", "setuptools_scm[toml]>=6.2, != 8.0.0"]
 
 [tool.setuptools_scm]
 write_to = "codespell_lib/_version.py"
@@ -74,6 +74,7 @@ exclude = [
 exclude = [
     "dist",
     "snap",
+    "tools",
 ]
 
 [tool.setuptools.package-data]
