# New ports collection makefile for:    xvile
# Version required:     7.1
# Date created:         Wed Nov 26, 1996
# Whom:                 pgf
#
# $Id: Makefile,v 1.11 1996/12/03 12:53:38 obrien Exp $
#

DISTNAME=	vile-7.1
PKGNAME=	xvile-7.1
CATEGORIES=	editors
MASTER_SITES=	ftp://ftp.clark.net/pub/dickey/vile/
EXTRACT_SUFX=	.tgz

MAINTAINER=	gj@freebsd.org

MAKEFILE=	makefile
GNU_CONFIGURE=	yes
CONFIGURE_ARGS= --with-screen=x11
MAN1=		xvile.1

.include <bsd.port.mk>
