# New ports collection makefile for:	uriparser
# Date Created:				31 Mar 2007
# Whom:					Ed Schouten <ed@fxq.nl>
#
# $FreeBSD$
#

PORTNAME=	uriparser
PORTVERSION=	0.6.3
CATEGORIES=	net
MASTER_SITES=	SF

MAINTAINER=	ed@fxq.nl
COMMENT=	URI parsing library

GNU_CONFIGURE=	yes
USE_BZIP2=	yes
USE_AUTOTOOLS=	libtool:15
USE_LDCONFIG=	yes

.include <bsd.port.mk>
