--- pyproject.toml.orig	2026-08-13 10:31:25 UTC
+++ pyproject.toml
@@ -5,7 +5,6 @@ requires = [
 build-backend = "setuptools.build_meta"
 requires = [
     "setuptools",  # >= 59 ?
-    "ctypesgen @ git+https://github.com/pypdfium2-team/ctypesgen@pypdfium2",
     "packaging",
     # NB: wheel is no longer needed with setuptools >= v70.1.0, but we still specify it for backward compatibility
     "wheel !=0.38.0, !=0.38.1",
