.Dd October, 1996
.Dt UULIB 3
.Sh NAME
.Nm libuu
.Nd Decoding Library Programming Interface
.Sh DESCRIPTION
This library is used for encoding/unencoding uuencoded, xxencoded, 
and Base64 encoded files.  It can also unencode BinHex files (but not
encode them).
.Sh DOCUMENTATION
Documentation for uulib is contained in FUNKYTOKENHEREshare/doc/uulib.
.Sh AUTHOR
.Ar Libuu
is written by
.Nm Frank Pilhofer <fp@informatik.uni-frankfurt.de>
with thanks to
.Nm Michael Newcomb,
.Nm Nico Mak,
.Nm Stephane Barizien,
.Nm Kris Karas,
and
.Nm Joachim Meyn.
.Sh SEE ALSO
.Xr uudeview 1
.Xr xdeview 1

http://zeus.informatik.uni-frankfurt.de/~fp/uudeview
.Sh HISTORY
See the file FUNKYTOKENHEREshare/doc/uulib/HISTORY.
