.Dd September, 2002
.Dt UULIB 3
.Sh NAME
.Nm libuu
.Nd Decoding Library Programming Interface
.Sh DESCRIPTION
This library is used for encoding and decoding files that are
uuencoded, xxencoded, Base64-encoded, BinHex-encoded, and yEnc-encoded.
.Sh DOCUMENTATION
Documentation for uulib is contained in FUNKYTOKENHEREshare/doc/uulib.
.Sh AUTHOR
.Ar Libuu
is written by
.Nm Frank Pilhofer <fp@fpx.de>
with thanks to
.Nm Michael Newcomb,
.Nm Nico Mak,
.Nm Stephane Barizien,
.Nm Kris Karas,
and
.Nm Joachim Meyn.
.Sh SEE ALSO
.Xr uudeview 1
.Xr xdeview 1

http://www.fpx.de/fp/Software/UUDeview/
.Sh HISTORY
See the file FUNKYTOKENHEREshare/doc/uulib/HISTORY.
