--- r10k.gemspec.orig	2021-04-30 19:31:50 UTC
+++ r10k.gemspec
@@ -29,8 +29,8 @@ Gem::Specification.new do |s|
       s.add_runtime_dependency(%q<multi_json>.freeze, ["~> 1.10"])
       s.add_runtime_dependency(%q<puppet_forge>.freeze, ["~> 2.3.0"])
       s.add_runtime_dependency(%q<gettext-setup>.freeze, ["~> 0.24"])
-      s.add_runtime_dependency(%q<fast_gettext>.freeze, ["~> 1.1.0"])
-      s.add_runtime_dependency(%q<gettext>.freeze, [">= 3.0.2", "< 3.3.0"])
+      s.add_runtime_dependency(%q<fast_gettext>.freeze, ["~> 1.1"])
+      s.add_runtime_dependency(%q<gettext>.freeze, [">= 3.0.2", "< 3.4.0"])
       s.add_development_dependency(%q<rspec>.freeze, ["~> 3.1"])
       s.add_development_dependency(%q<rake>.freeze, [">= 0"])
       s.add_development_dependency(%q<yard>.freeze, ["~> 0.9.11"])
@@ -42,8 +42,8 @@ Gem::Specification.new do |s|
       s.add_dependency(%q<multi_json>.freeze, ["~> 1.10"])
       s.add_dependency(%q<puppet_forge>.freeze, ["~> 2.3.0"])
       s.add_dependency(%q<gettext-setup>.freeze, ["~> 0.24"])
-      s.add_dependency(%q<fast_gettext>.freeze, ["~> 1.1.0"])
-      s.add_dependency(%q<gettext>.freeze, [">= 3.0.2", "< 3.3.0"])
+      s.add_dependency(%q<fast_gettext>.freeze, ["~> 1.1"])
+      s.add_dependency(%q<gettext>.freeze, [">= 3.0.2", "< 3.4.0"])
       s.add_dependency(%q<rspec>.freeze, ["~> 3.1"])
       s.add_dependency(%q<rake>.freeze, [">= 0"])
       s.add_dependency(%q<yard>.freeze, ["~> 0.9.11"])
@@ -56,8 +56,8 @@ Gem::Specification.new do |s|
     s.add_dependency(%q<multi_json>.freeze, ["~> 1.10"])
     s.add_dependency(%q<puppet_forge>.freeze, ["~> 2.3.0"])
     s.add_dependency(%q<gettext-setup>.freeze, ["~> 0.24"])
-    s.add_dependency(%q<fast_gettext>.freeze, ["~> 1.1.0"])
-    s.add_dependency(%q<gettext>.freeze, [">= 3.0.2", "< 3.3.0"])
+    s.add_dependency(%q<fast_gettext>.freeze, ["~> 1.1"])
+    s.add_dependency(%q<gettext>.freeze, [">= 3.0.2", "< 3.4.0"])
     s.add_dependency(%q<rspec>.freeze, ["~> 3.1"])
     s.add_dependency(%q<rake>.freeze, [">= 0"])
     s.add_dependency(%q<yard>.freeze, ["~> 0.9.11"])
