# New ports collection makefile for:	semi-1.13.x for emacs20
# Date created:		23 September 1998
# Whom:			Shigeyuki FUKUSHIMA <shige@FreeBSD.org>
#
# $FreeBSD$
#

MAINTAINER=	shige@FreeBSD.org

# This is a slave port.
PORTCLASS=	slave

MASTERDIR=	${.CURDIR}/../../editors/semi113

# emacs port setup
EMACS_PORT_NAME=	emacs20

.include <${MASTERDIR}/Makefile>
