--- offapi/com/sun/star/setup/OSType.idl.orig	Mon Dec 18 16:34:26 2000
+++ offapi/com/sun/star/setup/OSType.idl	Sun Jul 21 01:37:15 2002
@@ -88,6 +88,9 @@
 	UNIX_LINUX,
 
 	// DocMerge: empty anyway
+	UNIX_FREEBSD,
+
+	// DocMerge: empty anyway
 	UNIX_HP,
 
 	// DocMerge: empty anyway
