PORTNAME=	qqc2-breeze-style
DISTVERSION=	${KDE_PLASMA_VERSION}
CATEGORIES=	x11-themes kde kde-plasma

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Breeze inspired QQC2 Style

USES=		cmake kde:6 qt:6 tar:xz
USE_KDE=	iconthemes kirigami2 kquickcharts \
		ecm:build
USE_QT=		base declarative

.include <bsd.port.mk>
