--- chrome/browser/resources/settings/appearance_page/appearance_page.ts.orig	2022-05-25 04:00:49 UTC
+++ chrome/browser/resources/settings/appearance_page/appearance_page.ts
@@ -146,7 +146,7 @@ export class SettingsAppearancePageElement extends
             'prefs.autogenerated.theme.policy.color.controlledBy)',
       },
 
-      // <if expr="is_linux and not chromeos_ash and not chromeos_lacros">
+      // <if expr="is_posix and not chromeos_ash and not chromeos_lacros">
       /**
        * Whether to show the "Custom Chrome Frame" setting.
        */
@@ -168,7 +168,7 @@ export class SettingsAppearancePageElement extends
       'themeChanged_(' +
           'prefs.extensions.theme.id.value, useSystemTheme_, isForcedTheme_)',
 
-      // <if expr="is_linux and not chromeos_ash">
+      // <if expr="is_posix and not chromeos_ash">
       // NOTE: this pref only exists on Linux.
       'useSystemThemePrefChanged_(prefs.extensions.theme.use_system.value)',
       // </if>
@@ -187,7 +187,7 @@ export class SettingsAppearancePageElement extends
   private showReaderModeOption_: boolean;
   private isForcedTheme_: boolean;
 
-  // <if expr="is_linux and not chromeos_ash and not chromeos_lacros">
+  // <if expr="is_posix and not chromeos_ash and not chromeos_lacros">
   private showCustomChromeFrame_: boolean;
   // </if>
 
@@ -265,7 +265,7 @@ export class SettingsAppearancePageElement extends
     this.appearanceBrowserProxy_.useDefaultTheme();
   }
 
-  // <if expr="is_linux and not chromeos_ash">
+  // <if expr="is_posix and not chromeos_ash">
   private useSystemThemePrefChanged_(useSystemTheme: boolean) {
     this.useSystemTheme_ = useSystemTheme;
   }
@@ -326,10 +326,10 @@ export class SettingsAppearancePageElement extends
     }
 
     let i18nId;
-    // <if expr="is_linux and not chromeos_ash and not chromeos_lacros">
+    // <if expr="is_posix and not chromeos_ash and not chromeos_lacros">
     i18nId = useSystemTheme ? 'systemTheme' : 'classicTheme';
     // </if>
-    // <if expr="not is_linux or chromeos_ash or chromeos_lacros">
+    // <if expr="not is_posix or chromeos_ash or chromeos_lacros">
     i18nId = 'chooseFromWebStore';
     // </if>
     this.themeSublabel_ = this.i18n(i18nId);
