# Created by: fjoe@FreeBSD.org
# $FreeBSD$

MAINTAINER=	fjoe@FreeBSD.org
COMMENT=	The wxWidgets GUI toolkit contributed libraries

WXGTK_FLAVOR=	gtk2-contrib
MASTERDIR=	${.CURDIR}/../wxgtk26

NO_STAGE=	yes
.include "${MASTERDIR}/Makefile"
