--- build/top.mk.orig	Mon Apr  7 22:23:26 2003
+++ build/top.mk	Mon Jul  7 05:35:52 2003
@@ -192,6 +192,8 @@
 SLAPD_LIBS = @SLAPD_LIBS@ @SLAPD_PERL_LDFLAGS@ @SLAPD_SQL_LDFLAGS@ @SLAPD_SQL_LIBS@ @SLAPD_SLP_LIBS@
 SLURPD_LIBS = @SLURPD_LIBS@
 
+SLAPI_LIBS = @SLAPI_LIBS@
+
 # Our Defaults
 CC = $(AC_CC)
 DEFS = $(LDAP_INCPATH) $(XINCPATH) $(XDEFS) $(AC_DEFS) $(DEFINES)
