# Created by: Pav Lucistnik <pav@FreeBSD.org>
# $FreeBSD$

PORTNAME=	OLE
DISTVERSION=	1.0.0RC3
CATEGORIES=	devel www pear

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	PEAR class for reading and writing OLE containers

USES=		pear

.include <bsd.port.mk>
