--- cmake/modules/FindPDAL.cmake.orig	2024-02-22 20:36:47 UTC
+++ cmake/modules/FindPDAL.cmake
@@ -35,17 +35,10 @@ FIND_LIBRARY(PDAL_CPP_LIBRARY NAMES pdalcpp libpdalcpp
   )
 FIND_LIBRARY(PDAL_CPP_LIBRARY NAMES pdalcpp libpdalcpp)
 
-FIND_LIBRARY(PDAL_UTIL_LIBRARY NAMES pdal_util libpdal_util PATHS
-  "$ENV{LIB_DIR}/lib"
-  c:/msys/local/lib
-  NO_DEFAULT_PATH
-  )
-FIND_LIBRARY(PDAL_UTIL_LIBRARY NAMES pdal_util libpdal_util)
-
-IF (PDAL_INCLUDE_DIR AND PDAL_CPP_LIBRARY AND PDAL_UTIL_LIBRARY)
+IF (PDAL_INCLUDE_DIR AND PDAL_CPP_LIBRARY)
    SET(PDAL_FOUND TRUE)
-   SET(PDAL_LIBRARIES ${PDAL_CPP_LIBRARY} ${PDAL_UTIL_LIBRARY})
-ENDIF (PDAL_INCLUDE_DIR AND PDAL_CPP_LIBRARY AND PDAL_UTIL_LIBRARY)
+   SET(PDAL_LIBRARIES ${PDAL_CPP_LIBRARY})
+ENDIF (PDAL_INCLUDE_DIR AND PDAL_CPP_LIBRARY)
 
 IF (PDAL_FOUND)
    IF (NOT PDAL_FIND_QUIETLY)
