# New ports collection makefile for:	p5-Thread-Pool-Simple
# Date created:		2007-07-31
# Whom:			Andrej Zverev <az@FreeBSD.org>
#
# $FreeBSD$
#

PORTNAME=	Thread-Pool-Simple
PORTVERSION=	0.23
CATEGORIES=	devel perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Thread
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Simple thread-pool implementaion

PERL_CONFIGURE=	5.8.0+

MAN3=	Thread::Pool::Simple.3

.include <bsd.port.mk>
