From: Daniel Sheppard <dans@dansheps.com>
Date: Tue, 24 Jan 2023 13:51:57 -0600
Subject: [PATCH] Update for missing migrations

Obtained from:

https://github.com/DanSheps/netbox-secretstore/commit/9c3f69e5af6f5e8d6af11f5c8ea41433ef51145c

--- netbox_secretstore/migrations/0006_alter_secret_custom_field_data_and_more.py.orig	2023-03-16 06:29:56 UTC
+++ netbox_secretstore/migrations/0006_alter_secret_custom_field_data_and_more.py
@@ -0,0 +1,24 @@
+# Generated by Django 4.1.4 on 2023-01-24 19:50
+
+from django.db import migrations, models
+import utilities.json
+
+
+class Migration(migrations.Migration):
+
+    dependencies = [
+        ('netbox_secretstore', '0005_alter_secret_created_alter_secret_id_and_more'),
+    ]
+
+    operations = [
+        migrations.AlterField(
+            model_name='secret',
+            name='custom_field_data',
+            field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
+        ),
+        migrations.AlterField(
+            model_name='secretrole',
+            name='custom_field_data',
+            field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
+        ),
+    ]
