# New ports collection makefile for:	GNOME Metacity Themes
# Date created:				06 Mar 2004
# Whom:					Remington Lang <MrL0L@charter.net>
#
# $FreeBSD$

# Port logic stolen from x11-themes/kde-icons-noia by
# lioux@.

PORTNAME=	metacity-themes
PORTVERSION=	20040306
PORTREVISION=	5
CATEGORIES=	x11-themes gnome
MASTER_SITES=	# Empty
DISTFILES=	# Empty
EXTRACT_ONLY=	# Empty

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Meta-port for Gnome Metacity themes

RUN_DEPENDS=	${LOCALBASE}/share/themes/microgui/metacity-1/metacity-theme-1.xml:${PORTSDIR}/x11-themes/metacity-theme-microgui

NO_BUILD=	yes

do-install:    # Empty

.include <bsd.port.mk>
