.TH connect4 6 "8th May, 1997" "Version 3.2"
.SH NAME
\fBconnect4\fP - a game of placement
.SH SYNOPSIS
.IP "connect4" 10
\fB[ -Shv12 ]\fP  
.LP
.SH DESCRIPTION
\fBconnect4(6)\fP is a simple game where you must line up four tokens
in a row.
.SH OPTIONS
.IP "\fB-S\fP"
Display high scores
.IP "\fB-h\fP"
Help on command line switches
.IP "\fB-v\fP"
Display version number
.IP "\fB-1\fP"
Player has first move
.IP "\fB-2\fP"
Computer has first move
.SH NOTES
.LP
The real-life version of connect4 is basically an upright hollow board
with several vertical columns and windows. Tokens are placed into the
columns alternately by each player until one of the players has four
tokens in a row. These four tokens must be adjacent to each other but
the series of four can be in any direction.
.sp
Tokens are placed into a column by typing the number of the column
printed at the top of the screen. 
.sp 
To exit the game type \fBq\fP or \fBx\fP and \fBctrl-L\fP redraws the screen.
.SH BUGS
There are bound to be bugs in this program. Use at your own risk as no
guarantee will be made that this software will not break your system
in any way.
.SH AUTHORS
connect4 came from comp.sources.games Volume 6, Issue 51
.br
Submitted by Terry Jones <tcjones@watdragon.waterloo.edu> April,
1989
.sp
Man page by Joel Sutton <sutton@aardvark.apana.org.au>
.SH COPYRIGHT
Connect Four is undoubtedly a trade mark or some such of Milton Bradley.