--- pyproject.toml.orig	2026-05-20 08:28:34 UTC
+++ pyproject.toml
@@ -1,8 +1,6 @@
 [build-system]
-requires = [
-  "sphinx-theme-builder>=0.3.2"
-]
-build-backend = "sphinx_theme_builder"
+requires = ["flit-core >= 3.9.0"]
+build-backend = "flit_core.buildapi"
 
 [tool.sphinx-theme-builder]
 node-version = "22.9.0"
@@ -22,7 +20,7 @@ dependencies = [
 readme = "README.md"
 requires-python = ">=3.10"
 dependencies = [
-  "sphinx>=8.0,<10",
+  "sphinx>=5.0,<10",
   "beautifulsoup4",
   "docutils!=0.17.0",
   "Babel",
