--- manifest.inc.orig	Sat Jan 24 22:45:58 2004
+++ manifest.inc	Sun Jan 25 11:25:43 2004
@@ -28,9 +28,6 @@
  */
 
 $versions=array();
-$versions['AUTHORS']='1.16';
-$versions['LICENSE.txt']='1.2';
-$versions['README']='1.28.6.1';
 $versions['Version.php']='1.496.2.40';
 $versions['add_comment.php']='1.26.2.1';
 $versions['add_photo.php']='1.18';
@@ -39,7 +36,6 @@
 $versions['album_permissions.php']='1.33.2.1';
 $versions['albums.php']='1.109.2.1';
 $versions['captionator.php']='1.36';
-$versions['configure.bat']='1.2';
 $versions['configure.sh']='1.4';
 $versions['copy_photo.php']='1.3';
 $versions['create_user.php']='1.30';
@@ -77,7 +73,6 @@
 $versions['rotate_photo.php']='1.37';
 $versions['save_photos.php']='1.80';
 $versions['search.php']='1.45';
-$versions['secure.bat']='1.2';
 $versions['secure.sh']='1.5';
 $versions['session.php']='1.26';
 $versions['slideshow.php']='1.41.2.2';
