--- src/cfg-lex.l.orig	Wed Mar  5 13:14:04 2003
+++ src/cfg-lex.l	Wed Mar  5 13:14:13 2003
@@ -80,7 +80,7 @@
 	{ "dir_owner",		KW_DIR_OWNER },
 	{ "dir_group",		KW_DIR_GROUP },
         { "dir_perm",           KW_DIR_PERM },
-        { "template",           KW_FILE_TEMPLATE },
+/*        { "template",           KW_FILE_TEMPLATE },*/
         { "template-escape",	KW_TEMPLATE_ESCAPE },
         { "template_escape",	KW_TEMPLATE_ESCAPE },
  	{ "keep-alive",         KW_KEEP_ALIVE },
