# New ports collection makefile for:	py-breve
# Date created:		30 July 2008
# Whom:			Andriy Pylypenko <bamby@sippysoft.com>
#
# $FreeBSD$
#

PORTNAME=	dal
PORTVERSION=	20081016
PORTREVISION=	2
CATEGORIES=	devel python
MASTER_SITES=	http://download.sippysoft.com/bamby/
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	bamby@sippysoft.com
COMMENT=	A database abstraction layer for Python

USE_PYTHON=	2.5+
USE_PYDISTUTILS=	easy_install

.include <bsd.port.mk>
