#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['more_itertools']

package_data = \
{'': ['*']}

setup(name='more-itertools',
      version='%%PORTVERSION%%',
      description='More routines for operating on iterables, beyond itertools',
      author=None,
      author_email='Erik Rose <erikrose@grinchcentral.com>',
      url=None,
      packages=packages,
      package_data=package_data,
      python_requires='>=3.5',
     )
