--- pyproject.toml.orig	2026-05-18 09:01:46 UTC
+++ pyproject.toml
@@ -9,7 +9,7 @@ authors = [
 authors = [
     {name = "OpenStack", email = "openstack-discuss@lists.openstack.org"},
 ]
-license = "Apache-2.0"
+license = {text = "Apache-2.0"}
 requires-python = ">=3.10"
 classifiers = [
     "Environment :: OpenStack",
