--- src/main-dynamic-f90.inc~	Tue May 17 02:22:50 2005
+++ src/main-dynamic-f90.inc	Tue Jan  9 17:39:08 2007
@@ -1,5 +1,5 @@
       real*8,    dimension(:),allocatable :: cw_orb
-      real*8,    dimension(:),allocatable :
+      real*8,    dimension(:),allocatable :: cw_coul
       real*8,    dimension(:),allocatable :: cw_exch
       real*8,    dimension(:),allocatable :: cw_suppl
       real*8,    dimension(:),allocatable :: cw_sctch
