--- setup.py.orig	2026-05-01 00:40:41 UTC
+++ setup.py
@@ -50,95 +50,95 @@ DEPENDENCIES = [
 ]
 
 DEPENDENCIES = [
-    "antlr4-python3-runtime~=4.13.1",
-    'azure-appconfiguration~=1.7.2',
-    'azure-ai-projects~=1.0.0',
-    'azure-batch==15.0.0b1',
+    "antlr4-python3-runtime>=4.13.1",
+    'azure-appconfiguration>=1.7.2',
+    'azure-ai-projects>=1.0.0',
+    'azure-batch>=15.0.0b1',
     'azure-cli-core=={}'.format(VERSION),
-    'azure-cosmos~=3.0,>=3.0.2',
-    'azure-data-tables==12.4.0',
+    'azure-cosmos>=3.0.2',
+    'azure-data-tables>=12.4.0',
     'azure-datalake-store~=1.0.1',
-    'azure-keyvault-administration==4.4.0',
-    'azure-keyvault-certificates==4.7.0',
-    'azure-keyvault-keys==4.11.0',
-    'azure-keyvault-secrets==4.7.0',
-    'azure-keyvault-securitydomain==1.0.0b1',
-    'azure-mgmt-advisor==9.0.0',
-    'azure-mgmt-apimanagement==4.0.0',
-    'azure-mgmt-appconfiguration==6.0.0b1',
-    'azure-mgmt-appcontainers==2.0.0',
-    'azure-mgmt-applicationinsights~=1.0.0',
-    'azure-mgmt-authorization==5.0.0b1',
-    'azure-mgmt-batchai==7.0.0b1',
-    'azure-mgmt-batch~=17.3.0',
-    'azure-mgmt-billing==6.0.0',
-    'azure-mgmt-botservice~=2.0.0b3',
-    'azure-mgmt-cdn==12.0.0',
-    'azure-mgmt-cognitiveservices~=15.0.0b1',
-    'azure-mgmt-compute~=34.1.0',
-    'azure-mgmt-containerinstance==10.2.0b1',
-    'azure-mgmt-containerregistry==15.1.0b1',
-    'azure-mgmt-containerregistrytasks==1.0.0b1',
-    'azure-mgmt-containerservice~=41.1.0',
-    'azure-mgmt-cosmosdb==9.9.0',
-    'azure-mgmt-datalake-store~=1.1.0b1',
-    'azure-mgmt-datamigration~=10.0.0',
-    'azure-mgmt-eventgrid==10.2.0b2',
-    'azure-mgmt-eventhub~=12.0.0b1',
-    'azure-mgmt-extendedlocation==1.0.0b2',
-    'azure-mgmt-hdinsight==9.1.0b2',
-    'azure-mgmt-imagebuilder~=1.3.0',
-    'azure-mgmt-iotcentral~=10.0.0b1',
-    'azure-mgmt-iothub==5.0.0b1',
-    'azure-mgmt-iothubprovisioningservices==1.1.0',
-    'azure-mgmt-keyvault==13.0.0',
-    'azure-mgmt-loganalytics==13.0.0b4',
-    'azure-mgmt-managementgroups~=1.0.0',
-    'azure-mgmt-maps~=2.0.0',
-    'azure-mgmt-marketplaceordering==1.1.0',
-    'azure-mgmt-media~=9.0',
-    'azure-mgmt-monitor~=7.0.0b1',
-    'azure-mgmt-msi~=7.1.0',
-    'azure-mgmt-netapp~=10.1.0',
-    'azure-mgmt-policyinsights==1.1.0b4',
-    'azure-mgmt-postgresqlflexibleservers==3.0.0b1',
-    'azure-mgmt-privatedns~=1.0.0',
-    'azure-mgmt-rdbms==10.2.0b17',
-    'azure-mgmt-mysqlflexibleservers==1.1.0b2',
-    'azure-mgmt-recoveryservicesbackup~=9.2.0',
-    'azure-mgmt-recoveryservices~=4.0.0',
-    'azure-mgmt-redhatopenshift~=3.0.0',
-    'azure-mgmt-redis~=14.5.0',
-    'azure-mgmt-resource==24.0.0',
-    'azure-mgmt-resource-deployments==1.0.0b1',
-    'azure-mgmt-resource-deploymentscripts==1.0.0b1',
-    'azure-mgmt-resource-deploymentstacks==1.0.0',
-    'azure-mgmt-resource-templatespecs==1.0.0b1',
-    'azure-mgmt-search~=9.0',
-    'azure-mgmt-security==6.0.0',
-    'azure-mgmt-servicebus~=10.0.0b1',
-    'azure-mgmt-servicefabricmanagedclusters==2.1.0b1',
-    'azure-mgmt-servicelinker==1.2.0b3',
-    'azure-mgmt-servicefabric~=2.1.0',
-    'azure-mgmt-signalr==2.0.0b2',
-    'azure-mgmt-sqlvirtualmachine==1.0.0b5',
-    'azure-mgmt-sql==4.0.0b22',
-    'azure-mgmt-storage==24.0.0',
-    'azure-mgmt-synapse==2.1.0b5',
-    'azure-mgmt-trafficmanager~=1.0.0',
-    'azure-mgmt-web==9.0.0',
-    'azure-monitor-query==1.2.0',
-    'azure-storage-common~=1.4',
-    'azure-storage-blob==12.29.0b1',
-    'azure-storage-file-datalake==12.24.0b1',
-    'azure-storage-file-share==12.25.0b1',
-    'azure-storage-queue==12.16.0b1',
-    'azure-synapse-accesscontrol~=0.5.0',
-    'azure-synapse-artifacts~=0.22.0',
-    'azure-synapse-managedprivateendpoints~=0.4.0',
-    'azure-synapse-spark~=0.7.0',
-    'chardet~=5.2.0',
-    'colorama~=0.4.4',
+    'azure-keyvault-administration>=4.4.0',
+    'azure-keyvault-certificates>=4.7.0',
+    'azure-keyvault-keys>=4.11.0',
+    'azure-keyvault-secrets>=4.7.0',
+    'azure-keyvault-securitydomain>=1.0.0b1',
+    'azure-mgmt-advisor>=9.0.0',
+    'azure-mgmt-apimanagement>=4.0.0',
+    'azure-mgmt-appconfiguration>=6.0.0b1',
+    'azure-mgmt-appcontainers>=2.0.0',
+    'azure-mgmt-applicationinsights>=1.0.0',
+    'azure-mgmt-authorization>=5.0.0b1',
+    'azure-mgmt-batchai>=7.0.0b1',
+    'azure-mgmt-batch>=17.3.0',
+    'azure-mgmt-billing>=6.0.0',
+    'azure-mgmt-botservice>=2.0.0b3',
+    'azure-mgmt-cdn>=12.0.0',
+    'azure-mgmt-cognitiveservices>=15.0.0b1',
+    'azure-mgmt-compute>=34.1.0',
+    'azure-mgmt-containerinstance>=10.2.0b1',
+    'azure-mgmt-containerregistry>=15.1.0b1',
+    'azure-mgmt-containerregistrytasks>=1.0.0b1',
+    'azure-mgmt-containerservice>=41.1.0',
+    'azure-mgmt-cosmosdb>=9.9.0',
+    'azure-mgmt-datalake-store>=1.1.0b1',
+    'azure-mgmt-datamigration>=10.0.0',
+    'azure-mgmt-eventgrid>=10.2.0b2',
+    'azure-mgmt-eventhub>=12.0.0b1',
+    'azure-mgmt-extendedlocation>=1.0.0b2',
+    'azure-mgmt-hdinsight>=9.1.0b2',
+    'azure-mgmt-imagebuilder>=1.3.0',
+    'azure-mgmt-iotcentral>=10.0.0b1',
+    'azure-mgmt-iothub>=5.0.0b1',
+    'azure-mgmt-iothubprovisioningservices>=1.1.0',
+    'azure-mgmt-keyvault>=13.0.0',
+    'azure-mgmt-loganalytics>=13.0.0b4',
+    'azure-mgmt-managementgroups>=1.0.0',
+    'azure-mgmt-maps>=2.0.0',
+    'azure-mgmt-marketplaceordering>=1.1.0',
+    'azure-mgmt-media>=9.0',
+    'azure-mgmt-monitor>=7.0.0b1',
+    'azure-mgmt-msi>=7.1.0',
+    'azure-mgmt-netapp>=10.1.0',
+    'azure-mgmt-policyinsights>=1.1.0b4',
+    'azure-mgmt-postgresqlflexibleservers>=3.0.0b1',
+    'azure-mgmt-privatedns>=1.0.0',
+    'azure-mgmt-rdbms>=10.2.0b17',
+    'azure-mgmt-mysqlflexibleservers>=1.1.0b2',
+    'azure-mgmt-recoveryservicesbackup>=9.2.0',
+    'azure-mgmt-recoveryservices>=4.0.0',
+    'azure-mgmt-redhatopenshift>=3.0.0',
+    'azure-mgmt-redis>=14.5.0',
+    'azure-mgmt-resource>=24.0.0',
+    'azure-mgmt-resource-deployments>=1.0.0b1',
+    'azure-mgmt-resource-deploymentscripts>=1.0.0b1',
+    'azure-mgmt-resource-deploymentstacks>=1.0.0',
+    'azure-mgmt-resource-templatespecs>=1.0.0b1',
+    'azure-mgmt-search>=9.0',
+    'azure-mgmt-security>=6.0.0',
+    'azure-mgmt-servicebus>=10.0.0b1',
+    'azure-mgmt-servicefabricmanagedclusters>=2.1.0b1',
+    'azure-mgmt-servicelinker>=1.2.0b3',
+    'azure-mgmt-servicefabric>=2.1.0',
+    'azure-mgmt-signalr>=2.0.0b2',
+    'azure-mgmt-sqlvirtualmachine>=1.0.0b5',
+    'azure-mgmt-sql>=4.0.0b22',
+    'azure-mgmt-storage>=24.0.0',
+    'azure-mgmt-synapse>=2.1.0b5',
+    'azure-mgmt-trafficmanager>=1.0.0',
+    'azure-mgmt-web>=9.0.0',
+    'azure-monitor-query>=1.2.0',
+    'azure-storage-common>=1.4',
+    'azure-storage-blob>=12.29.0b1',
+    'azure-storage-file-datalake>=12.24.0b1',
+    'azure-storage-file-share>=12.25.0b1',
+    'azure-storage-queue>=12.16.0b1',
+    'azure-synapse-accesscontrol>=0.5.0',
+    'azure-synapse-artifacts>=0.22.0',
+    'azure-synapse-managedprivateendpoints>=0.4.0',
+    'azure-synapse-spark>=0.7.0',
+    'chardet>=5.2.0',
+    'colorama>=0.4.4',
     # On Linux, the distribution (Ubuntu, Debian, etc) and version are checked for `az feedback`
     'distro; sys_platform == "linux"',
     'fabric~=3.2.2',
@@ -147,19 +147,19 @@ DEPENDENCIES = [
     'packaging>=20.9',
     'paramiko>=2.0.8,<4.0.0',
     'pycomposefile>=0.0.34',
-    'PyGithub~=1.38',
-    'PyNaCl~=1.6.2',
-    'scp~=0.13.2',
+    'PyGithub>=1.38',
+    'PyNaCl>=1.5.0,<1.7',
+    'scp>=0.13.2',
     'semver~=3.0',
     'setuptools',
     'six>=1.10.0',  # six is still used by countless extensions
-    'sshtunnel~=0.1.4',
+    'sshtunnel>=0.1.4',
     # Even though knack already depends on tabulate, profile module directly uses it for interactive subscription
     # selection
     'tabulate',
     'urllib3',
-    'websocket-client~=1.8.0',
-    'xmltodict~=0.12'
+    'websocket-client>=1.8.0',
+    'xmltodict>=0.12'
 ]
 
 with open('README.rst', 'r', encoding='utf-8') as f:
