-- Do not filter out "unknown" versions to avoid compilation errors when git revision is unavailable.

--- scripts/build/depVersionsHeader.ts.orig	2026-05-14 00:45:08 UTC
+++ scripts/build/depVersionsHeader.ts
@@ -91,7 +91,7 @@ export function generateDepVersionsHeader(cfg: Config)
  */
 export function generateDepVersionsHeader(cfg: Config): string {
   const outPath = resolve(cfg.buildDir, "bun_dependency_versions.h");
-  const versions = computeVersions(cfg).filter(([, v]) => v !== "" && v !== "unknown");
+  const versions = computeVersions(cfg).filter(([, v]) => v !== "");
 
   const lines: string[] = [
     "// Auto-generated by scripts/build/depVersionsHeader.ts. Do not edit.",
