--- endpoints/lib/vboxwebService-5.0.wsdl	2017-07-10 13:31:02 UTC
+++ endpoints/lib/vboxwebService-5.1.wsdl
@@ -5,7 +5,7 @@
   Generator: src/VBox/Main/webservice/websrv-wsdl-service.xsl
 -->
 <definitions xmlns:interface="urn:vbox" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:vbox="http://www.virtualbox.org/" xmlns="http://schemas.xmlsoap.org/wsdl/" name="VirtualBox" targetNamespace="http://www.virtualbox.org/Service">
-  <import location="vboxweb-5.0.wsdl" namespace="http://www.virtualbox.org/"/>
+  <import location="vboxweb-5.1.wsdl" namespace="http://www.virtualbox.org/"/>
   <service name="vboxService">
     <port binding="vbox:vboxBinding" name="vboxServicePort">
       <soap:address location="http://localhost:18083/"/>
