# New ports collection makefile for:	gstreamer-plugins-sdl
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#

PORTREVISION=	1
CATEGORIES=	devel

COMMENT=	Gstreamer SDL plugin

GST_PLUGIN=	sdl

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
