PORTNAME=	gmp
DISTVERSION=	0.7-5
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	eduardo@FreeBSD.org
COMMENT=	Multiple Precision Arithmetic
WWW=		https://cran.r-project.org/web/packages/gmp/

LICENSE=	GPLv2+

LIB_DEPENDS=	libgmp.so:math/gmp

USES=		cran:auto-plist,compiles

.include <bsd.port.mk>
