# New ports collection makefile for:	ko-kde2-i18n
# Date created:				13 April 2001
# Whom:					Dmitry Sivachenko <demon@FreeBSD.org>
#
# $FreeBSD$
#

CATEGORIES=	korean kde misc

MAINTAINER=	ports@FreeBSD.org

LINGUAS=	"ko"
MASTERDIR=	${.CURDIR}/../../misc/kde2-i18n

SCRIPTS_ENV+=	LINGUAS=${LINGUAS}

.include "${MASTERDIR}/Makefile"
