# New ports collection Makefile for:	p5-Crypt-Rabbit
# Date created:				18 Dec 2006
# Whom:	      				Gabor Kovesdan
# $FreeBSD$

PORTNAME=	Crypt-Rabbit
PORTVERSION=	1.0.0
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	Perl extension for Rabbit stream cipher

PERL_CONFIGURE=	yes

MAN3=		Crypt::Rabbit.3

.include <bsd.port.mk>
