--- src/host/version.h.orig	2023-11-11 06:49:36 UTC
+++ src/host/version.h
@@ -1,3 +1,3 @@
 // This file is autogenerated, do not change it.
-#define VERSION 0
-#define VERSION_STR "<auto generated do not change>"
+#define VERSION 1174
+#define VERSION_STR "version 1174 (commit 7f00dcba5845a0158d53b9b2867f42e6979648ba)"
