--- pyproject.toml.orig	2026-01-21 14:20:40 UTC
+++ pyproject.toml
@@ -1,5 +1,5 @@
 [build-system]
-requires = ["setuptools>=69", "wheel"]
+requires = ["setuptools>=61", "wheel"]
 build-backend = "setuptools.build_meta"
 
 [project]
@@ -7,8 +7,7 @@ readme = "README.rst"
 version = "3.00"
 description = "C parser in Python"
 readme = "README.rst"
-license = "BSD-3-Clause"
-license-files = ["LICENSE"]
+license = { text = "BSD-3-Clause" }
 requires-python = ">=3.10"
 authors = [{name = "Eli Bendersky", email = "eliben@gmail.com"}]
 maintainers = [{name = "Eli Bendersky", email = "eliben@gmail.com"}]
