--- setup.py.orig	2026-05-14 15:24:59 UTC
+++ setup.py
@@ -84,15 +84,15 @@ setup(
         "azure-core<2.0.0,>=1.28.0",
         "azure-core-tracing-opentelemetry~=1.0.0b11",
         "azure-monitor-opentelemetry-exporter~=1.0.0b52",
-        "opentelemetry-sdk==1.40",
-        "opentelemetry-instrumentation-django==0.61b0",
-        "opentelemetry-instrumentation-fastapi==0.61b0",
-        "opentelemetry-instrumentation-flask==0.61b0",
-        "opentelemetry-instrumentation-psycopg2==0.61b0",
-        "opentelemetry-instrumentation-requests==0.61b0",
-        "opentelemetry-instrumentation-urllib==0.61b0",
-        "opentelemetry-instrumentation-urllib3==0.61b0",
-        "opentelemetry-instrumentation-logging==0.61b0",
+        "opentelemetry-sdk>=1.40",
+        "opentelemetry-instrumentation-django>=0.61b0",
+        "opentelemetry-instrumentation-fastapi>=0.61b0",
+        "opentelemetry-instrumentation-flask>=0.61b0",
+        "opentelemetry-instrumentation-psycopg2>=0.61b0",
+        "opentelemetry-instrumentation-requests>=0.61b0",
+        "opentelemetry-instrumentation-urllib>=0.61b0",
+        "opentelemetry-instrumentation-urllib3>=0.61b0",
+        "opentelemetry-instrumentation-logging>=0.61b0",
         "opentelemetry-resource-detector-azure<1.0.0,>=0.1.5",
     ],
     entry_points={
