# $FreeBSD$

PORTNAME=	Horde_HashTable
PORTVERSION=	1.2.4
CATEGORIES=	databases www pear
PKGNAMEPREFIX=	pear-

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Hash Table Interface

OPTIONS_DEFINE=	MEMCACHE
USES=	horde
USE_HORDE_RUN=	Horde_Exception

MEMCACHE_USE=	HORDE_RUN=Horde_Memcache

.include <bsd.port.mk>
