--- pyproject.toml.orig	2025-01-07 02:25:37 UTC
+++ pyproject.toml
@@ -52,7 +52,7 @@ requires = [
     # We build against the most recent supported NumPy 2.0 release;
     # see https://github.com/numpy/numpy/issues/27265
     "numpy~=2.0",
-    "setuptools~=75.7.0",
+    "setuptools",
 ]
 build-backend = "setuptools.build_meta"
 
