--- pyproject.toml.orig	2022-11-09 12:37:21 UTC
+++ pyproject.toml
@@ -4,8 +4,7 @@ requires-python = ">=3.10"
 description = "ml_dtypes is a stand-alone implementation of several NumPy dtype extensions used in machine learning."
 readme = "README.md"
 requires-python = ">=3.10"
-license = "Apache-2.0"
-license-files = ["LICENSE", "LICENSE.eigen"]
+license = {file = "LICENSE"}
 authors = [{name = "ml_dtypes authors", email="ml_dtypes@google.com"}]
 classifiers = [
     "Programming Language :: Python :: 3",
