--- konto_check.c.orig	2009-08-11 10:46:54.000000000 +0200
+++ konto_check.c	2009-08-11 10:47:04.000000000 +0200
@@ -74,31 +74,31 @@
 static int search_lutfile(char *name);
 
 #ifdef ZEND_ENGINE_2
-static ZEND_BEGIN_ARG_INFO(byref_0,1)
+ZEND_BEGIN_ARG_INFO(byref_0,1)
 ZEND_END_ARG_INFO()
 
-static ZEND_BEGIN_ARG_INFO(byref_1,1)
+ZEND_BEGIN_ARG_INFO(byref_1,1)
    ZEND_ARG_PASS_INFO(0)
 ZEND_END_ARG_INFO()
 
-static ZEND_BEGIN_ARG_INFO(byref_11,1)
+ZEND_BEGIN_ARG_INFO(byref_11,1)
    ZEND_ARG_PASS_INFO(0)
    ZEND_ARG_PASS_INFO(1)
    ZEND_ARG_PASS_INFO(0)
 ZEND_END_ARG_INFO()
 
-static ZEND_BEGIN_ARG_INFO(byref_2,1)
+ZEND_BEGIN_ARG_INFO(byref_2,1)
    ZEND_ARG_PASS_INFO(0)
    ZEND_ARG_PASS_INFO(0)
 ZEND_END_ARG_INFO()
 
-static ZEND_BEGIN_ARG_INFO(byref_3,1)
+ZEND_BEGIN_ARG_INFO(byref_3,1)
    ZEND_ARG_PASS_INFO(0)
    ZEND_ARG_PASS_INFO(0)
    ZEND_ARG_PASS_INFO(0)
 ZEND_END_ARG_INFO()
 
-static ZEND_BEGIN_ARG_INFO(byref_4,1)
+ZEND_BEGIN_ARG_INFO(byref_4,1)
    ZEND_ARG_PASS_INFO(0)
    ZEND_ARG_PASS_INFO(0)
    ZEND_ARG_PASS_INFO(0)
