--- pyproject.toml.orig	2026-04-02 07:38:28 UTC
+++ pyproject.toml
@@ -1,5 +1,5 @@
 [build-system]
-requires = ["setuptools>=68,<82.1"]
+requires = ["setuptools>=61"]
 build-backend = "backend"
 backend-path = ["_mypyc_hook"]
 
