# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD$

PORTNAME=	rendercheck
PORTVERSION=	1.5
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Small program for testing basic Render extension conformance

USES=		xorg xorg-cat:app
USE_XORG=	xrender

PLIST_FILES=	bin/rendercheck man/man1/rendercheck.1.gz

.include <bsd.port.mk>
