# New ports collection makefile for:	acroread-chsfont
# Version required:	1999.7.20
# Date created:		99/06/16
# Whom:			Satoshi Taoka <taoka@FreeBSD.org>
#
# $Id: Makefile,v 1.2 1999/07/04 07:56:55 obrien Exp $
#

DISTNAME=	chsfont
CATEGORIES=	chinese

MASTERDIR=	${.CURDIR}/../../print/acroread-commfont

.include "${MASTERDIR}/Makefile"
