# New ports collection makefile for:    p5-Sort-Tree
# Date created:				Oct 16th 2003
# Whom:	      				clsung@dragon2.net
#
# $FreeBSD$
#

PORTNAME=	Sort-Tree
PORTVERSION=	1.09
CATEGORIES=	devel perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Sort
PKGNAMEPREFIX=	p5-

MAINTAINER=	clsung@FreeBSD.org
COMMENT=	A perl module for sorting a objects into a tree structure

PERL_CONFIGURE=	YES

MAN3=		Sort::Tree.3

.include <bsd.port.mk>
