# New ports collection makefile for:	math/p5-Statistics-TTest
# Date created:				17 January 2008
# Whom:					dawe <daweonline@gmail.com>
#
# $FreeBSD$
#

PORTNAME=	Statistics-TTest
PORTVERSION=	1.1.0
PORTREVISION=	1
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	Statistics
PKGNAMEPREFIX=	p5-

MAINTAINER=	daweonline@gmail.com
COMMENT=	Perl module to perform T-test on 2 independent samples

BUILD_DEPENDS=	p5-Statistics-Descriptive>=0:${PORTSDIR}/math/p5-Statistics-Descriptive

PERL_CONFIGURE=	yes

MAN3=		Statistics::TTest.3 Statistics::PointEstimation.3

.include <bsd.port.mk>
