--- pyproject.toml.orig	2026-01-31 00:57:12 UTC
+++ pyproject.toml
@@ -18,7 +18,7 @@ requires = [
 
 [build-system]
 requires = [
-    "setuptools>=64.0",
+    "setuptools>=61.0",
     "setuptools-scm>=8;python_version>='3.8'",
     "setuptools-scm<8;python_version<'3.8'",
 ]
