--- py/test/Ice/properties/run.py.orig	2011-06-15 19:44:00.000000000 +0000
+++ py/test/Ice/properties/run.py	2012-09-11 19:05:41.531273236 +0000
@@ -24,14 +24,14 @@
 #
 # Write config
 #
-configPath = u"./config/中国_client.config"
+configPath = u"./config/中国_client.config".encode("utf-8")
 
 TestUtil.createConfig(configPath, 
                       ["# Automatically generated by Ice test driver.", 
                        "Ice.Trace.Protocol=1",
                        "Ice.Trace.Network=1", 
                        "Ice.ProgramName=PropertiesClient", 
-                       "Config.Path=./config/中国_client.config"])
+                       "Config.Path="+configPath])
 
 TestUtil.simpleTest()
 
