PORTNAME=	oci
DISTVERSION=	2.22.0
PORTREVISION=	1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ale_sagra@hotmail.com
COMMENT=	Ruby client for the Oracle Cloud Infrastructure API
WWW=		https://github.com/oracle/oci-ruby-sdk/

LICENSE=	APACHE20

RUN_DEPENDS=	rubygem-circuitbox>=2.0.0<2.1:www/rubygem-circuitbox \
		rubygem-event_stream_parser>=1.0.0<1.1:devel/rubygem-event_stream_parser \
		rubygem-inifile>=3.0.0<4:textproc/rubygem-inifile \
		rubygem-json>=1.4.6<3.0.0:devel/rubygem-json \
		rubygem-jwt2>=2.1<3:www/rubygem-jwt2 \
		rubygem-psych>=5.0.1<6:textproc/rubygem-psych

USES=		gem

NO_ARCH=	yes

.include <bsd.port.mk>
