--- dodatni.cc.orig	Sat Aug 18 18:18:15 2001
+++ dodatni.cc	Sat Aug 18 09:51:00 2001
@@ -1,5 +1,6 @@
 // generated by Fast Light User Interface Designer (fluid) version 1.00
 #include "bebac.h"
+#include <stdarg.h>
 #ifdef __WIN32__
 extern "C" {
 #define errno WSAGetLastError()
