--- password.cc.orig	Wed Apr 11 21:12:25 2001
+++ password.cc	Mon Feb  3 03:58:35 2003
@@ -1,6 +1,7 @@
 // generated by Fast Light User Interface Designer (fluid) version 1.00
 #include <FL/Fl_Menu_.H>
 #include "password.h"
+#undef Success
 #include <sqlplus.hh>
 #include "client.h"
 #include <FL/Fl_Pixmap.H>
