--- ipaplatform/freebsd/paths.py.orig	2026-08-19 13:55:40 UTC
+++ ipaplatform/freebsd/paths.py
@@ -0,0 +1,221 @@
+#
+# Copyright (C) 2026  FreeIPA Contributors see COPYING for license
+#
+
+from ipaplatform.base.paths import BasePathNamespace
+
+
+class FreeBSDPathNamespace(BasePathNamespace):
+    PKIDESTROY = "/usr/local/sbin/pkidestroy"
+    PKISPAWN = "/usr/local/sbin/pkispawn"
+    PKI = "/usr/local/bin/pki"
+    PKI_SERVER = "/usr/local/sbin/pki-server"
+    BIN_TOMCAT = "/usr/local/apache-tomcat-9.0/bin/catalina.sh"
+    BIN_PS = "/bin/ps"
+
+    PKI_CONFIGURATION = "/usr/local/etc/pki"
+    PKI_TOMCAT = "/var/db/pki/pki-tomcat/conf"
+    PKI_TOMCAT_ALIAS_DIR = "/var/db/pki/pki-tomcat/alias"
+    PKI_TOMCAT_ALIAS_PWDFILE_TXT = "/var/db/pki/pki-tomcat/alias/pwdfile.txt"
+    PKI_TOMCAT_PASSWORD_CONF = "/var/db/pki/pki-tomcat/conf/password.conf"
+    PKI_TOMCAT_SERVER_XML = "/var/db/pki/pki-tomcat/conf/server.xml"
+    PKI_ACME_CONFIGSOURCES_CONF = "/var/db/pki/pki-tomcat/conf/acme/configsources.conf"
+    PKI_ACME_DATABASE_CONF = "/var/db/pki/pki-tomcat/conf/acme/database.conf"
+    PKI_ACME_ENGINE_CONF = "/var/db/pki/pki-tomcat/conf/acme/engine.conf"
+    PKI_ACME_ISSUER_CONF = "/var/db/pki/pki-tomcat/conf/acme/issuer.conf"
+    PKI_ACME_REALM_CONF = "/var/db/pki/pki-tomcat/conf/acme/realm.conf"
+
+    VAR_LIB_PKI_DIR = "/var/db/pki"
+    VAR_LIB_PKI_CA_ALIAS_DIR = "/var/db/pki-ca/alias"
+    VAR_LIB_PKI_TOMCAT_DIR = "/var/db/pki/pki-tomcat"
+    CA_BACKUP_KEYS_P12 = "/var/db/pki/pki-tomcat/alias/ca_backup_keys.p12"
+    KRA_BACKUP_KEYS_P12 = "/var/db/pki/pki-tomcat/alias/kra_backup_keys.p12"
+    CA_CS_CFG_PATH = "/var/db/pki/pki-tomcat/conf/ca/CS.cfg"
+    CASIGNEDLOGCERT_CFG = "/var/db/pki/pki-tomcat/ca/profiles/ca/caSignedLogCert.cfg"
+    KRA_CS_CFG_PATH = "/var/db/pki/pki-tomcat/conf/kra/CS.cfg"
+    SVC_LIST_FILE = "/var/run/ipa/services.list"
+    IPA_OTPD_INETD_CONF = "/var/run/ipa/ipa-otpd.inetd.conf"
+    IPA_OTPD_INETD_PID = "/var/run/ipa/ipa-otpd-inetd.pid"
+    IPA_OTPD_SOCKET_DIR = "/var/run/krb5kdc"
+    IPA_OTPD_SOCKET = "/var/run/krb5kdc/DEFAULT.socket"
+    IPA_CCACHES = "/var/run/ipa/ccaches"
+    IPA_RENEWAL_LOCK = "/var/run/ipa/renewal.lock"
+    KLIST = "/usr/local/bin/klist"
+    KADMIN_LOCAL = "/usr/local/sbin/kadmin.local"
+    KDB5_UTIL = "/usr/local/sbin/kdb5_util"
+
+    ETC_IPA = "/usr/local/etc/ipa"
+    IPA_DEFAULT_CONF = "/usr/local/etc/ipa/default.conf"
+
+    IPA_CUSTODIA_CONF_DIR = "/usr/local/etc/ipa/custodia"
+    IPA_CUSTODIA_CONF = "/usr/local/etc/ipa/custodia/custodia.conf"
+    IPA_CUSTODIA_KEYS = "/usr/local/etc/ipa/custodia/server.keys"
+    IPA_CUSTODIA_SOCKET = "/var/run/httpd/ipa-custodia.sock"
+
+    KDCPROXY_CONFIG = "/usr/local/etc/ipa/kdcproxy/kdcproxy.conf"
+
+    VAR_LIB_IPA = "/var/db/ipa"
+    CA_BUNDLE_PEM = "/var/db/ipa-client/pki/ca-bundle.pem"
+    KDC_CA_BUNDLE_PEM = "/var/db/ipa-client/pki/kdc-ca-bundle.pem"
+    HTTPD_CERT_FILE = "/var/db/ipa/certs/httpd.crt"
+    HTTPD_KEY_FILE = "/var/db/ipa/private/httpd.key"
+    HTTPD_PASSWD_FILE_FMT = "/var/db/ipa/passwds/{host}-443-RSA"
+    HTTP_KEYTAB = "/var/db/ipa/gssproxy/http.keytab"
+    GSSPROXY_CONF = "/usr/local/etc/gssproxy/10-ipa.conf"
+    IPA_CCACHE_SWEEPER_GSSPROXY_SOCK = (
+        "/var/db/gssproxy/ipa_ccache_sweeper.sock"
+    )
+    RA_AGENT_PEM = "/var/db/ipa/ra-agent.pem"
+    RA_AGENT_KEY = "/var/db/ipa/ra-agent.key"
+    IPA_BACKUP_DIR = "/var/db/ipa/backup"
+    IPA_DNSSEC_DIR = "/var/db/ipa/dnssec"
+    IPA_KASP_DB_BACKUP = "/var/db/ipa/ipa-kasp.db.backup"
+    DNSSEC_TOKENS_DIR = "/var/db/ipa/dnssec/tokens"
+    DNSSEC_SOFTHSM_PIN = "/var/db/ipa/dnssec/softhsm_pin"
+    IPA_CA_CSR = "/var/db/ipa/ca.csr"
+    REPLICA_INFO_TEMPLATE = "/var/db/ipa/replica-info-%s"
+    REPLICA_INFO_GPG_TEMPLATE = "/var/db/ipa/replica-info-%s.gpg"
+    PKI_CA_PUBLISH_DIR = "/var/db/ipa/pki-ca/publish"
+    CERTUTIL = "/usr/local/bin/certutil"
+    PK12UTIL = "/usr/local/bin/pk12util"
+    MODUTIL = "/usr/local/bin/modutil"
+    SYSCONFIG_PKI_TOMCAT = "/var/db/pki/pki-tomcat/conf/tomcat.conf"
+    SYSCONFIG_PKI_TOMCAT_PKI_TOMCAT_DIR = "/usr/local/etc/pki/tomcat/pki-tomcat"
+    IPA_CLIENT_SYSRESTORE = "/var/db/ipa-client/sysrestore"
+    SYSRESTORE_INDEX = "/var/db/ipa-client/sysrestore/sysrestore.index"
+    SYSRESTORE = "/var/db/ipa/sysrestore"
+    STATEFILE_DIR = "/var/db/ipa/sysupgrade"
+
+    VAR_KERBEROS_KRB5KDC_DIR = "/usr/local/var/krb5kdc/"
+    KRB5_CONF = "/usr/local/etc/krb5.conf"
+    COMMON_KRB5_CONF_DIR = "/usr/local/etc/krb5.conf.d/"
+    KRB5_FREEIPA_DEFAULTS = "/usr/local/etc/krb5.conf.d/freeipa"
+    KRB5_FREEIPA = "/usr/local/etc/krb5.conf.d/freeipa-realm"
+    KRB5_FREEIPA_SERVER = "/usr/local/etc/krb5.conf.d/freeipa-server"
+    VAR_KRB5KDC_K5_REALM = "/usr/local/var/krb5kdc/.k5."
+    CACERT_PEM = "/usr/local/var/krb5kdc/cacert.pem"
+    KRB5KDC_KADM5_ACL = "/usr/local/var/krb5kdc/kadm5.acl"
+    KRB5KDC_KADM5_KEYTAB = "/usr/local/var/krb5kdc/kadm5.keytab"
+    KRB5KDC_KDC_CONF = "/usr/local/var/krb5kdc/kdc.conf"
+    KDC_CERT = "/usr/local/var/krb5kdc/kdc.crt"
+    KDC_KEY = "/usr/local/var/krb5kdc/kdc.key"
+
+    IPACTL = "/usr/local/sbin/ipactl"
+    IPA_CLIENT_AUTOMOUNT = "/usr/local/sbin/ipa-client-automount"
+    IPA_CLIENT_INSTALL = "/usr/local/sbin/ipa-client-install"
+    IPA_GETKEYTAB = "/usr/local/sbin/ipa-getkeytab"
+    IPA_RMKEYTAB = "/usr/local/sbin/ipa-rmkeytab"
+    SBIN_IPA_JOIN = "/usr/local/sbin/ipa-join"
+    CONNCHECK_CCACHE = "/usr/local/etc/ipa/.conncheck_ccache"
+    IPA_DNS_CCACHE = "/usr/local/etc/ipa/.dns_ccache"
+    OPENLDAP_LDAP_CONF = "/usr/local/etc/openldap/ldap.conf"
+    IPA_DNS_UPDATE_TXT = "/usr/local/etc/ipa/.dns_update.txt"
+    IPA_CA_CRT = "/usr/local/etc/ipa/ca.crt"
+    IPA_DNSKEYSYNCD_KEYTAB = "/usr/local/etc/ipa/dnssec/ipa-dnskeysyncd.keytab"
+    IPA_ODS_EXPORTER_KEYTAB = "/usr/local/etc/ipa/dnssec/ipa-ods-exporter.keytab"
+    IPA_SERVER_CONF = "/usr/local/etc/ipa/server.conf"
+    DNSSEC_OPENSSL_CONF = "/usr/local/etc/ipa/dnssec/openssl.cnf"
+    DNSSEC_SOFTHSM2_CONF = "/usr/local/etc/ipa/dnssec/softhsm2.conf"
+    DNSSEC_SOFTHSM_PIN_SO = "/usr/local/etc/ipa/dnssec/softhsm_pin_so"
+    IPA_NSSDB_DIR = "/usr/local/etc/ipa/nssdb"
+    IPA_NSSDB_PWDFILE_TXT = "/usr/local/etc/ipa/nssdb/pwdfile.txt"
+    NSS_DB_DIR = "/usr/local/etc/pki/nssdb"
+
+    LIBEXEC_IPA_DIR = "/usr/local/libexec/ipa"
+    IPA_OTPD = "/usr/local/libexec/ipa/ipa-otpd"
+    IPA_OTPD_WRAPPER = "/usr/local/libexec/ipa/ipa-otpd-wrapper"
+    IPA_OTPD_LOG = "/var/log/ipa-otpd.log"
+    LIBEXEC_CERTMONGER_DIR = "/usr/local/libexec/certmonger"
+    CERTMONGER_COMMAND_TEMPLATE = "/usr/local/libexec/ipa/certmonger/%s"
+    CERTMONGER_DOGTAG_SUBMIT = "/usr/local/libexec/certmonger/dogtag-submit"
+    DOGTAG_IPA_CA_RENEW_AGENT_SUBMIT = "/usr/local/libexec/certmonger/dogtag-ipa-ca-renew-agent-submit"
+    DOGTAG_IPA_RENEW_AGENT_SUBMIT = "/usr/local/libexec/certmonger/dogtag-ipa-renew-agent-submit"
+    IPA_SERVER_GUARD = "/usr/local/libexec/certmonger/ipa-server-guard"
+    IPA_DNSKEYSYNCD_REPLICA = "/usr/local/libexec/ipa/ipa-dnskeysync-replica"
+    IPA_DNSKEYSYNCD = "/usr/local/libexec/ipa/ipa-dnskeysyncd"
+    IPA_ODS_EXPORTER = "/usr/local/libexec/ipa/ipa-ods-exporter"
+    IPA_PKI_RETRIEVE_KEY = "/usr/local/libexec/ipa/ipa-pki-retrieve-key"
+    IPA_PKI_WAIT_RUNNING = "/usr/local/libexec/ipa/ipa-pki-wait-running"
+    IPA_CUSTODIA_HANDLER = "/usr/local/libexec/ipa/custodia"
+    IPA_CUSTODIA_CHECK = "/usr/local/libexec/ipa/ipa-custodia-check"
+
+    SSSD_CONF = "/usr/local/etc/sssd/sssd.conf"
+    SSSD_CONF_BKP = "/usr/local/etc/sssd/sssd.conf.bkp"
+    SSSD_CONF_DELETED = "/usr/local/etc/sssd/sssd.conf.deleted"
+    SSSD_DB = "/var/db/sss/db"
+    SSSD_LDB = "/var/db/sss/db/sssd.ldb"
+    SSSD_CONFIG_LDB = "/var/db/sss/db/config.ldb"
+    SSSD_MC_GROUP = "/var/db/sss/mc/group"
+    SSSD_MC_PASSWD = "/var/db/sss/mc/passwd"
+    SSSD_MC_INITGROUPS = "/var/db/sss/mc/initgroups"
+    SSSD_MC_SID = "/var/db/sss/mc/sid"
+    SSSD_PIPES = "/var/db/sss/pipes"
+    SSSD_PUBCONF_DIR = "/var/db/sss/pubconf"
+    SSSD_PUBCONF_KNOWN_HOSTS = "/var/db/sss/pubconf/known_hosts"
+    SSSD_PUBCONF_KRB5_INCLUDE_D_DIR = "/var/db/sss/pubconf/krb5.include.d/"
+    SSSD_KEYTABS_DIR = "/var/db/sss/keytabs"
+    SSSD_SECRETS = "/var/db/sss/secrets/secrets.ldb"
+
+    DSCTL = "/usr/local/bin/dsctl"
+
+    VAR_LIB_DIRSRV = "/var/db/dirsrv"
+    VAR_LIB_DIRSRV_INSTANCE_SCRIPTS_TEMPLATE = "/var/db/dirsrv/scripts-%s"
+    VAR_LIB_SLAPD_INSTANCE_DIR_TEMPLATE = "/var/db/dirsrv/slapd-%s"
+    SLAPD_INSTANCE_BACKUP_DIR_TEMPLATE = "/var/db/dirsrv/slapd-%s/bak/%s"
+    SLAPD_INSTANCE_DB_DIR_TEMPLATE = "/var/db/dirsrv/slapd-%s/db/%s"
+    SLAPD_INSTANCE_LDIF_DIR_TEMPLATE = "/var/db/dirsrv/slapd-%s/ldif"
+    VAR_RUN_DIRSRV_DIR = "/var/run/dirsrv"
+    DIRSRV_LOCK_DIR = "/var/run/dirsrv"
+
+    HTTPD = "/usr/local/sbin/httpd"
+    ETC_HTTPD_DIR = "/usr/local/etc/apache24"
+    HTTPD_ALIAS_DIR = "/usr/local/etc/apache24/alias"
+    GSSAPI_SESSION_KEY = "/usr/local/etc/apache24/alias/ipasession.key"
+    HTTPD_CONF_D_DIR = "/usr/local/etc/apache24/Includes/"
+    HTTPD_IPA_WSGI_MODULES_CONF = "/usr/local/etc/apache24/modules.d/290_freeipa.conf"
+    HTTPD_IPA_ENVVARS_CONF = "/usr/local/etc/apache24/envvars.d/ipa.env"
+    HTTPD_IPA_RC_CONF = "/usr/local/etc/rc.conf.d/apache24/ipa"
+    HTTPD_IPA_CONF = "/usr/local/etc/apache24/Includes/ipa.conf"
+    HTTPD_IPA_KDCPROXY_CONF = "/usr/local/etc/ipa/kdcproxy/ipa-kdc-proxy.conf"
+    HTTPD_IPA_KDCPROXY_CONF_SYMLINK = "/usr/local/etc/apache24/Includes/ipa-kdc-proxy.conf"
+    HTTPD_IPA_PKI_PROXY_CONF = "/usr/local/etc/apache24/Includes/ipa-pki-proxy.conf"
+    HTTPD_IPA_REWRITE_CONF = "/usr/local/etc/apache24/Includes/ipa-rewrite.conf"
+    HTTPD_NSS_CONF = "/usr/local/etc/apache24/Includes/nss.conf"
+    HTTPD_PASSWORD_CONF = "/usr/local/etc/apache24/password.conf"
+    HTTPD_SSL_CONF = "/usr/local/etc/apache24/extra/httpd-ssl.conf"
+    HTTPD_SSL_SITE_CONF = "/usr/local/etc/apache24/extra/httpd-ssl.conf"
+    HTTPD_IPA_SSL_CONF_SYMLINK = "/usr/local/etc/apache24/Includes/ipa-ssl.conf"
+    OLD_IPA_KEYTAB = "/usr/local/etc/apache24/ipa.keytab"
+    OLD_KRA_AGENT_PEM = "/usr/local/etc/apache24/alias/kra-agent.pem"
+    WSGI_PREFIX_DIR = "/var/run/httpd/wsgi"
+    IPA_HTTPD_KDCPROXY = "/usr/local/libexec/ipa/ipa-httpd-kdcproxy"
+    IPA_HTTPD_PASSWD_READER = "/usr/local/libexec/ipa/ipa-httpd-pwdreader"
+
+    BIN_CURL = "/usr/local/bin/curl"
+    CERTMONGER = "/usr/local/sbin/certmonger"
+    GPG2 = "/usr/local/bin/gpg"
+    GPG_AGENT = "/usr/local/bin/gpg-agent"
+    IPA_DNS_INSTALL = "/usr/local/sbin/ipa-dns-install"
+    IPA_REPLICA_CONNCHECK = "/usr/local/sbin/ipa-replica-conncheck"
+    IPA_SERVER_UPGRADE = "/usr/local/sbin/ipa-server-upgrade"
+    KDESTROY = "/usr/local/bin/kdestroy"
+    KINIT = "/usr/local/bin/kinit"
+    KTUTIL = "/usr/local/bin/ktutil"
+    NET = "/usr/local/bin/net"
+    NSUPDATE = "/usr/local/bin/nsupdate"
+    SMBD = "/usr/local/sbin/smbd"
+    SSSCTL = "/usr/local/sbin/sssctl"
+    SSS_SSH_AUTHORIZEDKEYS = "/usr/local/bin/sss_ssh_authorizedkeys"
+    SSS_SSH_KNOWNHOSTS = "/usr/local/bin/sss_ssh_knownhosts"
+    SSS_SSH_KNOWNHOSTSPROXY = "/usr/local/bin/sss_ssh_knownhostsproxy"
+    TDBTOOL = "/usr/local/bin/tdbtool"
+
+    SYSTEMCTL = None
+    SYSTEMD_TMPFILES = None
+    SBIN_INETD = "/usr/sbin/inetd"
+    SBIN_DAEMON = "/usr/sbin/daemon"
+    SBIN_SERVICE = "/usr/sbin/service"
+    SBIN_SYSRC = "/usr/sbin/sysrc"
+
+
+paths = FreeBSDPathNamespace()
