--- pyproject.toml.orig	2026-05-01 12:25:03 UTC
+++ pyproject.toml
@@ -1,6 +1,6 @@ build-backend = "setuptools.build_meta"
 [build-system]
 build-backend = "setuptools.build_meta"
-requires = [ "setuptools>=71" ]
+requires = [ "setuptools>=61" ]
 
 [project]
 name = "django-modelcluster"
@@ -8,7 +8,7 @@ keywords = [ "cluster", "django", "model" ]
 description = "Django extension to allow working with 'clusters' of models as a single unit, independently of the database"
 readme = "README.rst"
 keywords = [ "cluster", "django", "model" ]
-license = "BSD-3-Clause"
+license = { text = "BSD-3-Clause" }
 authors = [
   { name = "Matthew Westcott", email = "matthew.westcott@torchbox.com" },
   { name = "Wagtail Team", email = "hello@wagtail.org" },
