--- node-clipboard-rs/Cargo.toml.orig	2026-03-04 05:28:38 UTC
+++ node-clipboard-rs/Cargo.toml
@@ -16,7 +16,7 @@ tokio        = { version = "1.0", features = ["rt", "r
 tokio        = { version = "1.0", features = ["rt", "rt-multi-thread"] }
 
 # 仅在 Linux 平台上引入 wayland-clipboard-listener
-[target.'cfg(target_os = "linux")'.dependencies]
+[target.'cfg(any(target_os = "linux", target_os = "freebsd"))'.dependencies]
 wayland-clipboard-listener = "0.6.0"
 wl-clipboard-rs           = "0.9.3"
 
