# Created by: Mark Pulford <mark@kyne.com.au>
# $FreeBSD$

PORTNAME=	vp
PORTVERSION=	1.8
CATEGORIES=	graphics
MASTER_SITES=	http://elfga.com/~erik/files/

MAINTAINER=	erik@elfga.com
COMMENT=	Image viewer for X

USE_SDL=	image
GNU_CONFIGURE=	yes
USE_XZ=		yes

MAN1=		vp.1
PLIST_FILES=	bin/vp

NO_STAGE=	yes
.include <bsd.port.mk>
