--- cmake/SourcesDALTON.cmake.orig	2018-09-02 05:37:01 UTC
+++ cmake/SourcesDALTON.cmake
@@ -790,7 +790,7 @@ if(ENABLE_PCMSOLVER)
     DALTON/pcm/pcm_write.F90
     DALTON/pcm/pcm_utils.F90
    )
-   set(DALTON_FREE_FORTRAN_SOURCES "${DALTON_FREE_FORTRAN_SOURCES} ${DAL_PCM_SOURCES}")
+   set(DALTON_FREE_FORTRAN_SOURCES "${DALTON_FREE_FORTRAN_SOURCES};${DAL_PCM_SOURCES}")
 endif()
 set(DALTON_OWN_BLAS_SOURCES
     DALTON/pdpack/gp_blas.F
