# New ports collection makefile for:    font-misc-meltho
# Date created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD$
#

PORTNAME=	font-misc-meltho
PORTVERSION=	1.0.1
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org miscellaneous Meltho font

XORG_CAT=	font
INSTALLS_TTF=	yes
FONTDIR=	OTF

.include <bsd.port.mk>
