# New ports collection makefile for:	devel/p5-Test-Script
# Date created:				Wed Mar  7 20:14:32 CET 2007
# Whom:					lth@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	Test-Script
PORTVERSION=	1.02
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	Test
PKGNAMEPREFIX=	p5-

MAINTAINER=	lth@FreeBSD.org
COMMENT=	Test::Script - Cross-platform basic tests for scripts

PERL_CONFIGURE=	yes

MAN3=		Test::Script.3

.include <bsd.port.mk>
