--- components/BUILD.gn.orig	2026-08-31 10:59:09 UTC
+++ components/BUILD.gn
@@ -228,7 +228,6 @@ test("components_unittests") {
     "//components/contextual_search/internal:unit_tests",
     "//components/contextual_tasks:unit_tests",
     "//components/country_codes:unit_tests",
-    "//components/crash/core/common:unit_tests",
     "//components/critical_actions/core/browser:unit_tests",
     "//components/cross_device/logging:unit_tests",
     "//components/crx_file:unit_tests",
@@ -663,7 +662,7 @@ test("components_unittests") {
       "//components/user_education/webui:unit_tests",
     ]
 
-    if (!is_fuchsia) {  #!iOS and!Fuchsia
+    if (!is_fuchsia && !is_bsd) {  #!iOS and!Fuchsia
       deps += [
         "//components/crash/content/browser:unit_tests",
         "//components/crash/core/app:unit_tests",
@@ -837,7 +836,7 @@ test("components_unittests") {
     deps += [ "//components/constrained_window:unit_tests" ]
   }
 
-  if (is_win || is_mac || is_linux || is_chromeos) {
+  if (is_win || is_mac || (is_linux && !is_bsd) || is_chromeos) {
     deps += [
       "//components/metrics/private_metrics:unit_tests",
       "//components/metrics/structured:unit_tests",
