--- v8/src/objects/js-temporal-zoneinfo64.cc.orig	2025-10-30 15:44:36 UTC
+++ v8/src/objects/js-temporal-zoneinfo64.cc
@@ -11,7 +11,7 @@
 #include "temporal_rs/TimeZone.hpp"
 
 #ifdef V8_INTL_SUPPORT
-#include "udatamem.h"
+#include "../../third_party/icu/source/common/udatamem.h"
 #else
 // Defined in builtins-temporal-zoneinfo64-data.cc, generated by
 // include-file-as-bytes.py
