--- components/cbor/BUILD.gn.orig	2026-08-31 10:59:09 UTC
+++ components/cbor/BUILD.gn
@@ -12,7 +12,7 @@ buildflag_header("buildflags") {
   # TODO(crbug.com/535682335): Remove `USE_CBOR_RUST` buildflag entirely,
   # unconditionally enable Rust CBOR parser, and drop `is_cronet_build` check
   # once Cronet supports Crubit dependencies.
-  flags = [ "USE_CBOR_RUST=!$is_cronet_build" ]
+  flags = [ "USE_CBOR_RUST=false" ]
 }
 
 component("cbor") {
@@ -37,12 +37,12 @@ component("cbor") {
     "//base",
   ]
 
-  if (!is_cronet_build) {
-    public_deps = [
-      "//build/rust/crubit",
-      "//components/cbor/rust:cbor_rust_bindings",
-    ]
-  }
+#  if (!is_cronet_build) {
+#    public_deps = [
+#      "//build/rust/crubit",
+#      "//components/cbor/rust:cbor_rust_bindings",
+#    ]
+#  }
 }
 
 source_set("unit_tests") {
