--- ./components/storage_monitor.gypi.orig	2014-04-24 22:35:26.000000000 +0200
+++ ./components/storage_monitor.gypi	2014-04-24 23:23:44.000000000 +0200
@@ -20,10 +20,10 @@
         'storage_monitor/image_capture_device_manager.mm',
         'storage_monitor/media_storage_util.cc',
         'storage_monitor/media_storage_util.h',
-        'storage_monitor/media_transfer_protocol_device_observer_linux.cc',
-        'storage_monitor/media_transfer_protocol_device_observer_linux.h',
-        'storage_monitor/mtab_watcher_linux.cc',
-        'storage_monitor/mtab_watcher_linux.h',
+        #'storage_monitor/media_transfer_protocol_device_observer_linux.cc',
+        #'storage_monitor/media_transfer_protocol_device_observer_linux.h',
+        #'storage_monitor/mtab_watcher_linux.cc',
+        #'storage_monitor/mtab_watcher_linux.h',
         'storage_monitor/portable_device_watcher_win.cc',
         'storage_monitor/portable_device_watcher_win.h',
         'storage_monitor/removable_device_constants.cc',
@@ -35,16 +35,18 @@
         'storage_monitor/storage_monitor.h',
         'storage_monitor/storage_monitor_chromeos.cc',
         'storage_monitor/storage_monitor_chromeos.h',
-        'storage_monitor/storage_monitor_linux.cc',
-        'storage_monitor/storage_monitor_linux.h',
+        #'storage_monitor/storage_monitor_linux.cc',
+        #'storage_monitor/storage_monitor_linux.h',
+        'storage_monitor/storage_monitor_freebsd.cc',
+        'storage_monitor/storage_monitor_freebsd.h',
         'storage_monitor/storage_monitor_mac.h',
         'storage_monitor/storage_monitor_mac.mm',
         'storage_monitor/storage_monitor_win.cc',
         'storage_monitor/storage_monitor_win.h',
         'storage_monitor/transient_device_ids.cc',
         'storage_monitor/transient_device_ids.h',
-        'storage_monitor/udev_util_linux.cc',
-        'storage_monitor/udev_util_linux.h',
+        #'storage_monitor/udev_util_linux.cc',
+        #'storage_monitor/udev_util_linux.h',
         'storage_monitor/volume_mount_watcher_win.cc',
         'storage_monitor/volume_mount_watcher_win.h',
       ],
