--- pyproject.toml.orig	2026-09-25 16:23:47 UTC
+++ pyproject.toml
@@ -1,5 +1,5 @@
 [build-system]
-requires=['setuptools>=80.0', 'numpy>=1.25', 'Cython>=3.0']
+requires=['setuptools>=63.0', 'numpy>=1.25', 'Cython>=3.0']
 build-backend = "setuptools.build_meta"
 
 [project]
@@ -10,7 +10,6 @@ requires-python = ">=3.12"
 	   {name = "Philippa Doherty", email = "Philippa.Doherty@RoswellPark.org"}]
 readme = "README.md"
 requires-python = ">=3.12"
-license = "BSD-3-Clause"
 classifiers =['Development Status :: 5 - Production/Stable',
               'Environment :: Console',
               'Intended Audience :: Developers',
