#!/bin/sh

export JAVA_VERSION

PREFIX="%%PREFIX%%"
JAVA_VERSION="%%JAVA_VERSION%%"
JAVAVM="%%JAVAVM%%"
JAR_DIR="%%JAR_DIR%%"
JAR_FILE=xnap.jar

${JAVAVM} -jar ${PREFIX}/${JAR_DIR}/${JAR_FILE} "${@}"
