PORTNAME=	ghcprofview
PORTVERSION=	0.1.0.2
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Graphical viewer for GHC profile files
WWW=		https://github.com/portnov/ghcprofview-hs

LICENSE=	BSD3CLAUSE

LIB_DEPENDS=	libfreetype.so:print/freetype2 \
		libharfbuzz.so:print/harfbuzz

USES=		cabal gnome pkgconfig

USE_GNOME=	atk cairo gdkpixbuf2 glib20 gtk30 introspection pango

USE_CABAL=	OneTuple-0.3.1_3 \
		QuickCheck-2.14.2 \
		StateVar-1.2.2 \
		aeson-2.1.1.0 \
		ansi-terminal-0.11.3 \
		assoc-1.0.2_3 \
		async-2.2.4_2 \
		attoparsec-0.14.4_2 \
		base-compat-0.12.2 \
		base-compat-batteries-0.12.2 \
		base-orphans-0.8.7 \
		bifunctors-5.5.13 \
		bitvec-1.1.3.0 \
		blaze-builder-0.4.2.2_1 \
		blaze-html-0.9.1.2_2 \
		blaze-markup-0.8.2.8_3 \
		cabal-doctest-1.0.9_2 \
		colour-2.3.6 \
		comonad-5.0.8_1 \
		conduit-1.3.4.3_1 \
		conduit-extra-1.3.6 \
		contravariant-1.5.5 \
		data-default-class-0.1.2.0 \
		data-fix-0.3.2_3 \
		distributive-0.6.2.1_1 \
		dlist-1.0 \
		generically-0.1 \
		ghc-prof-1.4.1.11 \
		gi-atk-2.0.25 \
		gi-cairo-1.0.27 \
		gi-freetype2-2.0.2 \
		gi-gdk-3.0.26 \
		gi-gdkpixbuf-2.0.29 \
		gi-gio-2.0.30 \
		gi-glib-2.0.27 \
		gi-gmodule-2.0.3 \
		gi-gobject-2.0.28 \
		gi-gtk-3.0.39 \
		gi-harfbuzz-0.0.7 \
		gi-pango-1.0.27 \
		happy-1.20.0_1 \
		hashable-1.4.1.0 \
		haskell-gi-0.26.2 \
		haskell-gi-base-0.26.3 \
		haskell-gi-overloading-1.0 \
		haskell-lexer-1.1 \
		hsc2hs-0.68.8_1 \
		indexed-traversable-0.1.2_2 \
		indexed-traversable-instances-0.1.1.1 \
		integer-logarithms-1.0.3.1_3 \
		mono-traversable-1.0.15.3 \
		network-3.1.2.7 \
		pretty-show-1.10 \
		primitive-0.7.4.0 \
		random-1.2.1.1 \
		regex-base-0.94.0.2_1 \
		regex-tdfa-1.3.2 \
		resourcet-1.3.0 \
		safe-0.3.19 \
		scientific-0.3.7.0_3 \
		semialign-1.2.0.1_3 \
		semigroupoids-5.3.7 \
		split-0.2.3.5 \
		splitmix-0.1.0.4_1 \
		streaming-commons-0.2.2.5 \
		strict-0.4.0.1_4 \
		tagged-0.8.6.1_3 \
		text-short-0.1.5_1 \
		th-abstraction-0.4.5.0 \
		these-1.1.1.1_6 \
		time-compat-1.9.6.1_4 \
		transformers-compat-0.7.2 \
		typed-process-0.2.10.1 \
		unliftio-core-0.2.0.1_2 \
		unordered-containers-0.2.19.1_1 \
		uuid-types-1.0.5_3 \
		vector-0.13.0.0_1 \
		vector-algorithms-0.9.0.1_1 \
		vector-stream-0.1.0.0_1 \
		witherable-0.4.2_3 \
		xdg-basedir-0.2.2 \
		xml-conduit-1.9.1.1_2 \
		xml-types-0.3.8 \
		zlib-0.6.3.0

.include <bsd.port.mk>
