--- pyproject.toml.orig	2026-03-09 21:48:41 UTC
+++ pyproject.toml
@@ -7,7 +7,7 @@ maintainers = [{ name = "GeoPandas contributors" }]
 dynamic = ["version"]
 authors = [{ name = "Kelsey Jordahl", email = "kjordahl@alum.mit.edu" }]
 maintainers = [{ name = "GeoPandas contributors" }]
-license = "BSD-3-Clause"
+license = { text = "BSD 3-Clause" }
 description = "Geographic pandas extensions"
 keywords = ["GIS", "cartography", "pandas", "shapely"]
 classifiers = [
