--- src/modules/ssl/libssl.module.broken	Fri Dec 10 21:18:47 1999
+++ src/modules/ssl/libssl.module	Fri Dec 10 21:20:22 1999
@@ -260,7 +260,7 @@
     if [ ".$SSL_BASE" = . ]; then
         SSL_BASE=`egrep '^SSL_BASE=' $file | tail -1 | awk -F= '{print $2}'`
         if [ ".$SSL_BASE" = . ]; then
-            SSL_BASE="/usr/local/ssl"
+            SSL_BASE="@@PREFIX@@/ssl"
         fi
     fi
     case $SSL_BASE in
@@ -340,7 +340,7 @@
     #
     if [ ".$SSL_BASE" = .SYSTEM ]; then
         SSL_INCDIR=""
-        for p in . /usr/include /usr/include/ssl/ /usr/local/include /usr/local/include/ssl; do
+        for p in . /usr/include /usr/include/ssl/ /usr/local/include /usr/local/include/ssl @@PREFIX@@/include; do
             if [ -f "$p/openssl/ssl.h" ]; then
                 SSL_INCDIR="$p"
                 break
@@ -348,7 +348,7 @@
         done
         if [ ".$SSL_INCDIR" = . ]; then
             echo "Error: Cannot find SSL header files in any of the following dirs:" 1>&2
-            echo "Error: . /usr/include /usr/include/ssl/ /usr/local/include /usr/local/include/ssl" 1>&2
+            echo "Error: . /usr/include /usr/include/ssl/ /usr/local/include /usr/local/include/ssl @@PREFIX@@/include" 1>&2
             exit 1
         fi
     else
@@ -366,7 +366,7 @@
     #
     if [ ".$SSL_BASE" = .SYSTEM ]; then
         SSL_LIBDIR=""
-        for p in . /lib /usr/lib /usr/local/lib; do
+        for p in . /lib /usr/lib /usr/local/lib @@PREFIX@@/lib; do
             if [ -f "$p/libssl.a" -o -f "$p/libssl.so" ]; then
                 SSL_LIBDIR="$p"
                 my_real_ssl_libdir="$p"
@@ -375,7 +375,7 @@
         done
         if [ ".$SSL_LIBDIR" = . ]; then
             echo "Error: Cannot find SSL library files in any of the following dirs:" 1>&2
-            echo "Error: . /lib /usr/lib /usr/local/lib" 1>&2
+            echo "Error: . /lib /usr/lib /usr/local/lib @@PREFIX@@/lib" 1>&2
             exit 1
         fi
     else
@@ -449,7 +449,7 @@
     if [ ".$RSA_BASE" != . ]; then
         if [ ".$RSA_BASE" = .SYSTEM ]; then
             my_found=no
-            for p in . /lib /usr/lib /usr/local/lib; do
+            for p in . /lib /usr/lib /usr/local/lib @@PREFIX@@/lib; do
                 if [ -f "$p/librsaref.a" -o -f "$p/librsaref.so" ]; then
                     SSL_LDFLAGS="$SSL_LDFLAGS -L$p"
                     SSL_LIBS="$SSL_LIBS -lrsaref"
@@ -460,7 +460,7 @@
             done
             if [ .$my_found = .no ]; then
                 echo "Error: Cannot find RSAref library in any of the following dirs:" 1>&2
-                echo "Error: . /lib /usr/lib /usr/local/lib" 1>&2
+                echo "Error: . /lib /usr/lib /usr/local/lib @@PREFIX@@/lib" 1>&2
                 exit 1
             fi
         else
