# Created by: tonym
# $FreeBSD$

PORTNAME=	treeviewx
PORTVERSION=	0.5.1
PORTREVISION=	8
CATEGORIES=	biology
MASTER_SITES=	http://darwin.zoology.gla.ac.uk/~rpage/treeviewx/download/${PORTVERSION:S/.1//}/
DISTNAME=	tv-${PORTVERSION}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Phylogenetic tree viewer

USE_WX=		2.8
WX_COMPS=	wx
USES=		gmake
GNU_CONFIGURE=	yes

PLIST_FILES=	bin/tv

.include <bsd.port.mk>
