--- ./src/lxml/lxml.etree.c.orig	2012-03-26 10:31:59 UTC
+++ ./src/lxml/lxml.etree.c
@@ -1,5 +1,12 @@
 /* Generated by Cython 0.15.1 on Mon Mar 26 12:31:57 2012 */
 
+#if defined(__FreeBSD__)
+#include <sys/param.h>
+#if (__FreeBSD_version >= 1000000 && __FreeBSD_version < 1000010)
+#include <locale.h>
+#endif
+#endif
+
 #define PY_SSIZE_T_CLEAN
 #include "Python.h"
 #ifndef Py_PYTHON_H
