--- lib/unp.h.orig	Sun Sep 14 15:49:59 1997
+++ lib/unp.h	Thu Sep 30 11:12:55 1999
@@ -4,7 +4,7 @@
 #ifndef	__unp_h
 #define	__unp_h
 
-#include	"../config.h"	/* configuration options for current OS */
+#include	<unp/config.h>	/* configuration options for current OS */
 							/* "../config.h" is generated by configure */
 
 /* If anything changes in the following list of #includes, must change
@@ -197,7 +197,7 @@
 #define	max(a,b)	((a) > (b) ? (a) : (b))
 
 #ifndef	HAVE_ADDRINFO_STRUCT
-# include	"../lib/addrinfo.h"
+# include	<unp/addrinfo.h>
 #endif
 
 #ifndef	HAVE_IF_NAMEINDEX_STRUCT
