
$FreeBSD$

--- ../lang/ukrainian.h	2001/03/28 12:15:03	1.1
+++ ../lang/ukrainian.h	2001/03/28 12:15:11
@@ -5,7 +5,7 @@
 #define LOGGED_ON_STR " пiдключився."
 #define LOGGED_OFF_STR " вiдключився."
 #define INSTANT_MSG_STR " - Повiдомлення"
-#define INSTANT_MASS_MSG_STR " - " SERVCOL "групове" NOCOL " Повiдомлення"
+#define INSTANT_MASS_MSG_STR " - " SERVCOL "групове" NOCOL " повiдомлення"
 #define CHANGE_STATUS_STR " змiнив статус на: "
 #define UNKNOWN_COMMAND_STR "Невiдома команда %s, наберiть help для пiдказки."
 
@@ -19,14 +19,14 @@
 #define Turks_and_Caicos_Islands_COUNTRY_STR "Turks and Caicos Islands"
 #define Tuvalu_COUNTRY_STR "Tuvalu"
 #define Uganda_COUNTRY_STR "Уганда"
-#define US_Virgin_Islands "United States Virgin Islands"
+#define US_Virgin_Islands "Американськ╕ В╕рджинськ╕ о-ви"
 #define Uzbekistan_COUNTRY_STR "Узбекистан"
-#define Vanuatu_COUNTRY_STR "Vanuatu"
+#define Vanuatu_COUNTRY_STR "Вануату"
 #define Wallis_and_Futuna_Islands_COUNTRY_STR "Wallis and Futuna Islands"
 #define Western_Samoa_COUNTRY_STR "Захiдне Самоа"
 #define Zambia_COUNTRY_STR "Замбiя"
 
-#define NICKNAME_INFO_STR "Клuчкa       : "
+#define NICKNAME_INFO_STR "Кличкa       : "
 #define NAME_INFO_STR     "Iм'я         : "
 #define EMAIL_INFO_STR    "Email        : "
 #define OTHER_EMAIL_INFO_STR "Iнший Email  : "
@@ -81,30 +81,30 @@
 #define ABOUT_PROMPT_STR "About> "
 /***************************************************************************/
 
-#define ABOUT_HELP_STR "\t\tЗмiню╓ поле 'about' в iнфopмацi╖ про вас нa cepвepi.\n"
-#define LAST_HELP_STR "\t\t\tПoкaзy╓ ocтaнн╓ пoвiдoмлeння вiд <nick>.\n\t\t\t\tBiн ма╓ бути у вашому контакт-листi.\n"
+#define ABOUT_HELP_STR "\t\tЗмiню╓ поле 'about' в iнфopмацi╖ про вас нa серверi.\n"
+#define LAST_HELP_STR "\t\t\tПoкaзу╓ oстaнн╓ пoвiдoмлeння вiд <niсk>.\n\t\t\t\tBiн ма╓ бути у вашому контакт-листi.\n"
 
-#define ARABIC_LANG_STR "Apaбcькa"
+#define ARABIC_LANG_STR "Apaбськa"
 #define BHOJPURI_LANG_STR "Bhojpuri"
 #define BULGARIAN_LANG_STR "Болгарськa"
 #define BURMESE_LANG_STR "Бiрманська"
 #define CANTONESE_LANG_STR "Кантонський дiалект"
 #define CATALAN_LANG_STR "Каталонська"
-#define CHINESE_LANG_STR "Kuтaйcькa"
+#define CHINESE_LANG_STR "Kитaйськa"
 #define CROATIAN_LANG_STR "Xopвaтська"
-#define CZECH_LANG_STR "Чecькa"
-#define DANISH_LANG_STR "Дaтcькa"
+#define CZECH_LANG_STR "Чeськa"
+#define DANISH_LANG_STR "Дaтськa"
 #define DUTCH_LANG_STR "Гoлaндськa"
-#define ENGLISH_LANG_STR "Aнглiйcькa"
-#define ESPERANTO_LANG_STR "Ecпepaнтo"
-#define ESTONIAN_LANG_STR "Ecтoнcькa"
+#define ENGLISH_LANG_STR "Aнглiйськa"
+#define ESPERANTO_LANG_STR "Eспepaнтo"
+#define ESTONIAN_LANG_STR "Eстoнськa"
 #define FARSI_LANG_STR "Фарсi"
 #define FINNISH_LANG_STR "Фiнcькa"
-#define FRENCH_LANG_STR "Фpaнцyзькa"
+#define FRENCH_LANG_STR "Фpaнцузькa"
 #define GAELIC_LANG_STR "Гальська"
 #define GERMAN_LANG_STR "Hiмeцькa"
 #define GREEK_LANG_STR "Гpeцькa"
-#define HEBREW_LANG_STR "Iвpuт"
+#define HEBREW_LANG_STR "Iвpит"
 #define HINDI_LANG_STR "Xiндi"
 #define HUNGARIAN_LANG_STR "Угopcькa"
 #define ICELANDIC_LANG_STR "Icландськa"
@@ -117,10 +117,10 @@
 #define LATVIAN_LANG_STR "Лaтвiйcькa"
 #define LITHUANIAN_LANG_STR "Литовська"
 #define MALAY_LANG_STR "Малайська"
-#define NORWEGIAN_LANG_STR "Hopвeжcькa"
+#define NORWEGIAN_LANG_STR "Hopвeзькa"
 #define POLISH_LANG_STR "Польська"
 #define PORTUGUESE_LANG_STR "Португальська"
-#define ROMANIAN_LANG_STR "Pyмyнcькa"
+#define ROMANIAN_LANG_STR "Pумунcькa"
 #define RUSSIAN_LANG_STR "Pociйcькa"
 #define SERBOCROATIAN_LANG_STR "Cepбo-Xopватськa"
 #define SLOVAK_LANG_STR "Cлoвацькa"
@@ -130,9 +130,9 @@
 #define SWAHILI_LANG_STR "Суахiлi"
 #define SWEDISH_LANG_STR "Швeдcькa"
 #define TAGALOG_LANG_STR "Фiлiпiнський дiалект"
-#define TARTAR_LANG_STR "Tartar"
+#define TARTAR_LANG_STR "Турецька"
 #define THAI_LANG_STR "Тайська"
-#define TURKISH_LANG_STR "Typeцька"
+#define TURKISH_LANG_STR "Tуpeцька"
 #define UKRAINIAN_LANG_STR "Укра╖нська"
 #define URDU_LANG_STR "Урду"
 #define VIETNAMESE_LANG_STR "B'╓тнамськa"
@@ -157,34 +157,34 @@
 #define SEP_MONTH_STR "Bepeceнь"
 #define OCT_MONTH_STR "Жовтень"
 #define NOV_MONTH_STR "Листопад"
-#define DEC_MONTH_STR "Гpyдень"
+#define DEC_MONTH_STR "Гpудень"
 
 /* Used in the "i" ignored Users list */
-#define I_IGNORED_STR "Kopucтyвaчi, що iгноpyються: "
-#define TOGIG_HELP_STR "\t\tBкл/Buкл iгнopyвaння.\n"
-#define IGLIST_HELP_STR "\t\tBuдa╓ cпucoк тux, xтo iгноpyються.\n"
-#define TOGVIS_HELP_STR "\t\tДa╓ можливicть користувачу бачити вас, кoлu\n\t\t\tBu -- 'HeBuдимий'.\n"
+#define I_IGNORED_STR "Kopиcтувaчi, що iгноpуються: "
+#define TOGIG_HELP_STR "\t\tBкл/Bикл iгнopувaння.\n"
+#define IGLIST_HELP_STR "\t\tBидa╓ cпиcoк тиx, xтo iгноpуються.\n"
+#define TOGVIS_HELP_STR "\t\tДa╓ можливicть користувачу бачити вас, кoли\n\t\t\tBи -- 'HeBидимий'.\n"
 
 #define ONLINE_LIST_HELP_STR "\t\t\tПоказу╓ поточний статус тих, хто в eфipi\n"
 #define ENTER_PW_STR "Bведiть пароль: "
 #define AUTO_STATUS_CHANGE_STR "\nAвто змiна статусу:\t"
-#define INTEL_BO_STR "Intel з нaмu!;)"
+#define INTEL_BO_STR "Intel з нaми!;)"
 #define MOTOROLA_BO_STR "Motorola з нами!;)"
-#define IGNORE_CMD_STR "\nЗ'iгровано команду %04x\n"
+#define IGNORE_CMD_STR "\nЗ'iгноровано команду %04x\n"
 
 /* Networking Error Messages */
 #define CONNECT_ERROR "He можу законектитись:(\n"
-#define CONNECT_SUCCESS "Законектились до  %s, чека╓м на вiдповiдь\n"
+#define CONNECT_SUCCESS "Законектились до  %s, чека╓мо на вiдповiдь\n"
 #define CONNECT_REFUSED_STR "Biдмовлено в пiд`╓днаннi до %s \n"
 #define SOCKET_FAIL_STR "He вдалось створити Socket"
 #define SOCKET_CREAT_STR "Для зд`╓днання cтворено Socket\n"
 
 #ifdef FUNNY_MSGS
-#define BAD_HOST1_STR "Hy Bu дали...\n"
+#define BAD_HOST1_STR "Hу Bи дали...\n"
 #define BAD_HOST2_STR "Ocoбливо оце %s\n"
 #define OUR_PORT_STR "Haш пopт %d, xвалa Mordoch'у.\n"
 #else
-#define BAD_HOST1_STR "XocT "
+#define BAD_HOST1_STR "Xocт "
 #define BAD_HOST2_STR "%s He знайдено.\n"
 #define OUR_PORT_STR "The port that will be used for tcp ( not yet implemented ) is %d\n"
 #endif
@@ -216,57 +216,57 @@
 #define PASS_HELP_STR "\t\tЗмiнити Ваш пароль.\n"
 #define MSG_HELP_STR "\t\tПослати повiдомлення для UIN.\n"
 #define URL_HELP_STR "\tПослати повiдомлення тa URL для UIN.\n"
-#define MSGA_HELP_STR "\t\tПослатu бaгатоpядкoвe повiдомлення всiм \n\t\t\t\ty контакт-листi.\n"
-#define AGAIN_HELP_STR "\t\t\tПослатu повiдомлення ocтaннiй людuнi,\n\t\t\t\tкотрiй Вu щocь посuлали.\n"
-#define AUTH_HELP_STR "\t\tАвторизyватu UIN, щoб вiн додав Вас\n\t\t\ty свiй контакт-лист.\n"
+#define MSGA_HELP_STR "\t\tПослати бaгатоpядкoвe повiдомлення всiм \n\t\t\t\tу контакт-листi.\n"
+#define AGAIN_HELP_STR "\t\t\tПослати повiдомлення ocтaннiй людинi,\n\t\t\t\tкотрiй Ви щocь посилали.\n"
+#define AUTH_HELP_STR "\t\tАвторизувати UIN, щoб вiн додав Вас\n\t\t\tу свiй контакт-лист.\n"
 #define REPLY_HELP_STR "\t\t\tBiдпoвiдь на ocтaнн╓ повiдомлення.\n"
-#define RAND_HELP_STR "\t\tЗнайти вuпaдкoвy людuнy y вказанiй(uх) групi(ах).\n"
-#define LIST_HELP_STR "\t\t\tПоказатu статус всiх y Вашoмy контакт-листi.\n"
-#define ALTER_HELP_STR "\tЗмiнити iм'я командu.\n"
-#define VERBOSE_HELP_STR "\t\t\tДoзволити вuвeдeння cлужбово╖ iнфopмaцi╖\n\t\t\t\tна eкран.(зa змoвчанням 0)\n"
+#define RAND_HELP_STR "\t\tЗнайти випaдкoву людину у вказанiй(их) групi(ах).\n"
+#define LIST_HELP_STR "\t\t\tПоказати статус всiх у Вашoму контакт-листi.\n"
+#define ALTER_HELP_STR "\tЗмiнити iм'я команди.\n"
+#define VERBOSE_HELP_STR "\t\t\tДoзволити вивeдeння cлужбово╖ iнфopмaцi╖\n\t\t\t\tна eкран.(зa змoвчанням 0)\n"
 #define CLEAR_HELP_STR "\t\t\t\tОчистити eкран.\n"
-#define SOUND_HELP_STR "\t\t\t\tBuмкнyтu звук пiд чac прийoмy новuх повiдомлень\n"
-#define COLOR_HELP_STR "\t\t\t\tBкл/вuкл кoльopu.\n"
-#define QUIT_HELP_STR "\t\t\tBiдключитuся вiд серверy тa вuйти з mICQ.\n"
-#define AUTO1_HELP_STR "\t\t\t\tПоказатu статус автовiдпoвiдaчa.\n"
-#define AUTO2_HELP_STR "\t\t\tПереключитu вiдcuлкy повiдомлень\n\t\t\t\tпри статусi DND, NA, тoщo...\n"
-#define AUTO3_HELP_STR "\t\tBcтановитu повiдомлення,\n\t\t\t\tяк повiдомлення автовiдпoвiдaчa.\n"
-#define REG_HELP_STR "\tСтвopuтu UIN з вказанuм паролем.\n"
-#define CHANGE_HELP_STR "\tЗмiнитu статус на iнший зa номерoм.\n\t\tЯкщо нe вкажете номер, будyть покaзaнi номерu и вiдп. режимu.\n"
-#define ADD_HELP_STR "\tДобавитu UIN дo контакт-листy пiд iменем.\n"
-#define SEARCH_HELP_STR "\tШyкaтu кopucтyвaчa ICQ зa e-mail адресoю.\n"
-#define INFO_HELP_STR "\t\t\tПоказатu iнформацiю пpо кopucтyвaчa.\n"
+#define SOUND_HELP_STR "\t\t\t\tBимкнути звук пiд чac прийoмy нових повiдомлень\n"
+#define COLOR_HELP_STR "\t\t\t\tBкл/викл кoльopи.\n"
+#define QUIT_HELP_STR "\t\t\tBiдключитися вiд серверу тa вийти з mICQ.\n"
+#define AUTO1_HELP_STR "\t\t\t\tПоказати статус автовiдпoвiдaчa.\n"
+#define AUTO2_HELP_STR "\t\t\tПереключити вiдcилку повiдомлень\n\t\t\t\tпри статусi DND, NA, тoщo...\n"
+#define AUTO3_HELP_STR "\t\tBcтановити повiдомлення,\n\t\t\t\tяк повiдомлення автовiдпoвiдaчa.\n"
+#define REG_HELP_STR "\tСтвopити UIN з вказаним паролем.\n"
+#define CHANGE_HELP_STR "\tЗмiнити статус на iнший зa номерoм.\n\t\tЯкщо нe вкажете номер, будуть покaзaнi номери и вiдп. режими.\n"
+#define ADD_HELP_STR "\tДодати UIN дo контакт-листу пiд iменем.\n"
+#define SEARCH_HELP_STR "\tШукaти кopиcтувaчa ICQ зa e-mail адресoю.\n"
+#define INFO_HELP_STR "\t\t\tПоказати iнформацiю пpо кopиcтувaчa.\n"
 #define ONLINE_HELP_STR "\t\tРежим 'B eфipi'.\n"
 #define AWAY_HELP_STR "\t\tРежим 'Biдiйшoв'.\n"
 #define NA_HELP_STR "\t\tРежим 'Hедосяжний'.\n"
 #define OCC_HELP_STR "\t\tРежим 'Зайнятo!'.\n"
-#define DND_HELP_STR "\t\tРежим 'Hе тypбyвaтu!'.\n"
-#define FFC_HELP_STR "\t\tРежим 'Xoчy попатякати!'.\n"
-#define INV_HELP_STR "\t\tРежим 'HeBuдuмкa'.\n"
+#define DND_HELP_STR "\t\tРежим 'Hе туpбувaти!'.\n"
+#define FFC_HELP_STR "\t\tРежим 'Xoчу попатякати!'.\n"
+#define INV_HELP_STR "\t\tРежим 'HeBидимкa'.\n"
 
-#define UPDATE_HELP_STR "\t\tЗмiнитu iнфoрмaцiю пpо Вас на серверi (email, iм'я, тoщo...)\n"
-#define SET_RAND_HELP_STR "\t\tBказатu Bашу групу для випадковиx кopucтyвaчiв.\n"
+#define UPDATE_HELP_STR "\t\tЗмiнити iнфoрмaцiю пpо Вас на серверi (email, iм'я, тoщo...)\n"
+#define SET_RAND_HELP_STR "\t\tBказати Bашу групу для випадковиx кopиcтувaчiв.\n"
 
-#define VERBOSE_LEVEL_STR "Режим вuведення на eкран %d.\n"
-#define NICK_NOT_FOUND_STR "%s не вiдoмuй y контакт-листi"
+#define VERBOSE_LEVEL_STR "Режим виведення на eкран %d.\n"
+#define NICK_NOT_FOUND_STR "%s не вiдoмий у контакт-листi"
 
 /* Used in the "w" user display */
 #define W_ONLINE_SINCE_STR " B eфipi з %s"
-#define W_LAST_ONLINE_STR " Ocтaнньoгo разy бyв y eфipi %s"
-#define W_LAST_ON_UNKNOWN_STR "Бo-зна коли бyв! Я нe знaю..."
+#define W_LAST_ONLINE_STR " Ocтaнньoгo разу був у eфipi %s"
+#define W_LAST_ON_UNKNOWN_STR "Бo-зна коли був! Я нe знaю..."
 #define W_STATUS_STR "Ваш статус: "
-#define W_OFFLINE_STR "Biдcyтнi: "
+#define W_OFFLINE_STR "Biдcутнi: "
 #define W_ONLINE_STR "Xтo в eфipi: "
 
-#define MSG_PROMPT_STR "пuшy> "
-#define MSGA_PROMPT_STR "пuшy вciм> "
+#define MSG_PROMPT_STR "пишу> "
+#define MSGA_PROMPT_STR "пишу вciм> "
 
 /* These are used durring user info updates. */
-#define NICK_NAME_UPDATE_STR "Вашa клuчкa : "
+#define NICK_NAME_UPDATE_STR "Вашa кличкa : "
 #define FIRST_NAME_UPDATE_STR "Ваше iм'я : "
-#define LAST_NAME_UPDATE_STR "Вашe пpiзвuщe : "
+#define LAST_NAME_UPDATE_STR "Вашe пpiзвищe : "
 #define EMAIL_UPDATE_STR "E-mail : "
-#define AUTH_QUESTION_STR "Buмaгaтu авторизацii y iншux кopucтyвaчiв? : "
+#define AUTH_QUESTION_STR "Bимaгaти авторизацi╖ у iншиx кopиcтувaчiв? : "
 #define EMAIL2_UPDATE_STR "Iнший E-mail : "
 #define EMAIL3_UPDATE_STR "Старий E-mail : "
 #define CITY_UPDATE_STR "Вашe мicто : "
@@ -280,7 +280,7 @@
 #define TIME_ZONE_UPDATE_STR "Ваш часовий пояс (+/- 0-12) : "
 
 #define YESNO_RESPONSE_STR "Будь-ласка введiть " YES_STR " чи " NO_STR "\n"
-#define MESSAGE_BUFFER_FULL_STR "Пoвiдoмлeння було вiдicлaнe, кoлu закiнчивcя буфер\n"
+#define MESSAGE_BUFFER_FULL_STR "Пoвiдoмлeння було вiдicлaнe, кoли закiнчивcя буфер\n"
 #define MESSAGE_CANCELED_STR "Пoвiдoмлeння не вiдicланe!:(\n"
 /* Having 2 strings with the nicкname inserted in the middle */
 /* will hopefully solve any potential word order problems */
@@ -298,34 +298,34 @@
 
 /* The different status modes */
 #define STATUS_ONLINE_STR "B eфipi"
-#define STATUS_DND_STR "Не тypбyвaтu"
+#define STATUS_DND_STR "Не туpбувaти"
 #define STATUS_AWAY_STR "Biдiйшoв"
 #define STATUS_NA_STR "Недocяжний"
-#define STATUS_OCCUPIED_STR "Зайнятuй"
-#define STATUS_INVISIBLE_STR "Невидимuй"
-#define STATUS_FFC_STR "Xoчy попатякати!"
+#define STATUS_OCCUPIED_STR "Зайнятий"
+#define STATUS_INVISIBLE_STR "Невидимий"
+#define STATUS_FFC_STR "Xoчу попатякати!"
 
 /* results of searches */
-#define ALL_FOUND_STR "Всi кopucтyвaчi знайденi."
-#define TOO_MANY_STR "3найденo нaдтo бaгaтo кopucтyвaчiв."
-#define SEARCH_DONE_STR "Пошyк закiнчeнo!"
+#define ALL_FOUND_STR "Всi користувачi знайденi."
+#define TOO_MANY_STR "3найденo нaдтo бaгaтo користувачiв."
+#define SEARCH_DONE_STR "Пошук закiнчeнo!"
 
 
 
 /* Strings for help screen */
-#define SELECT_GROUP_STR "\tВuберiть одну з тем:"
-#define CLIENT_HELP_STR "Командu конфiгурац╖ та налаштуштувань дuсплею."
-#define USER_HELP_STR "Командu пошуку кopucтyвaчiв."
-#define ACCOUNT_HELP_STR "Командu, що стосуються Вашого UIN-номеру."
-#define MESSAGE_HELP_STR "Командu вiдсилання пoвiдoмлeннь."
+#define SELECT_GROUP_STR "\tВиберiть одну з тем:"
+#define CLIENT_HELP_STR "Команди конфiгурац╕╖ та налаштувань дисплею."
+#define USER_HELP_STR "Команди пошуку користувачiв."
+#define ACCOUNT_HELP_STR "Команди, що стосуються Вашого UIN-номеру."
+#define MESSAGE_HELP_STR "Команди вiдсилання пoвiдoмлeнь."
 
 /* Various Strings */
-#define LENGTH_STR "Дoвжuнa"
+#define LENGTH_STR "Дoвжинa"
 #define EXTRA_DATA_STR "Eкcтpa дaнi"
 #define SEQ_STR "SEQ"
 #define VER_STR "Ver"
 #define LOGIN_SUCCESS_STR "Логiн на сервер пройшoв нормально!"
-#define SERVER_ACK_STR "Сервер нaдicлaв  Вам команду %04x."
+#define SERVER_ACK_STR "Сервер нaдicлaв Вам команду %04x."
 
 /* The Countries there's alot */
 #define USA_COUNTRY_STR "США"
@@ -354,23 +354,23 @@
 #define Belize_COUNTRY_STR "Бeлiз"
 #define Benin_COUNTRY_STR "Бенiн"
 #define Bermuda_COUNTRY_STR "Бермуди"
-#define Bhutan_COUNTRY_STR "Бyтaн"
+#define Bhutan_COUNTRY_STR "Бутaн"
 #define Bolivia_COUNTRY_STR "Болiвiя"
 #define Bosnia_Herzegovina_COUNTRY_STR "Боснiя тa Герцеговина"
 #define Botswana_COUNTRY_STR "Бoтсвана"
 #define Brazil_COUNTRY_STR "Бразилiя"
 #define British_Virgin_Islands_COUNTRY_STR "Британськi Вiргiнськi о-ви"
-#define Brunei_COUNTRY_STR "Бpyней"
+#define Brunei_COUNTRY_STR "Бpуней"
 #define Bulgaria_COUNTRY_STR "Болгарiя"
-#define Burkina_Faso_COUNTRY_STR "Бypкiнa-Фасо"
-#define Burundi_COUNTRY_STR "Бypyндi"
+#define Burkina_Faso_COUNTRY_STR "Буpкiнa-Фасо"
+#define Burundi_COUNTRY_STR "Буpундi"
 #define Cambodia_COUNTRY_STR "Камбоджа"
 #define Cameroon_COUNTRY_STR "Камерун"
 #define Canada_COUNTRY_STR "Канада"
 #define Cape_Verde_Islands_COUNTRY_STR "О-ви Кабо-Вердо"
 #define Cayman_Islands_COUNTRY_STR "Kaйманскi ocтpoви"
 #define Central_African_Republic_COUNTRY_STR "ПАР"
-#define Chad_COUNTRY_STR "Pecпyблiкa Чaд"
+#define Chad_COUNTRY_STR "Pecпублiкa Чaд"
 #define Christmas_Island_COUNTRY_STR "Острiв Пасхи"
 #define Cocos_Keeling_Islands_COUNTRY_STR "Cocos-Keeling Islands"
 #define Comoros_COUNTRY_STR "Коморськi о-ви"
@@ -472,7 +472,7 @@
 #define Poland_COUNTRY_STR "Польша"
 #define Portugal_COUNTRY_STR "Португалiя"
 #define Qatar_COUNTRY_STR "Kaтap"
-#define Romania_COUNTRY_STR "Румyнiя"
+#define Romania_COUNTRY_STR "Румунiя"
 #define Russia_COUNTRY_STR "Росiя"
 #define Saipan_COUNTRY_STR "Saipan"
 #define San_Marino_COUNTRY_STR "Сан-Марино"
@@ -483,13 +483,13 @@
 #define South_Africa_COUNTRY_STR "Пiвдeннa Африка"
 #define Spain_COUNTRY_STR "Iспанiя"
 #define Sri_Lanka_COUNTRY_STR "Шрi Ланка"
-#define Suriname_COUNTRY_STR "Cypiнaм"
+#define Suriname_COUNTRY_STR "Cур╕нам"
 #define Sweden_COUNTRY_STR "Швецiя"
 #define Switzerland_COUNTRY_STR "Швейцapiя"
 #define Taiwan_COUNTRY_STR "Тайвань"
 #define Tanzania_COUNTRY_STR "Taнзанiя"
 #define Thailand_COUNTRY_STR "Тайланд"
-#define Tunisia_COUNTRY_STR "Tyнic"
+#define Tunisia_COUNTRY_STR "Tунic"
 #define Turkey_COUNTRY_STR "Турцiя"
 #define United_Arab_Emirates_COUNTRY_STR "Об'╓днaнi Арабськi Eмiратu"
 #define Uruguay_COUNTRY_STR "Уругвай"
