--- pytest.ini.orig	2026-04-19 05:34:30 UTC
+++ pytest.ini
@@ -10,6 +10,9 @@ addopts =
     -p no:warnings
     # Use custom pytest shard located in test/pytest_shard_custom.py instead
     -p no:pytest-shard
+    # Disable coverage collection (pytest-enabler auto-enables it; causes SIGBUS on FreeBSD)
+    -p no:enabler
+    -p no:cov
     # don't rewrite assertions (usually not a problem in CI due to differences in imports, see #95844)
     --assert=plain
 testpaths =
