--- pyproject.toml.orig	2026-06-02 08:32:39 UTC
+++ pyproject.toml
@@ -14,8 +14,7 @@ requires-python = ">=3.11"
   "threadpoolctl>=3.5.0",
 ]
 requires-python = ">=3.11"
-license = "BSD-3-Clause"
-license-files = ["COPYING"]
+license = {text="BSD-3-Clause"}
 classifiers=[
   "Intended Audience :: Science/Research",
   "Intended Audience :: Developers",
