# New ports collection makefile for:	ghostscript-gnu-commfont
# Date created:		Dec 24 2001
# Whom:			Tomokatsu SAITO <saito@a2z.co.jp>
#
# $FreeBSD$
#

MASTERDIR=	${.CURDIR}

COMMFONT=	yes

.include "${MASTERDIR}/Makefile.common"
