--- src/libs/libgroff/Makefile.sub.orig	2011-01-14 22:49:35.567009974 +0100
+++ src/libs/libgroff/Makefile.sub	2011-01-14 22:49:39.566978160 +0100
@@ -151,7 +151,7 @@
 
 MKINSTALLDIRS = $(SHELL) $(top_srcdir)/mkinstalldirs
 
-install_data: install_charset_data
+install_data:
 install_charset_data:
 	test $(GLIBC21) != no || $(MKINSTALLDIRS) $(DESTDIR)$(libdir)
 	if test -f $(DESTDIR)$(libdir)/charset.alias; then \
