--- pyproject.toml.orig	2026-05-06 14:38:18 UTC
+++ pyproject.toml
@@ -1,6 +1,6 @@ requires = [
 [build-system]
 requires = [
-    "setuptools>=77.0.0",
+    "setuptools>=61.0.0",
     "numpy>=2.0.0",
 ]
 build-backend = "setuptools.build_meta"
@@ -14,8 +14,7 @@ maintainers = [{ name = "Blosc Development Team", emai
 readme = "README.rst"
 authors = [{name = "David M. Cooke, Francesc Alted, and others", email = "blosc@blosc.org"}]
 maintainers = [{ name = "Blosc Development Team", email = "blosc@blosc.org"}]
-license = "MIT"
-license-files = ["LICENSE.txt", "LICENSES/*"]
+license = {text = "MIT"}
 classifiers = [
     "Development Status :: 6 - Mature",
     "Intended Audience :: Developers",
