--- fsk/gendf9icfilt.cc.orig	2013-12-13 08:19:49.459920041 -0500
+++ fsk/gendf9icfilt.cc	2013-12-13 08:43:50.641820677 -0500
@@ -41,6 +41,8 @@
 
 #include "getopt.h"
 
+#define FFTSZ 2048
+
 /* --------------------------------------------------------------------- */
 
 template<typename T> complex<T> rxfilter(T freq)
@@ -173,7 +175,8 @@
 		printtransferfunc(os, fftsz, over);
 	else
 		os << "/* this file is automatically generated, do not edit!! */\n\n";
-	complex<double> fftb[fftsz];
+//	complex<double> fftb[fftsz];
+	complex<double> fftb[FFTSZ];
 	double rpulse[fftsz], tpulse[fftsz];
 	double dover = double(over) / fftsz;
 	double sum;
