--- fsk/gendf9icfilt.cc.orig	2003-01-06 14:28:19 UTC
+++ fsk/gendf9icfilt.cc
@@ -41,6 +41,8 @@ using namespace std;
 
 #include "getopt.h"
 
+#define FFTSZ 2048
+
 /* --------------------------------------------------------------------- */
 
 template<typename T> complex<T> rxfilter(T freq)
@@ -173,7 +175,8 @@ static void printfcoeff(ostream& os, uns
 		printtransferfunc(os, fftsz, over);
 	else
 		os << "/* this file is automatically generated, do not edit!! */\n\n";
-	complex<double> fftb[fftsz];
+//	complex<double> fftb[fftsz];
+	complex<double> fftb[FFTSZ];
 	double rpulse[fftsz], tpulse[fftsz];
 	double dover = double(over) / fftsz;
 	double sum;
