Properly align both prompts.

--- parallel-dimensions/slim.theme.orig	2009-05-22 13:07:27.000000000 +0400
+++ parallel-dimensions/slim.theme	2009-05-22 13:07:52.000000000 +0400
@@ -26,7 +26,7 @@
 # Username / password request
 username_font          	Verdana:size=14:bold
 username_color        	#f9f9f9
-username_x              280
+username_x              50%
 username_y              183
 password_x              50%
 password_y              183
