# Created by: Skylord
# $FreeBSD$

PORTNAME=	stats
PORTVERSION=	1.1
PORTREVISION=	2
CATEGORIES=	net-p2p
MASTER_SITES=	SF/verlihub/VH_Stats/${DISTVERSION}

MAINTAINER=	me@skylord.ru

PLUGIN_DESC=	Statistics

NO_STAGE=	yes
.include <bsd.port.pre.mk>
.include "${PORTSDIR}/net-p2p/verlihub-plugins/Makefile.plugins"
.include <bsd.port.post.mk>
