.TH MCPLAY "1" "March 2010" "mcplay 0.3i" "User Commands"
.SH NAME
mcplay \- A curses based front-end for various audio players
.SH SYNOPSIS
.B mcplay
[\fIoptions\fR] [\fIfile|dir|playlist\fR]...
.SH DESCRIPTION
.B mcplay
is a reimplementation in C of the well-known python program 'cplay'.
.PP
The following players are supported: mpg123 ogg123 sox
.PP
Files, Directories and Playlist\-Files (m3u\-files) given as arguments on the
commandline will be added to the internal playlist.
.SH OPTIONS
.TP
\fB\-a\fR, \fB\-\-aggressive\fR
Increase the priority of the players (if possible).
.TP
\fB\-c\fR, \fB\-\-color\fR
Run program in colored mode (if available).
.TP
\fB\-l\fR, \fB\-\-logfile\fR
Log messages to this file.  [default: /tmp/mcplay.log]
.TP
\fB\-p\fR, \fB\-\-play\fR
Start playing the playlist.
.TP
\fB\-r\fR, \fB\-\-repeat\fR
Start in repeat playlist mode.
.TP
\fB\-R\fR, \fB\-\-random\fR
Start in random playlist mode.
.TP
\fB\-\-version\fR
Print version information.
.TP
\fB\-\-copyright\fR
Print copyright information.
.TP
\fB\-h\fR, \fB\-\-help\fR
Shows this text.
.PP
Press 'h' while mcplay is running for help on keys.
.SH SEE ALSO
Website: http://www.yahuxo.de/mcplay/
.SH AUTHOR
Tobias Rapp <yahuxo at gmx.de>
.SH LICENSE
Copyright (C) 2002 Tobias Rapp.

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, write to the Free Software
Foundation, 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

