# Created by: Anes Mukhametov <anes@anes.su>
# $FreeBSD$

PORTNAME=	Text-Hyphen
PORTVERSION=	0.11
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	anes@anes.su
COMMENT=	Determine positions for hyphens inside words

LICENSE=	BSD

NO_STAGE=	yes
USE_PERL5=	configure
USES=		perl5

MAN3=		Text::Hyphen.3

.include <bsd.port.mk>
