# New ports collection makefile for:   consolehm
# Version required:    1.2
# Date created:        27 September 1999
# Whom:                Mike Muir <mmuir@es.co.nz>
#
# $FreeBSD$
#

DISTNAME=	consolehm-1.2
CATEGORIES=	sysutils
MASTER_SITES= 	ftp://mongol.dhis.org/pub/consolehm/ \
		http://www.es.co.nz/~mmuir/

MAINTAINER=	mmuir@es.co.nz

WRKSRC=		${WRKDIR}/consolehm/consolehm
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
