--- cmake/libutils.cmake.orig	2025-03-31 07:51:10 UTC
+++ cmake/libutils.cmake
@@ -385,9 +385,6 @@ MACRO(MERGE_LIBRARIES_SHARED TARGET_ARG)
     ELSE()
       SET(DESTINATION "${INSTALL_LIBDIR}")
     ENDIF()
-    IF(ARG_NAMELINK_SKIP)
-      SET(INSTALL_ARGS NAMELINK_SKIP)
-    ENDIF()
     MYSQL_INSTALL_TARGET(${TARGET} DESTINATION "${DESTINATION}" ${COMP}
       ${INSTALL_ARGS})
   ENDIF()
@@ -643,9 +640,6 @@ FUNCTION(ADD_SHARED_LIBRARY TARGET_ARG)
       SET(COMP COMPONENT ${ARG_COMPONENT})
     ELSE()
       SET(COMP COMPONENT SharedLibraries)
-    ENDIF()
-    IF(ARG_NAMELINK_SKIP)
-      SET(INSTALL_ARGS NAMELINK_SKIP)
     ENDIF()
     MYSQL_INSTALL_TARGET(${TARGET} DESTINATION "${DESTINATION}" ${COMP}
       ${INSTALL_ARGS})
