.TH NIFTICLIB 1
.SH NAME    \" Section header
.PP
 
NIFTICLIB - Neuroimaging Informatics Technology Initiative data format

.SH "DESCRIPTION"

.B Nifticlib
is a set of tools and libraries for maintaining a common data format
among neuroimaging applications.  For documentation, please visit
http://nifti.nimh.nih.gov/

.SH "SEE ALSO"
afni(1), fsl(1), caret(1)

.SH AUTHOR
.nf
.na
Robert Cox, PhD, et. al.

