# $FreeBSD$

PORTNAME=	omniauth
PORTVERSION=	1.1.4
CATEGORIES=	security rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Generalized Rack framework for multiple-provider authentication.

RUN_DEPENDS=	rubygem-rack>=0:${PORTSDIR}/www/rubygem-rack \
		rubygem-hashie>=1.2:${PORTSDIR}/devel/rubygem-hashie

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes


.include <bsd.port.mk>
