--- src/wmclient.h.orig	2000-10-30 21:25:19.000000000 +0100
+++ src/wmclient.h	2007-10-09 15:57:28.000000000 +0200
@@ -20,24 +20,24 @@ extern "C" {
 #define WM_CLIENT_CLASS(klass)  GTK_CHECK_CLASS_CAST (klass, wm_client_get_type (), WmClientClass)
 #define IS_WM_CLIENT(obj)       GTK_CHECK_TYPE (obj, wm_client_get_type ())
 
-#define WM_CLIENT_X(obj)      ((gint16)(((WmClient *)obj)->x))
-#define WM_CLIENT_Y(obj)      ((gint16)(((WmClient *)obj)->y))
-#define WM_CLIENT_X_PREV(obj)  ((guint16)((WmClient *)obj)->priviousX)
-#define WM_CLIENT_Y_PREV(obj) ((guint16)((WmClient *)obj)->priviousY)
-#define WM_CLIENT_WIDTH(obj)  ((guint16)((WmClient *)obj)->width)
-#define WM_CLIENT_HEIGHT(obj) ((guint16)((WmClient *)obj)->height)
-#define WM_CLIENT_W_PREV(obj)  ((guint16)((WmClient *)obj)->priviousWidth)
-#define WM_CLIENT_H_PREV(obj) ((guint16)((WmClient *)obj)->priviousHeight)
-#define WM_CLIENT_SIZE_FLAG(obj) ((guint16)((WmClient *)obj)->size_flags)
-#define WM_CLIENT_W_INC(obj)  ((gint16)((WmClient *)obj)->width_inc)
-#define WM_CLIENT_H_INC(obj)  ((gint16)((WmClient *)obj)->height_inc)
-#define WM_CLIENT_W_BASE(obj)  ((gint16)((WmClient *)obj)->base_width)
-#define WM_CLIENT_H_BASE(obj)  ((gint16)((WmClient *)obj)->base_height)
-#define WM_CLIENT_W_MIN(obj)  ((gint16)((WmClient *)obj)->min_width)
-#define WM_CLIENT_H_MIN(obj)  ((gint16)((WmClient *)obj)->min_height)
-#define WM_CLIENT_W_MAX(obj)  ((gint16)((WmClient *)obj)->max_width)
-#define WM_CLIENT_H_MAX(obj)  ((gint16)((WmClient *)obj)->max_height)
-#define WM_CLIENT_STATE(obj)  ((gint16)((WmClient *)obj)->state)
+#define WM_CLIENT_X(obj)      ((((WmClient *)obj)->x))
+#define WM_CLIENT_Y(obj)      ((((WmClient *)obj)->y))
+#define WM_CLIENT_X_PREV(obj)  (((WmClient *)obj)->priviousX)
+#define WM_CLIENT_Y_PREV(obj) (((WmClient *)obj)->priviousY)
+#define WM_CLIENT_WIDTH(obj)  (((WmClient *)obj)->width)
+#define WM_CLIENT_HEIGHT(obj) (((WmClient *)obj)->height)
+#define WM_CLIENT_W_PREV(obj)  (((WmClient *)obj)->priviousWidth)
+#define WM_CLIENT_H_PREV(obj) (((WmClient *)obj)->priviousHeight)
+#define WM_CLIENT_SIZE_FLAG(obj) (((WmClient *)obj)->size_flags)
+#define WM_CLIENT_W_INC(obj)  (((WmClient *)obj)->width_inc)
+#define WM_CLIENT_H_INC(obj)  (((WmClient *)obj)->height_inc)
+#define WM_CLIENT_W_BASE(obj)  (((WmClient *)obj)->base_width)
+#define WM_CLIENT_H_BASE(obj)  (((WmClient *)obj)->base_height)
+#define WM_CLIENT_W_MIN(obj)  (((WmClient *)obj)->min_width)
+#define WM_CLIENT_H_MIN(obj)  (((WmClient *)obj)->min_height)
+#define WM_CLIENT_W_MAX(obj)  (((WmClient *)obj)->max_width)
+#define WM_CLIENT_H_MAX(obj)  (((WmClient *)obj)->max_height)
+#define WM_CLIENT_STATE(obj)  (((WmClient *)obj)->state)
 #define WM_CLIENT_BORDER_WIDTH(obj)  ((guint16)((WmClient *)obj)->border_width)
 #define WM_CLIENT_BORDER_FRAME(obj)  ((gchar *)((WmClient *)obj)->border_frame)
 #define WM_CLIENT_GROUP(obj)  (((WmClient *)obj)->group)
