#!/bin/sh
# $FreeBSD$

PATH=/bin:/usr/sbin
USER=umurmur
GROUP=umurmur
RUNDIR=/var/run/umurmur

case $2 in
	POST-DEINSTALL)
		if pw group show ${GROUP} 2>&1 > /dev/null; then
			echo "You should manually remove the \"${GROUP}\" group."
		fi

		if pw user show ${USER} 2>&1 > /dev/null; then
			echo "You should manually remove the \"${USER}\" user."
		fi

		rm -Rf ${RUNDIR}
		;;
esac
