.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH "BTTRACK" 1 "Jan 18 2003"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
bttrack \- tracker for bittorrent
.SH SYNOPSIS
.B bttrack \fI [ option ... ]
.SH DESCRIPTION
This manual page documents briefly the \fIbttrack\fP
command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBbttrack\fP is a program that serves as a "tracker" for 
bittorrent clients.  This program keeps track of the completion
of each client, and communcates that information when requested
to other clients.
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
.B \-\-port \fIportnum\fP
listen on port \fIportnum\fP (default 80)
.TP
.B \-\-dfile \fIfilename\fP
store recent downloader info in \fIfilename\fP
.TP
.B \-\-bind \fIip\fP
bind to \fIip\fP instead of the default
.TP
.B \-\-socket_timeout \fIsecs\fP
timeout for closing connections (default 15)
.TP
.B \-\-save_dfile_interval \fIsecs\fP
seconds between saving dfile (default 300)
.TP
.B \-\-timeout_downloaders_interval \fIsecs\fP
seconds between expiring downloaders (default 2700)
.TP
.B \-\-reannounce_interval \fIsecs\fP
seconds downloaders should wait between reannouncements (default 1800)
.TP
.B \-\-response_size \fInum\fP
number of peers to send in an info message (default 50)
.TP
.B \-\-timeout_check_interval \fIsecs\fP
time to wait between checking if any connections have timed out (default 5)
.TP
.B \-\-nat_check \fI[ 1 | 0 ]\fP
whether to check back and ban downloaders behind NAT (default 1)
.TP
.B \-\-min_time_between_log_flushes \fIsecs\fP
minimum time it must have been since the last flush to do another one (default 3.0)
.TP
.B \-\-allowed_dir \fIpath\fP
only allow downloads for .torrents in this directory (default '')
.TP
.B \-\-parse_allowed_interval \fImins\fP
minutes between reloading of allowed_dir (default 15)
.TP
.B \-\-show_names \fI[ 1 | 0 ]\fP
whether to display names from alowed dir (default 1)

.SH SEE ALSO
.BR bittorrent-downloader (1),
.BR btmakemetafile (1).
.br
.SH AUTHOR
This manual page was written by Michael Janssen <jamuraa@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
