--- sysctlinfo.h.orig	2020-10-05 19:37:03 UTC
+++ sysctlinfo.h
@@ -40,27 +40,27 @@
 /* 
  * MIB level 2, sysctlinfo identifiers
  */
-#define ENTRYFAKENAME				7
-#define ENTRYNAME				8
-#define ENTRYDESC				9
-#define ENTRYLABEL				10
-#define ENTRYKIND				11
-#define ENTRYFMT				12
-#define ENTRYNEXTNODE				13
-#define ENTRYNEXTLEAF				14
-#define ENTRYALLINFO				15
-#define ENTRYALLINFO_WITHNEXTNODE		16
-#define ENTRYALLINFO_WITHNEXTLEAF		17
-#define ENTRYIDBYNAME				18
-#define ENTRYFAKEIDBYNAME			19
-#define ENTRYDESCBYNAME				20
-#define ENTRYLABELBYNAME			21
-#define ENTRYKINDBYNAME				22
-#define ENTRYFMTBYNAME				23
-#define ENTRYALLINFOBYNAME			24
-#define ENTRYALLINFOBYNAME_WITHNEXTNODE		25
-#define ENTRYALLINFOBYNAME_WITHNEXTLEAF		26
-#define ENTRYIDINPUTBYNAME			27
+#define ENTRYFAKENAME				8
+#define ENTRYNAME				9
+#define ENTRYDESC				10
+#define ENTRYLABEL				11
+#define ENTRYKIND				12
+#define ENTRYFMT				13
+#define ENTRYNEXTNODE				14
+#define ENTRYNEXTLEAF				15
+#define ENTRYALLINFO				16
+#define ENTRYALLINFO_WITHNEXTNODE		17
+#define ENTRYALLINFO_WITHNEXTLEAF		18
+#define ENTRYIDBYNAME				19
+#define ENTRYFAKEIDBYNAME			20
+#define ENTRYDESCBYNAME				21
+#define ENTRYLABELBYNAME			22
+#define ENTRYKINDBYNAME				23
+#define ENTRYFMTBYNAME				24
+#define ENTRYALLINFOBYNAME			25
+#define ENTRYALLINFOBYNAME_WITHNEXTNODE		26
+#define ENTRYALLINFOBYNAME_WITHNEXTLEAF		27
+#define ENTRYIDINPUTBYNAME			28
 
 #define SYSCTLINFO_MAXFAKENAME			64
 
