.Dd May 7, 2003
.Dt FREEBSD-UPDATE 8
.Os FreeBSD
.Sh NAME
.Nm freebsd-update
.Nd fetch and install binary security updates to FreeBSD
.Sh SYNOPSIS
.Nm
.Cm command
.Sh DESCRIPTION
The
.Nm
tool is used to fetch, install, and rollback
binary security updates to the FreeBSD base system.
.Sh OPTIONS
The
.Cm command
can be any one of the following:
.Pp
.Bl -tag -width "rollback" -compact
.It fetch
Based on the currently installed world, fetch all available
binary updates.  Any updates previously fetched but not
installed will be fetched again.
.Pp
.It install
Install the most recently fetched updates.
.Pp
.It rollback
Uninstall the most recently installed updates.
.Pp
.It cron
If any binary updates are available, fetch them and
send an email to root; otherwise, exit silently. As
the name suggests, this is intended for usage via
cron(8).
.Pp
.El
.Sh TIPS
.Bl -bullet
.It
If your clock is set to local time, adding the line
.Pp
.Dl 0 3 * * * root /usr/local/sbin/freebsd-update cron
.Pp
to /etc/crontab will check for updates every night.  If your
clock is set to UTC, please pick a random time instead of
3AM, or the server hosting the updates will be very unhappy.
.It
.Nm
.Cm cron
waits a random amount of time, up to an hour, before contacting
the server in order to reduce the risk of "flash crowds" resulting
from cron jobs.
.El
.Sh FILES
.Bl -tag -width "$PREFIX/etc/freebsd-update.conf"
.It $PREFIX/freebsd-update/work
Location of downloaded updates and backups of files
which have been updated.
.It $PREFIX/etc/freebsd-update.conf
Location of the freebsd-update configuration file.
.Sh SEE ALSO
.Xr freebsd-update.conf 5
.Sh AUTHORS
.An Colin Percival Aq cperciva@daemonology.net
