.Dd May 7, 2003
.Dt FREEBSD-UPDATE.CONF 8
.Os FreeBSD
.Sh NAME
.Nm freebsd-update.conf
.Nd configuration file for freebsd-update
.Sh DESCRIPTION
The
.Nm
file controls where freebsd-update(8) fetches updates from, and
which RSA key should be trusted to sign the updates.
.Pp
A line of the form
.Dl URL=foobar
specifies the source from which updates should be fetched.  This
can be any type of URL suitable for fetch(1) -- in particular, HTTP,
FTP, and local paths are all permitted.
.Pp
A line of the form
.Dl KEYPRINT=0123456789ABCDEF0123456789ABCDEF
specifies the MD5 hash of the 2048 bit modulus belonging to an RSA
keypair which is trusted to sign updates.
.Pp
If more than one line of either of the above forms is included in
.Nm
then only the last one will take effect.  Any lines not of the above
forms will be ignored.
.Sh FILES
.Bl -tag -width "$PREFIX/etc/freebsd-update.conf"
.It $PREFIX/etc/freebsd-update.conf
Location of the freebsd-update configuration file.
.Sh SEE ALSO
.Xr fetch 1
.Xr freebsd-update 8
.Sh AUTHORS
.An Colin Percival Aq cperciva@daemonology.net
