# New ports collection makefile for: Mew (for mule)
# Version required:	1.94.1
# Date created:		17 January 1998
# Whom:			Kiriyama Kazuhiko <kiri@kiri.toba-cmt.ac.jp>
#
# $FreeBSD$
#

EMACS_PORT_NAME=	mule

.include "${.CURDIR}/../mew/Makefile"
