PORTNAME=	file-tail
PORTVERSION=	1.2.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby library that allows Ruby to 'tail' files
WWW=		https://github.com/flori/file-tail

LICENSE=	GPLv2
LICENSE_FILE=	${WRKSRC}/COPYING

RUN_DEPENDS=	rubygem-tins>=1.0<2:devel/rubygem-tins

USES=		gem

NO_ARCH=	yes

.include <bsd.port.mk>
