# configuration file for newsyslog for tinyauth
#
# see newsyslog.conf(5) for details
#
# logfilename          [owner:group]    mode count size when  flags [/pid_file] [sig_num]
/var/log/tinyauth.log			644  7	  1000 *      JC    /var/run/tinyauthd.pid
