PORTNAME=	isbnlib
PORTVERSION=	3.10.12
CATEGORIES=	textproc python
MASTER_SITES=	PYPI
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Extract, clean, transform, hyphenate and metadata for ISBNs
WWW=		https://github.com/xlcnd/isbnlib

LICENSE=	LGPL3
LICENSE_FILE=	${WRKSRC}/LICENSE-LGPL-3.0.txt

USES=		python:3.6+
USE_PYTHON=	autoplist concurrent distutils

NO_ARCH=	yes

.include <bsd.port.mk>
