# FreeBSD compatibility shim
find_package(SuiteSparse_config REQUIRED)
find_package(AMD REQUIRED)
find_package(CAMD REQUIRED)
find_package(COLAMD REQUIRED)
find_package(CCOLAMD REQUIRED)
find_package(CHOLMOD REQUIRED)
if(NOT SuiteSparse_FOUND)
  set(SuiteSparse_FOUND TRUE)
  set(SUITESPARSE_INCLUDE_DIRS "${SuiteSparse_config_INCLUDE_DIR}")
  set(SUITESPARSE_LIBRARIES "${SuiteSparse_config_LIBRARIES}")
  set(SuiteSparse_INCLUDE_DIRS "${SuiteSparse_config_INCLUDE_DIR}")
  set(SuiteSparse_LIBRARIES "${SuiteSparse_config_LIBRARIES}")
endif()
