HAVE_GLUT := yes
HAVE_LIBCRYPTO := no
HAVE_OPENSSL_SSL := no
HAVE_PTHREAD := yes
HAVE_X11 := yes
PTHREAD_LIBS := -lthr
SYS_CMARK_GFM_CFLAGS := $(shell pkg-config --cflags libcmark-gfm)
SYS_CMARK_CFM_LIBS := $(shell pkg-config --libs libcmark-gfm) -lcmark-gfm-extensions
SYS_CURL_CFLAGS := $(shell pkg-config --cflags libcurl)
SYS_CURL_LIBS := $(shell pkg-config --libs libcurl)
SYS_FREETYPE_CFLAGS := $(shell pkg-config --cflags freetype2)
SYS_FREETYPE_LIBS := $(shell pkg-config --libs freetype2)
SYS_GLUT_CFLAGS := $(shell pkg-config --cflags gl glut)
SYS_GLUT_LIBS := $(shell pkg-config --libs gl glut)
SYS_HARFBUZZ_CFLAGS := $(shell pkg-config --cflags harfbuzz)
SYS_HARFBUZZ_LIBS := $(shell pkg-config --libs harfbuzz)
SYS_JBIG2DEC_CFLAGS := $(shell pkg-config --cflags jbig2dec)
SYS_JIB2DEC_LIBS := $(shell pkg-config --libs jbig2dec)
SYS_LIBCRYPTO_CFLAGS :=
SYS_LIBCRYPTO_LIBS :=
SYS_LIBJPEG_CFLAGS := $(shell pkg-config --cflags libjpeg)
SYS_LIBJPEG_LIBS := $(shell pkg-config --libs libjpeg)
SYS_OPENJPEG_CFLAGS := $(shell pkg-config --cflags libopenjp2)
SYS_OPENJPEG_LIBS := $(shell pkg-config --libs libopenjp2)
SYS_PTHREAD_CFLAGS :=
SYS_PTHREAD_LIBS := -lpthread
SYS_ZLIB_CFLAGS := $(shell pkg-config --cflags zlib)
SYS_ZLIB_LIBS := $(shell pkg-config --libs zlib)
USE_SYSTEM_CMARK_GFM := yes
USE_SYSTEM_CURL := yes
USE_SYSTEM_FREETYPE := yes
USE_SYSTEM_GLUT := yes
USE_SYSTEM_HARFBUZZ := yes
USE_SYSTEM_JBIG2DEC := yes
USE_SYSTEM_LCMS2 := no
USE_SYSTEM_LIBJPEG := yes
USE_SYSTEM_OPENJPEG := yes
USE_SYSTEM_ZLIB := yes
X11_CFLAGS := $(shell pkg-config --cflags x11 xext)
X11_LIBS := $(shell pkg-config --libs x11 xext)
