--- libs/png/pngusr.h.orig	2012-05-22 20:07:48.130398383 +1200
+++ libs/png/pngusr.h	2012-05-22 20:08:22.669413168 +1200
@@ -292,5 +292,124 @@
 #define png_get_uint_31 pdf_png_get_uint_31
 #define png_set_add_alpha pdf_png_set_add_alpha
 
+#define png_check_cHRM_fixed pdf_png_check_cHRM_fixed
+#define png_check_keyword pdf_png_check_keyword
+#define png_convert_from_struct_tm pdf_png_convert_from_struct_tm
+#define png_convert_from_time_t pdf_png_convert_from_time_t
+#define png_convert_size pdf_png_convert_size
+#define png_correct_palette pdf_png_correct_palette
+#define png_create_write_struct pdf_png_create_write_struct
+#define png_create_write_struct_2 pdf_png_create_write_struct_2
+#define png_default_flush pdf_png_default_flush
+#define png_default_write_data pdf_png_default_write_data
+#define png_destroy_write_struct pdf_png_destroy_write_struct
+#define png_do_pack pdf_png_do_pack
+#define png_do_shift pdf_png_do_shift
+#define png_do_write_interlace pdf_png_do_write_interlace
+#define png_do_write_intrapixel pdf_png_do_write_intrapixel
+#define png_do_write_invert_alpha pdf_png_do_write_invert_alpha
+#define png_do_write_swap_alpha pdf_png_do_write_swap_alpha
+#define png_do_write_transformations pdf_png_do_write_transformations
+#define png_err pdf_png_err
+#define png_flush pdf_png_flush
+#define png_get_pHYs_dpi pdf_png_get_pHYs_dpi
+#define png_get_pixels_per_inch pdf_png_get_pixels_per_inch
+#define png_get_progressive_ptr pdf_png_get_progressive_ptr
+#define png_get_sCAL_s pdf_png_get_sCAL_s
+#define png_get_x_offset_inches pdf_png_get_x_offset_inches
+#define png_get_x_pixels_per_inch pdf_png_get_x_pixels_per_inch
+#define png_get_y_offset_inches pdf_png_get_y_offset_inches
+#define png_get_y_pixels_per_inch pdf_png_get_y_pixels_per_inch
+#define png_handle_iTXt pdf_png_handle_iTXt
+#define png_pass_height pdf_png_pass_height
+#define png_process_IDAT_data pdf_png_process_IDAT_data
+#define png_process_data pdf_png_process_data
+#define png_process_some_data pdf_png_process_some_data
+#define png_progressive_combine_row pdf_png_progressive_combine_row
+#define png_push_check_crc pdf_png_push_check_crc
+#define png_push_crc_finish pdf_png_push_crc_finish
+#define png_push_crc_skip pdf_png_push_crc_skip
+#define png_push_fill_buffer pdf_png_push_fill_buffer
+#define png_push_handle_iTXt pdf_png_push_handle_iTXt
+#define png_push_handle_tEXt pdf_png_push_handle_tEXt
+#define png_push_handle_unknown pdf_png_push_handle_unknown
+#define png_push_handle_zTXt pdf_png_push_handle_zTXt
+#define png_push_have_end pdf_png_push_have_end
+#define png_push_have_info pdf_png_push_have_info
+#define png_push_have_row pdf_png_push_have_row
+#define png_push_process_row pdf_png_push_process_row
+#define png_push_read_IDAT pdf_png_push_read_IDAT
+#define png_push_read_chunk pdf_png_push_read_chunk
+#define png_push_read_end pdf_png_push_read_end
+#define png_push_read_iTXt pdf_png_push_read_iTXt
+#define png_push_read_sig pdf_png_push_read_sig
+#define png_push_read_tEXt pdf_png_push_read_tEXt
+#define png_push_read_zTXt pdf_png_push_read_zTXt
+#define png_push_restore_buffer pdf_png_push_restore_buffer
+#define png_push_save_buffer pdf_png_push_save_buffer
+#define png_read_chunk_header pdf_png_read_chunk_header
+#define png_read_push_finish_row pdf_png_read_push_finish_row
+#define png_save_int_32 pdf_png_save_int_32
+#define png_save_uint_16 pdf_png_save_uint_16
+#define png_save_uint_32 pdf_png_save_uint_32
+#define png_set_compression_level pdf_png_set_compression_level
+#define png_set_compression_mem_level pdf_png_set_compression_mem_level
+#define png_set_compression_method pdf_png_set_compression_method
+#define png_set_compression_strategy pdf_png_set_compression_strategy
+#define png_set_compression_window_bits pdf_png_set_compression_window_bits
+#define png_set_expand_gray_1_2_4_to_8 pdf_png_set_expand_gray_1_2_4_to_8
+#define png_set_filter pdf_png_set_filter
+#define png_set_filter_heuristics pdf_png_set_filter_heuristics
+#define png_set_flush pdf_png_set_flush
+#define png_set_progressive_read_fn pdf_png_set_progressive_read_fn
+#define png_set_sCAL_s pdf_png_set_sCAL_s
+#define png_set_write_fn pdf_png_set_write_fn
+#define png_set_write_status_fn pdf_png_set_write_status_fn
+#define png_set_write_user_transform_fn pdf_png_set_write_user_transform_fn
+#define png_write_IDAT pdf_png_write_IDAT
+#define png_write_IEND pdf_png_write_IEND
+#define png_write_IHDR pdf_png_write_IHDR
+#define png_write_PLTE pdf_png_write_PLTE
+#define png_write_bKGD pdf_png_write_bKGD
+#define png_write_cHRM pdf_png_write_cHRM
+#define png_write_cHRM_fixed pdf_png_write_cHRM_fixed
+#define png_write_chunk pdf_png_write_chunk
+#define png_write_chunk_data pdf_png_write_chunk_data
+#define png_write_chunk_end pdf_png_write_chunk_end
+#define png_write_chunk_start pdf_png_write_chunk_start
+#define png_write_data pdf_png_write_data
+#define png_write_end pdf_png_write_end
+#define png_write_filtered_row pdf_png_write_filtered_row
+#define png_write_find_filter pdf_png_write_find_filter
+#define png_write_finish_row pdf_png_write_finish_row
+#define png_write_flush pdf_png_write_flush
+#define png_write_gAMA pdf_png_write_gAMA
+#define png_write_gAMA_fixed pdf_png_write_gAMA_fixed
+#define png_write_hIST pdf_png_write_hIST
+#define png_write_iCCP pdf_png_write_iCCP
+#define png_write_iTXt pdf_png_write_iTXt
+#define png_write_image pdf_png_write_image
+#define png_write_info pdf_png_write_info
+#define png_write_info_before_PLTE pdf_png_write_info_before_PLTE
+#define png_write_init pdf_png_write_init
+#define png_write_init_2 pdf_png_write_init_2
+#define png_write_init_3 pdf_png_write_init_3
+#define png_write_oFFs pdf_png_write_oFFs
+#define png_write_pCAL pdf_png_write_pCAL
+#define png_write_pHYs pdf_png_write_pHYs
+#define png_write_png pdf_png_write_png
+#define png_write_row pdf_png_write_row
+#define png_write_rows pdf_png_write_rows
+#define png_write_sBIT pdf_png_write_sBIT
+#define png_write_sCAL pdf_png_write_sCAL
+#define png_write_sCAL_s pdf_png_write_sCAL_s
+#define png_write_sPLT pdf_png_write_sPLT
+#define png_write_sRGB pdf_png_write_sRGB
+#define png_write_sig pdf_png_write_sig
+#define png_write_start_row pdf_png_write_start_row
+#define png_write_tEXt pdf_png_write_tEXt
+#define png_write_tIME pdf_png_write_tIME
+#define png_write_tRNS pdf_png_write_tRNS
+#define png_write_zTXt pdf_png_write_zTXt
 #endif /* PNG_PREFIX */
 
