Relax some version requirements.

--- pyproject.toml.orig	2006-07-24 01:21:28 UTC
+++ pyproject.toml
@@ -49,7 +49,7 @@ dependencies = [
 dynamic = ["version"]
 dependencies = [
     "click>=8.1.8",
-    "deepmerge>=2.0",
+    "deepmerge>=1.1.1",
     "jinja2>=3.1",
     "markdown>=3.7",
     "pygments>=2.20",
