# Created by: Thierry Thomas <thierry@pompo.net>

PORTNAME=	admisc
DISTVERSION=	0.29
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	thierry@FreeBSD.org
COMMENT=	Adrian Dusa's Miscellaneous

LICENSE=	GPLv3+

USES=		cran:compiles

.include <bsd.port.mk>
