# New ports collection makefile for:	sh-rtems-objc
# Date created:		9 June 2000
# Whom:			James Housley <jim@thehousleys.net>
#
# $FreeBSD$
#

PORTNAME=	objc

MAINTAINER=	jeh@FreeBSD.org

LCLTARGET=	sh-rtems

MASTERDIR=	${.CURDIR}/../i386-rtems-objc
.include "${MASTERDIR}/Makefile"
