--- pyproject.toml.orig	2026-05-01 00:38:10 UTC
+++ pyproject.toml
@@ -2,8 +2,6 @@ requires = [
 requires = [
     "setuptools>=24.2.0",
     "wheel",
-    "cmake",
-    "ninja",
 ]
 
 [tool.pytest.ini_options]
