--- tests/020-xauth-add-local.script.orig	2017-02-06 20:55:37 UTC
+++ tests/020-xauth-add-local.script
@@ -11,7 +11,7 @@ xauth add :3.5                . b90b0fd1
 xauth add :4                  . b90b0fd1cf6a0e7a2c74c00000000004
 
 # List the number of entries added
-xauth list | wc -l
+xauth list | wc -l | xargs echo
 
 # Try to match them and print cookie
 xauth list unix:0        | awk '{print $3}'
