# ex:ts=8
# Ports collection makefile for:	py-istring
# Date created:			Apr 28, 2002
# Whom:	      			ijliao
#
# $FreeBSD$
#

PORTNAME=	istring
PORTVERSION=	1.0.1
CATEGORIES=	devel python
MASTER_SITES=	http://www.neosynapse.net/downloads/
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	${PORTNAME}${PORTVERSION:S/.//g}

DEPRECATED=	"master site up but distfile unavailable"
EXPIRATION_DATE=2005-07-31

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Interpolated Strings

USE_PYTHON=	yes
USE_PYDISTUTILS=	yes
WRKSRC=		${WRKDIR}/${PORTNAME}

.include <bsd.port.mk>
