--- srclib/apr-util/xml/expat/buildconf.sh.orig	Wed Nov 17 02:12:20 2004
+++ srclib/apr-util/xml/expat/buildconf.sh	Sat Dec 11 17:04:11 2004
@@ -3,7 +3,7 @@
 #
 # Find libtoolize
 #
-libtoolize=`conftools/PrintPath glibtoolize libtoolize libtoolize15 libtoolize14`
+libtoolize=${LIBTOOLIZE}
 if [ "x$libtoolize" = "x" ]; then
     echo "libtoolize not found in path"
     exit 1
@@ -33,7 +33,7 @@
   ltfile=libtool.m4
 else
   ltpath=`dirname $libtoolize`
-  ltfile=${LIBTOOL_M4-`cd $ltpath/../share/aclocal ; pwd`/libtool.m4}
+  ltfile=${LIBTOOL_M4-`cd $ltpath/../../share/aclocal ; pwd`/libtool${LIBTOOL_VERSION}.m4}
 fi
 echo "Incorporating $ltfile into aclocal.m4 ..."
 echo "dnl THIS FILE IS AUTOMATICALLY GENERATED BY buildconf.sh" > aclocal.m4
