--- pyproject.toml.orig	2026-10-06 21:33:54 UTC
+++ pyproject.toml
@@ -7,7 +7,7 @@ authors = [
 authors = [
     {name = "David Aguilar", email = "davvid@gmail.com"}
 ]
-license = "GPL-2.0"
+license = {text = "GPL-2.0"}
 classifiers = [
     "Development Status :: 6 - Mature",
     "Intended Audience :: Developers",
