--- cmake/Modules/Pod2Man.cmake.orig	2018-10-13 18:36:15 UTC
+++ cmake/Modules/Pod2Man.cmake
@@ -21,7 +21,7 @@
 # To use it, include this file in CMakeLists.txt and
 # invoke POD2MAN(<podfile> <manfile> <section>)
 
-MACRO(POD2MAN PODFILE MANFILE SECTION)
+MACRO(POD2MAN PODFILE MANFILE SECTION MANPAGE_DEST_PREFIX)
 	FIND_PROGRAM(POD2MAN pod2man)
 	FIND_PROGRAM(GZIP gzip)
 
@@ -58,7 +58,7 @@ MACRO(POD2MAN PODFILE MANFILE SECTION)
 
 	INSTALL(
 		FILES ${CMAKE_CURRENT_BINARY_DIR}/${MANFILE}.${SECTION}.gz
-		DESTINATION share/man/man${SECTION}
+		DESTINATION ${MANPAGE_DEST_PREFIX}/man${SECTION}
     	)
 ENDMACRO(POD2MAN PODFILE MANFILE SECTION)
 
