--- xioopts.h.orig	2015-01-24 10:15:22 UTC
+++ xioopts.h
@@ -474,11 +474,13 @@ enum e_optcode {
    OPT_OPENSSL_CERTIFICATE,
    OPT_OPENSSL_CIPHERLIST,
    OPT_OPENSSL_COMMONNAME,
-#if OPENSSL_VERSION_NUMBER >= 0x00908000L
+#if OPENSSL_VERSION_NUMBER >= 0x00908000L && !defined(OPENSSL_NO_COMP)
    OPT_OPENSSL_COMPRESS,
 #endif
    OPT_OPENSSL_DHPARAM,
+#ifdef HAVE_RAND_egd_method
    OPT_OPENSSL_EGD,
+#endif
    OPT_OPENSSL_FIPS,
    OPT_OPENSSL_KEY,
    OPT_OPENSSL_METHOD,
