--- eb.c.orig	Sat Jun 23 02:44:43 2001
+++ eb.c	Sat Mar 30 18:53:13 2002
@@ -1018,10 +1018,16 @@
 	rb_define_const(mEB, "HOOK_BEGIN_COLOR_JPEG", INT2FIX(EB_HOOK_BEGIN_COLOR_JPEG));
  	rb_define_const(mEB, "HOOK_END_COLOR_GRAPHIC", INT2FIX(EB_HOOK_END_COLOR_GRAPHIC));
 
+#if	EB_VERSION_MINOR < 2
 	rb_define_const(mEB, "HOOK_STOP_CODE", INT2FIX(EB_HOOK_STOP_CODE));
 
 	rb_define_const(mEB, "HOOK_BEGIN_IN_COLOR_BMP", INT2FIX(EB_HOOK_BEGIN_IN_COLOR_BMP));
 	rb_define_const(mEB, "HOOK_BEGIN_IN_COLOR_JPEG", INT2FIX(EB_HOOK_BEGIN_IN_COLOR_JPEG));
+#else
+	rb_define_const(mEB, "HOOK_BEGIN_GRAPHIC_REFERENCE", INT2FIX(EB_HOOK_BEGIN_GRAPHIC_REFERENCE));
+	rb_define_const(mEB, "HOOK_END_GRAPHIC_REFERENCE", INT2FIX(EB_HOOK_END_GRAPHIC_REFERENCE));
+	rb_define_const(mEB, "HOOK_GRAPHIC_REFERENCE", INT2FIX(EB_HOOK_GRAPHIC_REFERENCE));
+#endif
 	rb_define_const(mEB, "HOOK_END_IN_COLOR_GRAPHIC", INT2FIX(EB_HOOK_END_IN_COLOR_GRAPHIC));
 
 	rb_define_const(mEB, "HOOK_BEGIN_WAVE", INT2FIX(EB_HOOK_BEGIN_WAVE));
