--- pyproject.toml.orig	2026-05-14 19:17:42 UTC
+++ pyproject.toml
@@ -10,7 +10,7 @@ readme = "README.md"
 ]
 description = "Tools to ease creating larger test libraries for Robot Framework using Python."
 readme = "README.md"
-license = "Apache-2.0"
+license = {text = "Apache-2.0"}
 keywords = ["robotframework", "testing", "testautomation", "library", "development"]
 classifiers = [
     "Development Status :: 5 - Production/Stable",
