--- pyproject.toml.orig	2020-02-02 00:00:00 UTC
+++ pyproject.toml
@@ -46,7 +46,7 @@ dependencies = [
     "packaging>=24.2",
     "array_api_compat>=1.7.1",
     "legacy-api-wrap",
-    "zarr >=2.18.7, !=3.0.*",
+    "zarr >=2.18.4, !=3.0.*",
     "scverse-misc>=0.0.3",
 ]
 dynamic = [ "version" ]
