--- pyproject.toml.orig	2026-04-24 14:50:35 UTC
+++ pyproject.toml
@@ -1,5 +1,5 @@
 [build-system]
-requires = ["build>=1.2.2", "setuptools>=80.7.1", "setuptools-scm>=9.2"]
+requires = ["setuptools>=61", "setuptools-scm>=9.2"]
 build-backend = "setuptools.build_meta"
 
 [project]
@@ -10,8 +10,7 @@ keywords = ["CLI", "cmd", "command", "interactive", "p
 readme = "README.md"
 requires-python = ">=3.10"
 keywords = ["CLI", "cmd", "command", "interactive", "prompt", "Python"]
-license = "MIT"
-license-files = ["LICENSE"]
+license = { file = "LICENSE" }
 classifiers = [
     "Development Status :: 5 - Production/Stable",
     "Environment :: Console",
@@ -31,7 +30,7 @@ dependencies = [
 dependencies = [
     "backports.strenum; python_version == '3.10'",
     "gnureadline>=8; platform_system == 'Darwin'",
-    "pyperclip>=1.8.2",
+    "pyperclip>=1.7",
     "pyreadline3>=3.4; platform_system == 'Windows'",
     "rich>=15.0.0",
     "rich-argparse>=1.7.2",
