.TH PRAAT 1
.SH NAME    \" Section header
.PP
 
PRAAT \- Doing phonetics by computer.

.SH SYNOPSIS
.PP
.nf 
.na 
praat
.ad
.fi

\" Optional sections
.SH "DESCRIPTION"

Praat is a sophisticated graphical tool for analyzing and manipulating
phonetic data.

Praat supports a variety of sound file formats, and consists of tools
to support speech analysis, labelling and segmentation, learning
algorithms, graphing, speech synthesis, listening experiments,
speech manipulation, and statistics.  It also includes a scripting
language to help automate the analysis process.

For documentation, see the Help menu in praat, or visit the WEB site:
https://www.fon.hum.uva.nl/praat/ .

.SH "SEE ALSO"
audacity(1)

.SH AUTHOR
.nf
.na
Paul Boersma and David Weenink   
Institute of Phonetic Sciences
University of Amsterdam

