--- pyproject.toml.orig	2026-03-20 15:34:30 UTC
+++ pyproject.toml
@@ -35,7 +35,7 @@ Repository = "https://github.com/python-metar/python-m
 Repository = "https://github.com/python-metar/python-metar/"
 
 [build-system]
-requires = ["setuptools>=64", "setuptools_scm>=8"]
+requires = ["setuptools>=61", "setuptools_scm>=8"]
 build-backend = "setuptools.build_meta"
 
 [project.optional-dependencies]
