# New ports collection makefile for:    xchomp
# Date created:         4 Jan 1995
# Whom:                 swallace
#
# $FreeBSD$
#

PORTNAME=	xchomp
PORTVERSION=	pl1
PORTREVISION=	2
CATEGORIES=	games
MASTER_SITES=	ftp://ftp.x.org/R5contrib/

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Pac-man-like game under X11

PLIST_FILES=	bin/xchomp
WRKSRC=		${WRKDIR}/xchomp
USE_IMAKE=	yes
USE_XORG=	x11 xext

.include <bsd.port.mk>
