--- pyproject.toml.orig	2026-08-09 01:21:15 UTC
+++ pyproject.toml
@@ -254,7 +254,7 @@ healthcheck = [
 ]
 
 [build-system]
-requires = ["maturin==1.9.4"]
+requires = ["maturin>=1.9.4"]
 build-backend = "maturin"
 
 [tool.maturin]
