--- pyproject.toml.orig	2026-08-15 23:56:31 UTC
+++ pyproject.toml
@@ -256,7 +256,7 @@ healthcheck = [
 ]
 
 [build-system]
-requires = ["maturin==1.9.4"]
+requires = ["maturin>=1.9.4"]
 build-backend = "maturin"
 
 [tool.maturin]
