--- pyproject.toml.orig	2026-06-10 13:39:49 UTC
+++ pyproject.toml
@@ -1,7 +1,6 @@ requires = [
 [build-system]
 requires = [
     "cython",
-    "cmake>=3.24.2,<3.28",
     "setuptools-rust<2",
     "patchelf>=0.17.0.0; sys_platform == 'linux'",
 ]
