# New ports collection makefile for:	lws
# Date created:				21 Aug 2002
# Whom:					Archie Cobbs
#
# $FreeBSD$
#

PORTNAME=		lws
PORTVERSION=		0.2.1
CATEGORIES=		www
MASTER_SITES=		${MASTER_SITE_LOCAL}
MASTER_SITE_SUBDIR=	archie

MAINTAINER=		archie@freebsd.org
COMMENT=	Lightweight threaded HTTP/HTTPS web server based on libpdel(3)

LIB_DEPENDS=		pdel.0:${PORTSDIR}/devel/libpdel

MAN1=			lws.1
MANCOMPRESSED=		yes

.include <bsd.port.mk>
