-- Remove version constraint on setuptools to be compatible with the port.
--- pyproject.toml.orig	2026-05-04 01:27:44 UTC
+++ pyproject.toml
@@ -1,5 +1,5 @@
 [build-system]
-requires = ["setuptools>=64"]
+requires = ["setuptools"]
 build-backend = "setuptools.build_meta"
 
 [project]
