--- bolt.gemspec.orig	2020-12-04 20:50:32 UTC
+++ bolt.gemspec
@@ -26,7 +26,7 @@ Gem::Specification.new do |s|
     if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
       s.add_runtime_dependency(%q<addressable>.freeze, ["~> 2.5"])
       s.add_runtime_dependency(%q<aws-sdk-ec2>.freeze, ["~> 1"])
-      s.add_runtime_dependency(%q<CFPropertyList>.freeze, ["~> 2.2"])
+      s.add_runtime_dependency(%q<CFPropertyList>.freeze, [">= 2.2"])
       s.add_runtime_dependency(%q<concurrent-ruby>.freeze, ["~> 1.0"])
       s.add_runtime_dependency(%q<hiera-eyaml>.freeze, ["~> 3"])
       s.add_runtime_dependency(%q<jwt>.freeze, ["~> 2.2"])
@@ -37,11 +37,11 @@ Gem::Specification.new do |s|
       s.add_runtime_dependency(%q<net-ssh-krb>.freeze, ["~> 0.5"])
       s.add_runtime_dependency(%q<orchestrator_client>.freeze, ["~> 0.4"])
       s.add_runtime_dependency(%q<puppet>.freeze, [">= 6.18.0"])
-      s.add_runtime_dependency(%q<puppetfile-resolver>.freeze, ["~> 0.4"])
+      s.add_runtime_dependency(%q<puppetfile-resolver>.freeze, [">= 0.4"])
       s.add_runtime_dependency(%q<puppet-resource_api>.freeze, [">= 1.8.1"])
       s.add_runtime_dependency(%q<puppet-strings>.freeze, ["~> 2.3"])
       s.add_runtime_dependency(%q<r10k>.freeze, ["~> 3.1"])
-      s.add_runtime_dependency(%q<ruby_smb>.freeze, ["~> 1.0"])
+      s.add_runtime_dependency(%q<ruby_smb>.freeze, [">= 1.0"])
       s.add_runtime_dependency(%q<terminal-table>.freeze, ["~> 1.8"])
       s.add_runtime_dependency(%q<winrm>.freeze, ["~> 2.0"])
       s.add_runtime_dependency(%q<winrm-fs>.freeze, ["~> 1.3"])
@@ -53,7 +53,7 @@ Gem::Specification.new do |s|
     else
       s.add_dependency(%q<addressable>.freeze, ["~> 2.5"])
       s.add_dependency(%q<aws-sdk-ec2>.freeze, ["~> 1"])
-      s.add_dependency(%q<CFPropertyList>.freeze, ["~> 2.2"])
+      s.add_dependency(%q<CFPropertyList>.freeze, [">= 2.2"])
       s.add_dependency(%q<concurrent-ruby>.freeze, ["~> 1.0"])
       s.add_dependency(%q<hiera-eyaml>.freeze, ["~> 3"])
       s.add_dependency(%q<jwt>.freeze, ["~> 2.2"])
@@ -64,11 +64,11 @@ Gem::Specification.new do |s|
       s.add_dependency(%q<net-ssh-krb>.freeze, ["~> 0.5"])
       s.add_dependency(%q<orchestrator_client>.freeze, ["~> 0.4"])
       s.add_dependency(%q<puppet>.freeze, [">= 6.18.0"])
-      s.add_dependency(%q<puppetfile-resolver>.freeze, ["~> 0.4"])
+      s.add_dependency(%q<puppetfile-resolver>.freeze, [">= 0.4"])
       s.add_dependency(%q<puppet-resource_api>.freeze, [">= 1.8.1"])
       s.add_dependency(%q<puppet-strings>.freeze, ["~> 2.3"])
       s.add_dependency(%q<r10k>.freeze, ["~> 3.1"])
-      s.add_dependency(%q<ruby_smb>.freeze, ["~> 1.0"])
+      s.add_dependency(%q<ruby_smb>.freeze, [">= 1.0"])
       s.add_dependency(%q<terminal-table>.freeze, ["~> 1.8"])
       s.add_dependency(%q<winrm>.freeze, ["~> 2.0"])
       s.add_dependency(%q<winrm-fs>.freeze, ["~> 1.3"])
@@ -81,7 +81,7 @@ Gem::Specification.new do |s|
   else
     s.add_dependency(%q<addressable>.freeze, ["~> 2.5"])
     s.add_dependency(%q<aws-sdk-ec2>.freeze, ["~> 1"])
-    s.add_dependency(%q<CFPropertyList>.freeze, ["~> 2.2"])
+    s.add_dependency(%q<CFPropertyList>.freeze, [">= 2.2"])
     s.add_dependency(%q<concurrent-ruby>.freeze, ["~> 1.0"])
     s.add_dependency(%q<hiera-eyaml>.freeze, ["~> 3"])
     s.add_dependency(%q<jwt>.freeze, ["~> 2.2"])
@@ -92,11 +92,11 @@ Gem::Specification.new do |s|
     s.add_dependency(%q<net-ssh-krb>.freeze, ["~> 0.5"])
     s.add_dependency(%q<orchestrator_client>.freeze, ["~> 0.4"])
     s.add_dependency(%q<puppet>.freeze, [">= 6.18.0"])
-    s.add_dependency(%q<puppetfile-resolver>.freeze, ["~> 0.4"])
+    s.add_dependency(%q<puppetfile-resolver>.freeze, [">= 0.4"])
     s.add_dependency(%q<puppet-resource_api>.freeze, [">= 1.8.1"])
     s.add_dependency(%q<puppet-strings>.freeze, ["~> 2.3"])
     s.add_dependency(%q<r10k>.freeze, ["~> 3.1"])
-    s.add_dependency(%q<ruby_smb>.freeze, ["~> 1.0"])
+    s.add_dependency(%q<ruby_smb>.freeze, [">= 1.0"])
     s.add_dependency(%q<terminal-table>.freeze, ["~> 1.8"])
     s.add_dependency(%q<winrm>.freeze, ["~> 2.0"])
     s.add_dependency(%q<winrm-fs>.freeze, ["~> 1.3"])
