--- pyproject.toml.orig	2026-04-17 15:53:18 UTC
+++ pyproject.toml
@@ -3,7 +3,7 @@ requires = [
 requires = [
   'meson-python',
   "cython>=3.0.13,<4",  # Sync with CYTHON_MIN_VER in setup
-  "numpy>=2.0.0,<3",
+  "numpy",
   "setuptools_scm>=9.2.0,<10",
 ]
 
