.TH aftp 1 "21st January, 1997" "Version 1.0p1"
.SH NAME
\fBaftp\fP - Transfer files to/from Apple II disk images.
.SH SYNOPSIS
.IP "aftp"
\fB[-poirh]\fP  \fIdisk image ... \fP
.LP
.SH DESCRIPTION
\fBaftp(1)\fP manipulates and browses Apple II disk images.  It supports
both Apple ][ DOS 3.3, ProDOS and XGS images.  Both binary floppy images
(.IIE) and hard disk volume (.HDV) images are also supported.
.SH OPTIONS
.IP "\fB-p\fP"
use a Prodos filesystem.
.IP "\fB-o\fP"
use a Prodos ordered image.
.IP "\fB-i\fP"
use an XGS image file.
.IP "\fB-r\fP"
load images as read-only.
.IP "\fB-h\fP"
display aftp help.
.SH NOTES
.LP
When invoked with a single disk image filename as the first parameter,
aftp operates in interactive mode and all of the interactive commands
are available. Specifing multiple disk images will display the root
directory of each image and then terminate without entering
interactive mode.
.sp
If you have ever used the unix \fBftp(1)\fP command, the \fBaftp(1)\fP
commands will be very familiar.  Interactive commands are:
.IP "\fBdir\fP"
display disk image directory.
.IP "\fBls\fP"
alias for the dir command.
.IP "\fBget\fP \fI[file]\fP"  
get a file from the disk image.
.IP "\fBput\fP \fI[file]\fP"   
put a file in the disk image.
.IP "\fBdel\fP \fI[file]\fP"   
delete a file from the disk image.
.IP "\fBcd\fP \fI[dir]\fP"   
change the current disk image directory.
.IP "\fBtext\fP"      
set text mode.
.IP "\fBbinary\fP"
set binary mode.
.IP "\fBhelp\fP"
display help.
.IP "\fBdump\fP"
display a hex dump of the disk image.
.IP "\fB!\fP\fIcommand\fP"
shell escape.
.IP "\fBquit\fP"
exit the program.
.LP
When putting files in disk images, the following default attributes
will be used depending on whether you are transferring in binary or
text mode:
.sp
.nf
DOS, Text			File type: T
DOS, Binary		File type: B
ProDOS, Text		File type: TXT, SubType: R=0
ProDOS, Binary		File type: BIN, SubType: A$=2000
.LP
.SH BUGS
File extentions are not properly recognised. To correct this problem
use a command line option to specify the type of disk image you are
accessing.
.sp
There is bound to be other bugs so be sure to backup your disk images
just in case.
.sp
Bug reports can be sent to Andru Luvisi <luvisi@andru.sonoma.edu>.
.SH AUTHOR
Written by Galen C. Hunt <gchunt@cc.dixie.edu>
.br
Ported to UNIX by Andru Luvisi <luvisi@andru.sonoma.edu>
.br
Man page by Joel Sutton <suttonj@interconnect.com.au>
.sp
This man page is based on the original README included with aftp.
.SH COPYRIGHT
Released into the public domain with no warranties - 13 Jun 1994 Release 1.0
