--- cpp/test/Ice/properties/run.py.orig	2019-08-12 19:54:18 UTC
+++ cpp/test/Ice/properties/run.py
@@ -35,10 +35,10 @@ if TestUtil.isAIX():
 #
 if sys.version_info[0] == 2:
     configPath = "./config/\xe4\xb8\xad\xe5\x9b\xbd_client.config"
-    decodedPath = configPath.decode("utf-8")
+    decodedPath = configPath
 else:
     configPath = "./config/\u4e2d\u56fd_client.config"
-    decodedPath = configPath # No need to decode with Python3, strings are already Unicode
+    decodedPath = configPath.encode("utf-8", "ignore") # No need to decode with Python3, strings are already Unicode
 
 TestUtil.createFile(decodedPath,
                     ["# Automatically generated by Ice test driver.",
