--- cpp.orig/test/Ice/properties/run.py	2013-03-11 15:19:47.000000000 +0000
+++ cpp/test/Ice/properties/run.py	2013-05-21 03:48:13.020195761 +0000
@@ -28,15 +28,15 @@
 #
 if sys.version_info[0] == 2:
     configPath = "./config/\xe4\xb8\xad\xe5\x9b\xbd_client.config".decode("utf-8")
-    TestUtil.createConfig(configPath, 
+    TestUtil.createConfig(configPath.encode("utf-8"), 
                           ["# Automatically generated by Ice test driver.", 
                            "Ice.Trace.Protocol=1",
                            "Ice.Trace.Network=1", 
                            "Ice.ProgramName=PropertiesClient", 
-                           "Config.Path=./config/中国_client.config"])
+                           "Config.Path=" + configPath.encode("utf-8")])
 else:
     configPath = "./config/\u4e2d\u56fd_client.config"
-    TestUtil.createConfig(configPath, 
+    TestUtil.createConfig(configPath.encode("utf-8"), 
                           ["# Automatically generated by Ice test driver.", 
                            "Ice.Trace.Protocol=1",
                            "Ice.Trace.Network=1", 
@@ -46,5 +46,5 @@
 
 TestUtil.simpleTest(client)
 
-if os.path.exists(configPath):
-    os.remove(configPath)
+if os.path.exists(configPath.encode("utf-8")):
+    os.remove(configPath.encode("utf-8"))
