# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)

PORTNAME=	Net_UserAgent_Detect
PORTVERSION=	2.5.2
PORTREVISION=	1
CATEGORIES=	net www pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PEAR class that determines the Web browser, version, and platform

LICENSE=	PHP202

USES=		pear
NO_ARCH=	yes

.include <bsd.port.mk>
