--- ldapcheck.c.orig	2009-04-09 05:26:46.000000000 +0200
+++ ldapcheck.c	2009-10-23 23:57:42.000000000 +0200
@@ -58,6 +58,22 @@
 #include "prop.h"
 #include "ldapcheck.h"
 
+#ifndef SIMPLEQ_HEAD 
+# define SIMPLEQ_HEAD			STAILQ_HEAD
+# define SIMPLEQ_HEAD_INITIALIZER	STAILQ_HEAD_INITIALIZER
+# define SIMPLEQ_ENTRY 			STAILQ_ENTRY
+# define SIMPLEQ_INIT 			STAILQ_INIT
+# define SIMPLEQ_INSERT_HEAD 		STAILQ_INSERT_HEAD
+# define SIMPLEQ_INSERT_TAIL 		STAILQ_INSERT_TAIL
+# define SIMPLEQ_INSERT_AFTER 		STAILQ_INSERT_AFTER
+# define SIMPLEQ_REMOVE_HEAD 		STAILQ_REMOVE_HEAD
+# define SIMPLEQ_FOREACH 		STAILQ_FOREACH
+# define SIMPLEQ_EMPTY 			STAILQ_EMPTY
+# define SIMPLEQ_FIRST 			STAILQ_FIRST
+# define SIMPLEQ_NEXT 			STAILQ_NEXT
+# define SIMPLEQ_REMOVE 		STAILQ_REMOVE
+#endif
+
 struct ldapconf_entry {
 	char *lc_url;
 	char *lc_dn;
