--- Makefile.install.orig	2013-12-20 08:40:13.447414000 -0500
+++ Makefile.install
@@ -24,7 +24,11 @@ LIBEXT = dll
 EXEEXT = .exe
 endif
 
-INSTALL_TARGETS = league xml fastcgi soap wsse wsdl2ada sql amf dd uml mofext ocl utp
+INSTALL_TARGETS = league xml fastcgi soap wsse wsdl2ada sql
+
+ifdef ENABLE_AMF
+INSTALL_TARGETS += amf dd uml mofext ocl utp
+endif
 
 ifdef HAS_FIREBIRD
 INSTALL_TARGETS += firebird
