# Created by: Pawel Worach
# $FreeBSD$

PORTNAME=	font-alias
PORTVERSION=	1.0.4
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org Font aliases

USES=		xorg-cat:font
NOFONT=		yes
NO_ARCH=	yes

.include <bsd.port.mk>
