#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['sphinx_theme_builder',
 'sphinx_theme_builder._internal',
 'sphinx_theme_builder._internal.cli']

package_data = \
{'': ['*']}

package_dir = \
{'': 'src'}

install_requires = \
['packaging', 'rich', 'tomli', 'nodeenv', 'setuptools', 'pep621']

extras_require = \
{'cli': ['build', 'click', 'sphinx-autobuild']}

entry_points = \
{'console_scripts': ['stb = sphinx_theme_builder._internal.cli:main']}

setup(name='sphinx-theme-builder',
      version='%%PORTVERSION%%',
      description='A tool for authoring Sphinx themes with a simple (opinionated) workflow.',
      author=None,
      author_email='Pradyun Gedam <mail@pradyunsg.me>',
      url=None,
      packages=packages,
      package_data=package_data,
      package_dir=package_dir,
      install_requires=install_requires,
      extras_require=extras_require,
      entry_points=entry_points,
      python_requires='~=3.7',
     )
