# $Id: Makefile,v 1.12 1999/04/30 04:58:30 taoka Exp $
#

    SUBDIR += ephem
    SUBDIR += luna
    SUBDIR += saoimage
    SUBDIR += sattrack
    SUBDIR += setiathome
    SUBDIR += ssystem
    SUBDIR += stars
    SUBDIR += sunclock
    SUBDIR += wmmoonclock
    SUBDIR += wmspaceweather
    SUBDIR += wmsun
    SUBDIR += x3arth
    SUBDIR += xearth
    SUBDIR += xephem
    SUBDIR += xglobe
    SUBDIR += xphoon
    SUBDIR += xtide

.include <bsd.port.subdir.mk>
