--- xsl/general-customization.xsl.orig	Sat Oct 16 20:19:30 2004
+++ xsl/general-customization.xsl	Sat Oct 16 20:19:53 2004
@@ -13,11 +13,11 @@
 <!-- Including new title page stylesheets for customizing the placement 
 	 of tags in the title page. -->
 <!-- This one is autogenerated from titlepage.xml -->
-<xsl:include href="titlepage.xsl"/>
+<!--<xsl:include href="titlepage.xsl"/>-->
 
 <!-- This one was edited by hand, to make titlepage a separate chunk
 	 for book and aricle -->
-<xsl:include href="titlepage2.xsl"/>
+<xsl:import href="titlepage2.xsl"/>
 
 <!-- Make a separate titlepage and link it behind the main page. -->
 <xsl:param name="generate.titlepage.link" select="1"/>
