.\" Copyright (c) 1997 Andreas Klemm <andreas@FreeBSD.org>. Neuss.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" $FreeBSD$
.Dd August 17, 1997
.Dt MPEG_MUSICIN 1
.Os FreeBSD
.Sh NAME
.Nm mpeg_musicin
.Nd MPEG/audio Layer 1 and Layer 2 decoder
.Sh SYNOPSIS
.Nm mpeg_musicin
queries for all arguments, or
.br
.Nm mpeg_musicin
.Op Fl l Ar lay
.br
.Op Fl m Ar mode
.br
.Op Fl p Ar psy
.br
.Op Fl s Ar sfrq
.br
.Op Fl b Ar br
.br
.Op Fl d Ar emp
.br
.Op Fl c
.br
.Op Fl o
.br
.Op Fl e
.br
inputCM
.br
.Op Ar outBS
.br
.Sh DESCRIPTION
The encoder and decoder software are configured to output
the coded audio bitstreams as a string of hexadecimal ascii
characters. For greater compression efficiency, compile flag,
BS_FORMAT, in common.h can be switched to configure the bitstream 
reading and writing routines to process raw binary bitstreams.
.br
The decoder program has a very crude implementation of bitstream
synchword detection. It may not be able to correctly decode valid
bitstreams which have false synchword patterns in the ancillary data
portion of the bitstream.
.Sh RESTRICTIONS
The software implements levels I and II and psychophysical auditory
models I and II as described in the ISO 3-11171 rev 1 standard.
There are future plans to implement level III.
.br
The input/output audio data may either be headerless raw 16 bit data
or alternatively an AIFF formatted file (Audio Interchange File Format)
with certain limitations.
.br 
For more information on the AIFF format see the postscript file
/sgi/aiff-c.9.26.91.ps at the anonymous ftp site FTP.SGI.COM
(192.48.153.1).
.br
The AIFF formatted file is a convenient way for storing sampling rate
of the audio file.
.br
The encoder and decoder software are configured to output the coded
audio bitstreams as a string of hexadecimal ascii characters.
For greater compression efficiency, compile flag, BS_FORMAT, 
in common.h can be switched to configure the bitstream reading 
and writing routines to process raw binary bitstreams.
.br
This software has been run and verified on a large variety of
computers and operating systems. In particular UNIX, MS_DOS (with
MicroSoft C version 6), Macintosh, AIX Platform (RS6000) and Convex.
.Sh OPTIONS
.Bl -tag -width Ds
.It Sy -l lay
use layer <lay> coding (default: 2)
.It Sy -m mode
channel mode : s/d/j/m (default: s)
.It Sy -p psy
psychoacoustic model 1/2 (default: 2)
.It Sy -s sfrq
input smpl rate in kHz (default: 44.1)
.It Sy -b br
total bitrate in kbps (default: 384)
.It Sy -d emp
de-emphasis n/5/c (default: n)
.It Sy -c
mark as copyright
.It Sy -o
mark as original
.It Sy -e
add error protection
.It Sy inputPCM
input PCM sound file (standard or AIFF)
.It Sy outBS
output bit stream of encoded audio (dflt inName+.mpg)
.Sh SEE ALSO
.Xr mpeg_musicout 1
.Sh HISTORY
Written by Andreas Klemm, August 17, 1997
