.\" $Id: pkg_update.1,v 2.0 2018/03/31 06:54:50 cvs Exp $
.TH PKG_UPDATE 1 "April 2017" "FreeBSD" "User Manuals"
.SH NAME
pkg_update \- Easy handling of jailed packages builds.
.SH SYNOPSIS
.TP
.B pkg_update [command] ...
.SH DESCRIPTION
.B pkg_update
is a script to handle an clean jail for package-builds.
.SH ARGUMENTS
.TP
.B update-ports
Start "make update" for the ports tree.
.TP
.B update-pkg
Force rebuild of pkg tools.
.TP
.B repo
Force rebuild of pkg repo.
.TP
.B make-packages
Builds a port and its dependencies in a clean /usr/local.
You should not run this on a server with configuration.
Existing packages are used.
Extra files in "${PREFIX}" are detected and reported.
The default list of ports is "data/make-packages.${hostname}"
.TP
.B clean-distfiles
Checks all distinfo files and moves the disfiles not found
to "/usr/ports/distfiles/Old/".
.TP
.B merge-distfiles
Copy all disfiles found that do not yet exist on the master
directory "/media/ports/distfiles/".
.TP
.B clean-packages
Find obsolete packages and move them out of the way.
.TP
.B pkg_update clean-openssl-packages
Find packages that use openssl and move them out of the way
.TP
.B full-update-jail
Do full update cycle:
1. "update-ports" to update the ports tree
2. "clean-packages" to keep only good packages
3. remove all old error logs
4. "make-packages" to rebuild missing packages
.TP
.B full-update-jail retry
Skip "update-ports" and procced as above.
.TP
.B fetch-distfiles
Fetch distfiles for list of ports.
.TP
.B fetch-recursive-distfiles
Fetch distfiles for list of ports and their dependecies.
.TP
.B fix-moved-ports
Check installed packages for moved ports.
Then register the new dir in the old installed package.
.TP
.B add-packages
Build a missing port and its missing dpendencies
/usr/local is not deleted, on success the port is installed.
Existing packages will be used.
.TP
.B list-installed-ports
List all installed ports.
.TP
.B show-version-list
List installed packages that are not in correct version.
.TP
.B show-packages
List build packages or report missing for each port
recorded in "data/install-packages.${hostname}".
.TP
.B check-installed-ports
Compare the list of installed ports with the list
recorded in data/install-packages.${hostname}".
.TP
.B show-missing-packages
Warn if no package is found for each port
recorded in "data/install-packages.${hostname}"
.TP
.B show-missing-installed
List build packages or report missing for each port
installed on this host.
.TP
.B check-update
1. check-installed-ports
2. show-missing-packages
3. show-missing-installed
.TP
.B clean
Clean all cached information.
.TP
.B make-version-list
Make new list of packages that are not in correct version.
.TP
.B make-deinstall-list
Make new list of ports that are not in correct version
and create a script "deinstall.${hostname}" to deinstall
all the old ports and the dependend ports in order.
.TP
.B check-reinstall
For each package deleted by "make-deinstall-list" warn
if no new package is found.
.TP
.B  reinstall
For each package deleted by "make-deinstall-list" try
to install the new package if it exists.
.TP
.B install-packages
For each port recorded in "data/install-packages.${hostname}"
try to to install the new package if it exists.
.TP
.B show-missing-reinstall
For each port recorded from "make-deinstall-list" warn
if no new package is found.
.TP
.B clean-reinstall
For each port recorded from "make-deinstall-list",
keep only the ports that have no package installed.
.TP
.B deinstall-packages
For each port recorded in "data/install-packages.${hostname}"
try to to deinstall the installed port.
.SH "IMPLEMENTATION NOTES"
This script uses only /bin/sh and it does not need an INDEX file.
.SH RETURN VALUES
undefined.
.SH "FILES"
.TP
.B /usr/ports/local/update/data/
Default location for configuration and varaible data.

.TP
.B /usr/ports/local/update/log-${hostname}
Default location for logsfiles.
.TP
.B /media/ports/distfiles/
Optional location lor a central hostng of distfiles.
.SH "EXAMPLES"
.B pkg_update full-update-jail clean-distfiles
.SH "SEE ALSO"
.TP
.B pkg_jail(1)
The tool to create and run the jail.
.SH "HISTORY"
http://www.dinoex.net/training/package.html
.TP
http://www.dinoex.net/training/package2.html
.SH "AUTHOR"
Dirk Meyer, dinoex@FreeBSD.org
