PORTNAME=	notes
PORTVERSION=	1.2
PORTREVISION=	3
CATEGORIES=	mail www
DISTNAME=	${PORTNAME}.${PORTVERSION}-1.4.0

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Allows you to create notes

USE_SM_COMPAT=	yes
USE_GENERIC_PKGMESSAGE=	yes

.include "${.CURDIR}/../squirrelmail/bsd.squirrelmail.mk"
.include <bsd.port.mk>
