--- ext/mcal/config.m4.orig	Tue Mar 27 22:34:31 2001
+++ ext/mcal/config.m4	Mon Nov 26 18:22:29 2001
@@ -40,7 +40,8 @@
   fi
 
   PHP_ADD_INCLUDE($MCAL_INCLUDE)
-  PHP_ADD_LIBRARY_WITH_PATH(mcal, $MCAL_LIBRARY, MCAL_SHARED_LIBADD)
+  PHP_ADD_LIBPATH($MCAL_LIBRARY, MCAL_SHARED_LIBADD)
+  PHP_ADD_LIBRARY(mcal, 1, MCAL_SHARED_LIBADD)
   PHP_SUBST(MCAL_SHARED_LIBADD)
   AC_DEFINE(HAVE_MCAL,1,[ ])
   PHP_EXTENSION(mcal,$ext_shared)
