/* ATTENTION: this file is automatically generated and will be overwritten!
 * Manual changes will get lost!
 */
#ifndef GEN_VERSION_SUFFIX_H
#define GEN_VERSION_SUFFIX_H
#define VERSION_SUFFIX "_git_release/0.3.x+0200"
#endif
