PORTNAME=	mvtnorm
DISTVERSION=	1.3-0
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Multivariate Normal and t Distributions
WWW=		https://cran.r-project.org/package=mvtnorm

USES=		cran:auto-plist,compiles

.include <bsd.port.mk>
