--- pyproject.toml.orig	2020-02-02 00:00:00 UTC
+++ pyproject.toml
@@ -1,5 +1,5 @@
 [project]
-name = "Pint"
+name = "pint"
 authors = [{ name = "Hernan E. Grecco", email = "hernan.grecco@gmail.com" }]
 dynamic = ["version"]
 license = { text = "BSD" }
