PORTNAME=	rbw
DISTVERSION=	1.15.0
PORTREVISION=	1
CATEGORIES=	security

MAINTAINER=	dtxdf@FreeBSD.org
COMMENT=	Unofficial bitwarden cli

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		cargo
USE_GITHUB=	yes
GH_ACCOUNT=	doy

PLIST_FILES=	bin/rbw \
		bin/rbw-agent

.include <bsd.port.mk>
