# Created by: wen@FreeBSD.org
# $FreeBSD$

PORTNAME=	pymongo
PORTVERSION=	2.8
CATEGORIES=	databases python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
PKGNAMESUFFIX=	28

MAINTAINER=	demon@FreeBSD.org
COMMENT=	Python driver for MongoDB

LICENSE=	APACHE20

CONFLICTS_INSTALL=	py[0-9][0-9]-pymongo

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
