--- cargo-crates/v8-150.4.0/build/toolchain/toolchain.gni.orig	2006-07-24 01:21:28 UTC
+++ cargo-crates/v8-150.4.0/build/toolchain/toolchain.gni
@@ -69,7 +69,7 @@ if (host_os == "mac") {
   host_shlib_extension = ".dylib"
 } else if (host_os == "win") {
   host_shlib_extension = ".dll"
-} else if (host_os == "linux" || host_os == "aix" || host_os == "zos") {
+} else if (is_posix) {
   host_shlib_extension = ".so"
 } else {
   assert(false, "Host platform not supported")
