--- config.mk.orig	2015-12-17 19:21:00 UTC
+++ config.mk
@@ -33,8 +33,6 @@ PROJECT_UCFIRST = $(shell echo '${PROJEC
 
 CPPFLAGS  = -DVERSION=\"${VERSION}\"
 CPPFLAGS += -DPROJECT=\"${PROJECT}\" -DPROJECT_UCFIRST=\"${PROJECT_UCFIRST}\"
-CPPFLAGS += -D_XOPEN_SOURCE=500
-CPPFLAGS += -D_POSIX_SOURCE
 ifeq ($(USEGTK3), 1)
 CPPFLAGS += -DHAS_GTK3
 CPPFLAGS += -DGSEAL_ENABLE
