--- config.mk.orig	2017-04-11 19:31:27 UTC
+++ config.mk
@@ -34,8 +34,6 @@ PROJECT_UCFIRST = $(shell echo '${PROJEC
 
 CPPFLAGS  = -DVERSION=\"${VERSION}\"
 CPPFLAGS += -DPROJECT=\"${PROJECT}\" -DPROJECT_UCFIRST=\"${PROJECT_UCFIRST}\"
-CPPFLAGS += -D_XOPEN_SOURCE=500
-CPPFLAGS += -D_POSIX_SOURCE
 ifeq ($(USEGTK3), 1)
 CPPFLAGS += -DHAS_GTK3
 CPPFLAGS += -DGSEAL_ENABLE
