# Created by: andrej@ebert.su
# $FreeBSD$

PORTNAME=	safe
PORTVERSION=	0.4
CATEGORIES=	security python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	Safe-${PORTVERSION}

MAINTAINER=	andrej@ebert.su
COMMENT=	Python library to test password strength

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
