# $Id: Makefile,v 1.16 1997/03/23 17:36:55 jfitz Exp $
#

    SUBDIR += afio
    SUBDIR += contool
    SUBDIR += idled
    SUBDIR += lsof
    SUBDIR += manck
    SUBDIR += mkisofs
    SUBDIR += pib
    SUBDIR += rtty
    SUBDIR += socket
    SUBDIR += stat
    SUBDIR += su2
    SUBDIR += tcplist
    SUBDIR += top
    SUBDIR += tua
    SUBDIR += xbatt
    SUBDIR += xcpustate
    SUBDIR += xdu
    SUBDIR += xloadface
    SUBDIR += xperfmon
    SUBDIR += xsysinfo
    SUBDIR += xsysstats

.include <bsd.port.subdir.mk>
