# $Id: Makefile,v 1.20 1994/11/20 23:10:25 ats Exp $
#
# XXX ncftp moved to core distribution
# tcpblast temporarily removed
#
SUBDIR= archie cern_httpd chimera dgd fspclient gn irc ircII lynx ncftp2 \
	pcnfsd pidentd pmf sup tcp_wrapper tkWWW tintin++ wais wu-ftpd
	yale-tftpd

.include <bsd.port.subdir.mk>
