.TH "MailScanner" "8" "4.52.2" "Julian Field" "Mail"
.SH "NAME"
.LP 
MailScanner \- Virus/Spam Scanner for Sendmail, Exim and Postfix
.SH "SEE ALSO"
.LP 
Please see http://www.mailscanner.info for current documentation. All current configuration options can be found at 
.br 

.br 
http://www.mailscanner.info/MailScanner.conf.index.html

