# $FreeBSD$

PORTNAME=	rex-nop
PORTVERSION=	0.1.0
CATEGORIES=	security rubygems
MASTER_SITES=	RG

MAINTAINER=	antoine@FreeBSD.org
COMMENT=	Ruby Exploitation(Rex) library for NOP generation

RUN_DEPENDS=	rubygem-rex-arch>=0:security/rubygem-rex-arch

NO_ARCH=	yes

USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
