--- cmake/FindGRASS.cmake.orig	2023-10-29 01:48:21 UTC
+++ cmake/FindGRASS.cmake
@@ -159,11 +159,9 @@ IF (UNIX)
 
 IF (UNIX)
     IF (CMAKE_SYSTEM_NAME STREQUAL "FreeBSD")
-        IF (GRASS_FIND_VERSION EQUAL 7)
-              FOREACH (VERSION_MINOR 9 8 7 6 5 4 3 2 1 0)
-                  LIST (APPEND GRASS_PATHS /usr/local/grass${GRASS_FIND_VERSION}${VERSION_MINOR})
-              ENDFOREACH(VERSION_MINOR)
-        ENDIF (GRASS_FIND_VERSION EQUAL 7)
+        FOREACH (VERSION_MINOR 9 8 7 6 5 4 3 2 1 0)
+            LIST (APPEND GRASS_PATHS %%LOCALBASE%%/grass${GRASS_FIND_VERSION}${VERSION_MINOR})
+        ENDFOREACH(VERSION_MINOR)
     ELSE (CMAKE_SYSTEM_NAME STREQUAL "FreeBSD")
         FOREACH (VERSION_MINOR 9 8 7 6 5 4 3 2 1 0)
             FOREACH (PATH /usr/lib64 /usr/lib)
