DISTVERSION?=	610.57.04
# Explicitly set PORTREVISION as it can be overridden by the master port
PORTREVISION=	0

MASTERDIR=	${.CURDIR}/../nvidia-drm-kmod
PKGNAMESUFFIX=	-devel

.include "${MASTERDIR}/Makefile"
