.\"Created with GNOME Manpages Editor
.\"http://sourceforge.net/projects/gmanedit2

.\"Replace <program> with the program name, x with the Section Number
.TH STENDHAL 1 "" "March 3, 2015" "Stendhal Client Manual"

.SH NAME
Stendal Client

..SH SYNOPSIS
.B stendhal
.RI [ vmargs ]
.br

.SH DESCRIPTION
Stendhal is a 2-dimenstional multiplayer-online role-playing game. It is set in a fantasy world and incorporates questing, fighting, special events, and more. This is the manual for the game client.

.SH VMARGS
These are arguments that will be passed to the Java Virtual Machine.

.SH "SEE ALSO"
stendhal-server(1)
