.\"Created with GNOME Manpages Editor
.\"http://sourceforge.net/projects/gmanedit2

.TH STENDHAL-SERVER 1 "" "March 3, 2015" "Stendhal Server Manual"

.SH NAME
Stendal Server

..SH SYNOPSIS
.B stendhal-server
.RI [ vmargs ]
.br

.SH DESCRIPTION
Stendhal is a 2-dimenstional multiplayer-online role-playing game. It is set in a fantasy world and incorporates questing, fighting, special events, and more. This is the manual for the game server.

.SH VMARGS
These are arguments that will be passed to the Java Virtual Machine.

.SS "Seasons:"
.IP \fB\-Dstendhal.christmas\fP
Enables Christmas maps.
.IP \fB\-Dstendhal.easter\fP
Enables Easter maps.
.IP \fB\-Dstendhal.minetown\fP
Enables Minetown Weeks maps.

.SH "SEE ALSO"
stendhal(1)
